INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Baumann''s Ventilation & Plumbing Ltd',
  '<p>Baumann''s Ventilation & Plumbing Ltd, located in Medicine Hat, Alberta, offers a range of essential services in residential and commercial heating, air-conditioning, and plumbing. This business has built a reputation for reliability and quality, serving the community with dedication and expertise. With a focus on customer satisfaction, Baumann''s provides comprehensive solutions tailored to meet diverse needs.</p><p>The company specializes in plumbing services that cover everything from routine maintenance to emergency repairs. Their team of skilled professionals ensures that every job is completed efficiently and effectively. In addition to plumbing, Baumann''s also excels in heating and air-conditioning services, ensuring homes and businesses maintain optimal comfort throughout the year. This commitment to excellence has garnered Baumann''s a loyal customer base in Medicine Hat and surrounding areas.</p><p>Baumann''s Ventilation & Plumbing Ltd prides itself on using high-quality materials and the latest techniques in the industry. The knowledgeable staff remains updated on industry trends and best practices, which enhances their service delivery. This proactive approach not only meets but exceeds customer expectations consistently. The business has achieved numerous accolades for its outstanding service and commitment to the community.</p><p>In summary, Baumann''s Ventilation & Plumbing Ltd provides reliable plumbing, heating, and air-conditioning services to Medicine Hat, Alberta. Their focus on quality and customer satisfaction makes them a trusted choice for many. Connect with Baumann''s for expert services in Medicine Hat today.</p>',
  '79 SW Dr S W',
  'Canada',
  'AB',
  'Medicine Hat',
  'T1A 8E8',
  'info@baumanns.ca',
  'canada/medicine-hat/home-services/baumann-s-ventilation-plumbing-ltd',
  'ChIJf_cSykctE1MR2evC5roeFuM',
  50.0180822,
  -110.7041215,
  '14035299744',
  'https://www.kwikr.ca/pictures/profile/pimage-997.jpg',
  'Plumbing',
  'Growth Plan',
  998,
  'http://www.baumanns.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'A&B Mechanical Ltd.',
  '<p>A&B Mechanical Ltd. offers comprehensive plumbing, heating, air conditioning, and indoor air quality services in Winnipeg, Manitoba. This local business excels in providing essential services to ensure a comfortable living environment for residents and businesses alike. A&B Mechanical Ltd. employs highly trained staff and qualified service technicians dedicated to maintaining optimal comfort while promoting cost savings for customers.</p> <p>The company specializes in a range of plumbing services, addressing everything from routine maintenance to emergency repairs. A&B Mechanical Ltd. also provides installation and repair for heating and air conditioning systems, ensuring that homes and businesses remain comfortable year-round. The focus on indoor air quality products further enhances the living conditions for customers, making A&B Mechanical Ltd. a go-to solution for all HVAC and plumbing needs.</p> <p>A&B Mechanical Ltd. has built a strong reputation in Winnipeg and surrounding areas through its commitment to quality service and customer satisfaction. The team prioritizes efficiency and reliability, ensuring that every job meets the highest standards. With a focus on saving money for clients while providing essential services, A&B Mechanical Ltd. continues to thrive in the local market.</p> <p>For reliable plumbing and HVAC services, A&B Mechanical Ltd. delivers expertise and professionalism. The commitment to customer comfort and satisfaction is evident in every service provided. Connect with A&B Mechanical Ltd. in Winnipeg for all plumbing and HVAC needs.',
  '1400 Spruce St',
  'Canada',
  'MB',
  'Winnipeg',
  'R3E 2V7',
  'office@abmech.ca',
  'canada/winnipeg/home-services/a-b-mechanical-ltd',
  'ChIJxYDUXHVz6lIREbEZGrPUBo4',
  49.9086212,
  -97.1862867,
  '12047833622',
  'https://www.kwikr.ca/pictures/profile/pimage-996.jpg',
  'Plumbing',
  'Growth Plan',
  997,
  'https://www.abmech.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Plumber Near Me',
  '<p>Plumber Near Me offers expert plumbing services specializing in drain and waterproofing solutions in Georgetown, Ontario. This local business serves the Greater Toronto Area and Halton Hills, ensuring reliable and efficient plumbing for residential and commercial clients. With a commitment to quality, Plumber Near Me has built a reputation for excellence in the plumbing industry.</p> <p>Offering a comprehensive range of services, Plumber Near Me addresses various plumbing needs, including drain cleaning, waterproofing, and emergency repairs. The team of skilled professionals utilizes advanced techniques and equipment to tackle even the most challenging plumbing issues. Clients benefit from prompt service and effective solutions tailored to specific requirements. </p> <p>Customer satisfaction remains a top priority. The business emphasizes clear communication and transparency throughout the service process. Clients appreciate the professionalism and expertise displayed by the team, leading to a high rate of repeat business and referrals. Plumber Near Me has gained recognition for its dedication to maintaining high standards in plumbing services.</p> <p>With a focus on quality workmanship and customer care, Plumber Near Me continues to thrive in the competitive plumbing market. The business combines technical knowledge with practical solutions to ensure long-lasting results. For reliable plumbing services in Georgetown, Ontario, reach out to Plumber Near Me today for expert assistance.</p>',
  '9660 Wellington Rd 42',
  'Canada',
  'ON',
  'Georgetown',
  'L7G 4S8',
  'info@plumbernearmeinc.ca',
  'canada/georgetown/home-services/plumber-near-me',
  'ChIJ3f2ILugNK4gRWpmksyxFA8c',
  43.7226161,
  -79.9822956,
  '14168001991',
  'https://www.kwikr.ca/pictures/profile/pimage-995.jpg',
  'Plumbing',
  'Growth Plan',
  996,
  'http://plumbernearmeinc.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Mid-City Plumbing & Heating Inc',
  '<p>Mid-City Plumbing & Heating Inc delivers reliable plumbing, heating, and HVAC services to Estevan, Saskatchewan. Established in 1966, the company has built a reputation for excellence in installation, repair, and service. With a team of certified Journeymen Technicians, Mid-City Plumbing & Heating Inc ensures prompt assistance around the clock, catering to the needs of residential and commercial clients alike.</p><p>Offering comprehensive plumbing solutions, Mid-City Plumbing & Heating Inc specializes in a range of services, including emergency repairs, routine maintenance, and system installations. The company prioritizes customer comfort and satisfaction, reflecting its commitment to quality service. Estevan residents benefit from the expertise of trained professionals who understand local plumbing and heating systems.</p><p>Mid-City Plumbing & Heating Inc also emphasizes the importance of energy efficiency in its HVAC services. Technicians provide recommendations for system upgrades and replacements that enhance performance while reducing energy costs. This focus on efficiency aligns with the growing demand for sustainable solutions in the community.</p><p>With decades of experience, Mid-City Plumbing & Heating Inc remains a trusted choice for plumbing and heating needs in Estevan. The company’s dedication to quality workmanship and customer service has solidified its position in the local market. Connect with Mid-City Plumbing & Heating Inc today for all plumbing and HVAC services in Estevan, Saskatchewan.</p>',
  '1237 6 St',
  'Canada',
  'SK',
  'Estevan',
  'S4A 1A9',
  'info@mcph.ca',
  'canada/estevan/home-services/mid-city-plumbing-heating-inc',
  'ChIJa-dtcpMiIFMR8fginPYrgl4',
  49.1429094,
  -102.9951079,
  '13066345512',
  'https://www.kwikr.ca/pictures/profile/pimage-994.jpg',
  'Plumbing',
  'Growth Plan',
  995,
  'http://mcph.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Chinook Plumbing Ltd.',
  '<p>Chinook Plumbing Ltd. offers reliable plumbing services in Calgary, Alberta. This local business specializes in residential and commercial plumbing solutions, ensuring quality work and customer satisfaction. With years of experience, Chinook Plumbing Ltd. has built a reputation for its skilled technicians and prompt service.</p><p>Located at 6773 Fairmount Dr SE, Chinook Plumbing Ltd. provides a wide range of plumbing services. These include emergency repairs, routine maintenance, and installation of plumbing fixtures. The team understands the urgency of plumbing issues and is committed to resolving problems efficiently. Their dedication to quality service has earned them positive feedback from the community.</p><p>Chinook Plumbing Ltd. is known for its attention to detail and professionalism. The technicians are trained to handle various plumbing challenges, from leaky faucets to complex pipe installations. The business prioritizes customer needs, ensuring that each job is completed to the highest standards. This commitment to excellence has resulted in numerous satisfied clients across Calgary.</p><p>The combination of expertise, reliability, and customer focus makes Chinook Plumbing Ltd. a trusted choice for plumbing services. Their ability to tackle diverse plumbing tasks sets them apart in the local market. For those in need of plumbing assistance in Calgary, Chinook Plumbing Ltd. presents a strong option. Contact Chinook Plumbing Ltd. at their Fairmount Dr SE location for professional plumbing services today.</p>',
  '6773 Fairmount Dr SE',
  'Canada',
  'AB',
  'Calgary',
  'T2H 0X6',
  'chinookplumbingltd@gmail.com',
  'canada/calgary/home-services/chinook-plumbing-ltd',
  'ChIJK5rbovtwcVMRV27gFnzud2k',
  50.992176,
  -114.064481,
  '14032438849',
  NULL,
  'Plumbing',
  'Growth Plan',
  994,
  'http://www.chinookplumbing.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Archie Horn & Son',
  '<p>Archie Horn & Son Ltd. offers comprehensive plumbing, heating, air conditioning, and renovation services in Hamilton, Ontario. With over 88 years of experience, this local business has built a reputation for reliability and convenience. The company is licensed, bonded, and insured, ensuring peace of mind for customers. Technicians are dedicated to delivering trouble-free service and worry-free installation.</p><p>Specializing in energy-efficient equipment, Archie Horn & Son Ltd. meets the diverse needs of residential and commercial clients. The commitment to customer satisfaction sets this plumbing service apart from competitors. Each project receives careful attention, ensuring high-quality workmanship and timely completion. The team understands the importance of a functioning plumbing system and works diligently to resolve issues promptly.</p><p>Archie Horn & Son Ltd. also excels in heating and air conditioning services, providing installation and maintenance for optimal comfort throughout the year. Renovation services further enhance the property value and aesthetic appeal of homes and businesses. The company’s extensive experience in the industry equips them to handle projects of all sizes effectively.</p><p>With a strong focus on customer satisfaction and efficient service delivery, Archie Horn & Son Ltd. remains a trusted choice for plumbing and HVAC needs in Hamilton. For reliable plumbing and renovation services, connect with Archie Horn & Son Ltd. at 31 Bigwin Rd #1, Hamilton, Ontario. </p>',
  '31 Bigwin Rd #1',
  'Canada',
  'ON',
  'Hamilton',
  'L8W 3R3',
  'admin@archiehorn-son.com',
  'canada/hamilton/home-services/archie-horn-son',
  'ChIJD7K1B_qZLIgR00TwocacVyo',
  43.19345,
  -79.82231,
  '19053185020',
  'https://www.kwikr.ca/pictures/profile/pimage-992.jpg',
  'Plumbing',
  'Growth Plan',
  993,
  'https://www.archiehorn-son.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'University Plumbing & Heating Ltd.',
  '<p>University Plumbing & Heating Ltd. offers comprehensive plumbing and heating services in Ontario. Located at 3655 Keele St, this local business specializes in residential and commercial plumbing solutions. With a commitment to quality and customer satisfaction, University Plumbing & Heating Ltd. has built a reputation for reliable service and skilled technicians. The company’s expertise includes installation, repair, and maintenance of plumbing systems, ensuring efficient operation and longevity.</p><p>Established in Ontario, University Plumbing & Heating Ltd. focuses on delivering timely and effective solutions. The team is equipped to handle various plumbing issues, from leaky faucets to complex heating system installations. The company emphasizes the importance of preventative maintenance, which can save customers time and money in the long run. Their trained professionals utilize modern techniques and high-quality materials to ensure lasting results.</p><p>Customer feedback highlights the professionalism and efficiency of University Plumbing & Heating Ltd. Clients appreciate the transparent pricing and detailed consultations provided before any work begins. The business''s dedication to excellence is evident in its approach to each project, regardless of size or complexity. With a strong presence in the local community, this plumbing service continues to meet the needs of residents and businesses alike.</p><p>University Plumbing & Heating Ltd. excels in providing plumbing and heating solutions, ensuring customer satisfaction through quality service. The skilled team is ready to tackle any plumbing challenge. Reach out to University Plumbing & Heating Ltd. at 3655 Keele St, Ontario for reliable plumbing services.</p>',
  '3655 Keele St',
  'Canada',
  'ON',
  'Toronto',
  'M3J 1M8',
  'daubie@eaglesnestgolf.comeaglesnestgolf.com',
  'canada/home-services/university-plumbing-heating-ltd',
  'ChIJFZuUxugxK4gR50_f7vhcUmA',
  43.752824,
  -79.4869458,
  '14166306010',
  NULL,
  'Plumbing',
  'Growth Plan',
  992,
  'http://www.universityplumbing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'MT Drains & Plumbing LTD',
  '<p>MT Drains & Plumbing LTD delivers exceptional plumbing, waterproofing, and drain services to the Richmond Hill area in Ontario. With over 30 years of industry experience, this company has established a reputation for reliability and efficiency. Certified technicians tackle various plumbing challenges, ensuring homes remain safe and comfortable.</p> <p>Services include internal and external basement waterproofing, foundation repairs, and sump pump installations. Each service comes with a lifetime warranty, reflecting the company''s commitment to quality. Free estimates are available, allowing customers to understand their options without obligation. This approach fosters trust and transparency, essential in the plumbing industry.</p> <p>MT Drains & Plumbing prioritizes customer satisfaction. The team focuses on delivering timely solutions, minimizing disruption to daily life. The extensive experience of the technicians translates into effective problem-solving, addressing issues before they escalate. This proactive approach ensures that homes are protected from water damage and related problems.</p> <p>Residents of Richmond Hill can rely on MT Drains & Plumbing for comprehensive plumbing solutions. The combination of quality service, extensive experience, and customer-centric policies positions this business as a leader in the local market. For those seeking dependable plumbing and waterproofing services, contacting MT Drains & Plumbing is a wise choice. Reach out to MT Drains & Plumbing LTD in Richmond Hill for a free on-site estimate today.</p>',
  '604 Edward Ave Unit #5',
  'Canada',
  'ON',
  'Richmond Hill',
  'L4C 9Y7',
  'newmarket@mtdrain.com',
  'canada/richmond-hill/home-services/mt-drains-plumbing-ltd',
  'ChIJ88wJpUcvK4gR5tj7_IKfbhA',
  43.8983553,
  -79.4303095,
  '19057615551',
  'https://www.kwikr.ca/pictures/profile/pimage-990.jpg',
  'Plumbing',
  'Growth Plan',
  991,
  'https://mtdrain.com/?utm_source=gmb_concord&utm_medium=referral',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'West Bay Mechanical Ltd',
  '<p>West Bay Mechanical Ltd provides comprehensive plumbing services in Nanaimo, British Columbia. The company specializes in residential and commercial plumbing solutions, ensuring efficient and reliable service. With a commitment to quality, West Bay Mechanical Ltd offers expertise in installations, repairs, and maintenance, catering to the diverse needs of the community.</p><p>Established in the heart of Nanaimo, West Bay Mechanical Ltd has built a solid reputation for its professionalism and customer satisfaction. The team is equipped to handle various plumbing challenges, from routine maintenance to emergency repairs. Knowledgeable staff members ensure that all work meets high standards of safety and efficiency. This local business emphasizes transparency and integrity in its operations, which fosters trust among its clientele.</p><p>West Bay Mechanical Ltd stands out for its prompt response times and thorough assessments. The company utilizes modern techniques and tools to deliver effective plumbing solutions. Clients benefit from tailored services designed to meet specific needs, whether for residential properties or commercial establishments. The focus on customer service ensures that every interaction is positive and productive.</p><p>West Bay Mechanical Ltd excels in providing reliable plumbing services that the Nanaimo community can depend on. With a strong commitment to quality and customer satisfaction, the company continues to grow and serve its local area effectively. Reach out to West Bay Mechanical Ltd for expert plumbing solutions in Nanaimo, British Columbia.',
  '1631 Harold Rd',
  'Canada',
  'BC',
  'Nanaimo',
  'V9X 1T4',
  'office@westbaymechanical.com',
  'canada/nanaimo/home-services/west-bay-mechanical-ltd',
  'ChIJOaaHPSoNj1QRznktg5ieVCA',
  49.1006461,
  -123.8862574,
  '12504788532',
  NULL,
  'Plumbing',
  'Growth Plan',
  990,
  'http://www.westbaymechanical.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Global Sewer Technologies',
  '<p>Global Sewer Technologies, located at 69 Maplecrete Rd in Concord, Ontario, provides expert plumbing services to the local community. With a focus on efficient solutions, this business specializes in sewer line repairs, drain cleaning, and emergency plumbing services. Their commitment to quality and customer satisfaction has earned them a solid reputation in the area.</p><p>This local plumber utilizes advanced technology and skilled technicians to address a variety of plumbing issues. From residential to commercial projects, Global Sewer Technologies delivers reliable services tailored to meet specific needs. Their team is trained to handle everything from routine maintenance to urgent repairs, ensuring that clients receive prompt attention when problems arise.</p><p>With years of experience in the plumbing industry, Global Sewer Technologies stands out for its dedication to problem-solving. The company emphasizes preventive measures, helping customers avoid costly repairs in the future. Their transparent pricing and thorough assessments foster trust and confidence among clients. The business also stays updated with the latest plumbing techniques, ensuring effective and modern solutions.</p><p>Global Sewer Technologies offers a comprehensive range of plumbing services, demonstrating expertise and reliability in Concord, Ontario. Their focus on customer satisfaction and high-quality work sets them apart in the plumbing industry. Reach out to Global Sewer Technologies for dependable plumbing solutions in Concord.',
  '69 Maplecrete Rd',
  'Canada',
  'ON',
  'Concord',
  'L4K 1E5',
  'info@globalsewer.com',
  'canada/concord/home-services/global-sewer-technologies',
  'ChIJmwSz8rMvK4gRDfUKhUiV9Mo',
  43.7904809,
  -79.519591,
  '19057386704',
  'https://www.kwikr.ca/pictures/profile/pimage-988.jpg',
  'Plumbing',
  'Growth Plan',
  989,
  'http://globalsewer.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Plomberie et Chauffage St Hyacinthe Inc',
  '<p>Plomberie et Chauffage St-Hyacinthe Inc offers comprehensive plumbing and heating services in Saint-Hyacinthe, Quebec. Established in 1954, this family-owned business has built a strong reputation for its expertise in installation, sales, and repairs. Serving the Rive-Sud area, the company addresses a wide range of plumbing and heating needs for both residential and commercial clients.</p><p>The team at Plomberie et Chauffage St-Hyacinthe focuses on delivering reliable solutions tailored to each client''s specific requirements. With decades of experience, the professionals understand the intricacies of plumbing systems and heating solutions. This knowledge ensures efficient service while maintaining high standards of quality and safety.</p><p>Offering both installation and repair services, Plomberie et Chauffage St-Hyacinthe specializes in various heating systems and plumbing fixtures. The company’s commitment to customer satisfaction is evident in its prompt service and thorough approach to problem-solving. Whether it’s a minor repair or a major installation, the skilled technicians are equipped to handle all challenges effectively.</p><p>With a long-standing presence in the community, Plomberie et Chauffage St-Hyacinthe has become a trusted name for plumbing and heating services. The blend of experience, dedication, and quality service sets this company apart. For expert plumbing and heating solutions in Saint-Hyacinthe, reach out to Plomberie et Chauffage St-Hyacinthe Inc today.</p>',
  '585 Av. Brodeur',
  'Canada',
  'QC',
  'Saint-Hyacinthe',
  'J2S 4J6',
  'plomberie@pcsh.ca',
  'canada/saint-hyacinthe/home-services/plomberie-et-chauffage-st-hyacinthe-inc',
  'ChIJ6zSTeGNOyEwRMgCATRq9ql0',
  45.6272454,
  -72.9426673,
  '14507747991',
  'https://www.kwikr.ca/pictures/profile/pimage-987.jpg',
  'Plumbing',
  'Growth Plan',
  988,
  'https://www.plomberieetchauffagesthyacinthe.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Plomberie Charbonneau Inc',
  '<p>Plomberie Charbonneau Inc, located at 1955 Rue Cabot in Montreal, Quebec, excels in providing personalized plumbing, heating, and air conditioning services. This local business operates 24 hours a day, ensuring reliable and tailored expertise for various plumbing needs. With a team of over 500 experienced plumbers, each trained in specialized techniques, the company guarantees quality and professionalism in every project.</p><p>The services offered by Plomberie Charbonneau include installation, repair, and maintenance, all adhering to the regulations outlined in the National Plumbing Code of Canada. This commitment to excellence ensures that every client receives courteous service and respect for warranties. The extensive training of the plumbers contributes to a high standard of workmanship, fostering trust within the Montreal community.</p><p>Plomberie Charbonneau Inc has built a reputation for reliability and efficiency, making it a go-to choice for plumbing issues in Montreal. The combination of a skilled workforce and a commitment to customer satisfaction sets this business apart in the competitive plumbing industry. Clients can expect timely responses and effective solutions for their plumbing, heating, and air conditioning needs.</p><p>With a comprehensive range of services and a dedicated team, Plomberie Charbonneau Inc remains a key player in the local plumbing sector. Contact Plomberie Charbonneau Inc for all plumbing needs in Montreal, Quebec, and experience quality service firsthand.</p>',
  '1955 Rue Cabot',
  'Canada',
  'QC',
  'Montreal',
  'H4E 1E2',
  'recevables@plomberie.com',
  'canada/montreal/home-services/plomberie-charbonneau-inc',
  'ChIJD274KZIQyUwRo6_hRLkaCkg',
  45.4656895,
  -73.5902783,
  '15147663531',
  'https://www.kwikr.ca/pictures/profile/pimage-986.jpg',
  'Plumbing',
  'Growth Plan',
  987,
  'https://plomberie.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Trust It Plumbing',
  '<p>Trust It Plumbing operates in Vancouver, British Columbia, providing a range of plumbing services tailored to meet the needs of the local community. This professional and experienced plumbing company specializes in trenchless water mains, camera inspections, perimeter drainage, sewer mains, hot water tanks, and sump pumps, among other services. Trust It Plumbing is dedicated to delivering fast, friendly, and reliable service, ensuring that plumbing issues are resolved efficiently.</p> <p>The company focuses on customer satisfaction and timely response to plumbing emergencies. Trust It Plumbing understands that plumbing problems can arise unexpectedly, which is why they are available for emergency calls. Their team of skilled professionals is equipped to handle various plumbing challenges, ensuring that residents of Metro Vancouver receive the highest quality service. With a commitment to excellence, Trust It Plumbing has built a reputation for reliability and professionalism in the local area.</p> <p>Offering a comprehensive array of plumbing solutions, Trust It Plumbing stands ready to assist with both routine maintenance and urgent repairs. Their expertise in advanced plumbing techniques, such as trenchless technology, sets them apart in the industry. With a focus on delivering effective solutions, Trust It Plumbing ensures that every customer receives the service they deserve. Contact Trust It Plumbing today for plumbing services in Vancouver, British Columbia.</p>',
  '230-997 Seymour St',
  'Canada',
  'BC',
  'Vancouver',
  'V6B 3M1',
  'trustitplumbing@gmail.com',
  'canada/vancouver/home-services/trust-it-plumbing',
  'ChIJc73hTZhzhlQRY3CDUDY5KK8',
  49.2789453,
  -123.1219901,
  '16044422069',
  'https://www.kwikr.ca/pictures/profile/pimage-985.jpg',
  'Plumbing',
  'Growth Plan',
  986,
  'https://www.trustitplumbing.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'BW Bouwman Plumbing Ltd',
  '<p>BW Bouwman Plumbing Ltd provides expert plumbing services in Rocky Mountain House, Alberta. This local business specializes in residential and commercial plumbing solutions, ensuring high-quality workmanship and customer satisfaction. With a focus on reliable service, BW Bouwman Plumbing Ltd has established a reputation for prompt and efficient plumbing repairs, installations, and maintenance.</p> <p>The team at BW Bouwman Plumbing Ltd brings years of experience to every job. They handle a variety of plumbing tasks, including leak detection, drain cleaning, and water heater installation. Customers appreciate the straightforward approach and clear communication throughout the service process. The business prioritizes using quality materials and modern techniques, contributing to long-lasting results.</p> <p>Community feedback highlights the professionalism and dependability of BW Bouwman Plumbing Ltd. Many clients commend the team''s ability to resolve plumbing issues quickly, minimizing disruption in their homes or businesses. The company’s commitment to excellence is evident in its dedication to meeting the unique needs of each customer.</p> <p>BW Bouwman Plumbing Ltd offers comprehensive plumbing solutions tailored to the Rocky Mountain House area. Their strengths lie in reliable service, skilled technicians, and a customer-first approach. This business continues to grow through positive word-of-mouth and consistent service quality. Reach out to BW Bouwman Plumbing Ltd for all plumbing needs in Rocky Mountain House, Alberta. </p>',
  '4436 47 Ave',
  'Canada',
  'AB',
  'Rocky Mountain House',
  'T4T 1A7',
  'bou2@telus.net',
  'canada/rocky-mountain-house/home-services/bw-bouwman-plumbing-ltd',
  'ChIJVVWFTy7ZdVMRsTPGT7G6CHg',
  52.3708264,
  -114.9070976,
  '14038454545',
  NULL,
  'Plumbing',
  'Growth Plan',
  985,
  'http://www.bouwmanplumbing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Kits Plumbing and Heating',
  '<p>Kits Plumbing and Heating, located at 2288 W Broadway #324 in Vancouver, British Columbia, specializes in comprehensive plumbing and heating services. With over 13 years of experience, this business excels in new construction and renovations, plumbing repairs, and the maintenance, repair, and installation of hot water tanks, furnaces, HVAC systems, drainage, air conditioning, heat pumps, and boilers. Kits Plumbing and Heating holds the TSBC Licence # LGA0201478, ensuring reliable and professional service.</p><p>This local business prioritizes punctuality and quality, offering dependable HVAC services that customers can trust. The commitment to customer satisfaction has fostered strong relationships and a solid reputation within the community. Kits Plumbing and Heating understands the importance of timely service, which is why they ensure that every call results in effective solutions tailored to individual needs.</p><p>The team of expert plumbers is dedicated to providing high-quality workmanship, whether for routine maintenance or urgent repairs. Customers appreciate the straightforward approach and clear communication, which simplifies the process of addressing plumbing and heating issues. Regular clients often highlight the professionalism and reliability of the service, making Kits Plumbing and Heating a preferred choice in Vancouver.</p><p>Kits Plumbing and Heating offers a wide range of plumbing and heating solutions, emphasizing quality and customer care. With a strong reputation built over years, this business continues to serve the Vancouver area effectively. Reach out to Kits Plumbing and Heating for exceptional services in Vancouver, British Columbia.</p>',
  '2288 W Broadway #324',
  'Canada',
  'BC',
  'Vancouver',
  'V6K 0B3',
  'kelly@kitsplumbingandheating.com',
  'canada/vancouver/home-services/kits-plumbing-and-heating',
  'ChIJg-YPbt5zhlQRerZ4NnuyeD0',
  49.2636205,
  -123.1572386,
  '17788753525',
  'https://www.kwikr.ca/pictures/profile/pimage-983.jpg',
  'Plumbing',
  'Growth Plan',
  984,
  'https://kitsplumbingandheating.com/?utm_campaign=gmb',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Plomberie de la Capitale',
  '<p>Plomberie de la Capitale provides exceptional plumbing services in L''Ancienne-Lorette, Quebec, with over 35 years of industry experience. This local business specializes in heavy residential plumbing, ensuring that no plumbing issue is too large to handle. The team has established a strong reputation for quality service and superior expertise, making it a trusted choice for residents.</p> <p>This company focuses on delivering timely and effective solutions for various plumbing needs. Whether dealing with complex installations or urgent repairs, Plomberie de la Capitale maintains high standards of professionalism. Their commitment to customer satisfaction reflects in their work ethic and approach to every project. The skilled technicians are equipped to manage a wide range of plumbing challenges, providing reliable service that residents can count on.</p> <p>The team at Plomberie de la Capitale demonstrates a deep understanding of plumbing systems, ensuring that every job is completed efficiently and effectively. Their extensive experience in the field allows them to identify issues quickly and implement appropriate solutions. This level of expertise sets them apart in the competitive plumbing industry.</p> <p>Plomberie de la Capitale offers comprehensive plumbing services, combining experience with a commitment to excellence. Their focus on heavy residential plumbing ensures that they can tackle any challenge. Connect with Plomberie de la Capitale in L''Ancienne-Lorette for all plumbing needs.',
  '6345 Bd Wilfrid-Hamel local 102',
  'Canada',
  'QC',
  'L''Ancienne-Lorette',
  'G2E 5W2',
  'service@plomberiedelacapitale.com',
  'canada/l-ancienne-lorette/home-services/plomberie-de-la-capitale',
  'ChIJ8TaxE1tmB0ERxlv538tHtmU',
  46.794756,
  -71.350704,
  '14187805710',
  'https://www.kwikr.ca/pictures/profile/pimage-982.jpg',
  'Plumbing',
  'Growth Plan',
  983,
  'http://plomberiedelacapitale.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Precision Plumbing Calgary',
  '<p>Precision Plumbing Calgary provides exceptional plumbing, gas fitting, and drain cleaning services to both commercial and residential customers in Calgary, Alberta. Established in 2009, this local business has built a reputation for delivering reliable and professional service. With a commitment to quality, Precision Plumbing collaborates with leading suppliers to ensure the highest standards in plumbing supplies and services.</p> <p>The team at Precision Plumbing consists of skilled plumbers who understand the urgency of plumbing emergencies. They prioritize customer satisfaction and work diligently to resolve issues efficiently. Whether dealing with a leaky faucet or a major drain blockage, the experienced professionals approach each task with expertise and care. The business serves not only Calgary but also the surrounding communities, including Cochrane and Airdrie, ensuring a broad reach for quality plumbing solutions.</p> <p>Precision Plumbing''s dedication to reasonable rates and superior service has garnered a loyal customer base. Their focus on treating clients and properties with respect sets them apart in the competitive plumbing market. Clients can expect timely responses and thorough work from the moment they contact the team to the completion of the project.</p> <p>Precision Plumbing Calgary excels in providing a range of plumbing services with a strong emphasis on customer care. Their expertise and commitment to quality make them a trusted choice for plumbing needs. Reach out to Precision Plumbing Calgary for reliable plumbing services in Alberta. </p>',
  '1011 57 Ave NE',
  'Canada',
  'AB',
  'Calgary',
  'T2E 8X9',
  'service@precision-plumbing.ca',
  'canada/calgary/home-services/precision-plumbing-calgary',
  'ChIJl8jrYrJlcVMRuOWuLgGl4g4',
  51.1050515,
  -114.0404558,
  '14032415200',
  'https://www.kwikr.ca/pictures/profile/pimage-981.jpg',
  'Plumbing',
  'Growth Plan',
  982,
  'https://precision-plumbing.ca/?utm_source=gmb&utm_medium=calgary',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Urban Plumbing & Heating Ltd.',
  '<p>Urban Plumbing & Heating Ltd. provides reliable plumbing services to the residents of Burnaby, British Columbia. This local business specializes in a variety of plumbing solutions, including installation, maintenance, and emergency repairs. With a commitment to customer satisfaction, Urban Plumbing & Heating Ltd. has built a reputation for quality and efficiency in the community.</p><p>The skilled team at Urban Plumbing & Heating Ltd. possesses extensive knowledge and experience in the plumbing industry. They handle everything from routine maintenance to complex plumbing issues, ensuring that homes and businesses operate smoothly. Their prompt response to emergency situations demonstrates their dedication to serving the Burnaby area effectively.</p><p>Urban Plumbing & Heating Ltd. utilizes modern technology and techniques to deliver superior service. The company emphasizes transparency and integrity, providing clients with clear estimates and timelines for projects. This approach fosters trust and long-term relationships with customers, setting them apart in the competitive plumbing market.</p><p>With a focus on quality workmanship and customer care, Urban Plumbing & Heating Ltd. remains a top choice for plumbing needs in Burnaby. Their expertise and commitment to excellence contribute to their strong standing in the community. Contact Urban Plumbing & Heating Ltd. at their location on Thunderbird Crescent for all plumbing services in Burnaby, British Columbia.</p>',
  '108-3191 Thunderbird Crescent',
  'Canada',
  'BC',
  'Burnaby',
  'V5A 3G1',
  'service@urbanph.com',
  'canada/burnaby/home-services/urban-plumbing-heating-ltd',
  'ChIJJwaVnyZ5hlQRWX33-7GvIxw',
  49.2560201,
  -122.9215877,
  '16047297519',
  NULL,
  'Plumbing',
  'Growth Plan',
  981,
  'https://urbanph.com/contact/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Drain Experts Plumbing',
  '<p>Drain Experts Plumbing provides reliable plumbing services in Brampton, Ontario. This local business excels in various plumbing solutions, including drain cleaning, plumbing installation, camera inspections, waterproofing, leak detection, and sump pump replacement. Open 24/7, Drain Experts Plumbing ensures that residents receive prompt assistance whenever needed. The company prides itself on its knowledgeable staff and fair pricing.</p><p>With a commitment to quality, Drain Experts Plumbing operates as a locally owned and operated business. The team understands the importance of being on time and offers free estimates for all services. Licensed and insured, the company builds trust within the community by delivering expert plumbing services that residents can rely on. The focus remains on providing efficient solutions to common plumbing issues, ensuring customer satisfaction at every step.</p><p>Drain Experts Plumbing has gained a reputation for its thorough approach to plumbing challenges. Utilizing advanced techniques, including camera inspections, the company identifies and addresses problems effectively. The experienced team is dedicated to offering solutions that enhance the safety and functionality of plumbing systems. Achievements include a strong track record of satisfied customers and a commitment to maintaining high standards in service delivery.</p><p>Drain Experts Plumbing offers a comprehensive range of plumbing services backed by a knowledgeable team. Their dedication to customer service and fair pricing positions them as a trustworthy choice for plumbing needs in Brampton, Ontario. Connect with Drain Experts Plumbing for reliable plumbing solutions in the area.',
  '215 Queen St E',
  'Canada',
  'ON',
  'Brampton',
  'L6W 0A9',
  'drainexpertsplumbing@gmail.com',
  'canada/brampton/home-services/drain-experts-plumbing',
  'ChIJx7tc5rYVK4gRvWgo9Gz5IYM',
  43.6945449,
  -79.7498572,
  '14166027886',
  'https://www.kwikr.ca/pictures/profile/pimage-979.jpg',
  'Plumbing',
  'Growth Plan',
  980,
  'https://www.drainexpertsplumbing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Apple Plumbing & Heating',
  '<p>Apple Plumbing & Heating provides essential plumbing, heating, and cooling services to the Richmond area in British Columbia. This local business excels in offering reliable solutions for residential and commercial needs. With a strong commitment to customer satisfaction, Apple Plumbing & Heating has established a reputation for quality workmanship and prompt service.</p> <p>The team at Apple Plumbing & Heating consists of skilled professionals who understand the intricacies of plumbing systems. They offer a wide range of services, including emergency repairs, routine maintenance, and installation of heating and cooling systems. This expertise ensures that customers receive the best solutions tailored to their specific requirements. The business operates throughout Richmond, Vancouver, and the Lower Mainland, providing accessible and efficient services to a diverse clientele.</p> <p>Apple Plumbing & Heating prioritizes safety and reliability in all projects. Their technicians are equipped with the latest tools and technology to handle any plumbing challenge. Customer feedback highlights the professionalism and dedication of the staff, making them a trusted choice for plumbing needs in the region. The business also emphasizes eco-friendly practices, contributing to sustainable living in the community.</p> <p>With a focus on quality service and customer care, Apple Plumbing & Heating remains a leading choice for plumbing, heating, and cooling solutions in Richmond, British Columbia. Connect with Apple Plumbing & Heating for expert services in the local area.</p>',
  '9151 Chapmond Crescent',
  'Canada',
  'BC',
  'Richmond',
  'V7E 1M6',
  'info@appleplumbingandheating.ca',
  'canada/richmond/home-services/apple-plumbing-heating',
  'ChIJ5cOAAvAKhlQR0cnwi3CoRNk',
  49.142307,
  -123.1903622,
  '16046184786',
  'https://www.kwikr.ca/pictures/profile/pimage-978.jpg',
  'Plumbing',
  'Growth Plan',
  979,
  'http://www.appleplumbingandheating.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'A E Air Plumbing & Heating Inc.',
  '<p>A E Air Plumbing & Heating Inc. provides essential HVAC and plumbing services to the Medicine Hat community in Alberta. This local business operates 24 hours a day for emergency calls, ensuring that residents have access to reliable plumbing solutions at any time. The office remains open Monday through Friday from 8 am to 4 pm, offering a range of services tailored to meet the needs of the local population.</p><p>With a commitment to quality and customer satisfaction, A E Air Plumbing & Heating Inc. focuses on delivering efficient plumbing and heating solutions. The team of skilled professionals is equipped to handle various plumbing issues, from routine maintenance to urgent repairs. This dedication to service has earned the business a positive reputation within the community.</p><p>Being locally owned and operated, A E Air Plumbing & Heating Inc. understands the unique needs of Medicine Hat residents. The business prioritizes quick response times and effective solutions, making it a trusted choice for plumbing and HVAC needs. Customers can expect transparent communication and reliable service, which has contributed to the company’s growing list of satisfied clients.</p><p>A E Air Plumbing & Heating Inc. excels in providing HVAC and plumbing services to the Medicine Hat area. The team is ready to assist with any plumbing emergencies or heating needs. Reach out to A E Air Plumbing & Heating Inc. in Medicine Hat for dependable service and expertise.</p>',
  '734 15 St SW',
  'Canada',
  'AB',
  'Medicine Hat',
  'T1A 4W6',
  'admin@aeair.ca',
  'canada/medicine-hat/home-services/a-e-air-plumbing-heating-inc',
  'ChIJqR96xYACiW8RX8FffqiLgUg',
  50.0254214,
  -110.7035098,
  '14039281625',
  'https://www.kwikr.ca/pictures/profile/pimage-977.jpg',
  'Plumbing',
  'Growth Plan',
  978,
  'https://aeair.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Fowler Plumbing',
  '<p>Fowler Plumbing, located at 3215 Jefferson Blvd Unit 301 in Windsor, Ontario, delivers exceptional plumbing services to the local community. This business specializes in plumbing repair and installation, ensuring that every customer receives top-notch service. With years of experience, the team at Fowler Plumbing possesses the knowledge necessary to tackle a variety of plumbing issues, from leaky faucets to new toilet installations.</p><p>The commitment to detail sets Fowler Plumbing apart from competitors. Each project receives careful attention, ensuring that every job is completed to the highest standard. Customer satisfaction remains the primary focus, with the team dedicated to treating each client with respect and dignity. This approach fosters trust and builds long-lasting relationships within the community.</p><p>Fowler Plumbing has established a reputation for reliability and professionalism in Windsor. The skilled plumbers are equipped to handle both residential and commercial plumbing needs, offering tailored solutions that meet the unique requirements of each client. The emphasis on quality workmanship and customer care has made Fowler Plumbing a preferred choice for many local residents.</p><p>Fowler Plumbing provides a comprehensive range of plumbing services, prioritizing customer satisfaction and quality work. The experienced team ensures that every plumbing issue is addressed promptly and efficiently. For reliable plumbing services in Windsor, contact Fowler Plumbing today. </p>',
  '3215 Jefferson Blvd Unit 301',
  'Canada',
  'ON',
  'Windsor',
  'N8T 2W7',
  'fowlerplumbing@gmail.com',
  'canada/windsor/home-services/fowler-plumbing',
  'ChIJx1Zta7UqJYgR0F7iztGbC9c',
  42.2924446,
  -82.942414,
  '15199793747',
  'https://www.kwikr.ca/pictures/profile/pimage-976.jpg',
  'Plumbing',
  'Growth Plan',
  977,
  'https://fowlerplumbing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Heartland Plumbing and Heating Ltd.',
  '<p>Heartland Plumbing and Heating Ltd. provides expert plumbing services, heating solutions, and emergency repairs in Sherwood Park, Alberta. This premier company specializes in a wide range of services including furnaces, boilers, gasfitting, and air conditioning. With a team of certified professionals, Heartland Plumbing ensures high-quality service for residential and commercial clients.</p> <p>The company employs Journeyman Plumbers, Gasfitters, Electricians, and Refrigeration/Air Conditioning Technicians, all fully certified with Alberta and Industry Training (AIT). Heartland Plumbing and Heating Ltd. maintains all necessary business licenses and is fully insured and bonded, ensuring peace of mind for customers. The commitment to safety is evident as all technicians undergo drug and alcohol testing.</p> <p>Heartland Plumbing has built a reputation for reliability and efficiency in Sherwood Park and Strathcona County. The emergency repair services offered are available around the clock, making it a trusted choice for urgent plumbing and heating needs. The company’s all-inclusive mechanical and electrical service approach sets it apart in the industry.</p> <p>Heartland Plumbing and Heating Ltd. excels in providing comprehensive plumbing and heating solutions with a focus on customer satisfaction. The skilled team is ready to tackle any challenge, ensuring that homes and businesses remain comfortable and functional. Connect with Heartland Plumbing and Heating Ltd. in Sherwood Park for all plumbing and heating service needs.</p>',
  '12 Hillview Crescent',
  'Canada',
  'AB',
  'Sherwood Park',
  'T8A 5J9',
  'heartlandgoc@gmail.com',
  'canada/sherwood-park/home-services/heartland-plumbing-and-heating-ltd',
  'ChIJQfI25KwXoFMRbIAV7qAP9zQ',
  53.5405496,
  -113.252639,
  '17808519090',
  'https://www.kwikr.ca/pictures/profile/pimage-975.jpg',
  'Plumbing',
  'Growth Plan',
  976,
  'https://heartlandplumbingandheating.ca/sherwood-park/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Khaira Bros Plumbing and Heating Ltd',
  '<p>Khaira Bros Plumbing and Heating Ltd provides essential plumbing and heating services to Surrey, British Columbia, and surrounding areas such as Langley, Delta, Burnaby, South Surrey, White Rock, Richmond, Vancouver, and Coquitlam. This local business specializes in a wide range of services including repairs, installations, and maintenance, ensuring homes and businesses remain comfortable and functional.</p><p>With a commitment to quality and customer satisfaction, Khaira Bros Plumbing and Heating Ltd has built a reputation for reliability and efficiency. The team consists of skilled professionals who understand the intricacies of plumbing and heating systems. They utilize advanced techniques and tools to address various issues, from minor leaks to complex heating installations. The company''s focus on timely service helps minimize disruptions for clients.</p><p>Khaira Bros Plumbing and Heating Ltd emphasizes transparency in pricing and service delivery. Clients appreciate the straightforward approach, which fosters trust and long-term relationships. The business remains dedicated to continuous improvement and staying updated with industry standards. This ensures that clients receive the best solutions tailored to their specific needs.</p><p>Offering a comprehensive range of plumbing and heating services, Khaira Bros Plumbing and Heating Ltd demonstrates expertise and dedication in every project. Their strong local presence and commitment to the community contribute to their ongoing success. Connect with Khaira Bros Plumbing and Heating Ltd for reliable services in Surrey, British Columbia.</p>',
  '8958 149 St',
  'Canada',
  'BC',
  'Surrey',
  'V3R 6W1',
  'info@khairabros.ca',
  'canada/surrey/home-services/khaira-bros-plumbing-and-heating-ltd',
  'ChIJAQDMwFfXhVQRRy8wryRedL8',
  49.1656345,
  -122.8096268,
  '16048316300',
  NULL,
  'Plumbing',
  'Growth Plan',
  975,
  'http://www.khairabros.ca/about-us-2/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Plomberie D Sévigny Inc',
  '<p>Plomberie D Sévigny Inc provides reliable plumbing services in Val-d''Or, Quebec. This business operates in residential, commercial, and industrial sectors, establishing a strong reputation in the Vallée-de-l''Or region. Their expertise covers a wide range of plumbing needs, ensuring quality solutions for various clients.</p> <p>The company specializes in both routine maintenance and emergency plumbing services. Their team of skilled plumbers addresses issues like leaks, clogs, and installations efficiently. With a commitment to customer satisfaction, Plomberie D Sévigny Inc emphasizes timely service and effective problem-solving. They utilize modern techniques and tools, ensuring high standards in all projects.</p> <p>Plomberie D Sévigny Inc has built a solid track record of successful projects across different sectors. Their experience in residential plumbing makes them a trusted choice for homeowners. In commercial settings, they understand the unique demands of businesses and provide tailored solutions. Industrial clients benefit from their extensive knowledge and capabilities, ensuring that operations run smoothly.</p> <p>This business prioritizes quality workmanship and customer care. Their dedication to excellence has earned them a loyal client base in Val-d''Or and surrounding areas. Plomberie D Sévigny Inc continues to grow, adapting to the evolving needs of the community. For reliable plumbing services in Val-d''Or, contact Plomberie D Sévigny Inc at 1124 Chem. Sullivan, Quebec. </p>',
  '1124 Chem. Sullivan',
  'Canada',
  'QC',
  'Val-d''Or',
  'J9P 1L3',
  'estimation@plomberiesevigny.com',
  'canada/val-d-or/home-services/plomberie-d-sévigny-inc',
  'ChIJoaYIWQlT30wRuelTaafy6Bw',
  48.1048846,
  -77.7955924,
  '18198246005',
  'https://www.kwikr.ca/pictures/profile/pimage-973.jpg',
  'Plumbing',
  'Growth Plan',
  974,
  'https://plomberiesevigny.com/',
  NULL,
  NULL,
  NULL,
  NULL
);
