INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Bois Franc de la Capitale 1991 Inc',
  '<p>Bois Franc de la Capitale 1991 Inc is a premier flooring store located in Québec City, Quebec. Specializing in a wide range of flooring options, this business offers hardwood, laminate, and vinyl flooring solutions tailored to diverse customer needs. With years of experience, Bois Franc de la Capitale 1991 Inc has built a reputation for quality products and exceptional service.</p><p>This flooring store provides expert guidance in selecting the right flooring materials for residential and commercial spaces. The knowledgeable staff assists customers in understanding the benefits of different flooring types, ensuring informed decisions. Bois Franc de la Capitale 1991 Inc prioritizes customer satisfaction, offering professional installation services that guarantee optimal results.</p><p>Located at 2700 Rue Jean-Perrin #110, the store is easily accessible to residents and businesses in the area. The commitment to high standards and attention to detail sets this flooring store apart in Québec City. Customers appreciate the extensive selection of flooring styles and finishes available, catering to various aesthetic preferences and functional requirements.</p><p>Bois Franc de la Capitale 1991 Inc excels in providing quality flooring solutions that enhance any space. With a focus on customer service and product knowledge, this business meets the demands of the local community. For flooring needs in Québec City, reach out to Bois Franc de la Capitale 1991 Inc for reliable and professional assistance.</p>',
  '2700 Rue Jean-Perrin #110',
  'Canada',
  'QC',
  'Québec City',
  'G2C 1S9',
  'acoghill@valleystonescapes.ca',
  'canada/québec-city/home-services/bois-franc-de-la-capitale-1991-inc',
  'ChIJYdEq8oSXuEwRszWVnMf9ZrM',
  46.8221269,
  -71.3125578,
  '14188470661',
  'https://www.kwikr.ca/pictures/profile/pimage-282.jpg',
  'Flooring=>Laminate Flooring',
  'Pay-as-you-go',
  298,
  'https://flordeco.ca/fr/marchand/quebec/planchers-bfc',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Ashley Fine Floors',
  '<p>Ashley Fine Floors provides a comprehensive range of flooring solutions in Edmonton, Alberta. This family-owned and operated business has been serving the community for over 30 years, establishing a reputation for quality and reliability. The store offers various flooring options, including hardwood, laminate, tile, and carpet, catering to both residential and commercial needs.</p> <p>The expertise of Ashley Fine Floors ensures that customers receive personalized service tailored to their specific requirements. Knowledgeable staff guide clients through the selection process, helping to identify the best materials for each project. The business prides itself on its extensive inventory, featuring products from leading manufacturers. This commitment to quality ensures that every installation meets high standards of durability and aesthetics.</p><p>In addition to a wide selection of flooring types, Ashley Fine Floors also offers professional installation services. This comprehensive approach simplifies the renovation process, allowing customers to enjoy a seamless experience from selection to completion. The company’s dedication to customer satisfaction has resulted in a loyal client base and numerous positive reviews throughout Edmonton.</p><p>Ashley Fine Floors remains a trusted destination for flooring solutions, combining experience, quality products, and exceptional service. The business continues to thrive in Edmonton, making it a go-to choice for all flooring needs. Visit Ashley Fine Floors at 14340 111 Ave NW, Edmonton, Alberta, T5M 2P4 for expert guidance and quality flooring solutions.</p>',
  '14340 111 Ave NW',
  'Canada',
  'AB',
  'Edmonton',
  'T5M 2P4',
  'mciupa@gmail.com',
  'canada/edmonton/home-services/ashley-fine-floors',
  'ChIJK5bk4PwjoFMR1koH05R268w',
  53.5592231,
  -113.569799,
  '17804549503',
  'https://www.kwikr.ca/pictures/profile/pimage-281.jpg',
  'Flooring=>Laminate Flooring',
  'Pay-as-you-go',
  297,
  'https://ashleyfinefloors.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Alexanian Carpet & Flooring & Rug Cleaning',
  '<p>Alexanian Carpet & Flooring & Rug Cleaning serves Brantford, Ontario, with a comprehensive range of flooring solutions. Established in 1925, this flooring store has built a strong reputation for quality and customer service. The business offers a variety of products, including broadloom carpet, area rugs, ceramic tile, hardwood flooring, laminates, vinyl flooring, cork, engineered flooring, and window coverings. With a commitment to excellence, Alexanian continues to meet the needs of homeowners and businesses alike.</p><p>The history of Alexanian Carpet & Flooring is rooted in a dedication to customer satisfaction. Founder Aris Alexanian created a culture focused on service and quality, a legacy that remains integral to the company’s operations today. The flooring store emphasizes providing the latest styles and durable materials, ensuring customers find the perfect match for their homes. Each product is carefully selected to enhance both aesthetic appeal and functionality.</p><p>Renovating or moving into a new space can be overwhelming, but Alexanian simplifies the process. The knowledgeable staff assists clients in selecting the right flooring options tailored to their specific needs. This personalized service sets Alexanian apart in the competitive flooring market.</p><p>Alexanian Carpet & Flooring & Rug Cleaning excels in delivering high-quality flooring solutions and customer service. The business’s long-standing commitment to excellence makes it a trusted choice in Brantford. Visit 57 Copernicus Blvd in Brantford for exceptional flooring services.</p>',
  '57 Copernicus Blvd',
  'Canada',
  'ON',
  'Brantford',
  'N3P 1N4',
  'stephen@jenkynscoatings.com',
  'canada/brantford/home-services/alexanian-carpet-flooring-rug-cleaning',
  'ChIJlctv-KhlLIgRjuz7i-8oodE',
  43.1801605,
  -80.2409958,
  '15197525493',
  'https://www.kwikr.ca/pictures/profile/pimage-280.jpg',
  'Flooring=>Laminate Flooring',
  'Pay-as-you-go',
  296,
  'https://www.alexanian.com/stores/detail?selid=3-Brantford&selid=3-Brantford',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'End Of The Roll Flooring Centres - Pickering',
  '<p>End Of The Roll Flooring Centres in Pickering, Ontario, serves as a comprehensive flooring store, offering a vast selection of brand name flooring options. Customers can find carpet, area rugs, luxury vinyl, laminate, tile, stone, decking, and athletic flooring, along with solid and engineered hardwood. This store provides everything necessary for installation and maintenance, ensuring a complete flooring solution.</p><p>End Of The Roll Flooring Centres has established a reputation for quality and variety. The knowledgeable staff assists customers in selecting the right flooring, addressing any installation queries, and connecting them with trusted installation partners. This commitment to customer service enhances the shopping experience, making it efficient and enjoyable.</p><p>With a focus on providing immediate access to flooring solutions, End Of The Roll Pickering allows customers to take home their selections today. The extensive inventory caters to various styles and preferences, making it a go-to destination for homeowners and contractors alike. The store''s environment is designed to make every visit feel special, akin to walking down a red carpet.</p><p>End Of The Roll Flooring Centres in Pickering, Ontario, excels in delivering a diverse range of flooring products and exceptional customer support. The combination of quality materials and expert assistance positions this store as a leader in the flooring industry. Visit End Of The Roll Flooring Centres today to explore the extensive selection available in Pickering.</p>',
  '1095 Kingston Rd Unit 2',
  'Canada',
  'ON',
  'Pickering',
  'L1V 1B5',
  'info@mrmarbleandstone.com',
  'canada/pickering/home-services/end-of-the-roll-flooring-centres-pickering',
  'ChIJmbKn5gbf1IkRAZDnFC2ZgtA',
  43.8274996,
  -79.0985725,
  '19054206001',
  'https://www.kwikr.ca/pictures/profile/pimage-279.jpg',
  'Flooring=>Laminate Flooring',
  'Pay-as-you-go',
  295,
  'https://endoftheroll.com/?location=pickering',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Modern Hardwood',
  '<p>Modern Hardwood, located at 443 Eastchester Ave E #2 in St. Catharines, Ontario, specializes in providing high-quality flooring solutions. This flooring store offers a wide range of products, including hardwood, laminate, and vinyl flooring, catering to both residential and commercial needs. With a commitment to quality and customer satisfaction, Modern Hardwood has established itself as a reliable choice for flooring in the local area.</p><p>The store features an extensive selection of flooring options that suit various styles and budgets. Knowledgeable staff members assist customers in choosing the right materials for their projects, ensuring a seamless experience from selection to installation. Modern Hardwood emphasizes durability and aesthetic appeal, making it a go-to destination for homeowners and contractors alike.</p><p>In addition to flooring products, Modern Hardwood provides expert installation services. The team is skilled in ensuring that every installation meets high standards of craftsmanship. This dedication to quality has earned the business a strong reputation in St. Catharines and surrounding areas.</p><p>Modern Hardwood excels in delivering exceptional flooring solutions backed by professional service. The combination of a diverse product range and expertise in installation sets this business apart. For those seeking reliable flooring options in St. Catharines, Modern Hardwood remains a top choice. Connect with Modern Hardwood today for all flooring needs in St. Catharines, Ontario.</p>',
  '443 Eastchester Ave E #2',
  'Canada',
  'ON',
  'St. Catharines',
  'L2M 6S2',
  'admin@foreverepoxy.ca',
  'canada/st-catharines/home-services/modern-hardwood',
  'ChIJpY8QwIZQ04kRT7RkLG_jbYs',
  43.1685905,
  -79.2072252,
  '19056824000',
  'https://www.kwikr.ca/pictures/profile/pimage-278.jpg',
  'Flooring=>Laminate Flooring',
  'Pay-as-you-go',
  294,
  'http://www.modernhardwood.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Flordeco Bernier',
  '<p>Flordeco Bernier operates as a premier flooring store located at 95 Rue Collard in Alma, Quebec. This business offers a comprehensive range of flooring solutions to meet diverse customer needs. With a team of qualified personnel, Flordeco Bernier provides expert advice and professional support for renovation projects. The store prides itself on its knowledgeable designers and installers who assist clients in making informed decisions about their flooring choices.</p><p>Flordeco Bernier specializes in various types of flooring, including hardwood, laminate, tile, and vinyl. The staff is dedicated to ensuring that each customer finds the perfect flooring option that aligns with their aesthetic preferences and functional requirements. The store''s commitment to quality and customer satisfaction has earned it a strong reputation within the Alma community.</p><p>Regular visits to Flordeco Bernier reveal a vibrant atmosphere where creativity meets practicality. Customers appreciate the personalized service and the expertise offered by the team. The store’s focus on building lasting relationships with clients contributes to its success and growth in the local market.</p><p>Flordeco Bernier provides valuable flooring solutions backed by a team of professionals ready to assist with renovations. The combination of quality products and dedicated service positions the business as a reliable choice for flooring needs in Alma, Quebec. Contact Flordeco Bernier today for expert assistance with flooring projects in the area.</p>',
  '95 Rue Collard',
  'Canada',
  'QC',
  'Alma',
  'G8B 1M7',
  'customerservice@armorrock.com',
  'canada/alma/home-services/flordeco-bernier',
  'ChIJZ3OQnSx26kwRjac211VYiKw',
  48.5457723,
  -71.6446432,
  '14186688731',
  'https://www.kwikr.ca/pictures/profile/pimage-277.jpg',
  'Flooring=>Laminate Flooring',
  'Pay-as-you-go',
  293,
  'https://flordeco.ca/pages/flordeco-alma-flordeco-bernier',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Floors By Design',
  '<p>Floors By Design, located in Regina, Saskatchewan, offers an extensive range of flooring solutions tailored to meet diverse customer needs. This flooring store features a large showroom showcasing products such as hardwood, laminate, cork, carpet, porcelain, ceramic, stone and glass tile, as well as vinyls and luxury vinyl plank (LVP). The store also provides in-floor heating options and Wedi Systems for added convenience.</p> <p>With a commitment to quality, Floors By Design employs skilled installers for all products, ensuring professional results for any project. Whether it is hardwood flooring, tile layering for kitchens and bathrooms, or carpet installation, experienced professionals handle every detail. Customers can also benefit from the opportunity to sign out material sample boards, allowing them to visualize how products will look in their own spaces. This hands-on approach helps streamline the selection process.</p> <p>Floors By Design emphasizes collaboration, encouraging customers to bring along cabinet, counter, and paint samples to assist in making informed choices. The combination of a diverse product range and expert installation services positions the store as a reliable choice for flooring needs in Regina.</p> <p>Explore the variety of flooring options and professional installation services available at Floors By Design. The dedication to customer satisfaction and quality makes this store a top choice for flooring solutions in Regina. Visit the showroom at 206 4 Ave E, Regina, Saskatchewan, to discover the perfect flooring today.</p>',
  '206 4 Ave E',
  'Canada',
  'SK',
  'Regina',
  'S4N 4Z6',
  'info@docteursablage.com',
  'canada/regina/home-services/floors-by-design',
  'ChIJ7dGDAaUfHFMRAcSu5w9og3E',
  50.4632111,
  -104.5803617,
  '13063596300',
  'https://www.kwikr.ca/pictures/profile/pimage-276.jpg',
  'Flooring=>Laminate Flooring',
  'Pay-as-you-go',
  292,
  'http://floorsbydesign.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Eden Tile-It Mount Hope',
  '<p>Eden Tile-It Mount Hope is a premier flooring store located at 3727 Hwy 6 in Mount Hope, Ontario. This business specializes in a wide range of flooring solutions, catering to both residential and commercial clients. With a commitment to quality and customer satisfaction, Eden Tile-It offers an extensive selection of tiles, hardwood, laminate, and vinyl flooring. The knowledgeable staff provides expert guidance to help customers choose the right materials for their projects.</p><p>The flooring industry has seen significant growth, and Eden Tile-It Mount Hope has positioned itself as a reliable source for high-quality products and services. The store features a diverse inventory that includes modern designs and classic styles, ensuring that every customer finds something that meets their aesthetic and functional needs. The team at Eden Tile-It is dedicated to providing personalized service, making the flooring selection process seamless and enjoyable.</p><p.Eden Tile-It Mount Hope prides itself on its strong community ties and its reputation for excellence. The business has received positive feedback for its competitive pricing and timely installation services. Customers appreciate the attention to detail and the commitment to ensuring each project is completed to the highest standards.</p><p.Eden Tile-It Mount Hope delivers exceptional flooring solutions, expert advice, and a wide selection of materials. This business continues to serve the Mount Hope area with dedication and integrity. Visit Eden Tile-It Mount Hope for quality flooring solutions that enhance any space.</p>',
  '3727 Hwy 6',
  'Canada',
  'ON',
  'Mount Hope',
  'L0R 1W0',
  'info@lbepoxyflooring.ca',
  'canada/mount-hope/home-services/eden-tile-it-mount-hope',
  'ChIJq6w38heOLIgRPywcmq51c5o',
  43.1410979,
  -79.9208724,
  '19056795669',
  'https://www.kwikr.ca/pictures/profile/pimage-275.jpg',
  'Flooring=>Laminate Flooring',
  'Pay-as-you-go',
  291,
  'http://www.tileit.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Alexanian Carpet & Flooring & Rug Cleaning',
  '<p>Alexanian Carpet & Flooring & Rug Cleaning provides comprehensive flooring solutions in Toronto, Ontario. Established in 1925, this flooring store offers a wide range of products, including broadloom carpet, area rugs, ceramic tile, hardwood flooring, laminates, vinyl flooring, cork, engineered flooring, and window coverings. The company has built a strong reputation based on its commitment to quality and customer service.</p><p>The legacy of Aris Alexanian, the founder, continues to influence the company’s operations. His dedication to customers and staff established a culture of excellence that persists today. Alexanian Carpet & Flooring prioritizes customer satisfaction, ensuring that each client finds the perfect flooring for their home. The extensive selection meets diverse styles and preferences, making it easy for customers to create inviting spaces.</p><p>Renovating a home or moving into a new space becomes an enjoyable experience with Alexanian’s expert guidance. The knowledgeable staff assists clients in selecting durable and stylish flooring options that enhance any room. The commitment to providing high-quality products and exceptional service has positioned Alexanian Carpet & Flooring as a trusted name in the local community.</p><p>This flooring store combines a rich history with modern offerings, ensuring customers receive the best in flooring solutions. Explore the variety of options available at Alexanian Carpet & Flooring & Rug Cleaning in Toronto. Connect with this local business to discover the perfect flooring for any project.</p>',
  '845 Eglinton Ave E',
  'Canada',
  'ON',
  'Toronto',
  'M4G 2L5',
  'importdata-238@kwikr.ca',
  'canada/toronto/home-services/alexanian-carpet-flooring-rug-cleaning',
  'ChIJ4yY8otjM1IkRhvLWngn4rG0',
  43.7128706,
  -79.3622252,
  '14166447596',
  'https://www.kwikr.ca/pictures/profile/pimage-274.jpg',
  'Flooring=>Laminate Flooring',
  'Pay-as-you-go',
  290,
  'https://www.alexanian.com/stores/detail?selid=17-Toronto-Laird&selid=17-Toronto-Laird',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Floortrends',
  '<p>Floortrends, located at 900 Division St #110 in Cobourg, Ontario, specializes in a comprehensive range of flooring solutions. This flooring store provides sales and installation of luxury vinyl, tile, carpet, area rugs, hardwood, laminate, backsplashes, showers, and commercial flooring products. With the largest selection of flooring in Cobourg and Northumberland County, Floortrends caters to diverse customer needs.</p> <p>The team at Floortrends consists of flooring experts dedicated to assisting customers with their projects. An online visualization tool is available to help clients envision their chosen flooring in their spaces. The user-friendly website allows browsing of products conveniently from home, streamlining the shopping experience. Customers can expect personalized service and expert guidance throughout their flooring journey.</p> <p>Floortrends boasts a beautiful showroom, inviting potential customers to explore the extensive range of flooring options. The business has established a reputation for quality, reliability, and exceptional customer service. In-home consultations are offered, providing tailored advice and recommendations for individual projects.</p> <p>This flooring store excels in providing a variety of products and services to meet the demands of both residential and commercial clients. Discover the extensive selection and expertise that Floortrends offers. Visit Cobourg’s premier flooring destination today for all flooring needs.</p> <p>Connect with Floortrends in Cobourg to explore flooring solutions tailored to any project. </p>',
  '900 Division St #110',
  'Canada',
  'ON',
  'Cobourg',
  'K9A 5V2',
  'mike@aaacarpetrepair.ca',
  'canada/cobourg/home-services/floortrends',
  'ChIJ-Z7m68DF1YkRGFRsfR-FjAM',
  43.9766426,
  -78.1720733,
  '19053779520',
  'https://www.kwikr.ca/pictures/profile/pimage-273.jpg',
  'Flooring=>Laminate Flooring',
  'Pay-as-you-go',
  289,
  'https://www.floortrends.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Stittsville Flooring',
  '<p>Stittsville Flooring operates as a family-owned flooring store located in Stittsville, Ontario. This business specializes in high-quality porcelain ceramics and mosaics sourced from various regions worldwide. Stittsville Flooring hand-selects imported products to guarantee customers receive exceptional quality at competitive prices.</p> <p>The commitment to quality is evident in every aspect of Stittsville Flooring''s operations. The knowledgeable team provides expert guidance to help customers choose the right flooring solutions for their homes or businesses. This flooring store caters to a diverse clientele, offering a wide range of styles and materials that suit various tastes and budgets. The family-owned nature of the business fosters a personalized shopping experience, making each customer feel valued and understood.</p> <p>Stittsville Flooring prioritizes customer satisfaction, evident in their approach to product selection and service. The store''s dedication to sourcing high-quality materials ensures that customers receive flooring options that are both durable and aesthetically pleasing. The team remains informed about the latest trends in flooring design, providing clients with contemporary options that enhance their spaces.</p> <p>Stittsville Flooring excels in delivering quality products and personalized service. The family''s passion for flooring translates into a commitment to excellence. For those seeking reliable flooring solutions in Stittsville, Ontario, connect with Stittsville Flooring for exceptional products and service.',
  '109 Iber Rd Unit 5',
  'Canada',
  'ON',
  'Stittsville',
  'K2S 1E7',
  'info@whitelambfinlay.com',
  'canada/stittsville/home-services/stittsville-flooring',
  'ChIJzUxxLcH_zUwR2YXQcJ4xMmM',
  45.278318,
  -75.9046984,
  '13435457325',
  'https://www.kwikr.ca/pictures/profile/pimage-272.jpg',
  'Flooring=>Laminate Flooring',
  'Pay-as-you-go',
  288,
  'https://www.stittsvillefloors.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Dragona Flooring Toronto - Flooring Outlet',
  '<p>Dragona Flooring Toronto operates as a leading flooring outlet in the heart of Toronto, Ontario. This flooring store specializes in providing a diverse selection of quality flooring options tailored for both homeowners and contractors. The product range includes hardwood, engineered hardwood, laminate, vinyl, and vinyl click flooring, alongside essential tools and accessories for any flooring project.</p> <p>This business excels in creating strong partnerships with top manufacturers and distributors, ensuring access to high-quality products at competitive prices. Dragona Flooring Toronto prioritizes customer satisfaction by offering personalized service and expert advice to assist clients in achieving their home renovation goals. The knowledgeable staff is ready to guide customers through the extensive inventory, making the selection process straightforward and efficient.</p> <p>Located at 470 Norfinch Dr Unit B, Dragona Flooring Toronto is easily accessible for residents and contractors throughout the city. The outlet’s commitment to quality and affordability has earned it a solid reputation in the local community. Customers appreciate the wide variety of flooring solutions available, catering to different styles and budgets.</p> <p>Dragona Flooring Toronto provides an extensive range of flooring products, expert guidance, and strong industry connections. This flooring outlet stands ready to assist with any renovation project. Visit Dragona Flooring Toronto in Ontario for exceptional flooring solutions and reliable service.</p>',
  '470 Norfinch Dr Unit B',
  'Canada',
  'ON',
  'Toronto',
  'M3N 1Y4',
  'importdata-233@kwikr.ca',
  'canada/toronto/home-services/dragona-flooring-toronto-flooring-outlet',
  'ChIJl4DHeXwvK4gR3McDBCg_AYY',
  43.7714673,
  -79.5331317,
  '14169442001',
  'https://www.kwikr.ca/pictures/profile/pimage-271.jpg',
  'Flooring=>Laminate Flooring',
  'Pay-as-you-go',
  287,
  'http://dragonaflooring.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'End Of The Roll Flooring Centres - Nanaimo',
  '<p>End Of The Roll Flooring Centres, located at 6535 Metral Dr in Nanaimo, British Columbia, provides an extensive selection of brand name flooring options. This flooring store specializes in various products, including carpet, area rugs, luxury vinyl, laminate, tile and stone, decking, athletic flooring, and solid and engineered hardwood. Customers can find everything needed for installation and maintenance, ensuring a comprehensive shopping experience.</p> <p>With a commitment to quality and customer satisfaction, End Of The Roll Flooring Centres has established itself as a reliable source for flooring solutions in the Nanaimo area. The knowledgeable staff assists customers in selecting the right flooring to match their home’s aesthetic and functional needs. They also address installation inquiries, collaborating with trusted installation partners to ensure a seamless process. The store’s focus on customer service creates an inviting atmosphere that makes shopping feel enjoyable.</p> <p>This flooring store emphasizes convenience by offering products that customers can take home today. The extensive inventory caters to diverse preferences and budgets, making it easy to find the perfect flooring solution. End Of The Roll Nanaimo strives to enhance every shopping experience, ensuring that customers leave satisfied with their choices.</p> <p>Explore the vast selection of flooring options and experience exceptional service at End Of The Roll Flooring Centres in Nanaimo. Connect with this local business today for all flooring needs.</p>',
  '6535 Metral Dr',
  'Canada',
  'BC',
  'Nanaimo',
  'V9T 2L9',
  'contactus@drcarpet.ca',
  'canada/nanaimo/home-services/end-of-the-roll-flooring-centres-nanaimo',
  'ChIJa0zW3C2iiFQR9R843MO9r9Q',
  49.2320072,
  -124.0476921,
  '12507564944',
  'https://www.kwikr.ca/pictures/profile/pimage-270.jpg',
  'Flooring=>Heated Flooring',
  'Pay-as-you-go',
  286,
  'https://endoftheroll.com/?location=nanaimo',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Les Plancher Payless',
  '<p>Les Plancher Payless operates as a flooring store located at 84c Brunswick Blvd in Dollard-Des Ormeaux, Quebec. This specialty store provides an extensive selection of flooring options that includes exotic wood, laminate, and tile. With a focus on quality and variety, Les Plancher Payless caters to both residential and commercial customers seeking durable and stylish flooring solutions.</p><p>Established with a commitment to customer satisfaction, this business has become a trusted name in the local community. The knowledgeable staff assists customers in selecting the perfect flooring that meets their needs and budget. The store''s diverse inventory allows for customization in design, ensuring that every space can reflect personal style. Les Plancher Payless prides itself on providing high-quality materials that enhance any interior environment.</p><p>In addition to an impressive product range, Les Plancher Payless emphasizes exceptional service. From the moment customers enter the store, they receive personalized attention and expert guidance. The team understands the importance of making informed choices when it comes to flooring. They offer insights into the benefits of various materials, helping clients make decisions that align with their preferences and requirements.</p><p>Les Plancher Payless remains dedicated to delivering quality flooring solutions and outstanding customer service in Dollard-Des Ormeaux. Explore the extensive options available and experience the difference in quality and service. Visit Les Plancher Payless today to discover the ideal flooring for any space.</p>',
  '84c Brunswick Blvd',
  'Canada',
  'QC',
  'Dollard-Des Ormeaux',
  'H9B 2C5',
  'interpose.couvreplancher@gmail.com',
  'canada/dollard-des-ormeaux/home-services/les-plancher-payless',
  'ChIJu8JyeeI8yUwRWetAk7MOMXg',
  45.4777042,
  -73.8091235,
  '15146857877',
  NULL,
  'Flooring=>Heated Flooring',
  'Pay-as-you-go',
  285,
  'http://plancherspayless.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Jenkins Flooring Brandon',
  '<p>Jenkins Flooring Brandon operates as a leading flooring store located at 760 1st St, Brandon, Manitoba. This local business specializes in providing a wide range of flooring solutions, including hardwood, laminate, vinyl, and carpet options. With a commitment to quality and customer satisfaction, Jenkins Flooring has established a strong reputation in the community.</p> <p>The store offers expert advice on flooring selection, ensuring that customers find the perfect match for their homes or businesses. With years of experience in the industry, Jenkins Flooring Brandon understands the unique needs of the local area. The knowledgeable staff provides personalized service, guiding clients through the entire process from selection to installation.</p> <p>Jenkins Flooring Brandon emphasizes quality products and reliable installation services. The business prides itself on using durable materials that enhance the aesthetic appeal of any space. Customer feedback highlights the professionalism and efficiency of the installation team, further solidifying the store''s reputation within the community.</p> <p>Overall, Jenkins Flooring Brandon delivers exceptional flooring options and services tailored to the needs of its clients. The combination of quality products and dedicated service makes this business a trusted choice for flooring solutions in Brandon, Manitoba. Visit Jenkins Flooring Brandon today to explore the extensive range of flooring options available.',
  '760 1st St',
  'Canada',
  'MB',
  'Brandon',
  'R7A 2X4',
  'info@curlyscarpetrepair.com',
  'canada/brandon/home-services/jenkins-flooring-brandon',
  'ChIJPwEdYBaX51IRb90QfupbcpA',
  49.8376937,
  -99.9397913,
  '12047280153',
  NULL,
  'Flooring=>Heated Flooring',
  'Pay-as-you-go',
  284,
  'http://jenkinsflooring.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Speers Flooring Ltd',
  '<p>Speers Flooring Ltd, located at 266 Speers Rd in Oakville, Ontario, offers a comprehensive selection of high-quality flooring solutions. With over 60 years of experience, this family-owned and operated business specializes in Engineered and Solid Hardwoods, Cork, LVP Vinyl, and Laminate floors. Speers Flooring is dedicated to maintaining the highest standards in flooring, ensuring customer satisfaction through quality products and exceptional service.</p><p>The extensive range of flooring options caters to diverse tastes and preferences. Engineered and Solid Hardwoods provide durability and elegance, while Cork flooring offers a unique, eco-friendly alternative. LVP Vinyl and Laminate floors deliver affordability without sacrificing style. Each product is carefully selected to meet the needs of Oakville residents seeking reliable and aesthetically pleasing flooring solutions.</p><p>Speers Flooring has built a strong reputation within the community, evidenced by loyal customers and repeat business. The commitment to quality and service has positioned the company as a trusted choice for homeowners and businesses alike. Knowledgeable staff members offer expert guidance, ensuring that each customer finds the perfect flooring to suit their space.</p><p>Speers Flooring Ltd excels in providing a wide array of flooring products, backed by decades of experience and a commitment to quality. This local business continues to serve Oakville with dedication and expertise. Visit Speers Flooring in Oakville for top-notch flooring solutions that enhance any environment.</p>',
  '266 Speers Rd',
  'Canada',
  'ON',
  'Oakville',
  'L6K 2E9',
  'info@hmacarpet.com',
  'canada/oakville/home-services/speers-flooring-ltd',
  'ChIJq2km6P5cK4gR1VVWzENjPoo',
  43.4425318,
  -79.6909014,
  '19058458562',
  'https://www.kwikr.ca/pictures/profile/pimage-267.jpg',
  'Flooring=>Heated Flooring',
  'Pay-as-you-go',
  283,
  'http://www.speersflooring.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Les Tapis Gilles Lamothe Inc.',
  '<p>Les Tapis Gilles Lamothe Inc. operates as a premier flooring store located at 181 Rue Papineau in Papineauville, Quebec. Established in 1972 and acquired by M. Gilles Lamothe in 1984, this business spans 5,600 square feet and specializes in the sale and installation of various flooring types. The dedicated team focuses on understanding customer needs and providing tailored solutions.</p> <p>This flooring store offers an extensive selection of products, including hardwood, laminate, vinyl, and carpet options. Each flooring type meets high standards of quality and durability. The knowledgeable staff assists customers in making informed decisions, ensuring satisfaction with every purchase. They emphasize personalized service, guiding clients through the entire process from selection to installation.</p> <p>Les Tapis Gilles Lamothe Inc. prides itself on its commitment to customer care and expertise in flooring solutions. The team’s experience and dedication contribute to a seamless shopping experience. Customers can expect reliable service and quality products that enhance their living spaces.</p> <p>With a strong reputation built over decades, Les Tapis Gilles Lamothe Inc. remains a trusted choice for flooring needs in Papineauville. Their mission centers on customer satisfaction, making them a valuable resource for homeowners and businesses alike. Visit this flooring store in Papineauville to explore exceptional options for enhancing any space.</p>',
  '181 Rue Papineau',
  'Canada',
  'QC',
  'Papineauville',
  'J0V 1R0',
  'brandon@thedecorgroup.com',
  'canada/papineauville/home-services/les-tapis-gilles-lamothe-inc',
  'ChIJ_eTevURZzkwRokIdChPv4ds',
  45.615854,
  -75.0098525,
  '18194276630',
  'https://www.kwikr.ca/pictures/profile/pimage-266.jpg',
  'Flooring=>Heated Flooring',
  'Pay-as-you-go',
  282,
  'https://www.tapisgilleslamothe.com/?utm_source=gmb&utm_medium=yext',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Forever Flooring',
  '<p>Forever Flooring operates as a premier flooring store located at 150 Duke St #2, Miramichi, New Brunswick. This local business specializes in a wide range of flooring solutions, including hardwood, laminate, vinyl, and tile options. With years of experience in the industry, Forever Flooring has established a reputation for quality products and exceptional customer service. The store caters to both residential and commercial clients, ensuring that every project receives the attention it deserves.</p> <p>The team at Forever Flooring understands the importance of choosing the right flooring for each unique space. They offer expert advice, helping customers navigate through various flooring styles and materials. This flooring store prides itself on providing high-quality products that enhance the aesthetic appeal and functionality of any room. Their knowledgeable staff assists clients in making informed decisions tailored to their specific needs.</p> <p>Forever Flooring also emphasizes the significance of proper installation. Their experienced installers ensure that every flooring project is completed to the highest standards, contributing to the durability and longevity of the products. This commitment to excellence has earned them numerous satisfied customers throughout Miramichi.</p> <p>Forever Flooring delivers a comprehensive selection of flooring options, expert guidance, and skilled installation services. This flooring store remains dedicated to meeting the needs of the local community. Visit Forever Flooring in Miramichi to explore the extensive product range and receive professional assistance for flooring projects.</p>',
  '150 Duke St #2',
  'Canada',
  'NB',
  'Miramichi',
  'E1N 1H8',
  'info@nyservices.ca',
  'canada/miramichi/home-services/forever-flooring',
  'ChIJs_8qJTn1oUwREF8XjcQ38ks',
  47.0299394,
  -65.4679306,
  '15066278453',
  NULL,
  'Flooring=>Heated Flooring',
  'Pay-as-you-go',
  281,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Tip Top Carpet One Floor & Home',
  '<p>Tip Top Carpet One Floor & Home serves Abbotsford, British Columbia, as a retailer specializing in carpet, luxury vinyl plank (LVP), and hardwood flooring. This flooring store offers a diverse selection of quality products, ensuring customers find the perfect flooring solutions for their homes or businesses. With a commitment to customer satisfaction, Tip Top Carpet One has built a reputation for reliability and excellence in the local community.</p><p>The extensive inventory includes various styles and materials to meet different preferences and budgets. Customers appreciate the knowledgeable staff who guide them through the selection process, helping to make informed choices. The store''s focus on high-quality products ensures that every flooring installation meets industry standards and enhances the overall aesthetic of any space.</p><p>Tip Top Carpet One Floor & Home also emphasizes the importance of sustainability. Many products offered are sourced from environmentally responsible manufacturers, aligning with the growing demand for eco-friendly options. This commitment to sustainability resonates with customers who prioritize green living.</p><p>The business''s achievements include numerous positive reviews from satisfied customers, highlighting the exceptional service and quality products. Tip Top Carpet One continues to thrive in the competitive flooring market by prioritizing customer needs and maintaining high standards.</p><p>Explore the wide range of flooring options available at Tip Top Carpet One Floor & Home, where quality meets customer service. Visit the store at 31388 Peardonville Rd, Abbotsford, British Columbia, to experience the offerings firsthand.</p>',
  '31388 Peardonville Rd',
  'Canada',
  'BC',
  'Abbotsford',
  'V2T 6L1',
  'info@liteforminternational.com',
  'canada/abbotsford/home-services/tip-top-carpet-one-floor-home',
  'ChIJGUnZ1LbKhVQRDseo82xCmj8',
  49.0452964,
  -122.3547412,
  '17787712138',
  NULL,
  'Flooring=>Heated Flooring',
  'Pay-as-you-go',
  280,
  'http://www.tiptopcarpetoneabbotsford.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Miracle 786 Flooring',
  '<p>Miracle 786 Flooring offers a comprehensive range of flooring solutions in Surrey, British Columbia. This flooring store specializes in high-quality materials, including hardwood, laminate, vinyl, and carpet. The business prides itself on exceptional customer service and a wide selection of products tailored to meet various design needs. With years of experience, Miracle 786 Flooring has established a reputation for reliability and quality in the local market.</p><p>The store''s knowledgeable staff assists customers in selecting the right flooring for their homes or businesses. Each product is carefully curated to ensure durability and aesthetic appeal. Miracle 786 Flooring also provides installation services, ensuring a seamless process from selection to completion. The commitment to quality craftsmanship is evident in every project undertaken.</p><p>Miracle 786 Flooring actively engages with the community, participating in local events and supporting neighborhood initiatives. This involvement enhances the store''s reputation as a trusted local business. Customers appreciate the personalized attention and expertise offered by the team, which sets Miracle 786 Flooring apart from competitors.</p><p>Miracle 786 Flooring delivers a diverse array of flooring options, outstanding service, and community engagement. This flooring store continues to build strong relationships with customers in Surrey, British Columbia. Connect with Miracle 786 Flooring at 14757 104 Ave to explore flooring solutions today.</p>',
  '14757 104 Ave',
  'Canada',
  'BC',
  'Surrey',
  'V3R 5X4',
  'info@aucourantlighting.com',
  'canada/surrey/home-services/miracle-786-flooring',
  'ChIJ5092sxXXhVQRXGyTtlS_Tus',
  49.1917955,
  -122.8136455,
  '16047795982',
  NULL,
  'Flooring=>Heated Flooring',
  'Pay-as-you-go',
  279,
  'http://miracleflooring.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'End Of The Roll Flooring Centres - Calgary North',
  '<p>End Of The Roll Flooring Centres in Calgary, Alberta, provides an extensive selection of flooring options, catering to diverse customer needs. This flooring store stocks a wide range of products, including carpet, area rugs, luxury vinyl, laminate, tile and stone, decking, and athletic flooring. With a focus on quality, the store features both solid and engineered hardwood, ensuring that customers find the perfect fit for their homes.</p><p>Located at 1922 32 Ave NE, End Of The Roll Calgary North emphasizes convenience and accessibility. The knowledgeable staff assists customers in selecting the right flooring while addressing installation queries through trusted partners. This commitment to customer service enhances the shopping experience, making it feel special and personalized.</p><p>The store’s reputation in Calgary is built on offering one of the largest selections of brand-name flooring in Canada, allowing customers to take their choices home immediately. The variety ensures that every customer can find something that suits their style and budget. The focus on cleanliness and maintenance products further supports customers in preserving their flooring investments.</p><p>End Of The Roll Flooring Centres excels in providing quality flooring solutions and exceptional customer service. The extensive inventory and dedicated staff contribute to a positive shopping environment. Connect with End Of The Roll Flooring Centres in Calgary for all flooring needs and experience the difference today.</p>',
  '1922 32 Ave NE',
  'Canada',
  'AB',
  'Calgary',
  'T2E 6R6',
  'info@arevco.ca',
  'canada/calgary/home-services/end-of-the-roll-flooring-centres-calgary-north',
  'ChIJ4VFao-FkcVMRY6eh72zFB2g',
  51.0818194,
  -114.0125908,
  '14032911144',
  NULL,
  'Flooring=>Heated Flooring',
  'Pay-as-you-go',
  278,
  'https://endoftheroll.com/?location=calgary-north',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Tapis Milton Enr',
  '<p>Tapis Milton Enr, located at 1020 Rue Dufferin in Granby, Quebec, has been a trusted name in flooring solutions for over 30 years. This flooring store specializes in the sale of floor coverings and installation products. With a team of experienced advisors, Tapis Milton guides customers through every step of their flooring projects, ensuring satisfaction and quality.</p><p>The extensive range of flooring options includes carpets, hardwood, laminate, and vinyl, catering to diverse tastes and needs. Tapis Milton Enr emphasizes quality and durability, providing products that enhance both aesthetics and functionality in homes and businesses. The company’s commitment to customer service and expertise has earned it a loyal clientele in Granby and surrounding areas.</p><p>Tapis Milton Enr prides itself on its knowledgeable staff, who are ready to assist customers in making informed decisions. The store’s dedication to supporting local residents with their flooring needs contributes to the community''s overall growth and development. With a solid reputation built over decades, Tapis Milton continues to be a reliable partner for flooring projects of all sizes.</p><p>Offering a wide selection of flooring products and personalized service, Tapis Milton Enr remains a cornerstone in the Granby area. The combination of experience and a customer-focused approach ensures each project is handled with care. Connect with Tapis Milton Enr for expert flooring solutions in Granby, Quebec.</p>',
  '1020 Rue Dufferin',
  'Canada',
  'QC',
  'Granby',
  'J2H 0T6',
  'commandes@lumidecor.ca',
  'canada/granby/home-services/tapis-milton-enr',
  'ChIJ-awvUrPOyUwRfWOOH7KtDBE',
  45.4423767,
  -72.7168589,
  '14507770410',
  NULL,
  'Flooring=>Heated Flooring',
  'Pay-as-you-go',
  277,
  'https://www.tapismilton.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Local Flooring Group',
  '<p>Local Flooring Group operates as a premier flooring store located at 101A English Crescent in Saskatoon, Saskatchewan. This business specializes in flooring solutions tailored for the unique lifestyle of Saskatchewan residents. With a focus on durability and style, Local Flooring Group offers products designed to withstand the demands of families with kids, pets, and active lifestyles.</p> <p>The flooring options available at Local Flooring Group are crafted specifically for the local environment. High-volume stock ensures that customers find what they need without delay. Competitive pricing allows homeowners to enhance their spaces without overspending. Each flooring design reflects a commitment to quality and aesthetic appeal, making homes not just functional but also Instagram-worthy.</p><p>Supporting local businesses is essential for community growth. Local Flooring Group exemplifies this by offering products that cater to the needs of Saskatoon residents. The combination of practical flooring solutions and stylish designs sets this store apart in the market. Engagement with customers is evident through their active presence on social media platforms like Instagram and Facebook, showcasing various designs and inspiring home transformations.</p><p>Local Flooring Group provides durable flooring options, competitive prices, and a focus on local community support. The commitment to quality and customer satisfaction makes this store a reliable choice for flooring needs. Connect with Local Flooring Group in Saskatoon for exceptional flooring solutions that enhance any home.</p>',
  '101A English Crescent',
  'Canada',
  'SK',
  'Saskatoon',
  'S7K 8G4',
  'info@roycelight.com',
  'canada/saskatoon/home-services/local-flooring-group',
  'ChIJI_gR5uP1BFMRI70fkLd73vc',
  52.1805574,
  -106.6444677,
  '13069866237',
  NULL,
  'Flooring=>Heated Flooring',
  'Pay-as-you-go',
  276,
  'https://localflooringgroup.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Canadian Home Style',
  '<p>Canadian Home Style operates as a leading flooring store in North Vancouver, British Columbia, providing a wide array of services including flooring installation, kitchen renovations, and bathroom remodeling. The business is recognized for its commitment to quality and sustainability, showcasing premium products in its showroom. Customers can explore options ranging from carpet and hardwood flooring to luxury vinyl, cork, and laminate flooring.</p><p>With a strong focus on excellence, Canadian Home Style has received the Consumer''s Choice Award for flooring and cabinetry in North Vancouver for four consecutive years, from 2021 to 2024. This achievement highlights the company''s dedication to customer satisfaction and industry standards. The team at Canadian Home Style understands the importance of selecting the right materials for each project, ensuring that every renovation meets the needs and preferences of clients.</p><p>The showroom located at 1420 Marine Dr serves as a hub for homeowners and designers alike, offering a diverse selection of flooring options and cabinetry solutions. Each product reflects the company''s philosophy of providing lifelong solutions that enhance the beauty and functionality of residential spaces. Canadian Home Style''s expertise extends beyond flooring, encompassing comprehensive kitchen and bathroom renovation services tailored to individual requirements.</p><p>Canadian Home Style excels in delivering high-quality flooring and renovation services in North Vancouver. The company''s award-winning reputation and commitment to customer satisfaction make it a reliable choice for homeowners. Visit Canadian Home Style at 1420 Marine Dr in North Vancouver to explore flooring and renovation solutions tailored to specific needs. </p>',
  '1420 Marine Dr',
  'Canada',
  'BC',
  'North Vancouver',
  'V7P 1T6',
  'taylor@outdoor-lighting.ca',
  'canada/north-vancouver/home-services/canadian-home-style',
  'ChIJxyDyIdFxhlQRHl9WD8bPKOM',
  49.3240244,
  -123.1139135,
  '16049806772',
  NULL,
  'Flooring=>Heated Flooring',
  'Pay-as-you-go',
  275,
  'https://canadianhomestyle.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Prosol inc.',
  '<p>Prosol Inc. operates as a premier flooring store located in Kingston, Ontario. This business specializes in a wide range of flooring solutions, including hardwood, laminate, vinyl, and tile. Prosol Inc. serves both residential and commercial clients, providing high-quality products and expert installation services. The company is known for its commitment to customer satisfaction and a diverse selection of flooring options that cater to various styles and budgets.</p> <p>The team at Prosol Inc. possesses extensive knowledge of flooring materials and trends. They guide customers through the selection process, ensuring that each choice aligns with individual needs and preferences. The store features an impressive showroom that showcases the latest designs and innovations in flooring. This allows clients to visualize how different materials will enhance their spaces.</p> <p>Prosol Inc. has built a reputation for reliability and professionalism in Kingston. The business emphasizes quality workmanship and timely project completion. Numerous satisfied customers attest to the durability and aesthetic appeal of their flooring installations. The company’s dedication to using premium materials sets it apart in the competitive flooring market.</p> <p>Offering a comprehensive range of flooring products and services, Prosol Inc. excels in meeting the needs of its clients. The business fosters strong relationships with customers through its knowledgeable staff and commitment to quality. Connect with Prosol Inc. for exceptional flooring solutions in Kingston, Ontario.',
  '1663 Venture Dr Unit 1D',
  'Canada',
  'ON',
  'Kingston',
  'K7P 0E9',
  'serviceweb@unionltg.com',
  'canada/kingston/home-services/prosol-inc',
  'ChIJoR4MEC2s0kwRbPrj_Vzw4gA',
  44.2715692,
  -76.5617677,
  '16133841212',
  NULL,
  'Flooring=>Heated Flooring',
  'Pay-as-you-go',
  274,
  'http://www.prosol.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);
