INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'NR Renovations',
  '<p>NR Renovations operates as a reliable general contractor in Mitchell, Ontario, specializing in home renovation services. Focused on transforming living spaces, this local business excels in various renovation projects, ensuring each home reflects the owner''s vision. The team at NR Renovations is dedicated to quality craftsmanship and customer satisfaction, making homes feel new again.</p><p>With a strong commitment to excellence, NR Renovations handles projects ranging from kitchen and bathroom remodels to complete home renovations. The skilled professionals bring years of experience to each job, ensuring that every detail is meticulously addressed. This dedication to quality has earned NR Renovations a solid reputation in the community, with numerous satisfied clients who appreciate the transformative results.</p><p>Located at 152 Georgina St, NR Renovations serves the Mitchell area and surrounding regions, providing tailored solutions that meet the unique needs of each homeowner. The team emphasizes clear communication and collaboration throughout the renovation process, fostering trust and transparency. NR Renovations understands that home renovations can be overwhelming, and they strive to simplify the experience for their clients.</p><p>NR Renovations offers a range of services aimed at enhancing residential spaces, showcasing a commitment to quality and customer satisfaction. The business''s focus on making homes new again resonates with homeowners seeking to improve their living environments. Contact NR Renovations in Mitchell for expert renovation services that breathe new life into homes. </p>',
  '152 Georgina St',
  'Canada',
  'ON',
  'Mitchell',
  'N0K 1N0',
  'richardsipd@gmail.com',
  'canada/mitchell/home-services/nr-renovations',
  'ChIJzfhpPyU1KYgR3WJ-pTB625U',
  43.4619785,
  -81.1969825,
  '15193489366',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  723,
  'http://nrrenovations.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Richard’s Island Perimeter Drains',
  '<p>Richard’s Island Perimeter Drains operates as a general contractor specializing in perimeter drain and foundation repair services in Duncan, British Columbia. This family-owned business provides comprehensive solutions for drainage issues, catering to clients from Victoria to Lantzville. With a commitment to quality, Richard’s Island Perimeter Drains offers a range of services, including camera inspections of perimeter drains, power flushing, partial and full replacements, as well as foundation repairs.</p><p>Utilizing advanced technology, the company conducts thorough camera inspections that identify potential problems within drainage systems. Power flushing services ensure that drains remain clear and functional, preventing future issues. The team at Richard’s Island Perimeter Drains understands the importance of maintaining a healthy foundation and offers both partial and full replacement options tailored to the specific needs of each property.</p><p>Customer satisfaction remains a top priority for Richard’s Island Perimeter Drains. The business prides itself on its transparent communication and reliable service. Family values drive the company, ensuring that every client receives personalized attention and expert advice. The team is always ready to discuss drainage concerns and provide practical solutions.</p><p>Richard’s Island Perimeter Drains delivers essential services that enhance property safety and functionality in Duncan and surrounding areas. With a focus on quality and customer care, the business stands ready to assist with all drainage needs. Reach out to Richard’s Island Perimeter Drains at their location on Riverbottom Rd for expert assistance.</p>',
  '5580 Riverbottom Rd',
  'Canada',
  'BC',
  'Duncan',
  'V9L 6J5',
  'audrius65@hotmail.com',
  'canada/duncan/home-services/richard’s-island-perimeter-drains',
  'ChIJE8nyIJxFj1QR-FVHAWiujrM',
  48.7741407,
  -123.8067951,
  '17789773355',
  'https://www.kwikr.ca/pictures/profile/pimage-718.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  722,
  'http://www.richardsipd.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Kingsmill Homes',
  '<p>Kingsmill Homes operates as a general contractor in Toronto, Ontario, specializing in design build services. The firm provides superior quality new build and renovation solutions tailored to meet the diverse needs of clients in the area. With a strong emphasis on craftsmanship and attention to detail, Kingsmill Homes has established a reputation for delivering exceptional results.</p><p>This company focuses on both residential and commercial projects, ensuring that each construction or renovation meets the highest standards. Kingsmill Homes utilizes a collaborative approach, working closely with clients to understand their visions and requirements. The team prioritizes transparency and communication throughout the entire process, which fosters trust and satisfaction.</p><p>Kingsmill Homes has successfully completed numerous projects, showcasing versatility in design and functionality. The firm’s commitment to using quality materials and innovative techniques sets it apart in the competitive Toronto market. Clients appreciate the seamless integration of aesthetics and practicality in every project.</p><p>By choosing Kingsmill Homes, clients gain access to a dedicated team that values integrity and excellence. The firm’s extensive experience in the industry enables it to navigate challenges effectively, ensuring projects are completed on time and within budget. Kingsmill Homes remains a reliable choice for those seeking renovation and new build services in Toronto.</p><p>Explore the superior quality services offered by Kingsmill Homes, a trusted general contractor in Toronto, Ontario. Contact Kingsmill Homes for expert design build solutions today.</p>',
  '53 Ostend Ave',
  'Canada',
  'ON',
  'Toronto',
  'M6S 1L5',
  'info@immoblex.ca',
  'canada/toronto/home-services/kingsmill-homes',
  'ChIJJ3Skojw3K4gRm6h5LSVp1VQ',
  43.6491584,
  -79.4805365,
  '14169193117',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  721,
  'http://kingsmillhomes.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Les Constructions Immoblex Inc.',
  '<p>Les Constructions Immoblex Inc. operates as a general contractor in Saint-Jérôme, Quebec, offering a variety of construction services. This local business specializes in new constructions, renovations, expansions, emergency renovations, and unconventional projects. With a strong commitment to quality and customer satisfaction, the company has built a reputation for delivering reliable and efficient services.</p><p>The expertise of Les Constructions Immoblex Inc. encompasses a wide range of construction needs. New constructions are handled with precision, ensuring that each project meets the specific requirements of clients. Renovations and expansions are executed with attention to detail, transforming spaces while maintaining functionality. Emergency renovations are available to address urgent needs, providing timely solutions to unexpected situations. Unconventional projects showcase the company''s versatility and creativity in tackling unique challenges.</p><p>Located at 702 9 Ave, the business serves the Saint-Jérôme community and surrounding areas. Its experienced team possesses the knowledge and skills necessary to manage various construction projects, ensuring compliance with local regulations and standards. The company prioritizes effective communication with clients, fostering a collaborative environment that leads to successful outcomes.</p><p>Les Constructions Immoblex Inc. offers comprehensive construction solutions, emphasizing quality and client satisfaction. The company’s dedication to excellence in new constructions and renovations makes it a reliable choice for any construction project. Reach out to Les Constructions Immoblex Inc. in Saint-Jérôme for expert general contracting services.</p>',
  '702 9 Ave',
  'Canada',
  'QC',
  'Saint-Jérôme',
  'J7Z 4T2',
  'jfredericks@seagateconstruction.ca',
  'canada/saint-jérôme/home-services/les-constructions-immoblex-inc',
  'ChIJkz2mCOXVyEwRVvQX1dOvEr0',
  45.7588966,
  -73.9912956,
  '18193250383',
  'https://www.kwikr.ca/pictures/profile/pimage-716.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  720,
  'http://www.immoblex.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Seagate Construction Inc.',
  '<p>Seagate Construction Inc. operates as a general contractor in Dartmouth, Nova Scotia, delivering quality construction services with a strong commitment to excellence. The company is led by partners John Fredericks and Steve Harris, who bring over 35 years of combined experience in the construction industry. Their expertise spans various aspects of construction, ensuring that clients receive reliable and professional service.</p> <p>Seagate Construction Inc. specializes in residential and commercial projects, focusing on renovations, new builds, and project management. The company''s hands-on approach guarantees attention to detail and adherence to timelines. Each project benefits from the partners'' extensive knowledge, allowing for effective problem-solving and innovative solutions tailored to client needs. Their dedication to quality craftsmanship is evident in every completed project.</p> <p>Located at 11 Morris Dr #114, Seagate Construction Inc. serves Dartmouth and surrounding areas, building a reputation for reliability and professionalism. Clients appreciate the transparent communication and commitment to customer satisfaction. The team prides itself on maintaining high standards and fostering strong relationships with clients, ensuring a smooth construction process from start to finish.</p> <p>Seagate Construction Inc. offers a range of services, including renovations and new construction, backed by years of experience and a focus on quality. The team''s commitment to excellence positions them as a trusted choice in the local construction market. Connect with Seagate Construction Inc. for reliable general contracting services in Dartmouth, Nova Scotia. </p>',
  '11 Morris Dr #114',
  'Canada',
  'NS',
  'Dartmouth',
  'B3B 1M2',
  'estimates@frescoconstruction.com',
  'canada/dartmouth/home-services/seagate-construction-inc',
  'ChIJsXTEYjMgWksR9BYEZmBVmxE',
  44.7061507,
  -63.6136508,
  '19024043435',
  'https://www.kwikr.ca/pictures/profile/pimage-715.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  719,
  'https://seagateconstruction.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Fresco Construction',
  '<p>Fresco Construction operates as a family-owned general contractor located in Woodbridge, Ontario. This business specializes in various sectors including Retail General Contracting, Medical General Contracting, Custom Cottage Building, and Residential Developments. With a strong commitment to quality and client satisfaction, Fresco Construction has earned a reputation for reliability and expertise in the construction industry.</p> <p>Fresco Construction focuses on delivering tailored solutions for diverse construction needs. The team brings extensive experience in retail projects, ensuring that commercial spaces are functional and appealing. In the medical sector, they adhere to strict regulations and standards, providing safe and efficient environments for healthcare facilities. Custom cottage building services reflect the company’s dedication to craftsmanship, creating unique retreats that blend seamlessly with nature. Residential developments showcase their ability to construct homes that meet modern living standards.</p> <p>The commitment to quality craftsmanship and customer service sets Fresco Construction apart. Their family-owned values ensure that every project receives personal attention, resulting in satisfied clients and successful outcomes. The team’s extensive experience across various sectors allows for adaptability and innovative solutions tailored to specific client needs. Fresco Construction continues to make a significant impact in the Woodbridge area.</p> <p>Fresco Construction offers a comprehensive range of general contracting services, ensuring quality and satisfaction in every project. The expertise in retail, medical, cottage, and residential construction highlights their versatility and dedication. Connect with Fresco Construction in Woodbridge for exceptional general contracting services.</p>',
  '32 Woburn Dr',
  'Canada',
  'ON',
  'Woodbridge',
  'L4L 7H8',
  'info@fatcatcontracting.com',
  'canada/woodbridge/home-services/fresco-construction',
  'ChIJ7ffDyy7XKogRyVSUM-txREQ',
  43.8110531,
  -79.6034313,
  '18668730368',
  'https://www.kwikr.ca/pictures/profile/pimage-714.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  718,
  'http://frescoconstruction.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Fat Cat Contracting Inc.',
  '<p>Fat Cat Contracting Inc. delivers top-tier general contracting services in Caledonia, Ontario. This licensed and insured company specializes in home renovations, ensuring exceptional quality results through skilled craftsmanship. With a commitment to excellence, Fat Cat Contracting has built a strong reputation in the community.</p><p>The team at Fat Cat Contracting consists of highly trained professionals dedicated to transforming residential spaces. Services include kitchen and bathroom remodels, home additions, and general renovations tailored to meet client needs. Each project receives meticulous attention to detail, reflecting the company''s commitment to quality and customer satisfaction.</p><p>Fat Cat Contracting proudly serves the Haldimand-Norfolk, Glanbrook, Hamilton, Ancaster, and Dundas areas. The company’s licensed and insured status provides peace of mind to homeowners, ensuring that every project adheres to safety standards and regulations. The commitment to delivering high-quality workmanship has garnered positive feedback from clients across the region.</p><p>With a focus on exceptional service and quality results, Fat Cat Contracting Inc. stands ready to assist with any home renovation project. The combination of experience, dedication, and a customer-first approach makes this business a reliable choice for homeowners in need of renovations. Reach out to Fat Cat Contracting Inc. at their Caledonia location for a free quote today.</p>',
  '3 Dunrobin Dr',
  'Canada',
  'ON',
  'Caledonia',
  'N3W 2N9',
  'info@constructionpro-lam.com',
  'canada/caledonia/home-services/fat-cat-contracting-inc',
  'ChIJ-QU9MmyNLIgR6M-DK0O15Ts',
  43.0590033,
  -79.9442524,
  '19059792733',
  'https://www.kwikr.ca/pictures/profile/pimage-713.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  717,
  'http://www.fatcatcontracting.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Construction Pro-Lam Inc',
  '<p>Construction Pro-Lam Inc, located in Maskinongé, Quebec, offers comprehensive general contracting services since 1996. This business specializes in residential, commercial, industrial, and agricultural construction projects, ensuring high standards and reliability. Collaborating with trusted subcontractors for plumbing and electrical work enhances the overall service quality.</p> <p>Construction Pro-Lam Inc has built a strong reputation in the Mauricie region through years of dedicated service. The team focuses on delivering projects on time and within budget, making them a preferred choice for various construction needs. Their expertise spans multiple sectors, allowing them to handle diverse projects with ease and professionalism.</p> <p>The company prioritizes customer satisfaction and quality workmanship. Each project receives meticulous attention to detail, ensuring that every aspect meets the clients’ requirements. With a commitment to using the best materials and practices, Construction Pro-Lam Inc maintains a competitive edge in the industry. Their partnerships with skilled subcontractors for specialized tasks further solidify their capability to manage complex projects efficiently.</p> <p>Construction Pro-Lam Inc provides reliable general contracting services in Maskinongé and surrounding areas. Their extensive experience and focus on quality make them a trusted partner for construction needs. Connect with Construction Pro-Lam Inc today to explore their services in Maskinongé, Quebec.</p>',
  '69 Boul Est',
  'Canada',
  'QC',
  'Maskinongé',
  'J0K 1N0',
  'francois@laplanteconstruction.ca',
  'canada/maskinongé/home-services/construction-pro-lam-inc',
  'ChIJ30q4JmwcxkwRJckrGHUtRe4',
  46.2345022,
  -72.994094,
  '18192272490',
  'https://www.kwikr.ca/pictures/profile/pimage-712.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  716,
  'https://www.constructionpro-lam.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Laplante Construction (2006) Inc',
  '<p>Laplante Construction (2006) Inc is a trusted general contractor based in Lac-Beauport, Quebec. The company specializes in commercial and industrial construction and renovation projects. With a solid reputation built over years of dedicated service, Laplante Construction delivers quality craftsmanship tailored to meet the specific needs of businesses in the region.</p><p>This local business focuses on providing comprehensive construction solutions that include everything from initial design to final execution. Laplante Construction employs skilled professionals who ensure that every project adheres to industry standards and client specifications. The team’s commitment to excellence is evident in their attention to detail and efficient project management.</p><p>Laplante Construction has successfully completed numerous projects, earning recognition for its reliability and expertise. Clients appreciate the company’s ability to handle diverse construction tasks, which range from small renovations to large-scale industrial builds. The firm’s understanding of the local market in Lac-Beauport allows for tailored solutions that resonate with community needs.</p><p>With a focus on quality and customer satisfaction, Laplante Construction continues to serve the Lac-Beauport area with integrity and professionalism. The company’s extensive experience in commercial and industrial construction positions it as a leader in the local industry. For exceptional construction and renovation services, contact Laplante Construction at 245 Chem. du Tour-du-Lac, Lac-Beauport, Quebec. </p>',
  '245 Chem. du Tour-du-Lac',
  'Canada',
  'QC',
  'Lac-Beauport',
  'G3B 1G3',
  'info@constructionmauricesamson.ca',
  'canada/lac-beauport/home-services/laplante-construction-2006-inc',
  'ChIJPZFJ1XukuEwRB9b1WOEvxA4',
  46.9554616,
  -71.2669811,
  '14188413380',
  'https://www.kwikr.ca/pictures/profile/pimage-711.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  715,
  'http://www.laplanteconstruction.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Construction Maurice Samson',
  '<p>Construction Maurice Samson operates as a general contractor in Saint-Gérard-des-Laurentides, Quebec. This reputable company excels in residential renovation projects, particularly in the installation of doors and windows. With a strong presence in the Mauricie region, they have established themselves as a trusted choice for homeowners seeking quality craftsmanship.</p><p>Known for their commitment to excellence, Construction Maurice Samson emphasizes meticulous attention to detail in every project. Their skilled team ensures that each installation meets high standards, contributing to the overall aesthetic and functionality of homes. The company takes pride in its ability to transform spaces, enhancing both comfort and value for clients. With a focus on customer satisfaction, they deliver reliable services that resonate with the needs of the community.</p><p>This general contractor stands out in the competitive landscape of residential renovations in Shawinigan. Their extensive experience and knowledge in the field enable them to tackle projects of various sizes and complexities. The company has garnered positive feedback from clients, reinforcing its reputation for quality and dependability. Their specialization in door and window installation further showcases their expertise, making them a go-to option for homeowners in the area.</p><p>Construction Maurice Samson provides comprehensive renovation services with a focus on quality and customer satisfaction. Their expertise in installing doors and windows positions them as a valuable resource for residents in Saint-Gérard-des-Laurentides. Engage with this trusted contractor for exceptional renovation services.',
  '110 Chem. des Plaines',
  'Canada',
  'QC',
  'Saint-Gérard-des-Laurentides',
  'G9R 1N9',
  'jfturbide@immeublestondreau.com',
  'canada/saint-gérard-des-laurentides/home-services/construction-maurice-samson',
  'ChIJ2YNy24dPxkwRlT5n6g0UNqA',
  46.602245,
  -72.7937291,
  '18195396846',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  714,
  'http://www.constructionmauricesamson.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Les immeubles tondreau',
  '<p>Les immeubles tondreau operates as a reputable general contractor in Québec City, Quebec. This business specializes in a variety of construction services, ensuring high-quality workmanship and customer satisfaction. With a commitment to excellence, the company has built a strong reputation within the local community. Their portfolio includes residential and commercial projects, showcasing a diverse range of skills and expertise.</p><p>Located at 275 Rue Fichet, Les immeubles tondreau serves clients throughout Québec City. The team consists of experienced professionals who understand the intricacies of construction. They prioritize clear communication and project management, ensuring that timelines and budgets are adhered to. Clients appreciate the attention to detail and the ability to handle projects of all sizes, from renovations to new builds.</p><p>Les immeubles tondreau emphasizes the importance of quality materials and sustainable practices in all projects. This approach not only enhances durability but also contributes positively to the environment. The business has received positive feedback for its reliability and professionalism, making it a preferred choice for many in the area.</p><p>In summary, Les immeubles tondreau provides comprehensive general contracting services in Québec City. Their dedication to quality and customer satisfaction sets them apart in the construction industry. Connect with Les immeubles tondreau at 275 Rue Fichet for exceptional contracting services in Québec City.</p>',
  '275 Rue Fichet',
  'Canada',
  'QC',
  'Québec City',
  'G1C 7Z9',
  'shelley@dclimited.ca',
  'canada/québec-city/home-services/les-immeubles-tondreau',
  'ChIJQ9Yupu69uEwRVB4OyfYKCJw',
  46.8764351,
  -71.1938996,
  '14186149915',
  'https://www.kwikr.ca/pictures/profile/pimage-709.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  713,
  'http://www.immeublestondreau.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'DeSaulniers Construction Ltd',
  '<p>DeSaulniers Construction Ltd, located at 1120 Marleau Ave in Cornwall, Ontario, has been a key player in the construction industry since its founding in 2001. This general contractor specializes in innovative solutions for both public and private sectors, delivering exceptional results in institutional, industrial, commercial, and multi-residential construction and retrofitting. The company’s emphasis on quality and efficiency has earned it a strong reputation in Eastern Ontario.</p><p>DeSaulniers Construction Ltd employs a hands-on approach, ensuring that every project meets the highest standards. The company boasts accomplished in-house design and build teams that collaborate closely with a network of licensed sub-trades and professional services. This integrated model streamlines project execution and enhances overall quality. The team’s expertise in retrofitting and construction allows for tailored solutions that meet diverse client needs.</p><p>With a commitment to innovation, DeSaulniers Construction Ltd continues to adapt to the evolving demands of the construction industry. The company’s ability to manage complex projects efficiently sets it apart in the competitive landscape. Clients benefit from personalized service and a dedication to delivering projects on time and within budget.</p><p>DeSaulniers Construction Ltd offers comprehensive general contracting services, focusing on quality and client satisfaction. Its innovative approach and skilled teams contribute to successful project outcomes. Connect with DeSaulniers Construction Ltd in Cornwall, Ontario, for expert construction services.</p>',
  '1120 Marleau Ave',
  'Canada',
  'ON',
  'Cornwall',
  'K6H 2W8',
  'courtney.keenan@k-lineconstruction.com',
  'canada/cornwall/home-services/desaulniers-construction-ltd',
  'ChIJZ5nY5OIZzEwRAfTEm6JsytU',
  45.0347644,
  -74.7151,
  '16139370016',
  'https://www.kwikr.ca/pictures/profile/pimage-708.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  712,
  'https://dclimited.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'K-Line Construction Ltd',
  '<p>K-Line Construction Ltd operates as a general contractor in Hanwell, New Brunswick, specializing in diverse construction services. The company excels in civil and utility construction, showcasing a strong commitment to quality and efficiency. With a proven track record, K-Line Construction Ltd has established itself as a reliable partner for various construction projects.</p> <p>The company’s expertise spans multiple sectors, including residential, commercial, and infrastructure development. K-Line Construction Ltd employs skilled professionals who ensure that each project meets high standards. The focus on safety and compliance with local regulations enhances the company’s reputation in the industry. K-Line Construction Ltd also emphasizes sustainable practices, contributing positively to the community and environment.</p> <p>K-Line Construction Ltd has successfully completed numerous projects, demonstrating its ability to manage complex tasks effectively. The company’s dedication to customer satisfaction is evident in its approach to project management and communication. Clients appreciate the transparency and professionalism that K-Line Construction Ltd brings to every job.</p> <p>In summary, K-Line Construction Ltd provides comprehensive general contracting services in Hanwell, New Brunswick, excelling in civil and utility construction. The company’s strengths lie in its skilled workforce, commitment to safety, and focus on customer satisfaction. For reliable construction services, reach out to K-Line Construction Ltd in Hanwell. </p>',
  '8 Avery St',
  'Canada',
  'NB',
  'Hanwell',
  'E3C 0E6',
  'info@terraex.ca',
  'canada/hanwell/home-services/k-line-construction-ltd',
  'ChIJT7FomJgYpEwRF0qhiycmq9k',
  45.9240642,
  -66.7183051,
  '15064541302',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  711,
  'http://www.k-lineconstruction.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'TerraEx Inc',
  '<p>TerraEx Inc, located at 1942 Manawagonish Rd in Saint John, New Brunswick, operates as a family-owned and operated general contractor. This heavy civil construction company serves Southern New Brunswick with a focus on site development, site services, demolition, municipal infrastructure, and landscaping. With a proven track record of collaboration with private developers and government entities, TerraEx has built a reputation for reliability and quality.</p> <p>The services provided by TerraEx encompass a wide range of construction needs. Site development includes everything from land clearing to grading, ensuring a solid foundation for any project. Site services extend to utilities installation and maintenance, crucial for any construction project. Demolition services are executed with precision, ensuring safety and efficiency. Municipal infrastructure projects demonstrate the company’s capability to handle large-scale jobs that serve the community. Landscaping services enhance the aesthetic appeal of properties, adding value and functionality.</p> <p>TerraEx has achieved numerous milestones in its years of operation, reflecting a commitment to excellence and customer satisfaction. The company’s experience with various levels of government showcases its ability to meet regulatory standards and deliver on time. The dedicated team at TerraEx ensures that each project is completed with attention to detail and adherence to safety protocols.</p> <p>TerraEx Inc delivers comprehensive construction solutions, showcasing expertise in site development and infrastructure projects. The company’s strengths lie in its family-oriented approach and commitment to quality. Connect with TerraEx Inc in Saint John for reliable construction services that fulfill diverse needs. </p>',
  '1942 Manawagonish Rd',
  'Canada',
  'NB',
  'Saint John',
  'E2M 5H5',
  'service@ultrarenovations.com',
  'canada/saint-john/home-services/terraex-inc',
  'ChIJFVZ1Gia1p0wRYhnJHknGTSE',
  45.2360192,
  -66.1398345,
  '15066724422',
  'https://www.kwikr.ca/pictures/profile/pimage-706.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  710,
  'http://www.terraex.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Ultra Renovations',
  '<p>Ultra Renovations operates as a leading general contractor in Swift Current, Saskatchewan, specializing in comprehensive home renovation services. The business focuses on both interior and exterior projects, ensuring quality craftsmanship for homes, cottages, and cabins. With a commitment to serving Swift Current and its surrounding areas, Ultra Renovations also extends its expertise to Moose Jaw, Regina, and the towns in between.</p><p>Expertise in home renovations encompasses a wide range of services. From roofing and kitchen renovations to bathroom upgrades and the construction of fences and decks, Ultra Renovations handles diverse projects with professionalism. The company also offers installation of new windows and doors, exterior siding, and home additions. Each project receives meticulous attention to detail, ensuring that clients achieve their desired results.</p><p>Ultra Renovations prides itself on delivering reliable and efficient renovation solutions. The experienced team understands the unique needs of homeowners and collaborates closely to bring visions to life. With a focus on customer satisfaction, the company provides free quotes, allowing clients to plan their renovations with confidence.</p><p>With a strong reputation in the local community, Ultra Renovations remains dedicated to enhancing homes in Swift Current and beyond. Quality workmanship and a commitment to service define this business. Reach out to Ultra Renovations for expert home renovation services in Swift Current, Saskatchewan.</p>',
  '134 Central Ave N',
  'Canada',
  'SK',
  'Swift Current',
  'S9H 0L1',
  'cegerco@cegerco.com',
  'canada/swift-current/home-services/ultra-renovations',
  'ChIJHfwEm0jeEFMRXb_ciMbpy8Y',
  50.2841272,
  -107.8001612,
  '13067785872',
  'https://www.kwikr.ca/pictures/profile/pimage-705.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  709,
  'https://ultrarenovations.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Cegerco',
  '<p>Cegerco operates as a reliable general contractor in Chicoutimi, Quebec, providing top-notch construction services. With a focus on residential and commercial projects, Cegerco has built a reputation for quality workmanship and timely project completion. The company is located at 1180 Rue Bersimis and serves the surrounding areas, ensuring all construction needs are met efficiently.</p><p>The team at Cegerco consists of experienced professionals who prioritize client satisfaction. They manage various projects, from renovations to new constructions, ensuring that all work adheres to industry standards. Cegerco emphasizes effective communication and transparency throughout the construction process, which fosters trust and reliability among clients.</p><p>Cegerco’s commitment to excellence is evident in its portfolio, showcasing a variety of successful projects that highlight their versatility and skill. The company utilizes modern techniques and quality materials to deliver results that meet client expectations. Their focus on safety and compliance with local regulations further enhances their credibility in the industry.</p><p>Cegerco stands out for its dedication to providing comprehensive general contracting services in Chicoutimi. The combination of skilled professionals, a strong emphasis on quality, and a commitment to customer satisfaction positions Cegerco as a leader in the construction sector. Contact Cegerco at 1180 Rue Bersimis for expert general contracting services in Chicoutimi, Quebec.</p>',
  '1180 Rue Bersimis',
  'Canada',
  'QC',
  'Chicoutimi',
  'G7K 1A5',
  'office@ltlgroup.ca',
  'canada/chicoutimi/home-services/cegerco',
  'ChIJu7hUbMImwEwRIKSSVOKvlYE',
  48.3948055,
  -71.110275,
  '14185436159',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  708,
  'https://www.cegerco.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'LTL Contracting',
  '<p>LTL Contracting operates as a trusted general contractor in Shuniah, Ontario, specializing in construction, directional drilling, equipment rentals, and environmental services. With over 30 years of experience, LTL Contracting has established a solid reputation in Northwestern Ontario for delivering reliable and efficient solutions tailored to client needs.</p> <p>The company excels in various construction projects, ensuring high-quality workmanship and adherence to timelines. Directional drilling services are performed with precision, allowing for minimal disruption and maximum efficiency. Equipment rentals offer clients access to a wide range of machinery, simplifying project execution and reducing costs. Environmental services provided by LTL Contracting focus on sustainable practices, addressing the growing need for eco-friendly solutions in construction.</p> <p>Achievements in the industry include successful completion of numerous projects across the region, showcasing the company''s commitment to excellence. LTL Contracting prioritizes customer satisfaction and invests in the latest technology to enhance service delivery. The skilled team at LTL Contracting brings extensive knowledge and expertise, ensuring that all projects meet industry standards and regulations.</p> <p>LTL Contracting offers a comprehensive suite of services, highlighting strengths in construction, drilling, equipment rental, and environmental solutions. The company’s longstanding presence in Shuniah reflects its dedication to the community and commitment to quality. Reach out to LTL Contracting for reliable general contracting services in Shuniah, Ontario.</p>',
  '227 ON-527',
  'Canada',
  'ON',
  'Shuniah',
  'P7A 0N4',
  'team@devmaninc.com',
  'canada/shuniah/home-services/ltl-contracting',
  'ChIJO5nu0hU7WU0RPCB9a-3ZAxo',
  48.4975454,
  -89.1399775,
  '18076233600',
  'https://www.kwikr.ca/pictures/profile/pimage-703.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  707,
  'http://www.ltlgroup.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Devman Group Inc.',
  '<p>Devman Group Inc. operates as a leading general contractor located at 280 Yorktech Dr Unit 22 in Markham, Ontario. This firm specializes in custom renovation and refurbishment services for condominium common areas throughout the Greater Toronto Area. The business emphasizes tailored solutions that enhance both the aesthetics and functionality of shared spaces, driving up their value.</p> <p>With a commitment to quality and exceptional communication, Devman Group Inc. ensures that every project aligns with the specific needs of condominium communities. The focus on customer satisfaction has led to a strong reputation in the industry. Clients benefit from a collaborative approach that prioritizes their vision while maintaining high standards of workmanship. The team at Devman Group possesses extensive experience in managing renovations, ensuring projects are completed efficiently and effectively.</p> <p>Devman Group Inc. excels in delivering results that transform communal areas into inviting and functional spaces. Their dedication to service and quality has garnered positive feedback from numerous clients, showcasing their ability to meet diverse renovation needs. The firm’s expertise in custom solutions sets it apart in the competitive market of general contracting. </p> <p>Devman Group Inc. provides comprehensive renovation services, focusing on the unique requirements of condominium communities in Markham, Ontario. Their strengths lie in quality craftsmanship and effective communication. Engage with Devman Group Inc. today for expert renovation services in Markham. </p>',
  '280 Yorktech Dr Unit 22',
  'Canada',
  'ON',
  'Markham',
  NULL,
  'shirley@kedevelopment.ca',
  'canada/markham/home-services/devman-group-inc',
  'ChIJ4RFUhS7S1IkRjTrla-lgTTE',
  43.8464179,
  -79.3493332,
  '19056040555',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  706,
  'https://www.devmaninc.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Kerkhof Enterprises',
  '<p>Kerkhof Enterprises operates as a reliable general contractor located in Spruce Grove, Alberta. This business specializes in custom home building, particularly for acreage and recreational properties. With a strong focus on quality and customer satisfaction, Kerkhof Enterprises offers a range of services tailored to meet diverse construction needs.</p><p>The company excels in acreage development, providing essential services like land clearing, septic and wastewater management system design, and installation. New electrical service installation is also part of their comprehensive offerings. Experienced professionals ensure that all projects meet local regulations and standards, enhancing the safety and functionality of each construction endeavor.</p><p>Kerkhof Enterprises has built a reputation for delivering projects on time and within budget. Clients appreciate the attention to detail and the commitment to high-quality craftsmanship. The team understands the unique challenges associated with building on acreage and recreational land, making them a preferred choice for many in the region.</p><p>This general contractor not only meets construction needs but also fosters positive relationships with clients through transparent communication and dedicated service. Their experience in the industry positions them as a leader in custom home building in Alberta. For those seeking reliable construction services, Kerkhof Enterprises provides the expertise and support necessary to bring visions to life. Connect with Kerkhof Enterprises in Spruce Grove for exceptional construction solutions.</p>',
  '27227 Township Rd 522',
  'Canada',
  'AB',
  'Spruce Grove',
  'T7X 3R7',
  'careers@bda.ca',
  'canada/spruce-grove/home-services/kerkhof-enterprises',
  'ChIJmxQ9eL2Nn1MRQBSjWMMp7Ks',
  53.4826159,
  -113.9060732,
  '17809930836',
  'https://www.kwikr.ca/pictures/profile/pimage-701.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  705,
  'http://www.kedevelopment.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'BDA Inc.',
  '<p>BDA Inc. operates as a reliable general contractor in Etobicoke, Ontario, specializing in residential and commercial construction projects. With a strong commitment to quality and customer satisfaction, BDA Inc. has built a reputation for delivering exceptional results on time and within budget. The company serves the local community by offering a range of services including renovations, new builds, and project management.</p><p>The team at BDA Inc. consists of skilled professionals who bring years of experience to each project. Their approach emphasizes clear communication and collaboration with clients, ensuring that every detail aligns with expectations. This contractor utilizes high-quality materials and innovative techniques to enhance the durability and aesthetic appeal of each project. BDA Inc. understands the importance of adhering to local building codes and regulations, providing peace of mind to clients throughout the construction process.</p><p>BDA Inc. has successfully completed numerous projects in the area, showcasing their ability to handle diverse construction challenges. Their dedication to excellence has garnered positive feedback from clients, reflecting the company’s commitment to delivering outstanding service. This general contractor continues to contribute to the growth and development of Etobicoke through their reliable services and community involvement.</p><p>BDA Inc. offers a comprehensive range of general contracting services that prioritize quality and customer satisfaction. With a skilled team and a proven track record, this company remains a trusted partner for construction needs in Etobicoke. Connect with BDA Inc. today to explore their services in Ontario.</p>',
  '36 Butterick Rd',
  'Canada',
  'ON',
  'Etobicoke',
  'M8W 3Z8',
  'elwooddisposal@outlook.com',
  'canada/etobicoke/home-services/bda-inc',
  'ChIJL5CtrSA2K4gRNEa4aYrePW0',
  43.6125354,
  -79.5305157,
  '14162511757',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  704,
  'https://www.bda.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Elwood Homes & Construction',
  '<p>Elwood Homes & Construction operates as a reliable general contractor in Fenelon Falls, Ontario. This business specializes in residential and commercial construction projects, offering services such as renovations, custom builds, and property management. With a commitment to quality and customer satisfaction, Elwood Homes has established a strong reputation in the local community.</p> <p>The team at Elwood Homes & Construction brings extensive experience to every project. They focus on understanding client needs and delivering results that meet those expectations. The use of high-quality materials and skilled craftsmanship ensures durability and aesthetic appeal in all completed projects. This dedication to excellence has garnered positive feedback from clients throughout the Fenelon Falls area.</p> <p>Elwood Homes actively engages with the community, contributing to local initiatives and supporting sustainable building practices. Their approach combines traditional methods with modern techniques, ensuring each project is completed efficiently and effectively. The company values transparency, providing clients with clear timelines and budgets, fostering trust and collaboration.</p> <p>Elwood Homes & Construction offers a comprehensive range of services in general contracting, including renovations and custom builds. Their commitment to quality and community involvement enhances their reputation. Engage with Elwood Homes & Construction for reliable services in Fenelon Falls, Ontario.',
  '491 Kawartha Lakes County Rd 30',
  'Canada',
  'ON',
  'Fenelon Falls',
  'K0M 1N0',
  'carlos@firstclassrenos.com',
  'canada/fenelon-falls/home-services/elwood-homes-construction',
  'ChIJB3PcGrQp1UwRuPH1G6rH8kQ',
  44.5214649,
  -78.6523844,
  '17056579543',
  'https://www.kwikr.ca/pictures/profile/pimage-699.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  703,
  'https://elwoodhomesandconstruction.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'First Class Roofing & Renovations Okotoks',
  '<p>First Class Roofing & Renovations Okotoks operates as a reliable general contractor in Okotoks, Alberta. This BBB Accredited business excels in both commercial and residential construction projects. With over 30 years of experience, First Class offers licensed, bonded, and insured services. The company provides free estimates, showcasing a commitment to transparency and quality.</p><p>The team at First Class specializes in roofing and renovations, ensuring that every project meets high standards. An in-house insurance claim specialist simplifies the process for clients, making it easier to navigate claims. The advanced team of in-house installers guarantees that projects are completed efficiently and effectively. Client satisfaction remains a priority, with a focus on delivering quality results.</p><p>First Class Roofing & Renovations Okotoks has built a reputation for trustworthiness and expertise in the local area. The combination of skilled professionals and a commitment to quality ensures that clients receive top-notch service. The business''s extensive experience allows it to handle a variety of construction needs, making it a go-to option for residents in Okotoks.</p><p>With a focus on quality, transparency, and customer satisfaction, First Class Roofing & Renovations Okotoks provides essential construction services for the community. The business stands ready to assist with any roofing or renovation needs. Connect with First Class Roofing & Renovations Okotoks for expert services in Okotoks, Alberta.</p>',
  '17089 306 Ave E',
  'Canada',
  'AB',
  'Okotoks',
  'T1S 1A2',
  'contact@menuiseriesimonfortin.ca',
  'canada/okotoks/home-services/first-class-roofing-renovations-okotoks',
  'ChIJTy77ZRGZcVMRDezOXmYtV5E',
  50.7710915,
  -113.9651512,
  '14038375028',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  702,
  'https://www.firstclassrenos.com/?utm_source=google&utm_medium=wix_google_business_profile&utm_campaign=2743003828743871207',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Fortin Frenette Ebenistes Inc.',
  '<p>Fortin Frenette Ebenistes Inc. operates as a general contractor in West Brome, Quebec, specializing in high-end architectural projects. This company delivers exceptional craftsmanship and attention to detail, making it a notable choice for discerning clients in the region. With a focus on quality, Fortin Frenette Ebenistes Inc. has built a reputation for excellence in its field.</p> <p>The team at Fortin Frenette Ebenistes Inc. brings extensive experience to every project, ensuring that each design meets the client''s vision and standards. The company handles a variety of construction tasks, from custom woodwork to complete renovations, showcasing versatility and skill. Clients can expect personalized service and a commitment to delivering results that exceed expectations.</p> <p>Located at 1060 Knowlton Rd, the company serves the local community with pride. Its dedication to high-quality materials and sustainable practices further enhances its standing in the competitive contracting industry. Fortin Frenette Ebenistes Inc. not only meets the needs of its clients but also contributes positively to the local economy through job creation and community engagement.</p> <p>Fortin Frenette Ebenistes Inc. offers a range of services focused on high-end architectural projects, emphasizing quality and client satisfaction. The company''s commitment to excellence is evident in every project undertaken. For those in need of expert general contracting services in West Brome, Quebec, reach out to Fortin Frenette Ebenistes Inc. for a consultation.</p>',
  '1060 Knowlton Rd',
  'Canada',
  'QC',
  'West Brome',
  'J0E 2P0',
  'info@bienconstruire.ca',
  'canada/west-brome/home-services/fortin-frenette-ebenistes-inc',
  'ChIJBYn7UtQCtkwR-1yZv1QUUbE',
  45.1989704,
  -72.6628191,
  '14505313756',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  701,
  'https://menuiseriesimonfortin.ca/en/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Construction RGP Brouillard',
  '<p>Construction RGP Brouillard operates as a general contractor in Saint-Hyacinthe, Quebec, specializing in commercial, industrial, agro-food, and multi-residential construction projects. With a strong commitment to quality and efficiency, this local business has consistently delivered exceptional results, contributing to the growth of the community.</p> <p>The company excels in managing diverse construction needs, ensuring that each project meets industry standards and client expectations. Construction RGP Brouillard employs skilled professionals who bring expertise and dedication to every task. The team focuses on innovative solutions tailored to specific requirements, enhancing the overall construction experience.</p> <p>In addition to its technical capabilities, Construction RGP Brouillard emphasizes safety and sustainability in its operations. This approach not only protects workers but also supports environmental responsibility. Clients appreciate the transparency and communication throughout the construction process, fostering trust and reliability.</p> <p>Construction RGP Brouillard has established a reputation for completing projects on time and within budget. The company’s portfolio includes a variety of successful ventures, showcasing its versatility and commitment to excellence. Local businesses and residents have benefitted from its services, contributing to the economic development of Saint-Hyacinthe.</p> <p>Construction RGP Brouillard offers comprehensive general contracting services that prioritize quality, safety, and client satisfaction. The company’s achievements reflect its dedication to the construction industry. Connect with Construction RGP Brouillard at 7380 Bd Laurier O, Saint-Hyacinthe, Quebec, for reliable construction services.</p>',
  '7380 Bd Laurier O',
  'Canada',
  'QC',
  'Saint-Hyacinthe',
  'J2S 9A9',
  'sahibjeetconstruction@gmail.com',
  'canada/saint-hyacinthe/home-services/construction-rgp-brouillard',
  'ChIJT1fGj7FNyEwRfjzEcF6bWhU',
  45.601653,
  -73.001651,
  '14507745567',
  'https://www.kwikr.ca/pictures/profile/pimage-696.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  700,
  'http://www.bienconstruire.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Sahibjeet Construction and renovation ltd',
  '<p>Sahibjeet Construction and Renovation Ltd, located at 14160 78 Ave, Surrey, British Columbia, specializes in comprehensive general contracting services. This business excels in home renovations, including kitchen, washroom, and basement remodeling, as well as new construction projects. With a focus on quality and customer satisfaction, Sahibjeet Construction has established itself as a reliable choice for homeowners in the region.</p><p>The company offers a wide range of services tailored to meet the unique needs of each client. From initial design consultations to project completion, Sahibjeet Construction ensures that every aspect of the renovation process is handled with professionalism. The team is skilled in various construction techniques and stays updated on the latest industry trends, which enhances the quality of their work.</p><p>Clients appreciate the attention to detail and commitment to delivering projects on time and within budget. Sahibjeet Construction has garnered positive feedback for its transparent communication and dedication to exceeding customer expectations. The business has successfully completed numerous projects in Surrey, contributing to the community''s growth and aesthetic appeal.</p><p>Sahibjeet Construction and Renovation Ltd offers a full suite of renovation and construction services, showcasing expertise in kitchen, washroom, and basement remodeling alongside new builds. This commitment to quality and customer satisfaction makes the company a valuable asset to Surrey. Connect with Sahibjeet Construction for exceptional services in British Columbia.</p>',
  '14160 78 Ave',
  'Canada',
  'BC',
  'Surrey',
  'V3W 2Y1',
  'info@fortsaskreno.com',
  'canada/surrey/home-services/sahibjeet-construction-and-renovation-ltd',
  'ChIJ0fYRsRvbhVQRGNr5pGXrQNE',
  49.144353,
  -122.8301825,
  '16047201515',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  699,
  'https://sahibjeetconstruction.com/',
  NULL,
  NULL,
  NULL,
  NULL
);
