INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Jordans Flooring',
  '<p>Jordans Flooring, located at 7290 11 St SE in Calgary, Alberta, provides an extensive selection of high-quality flooring products and full installation services. This family-owned flooring store serves the Calgary area with a commitment to customer satisfaction and offers a wide range of options to fit various budgets and styles. From hardwood to laminate, and carpets to tiles, Jordans Flooring caters to diverse flooring needs.</p><p>The store features a vast inventory that includes products suitable for residential and commercial spaces. Jordans Flooring prides itself on its knowledgeable staff, who assist customers in selecting the perfect flooring solutions tailored to their specific requirements. The installation team ensures that every project is completed with precision and care, enhancing the overall customer experience.</p><p>Jordans Flooring has built a strong reputation in Calgary for its reliability and dedication to quality. Customers appreciate the transparent pricing and the extensive variety of styles available, making it easier to find the right match for any decor. The business is committed to maintaining high standards in both product offerings and customer service.</p><p>With a focus on quality and customer satisfaction, Jordans Flooring delivers exceptional flooring solutions for every project. The combination of a vast selection and expert installation services positions the store as a top choice in Calgary. Visit Jordans Flooring today to explore flooring options that meet every need in Calgary, Alberta.</p>',
  '7290 11 St SE',
  'Canada',
  'AB',
  'Calgary',
  'T2H 2S9',
  'shopillights@gmail.com',
  'canada/calgary/home-services/jordans-flooring',
  'ChIJL7r4qFdwcVMR-eY2JMJXjjI',
  50.9892261,
  -114.0387536,
  '14032121000',
  NULL,
  'Flooring=>Heated Flooring',
  'Pay-as-you-go',
  273,
  'https://jordansflooring.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Fiber & Cloth Inc.',
  '<p>Fiber & Cloth Inc. offers a wide range of flooring solutions in Toronto, Ontario. This flooring store specializes in high-quality materials, including hardwood, laminate, and vinyl, catering to both residential and commercial clients. With a commitment to customer satisfaction, the business has built a reputation for reliability and excellence in the local area.</p> <p>The store features an extensive selection of flooring options, ensuring that customers find the perfect match for their needs. Knowledgeable staff members provide expert guidance, helping clients navigate the various choices available. Fiber & Cloth Inc. emphasizes quality and durability, ensuring that each product meets high standards. The business also offers professional installation services, guaranteeing a seamless transition from selection to completion.</p> <p>Located at 491 Champagne Dr, Fiber & Cloth Inc. serves the Toronto community with pride. The store has received positive feedback for its attentive service and extensive product range. Customers appreciate the personalized approach, which enhances the shopping experience. The business remains dedicated to keeping up with industry trends, ensuring the latest styles and materials are available.</p> <p>Fiber & Cloth Inc. delivers exceptional flooring solutions, expert advice, and reliable installation services. The commitment to quality and customer satisfaction sets this flooring store apart in Toronto. Visit Fiber & Cloth Inc. today to explore the flooring options available in Ontario''s thriving market.</p>',
  '491 Champagne Dr',
  'Canada',
  'ON',
  'Toronto',
  'M3J 2C6',
  'lightdepot2@hotmail.com',
  'canada/toronto/home-services/fiber-cloth-inc',
  'ChIJi5qSnQEuK4gRKQAiwSASeb4',
  43.7644413,
  -79.4750542,
  '14167990888',
  NULL,
  'Flooring=>Heated Flooring',
  'Pay-as-you-go',
  272,
  'http://www.fiberandcloth.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Plancher Tendance Rive-Sud',
  '<p>Plancher Tendance Rive-Sud provides expert wood floor installation services in Saint-Michel, Quebec. This local business specializes in wood floor restoration, dust-free sanding, staining, and varnishing. With a commitment to quality and customer satisfaction, Plancher Tendance Rive-Sud has established itself as a reliable choice for homeowners seeking to enhance their living spaces with beautiful wood flooring.</p> <p>The company focuses on delivering exceptional craftsmanship and attention to detail. Their dust-free sanding technique minimizes mess, ensuring a clean environment during the restoration process. This method not only improves the overall experience but also enhances the final appearance of the floors. Clients appreciate the thorough approach to each project, whether it involves refinishing existing floors or installing new ones.</p> <p>Plancher Tendance Rive-Sud has garnered positive feedback from the local community for its professionalism and reliability. The skilled team works closely with clients to understand their specific needs and preferences, resulting in tailored solutions that meet and exceed expectations. This dedication to customer service contributes to their growing reputation in the wood flooring industry.</p> <p>Plancher Tendance Rive-Sud offers a range of services, including wood floor installation, restoration, and finishing. Their expertise and commitment to quality make them a preferred choice in Saint-Michel. Reach out to Plancher Tendance Rive-Sud for top-notch wood floor services in Quebec. </p>',
  '1714 martin',
  'Canada',
  'QC',
  'Saint-Michel',
  'J0L 2J0',
  'info@eclairagediode.com',
  'canada/saint-michel/home-services/plancher-tendance-rive-sud',
  'ChIJx-d-OrpxyUwRd3CZ9krs9Ek',
  45.2359918,
  -73.568818,
  '14509932990',
  'https://www.kwikr.ca/pictures/profile/pimage-255.jpg',
  'Flooring=>Hardwood Flooring',
  'Pay-as-you-go',
  271,
  'http://planchertendancerivesud.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Service De Plancher Marcel & Fils',
  '<p>Service De Plancher Marcel & Fils offers expert wood floor installation and repair services in Saint-Jacques, Quebec. This local business specializes in sanding and finishing techniques, ensuring high-quality results for residential and commercial spaces. The company serves not just Saint-Jacques but also extends its services to Laval and the regions of Lanaudière and La Mauricie, including Mascouche, Trois-Rivières, Joliette, and Terrebonne.</p><p>With a strong focus on customer satisfaction, Service De Plancher Marcel & Fils has built a reputation for reliability and quality. The team employs skilled professionals who understand the intricacies of wood flooring. They utilize advanced techniques in sanding and varnishing, ensuring a smooth and durable finish. This attention to detail sets the company apart in the competitive wood floor installation market.</p><p>Service De Plancher Marcel & Fils prides itself on its commitment to excellence. The business has successfully completed numerous projects, earning positive feedback from clients throughout the region. The combination of expertise and quality materials guarantees long-lasting results, making it a trusted choice for wood floor needs.</p><p>In summary, Service De Plancher Marcel & Fils provides comprehensive wood floor installation and repair services in Saint-Jacques and surrounding areas. Their expertise in sanding and finishing, coupled with a focus on customer satisfaction, positions them as a leader in the industry. Reach out to Service De Plancher Marcel & Fils for exceptional wood flooring services in Quebec.</p>',
  NULL,
  'Canada',
  'QC',
  'Saint-Jacques',
  'J0K 2R0',
  'salesnanaimo@mclarenlighting.com',
  'canada/saint-jacques/home-services/service-de-plancher-marcel-fils',
  'ChIJg3_25SK5yEwRUNgYRSja8dg',
  45.9466892,
  -73.564154,
  '14506694411',
  'https://www.kwikr.ca/pictures/profile/pimage-254.jpg',
  'Flooring=>Hardwood Flooring',
  'Pay-as-you-go',
  270,
  'https://www.planchermarcel.com/?utm_medium=referral&utm_source=gmb&utm_campaign=lnk-gmb',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'YF Custom Flooring',
  '<p>YF Custom Flooring offers expert wood floor installation services in Edmonton, Alberta. This local business specializes in transforming spaces with high-quality flooring solutions tailored to meet customer needs. With a commitment to craftsmanship and customer satisfaction, YF Custom Flooring has built a reputation for reliability and excellence. The team at YF Custom Flooring brings years of experience to every project, ensuring durable and aesthetically pleasing results.</p> <p>Located at 300 Ormsby Rd E Northwest, YF Custom Flooring serves the Edmonton area with a focus on residential and commercial properties. The business utilizes premium materials and advanced techniques to deliver superior flooring options. Customers appreciate the personalized approach and attention to detail that YF Custom Flooring provides. Each installation project receives careful planning and execution, resulting in beautiful floors that enhance any environment.</p> <p>YF Custom Flooring emphasizes the importance of quality and service in every job. Clients benefit from the team’s extensive knowledge of wood flooring products and installation methods. This dedication to excellence has earned YF Custom Flooring numerous positive reviews from satisfied customers. The company continues to grow its presence in the local market by maintaining high standards and a customer-first philosophy.</p> <p>YF Custom Flooring delivers exceptional wood floor installation services, showcasing a commitment to quality and customer satisfaction. This local business stands ready to transform spaces in Edmonton, Alberta. Connect with YF Custom Flooring today for expert flooring solutions that elevate any home or business.</p>',
  '300 Ormsby Rd E Northwest',
  'Canada',
  'AB',
  'Edmonton',
  'T5T 5J6',
  'n.brazeau@eclairage-etc.com',
  'canada/edmonton/home-services/yf-custom-flooring',
  'ChIJtSy0k3QgoFMR2X54AT9-HAM',
  53.5014174,
  -113.64696,
  '17807092444',
  NULL,
  'Flooring=>Hardwood Flooring',
  'Pay-as-you-go',
  269,
  'http://www.yfcustomflooring.com/index.html',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Bois et Tendance',
  '<p>Bois et Tendance offers exceptional wood floor installation services in Sainte-Julie, Quebec. This local business focuses on excellence, ensuring that each project meets high standards. The team consists of skilled professionals with extensive expertise in hardwood flooring installation. Whether the project is residential or commercial, Bois et Tendance handles a wide range of flooring needs, from simple installations to complex, large-scale projects.</p> <p>The commitment to quality is evident in every aspect of Bois et Tendance''s work. The team understands the nuances of wood flooring and provides tailored solutions to meet the specific needs of each client. With a focus on customer satisfaction, the company ensures that each installation enhances the beauty and functionality of the space. The professionals use only the finest materials, ensuring durability and aesthetic appeal in every project. </p> <p>Bois et Tendance has built a reputation for reliability and excellence in the local community. The business has successfully completed numerous projects, showcasing its ability to tackle diverse flooring challenges. Clients appreciate the attention to detail and the seamless execution of installations. The team’s dedication to craftsmanship and customer service sets Bois et Tendance apart in the competitive market of wood floor installation.</p> <p>Bois et Tendance excels in providing high-quality wood floor installation services in Sainte-Julie, Quebec. The combination of skilled professionals, a commitment to excellence, and a broad range of project capabilities makes this company a trusted choice for flooring needs. Connect with Bois et Tendance to explore expert wood floor installation services in Sainte-Julie.</p>',
  '447 Rue Flaubert',
  'Canada',
  'QC',
  'Sainte-Julie',
  'J3E 2W6',
  'customercare@robinsonco.ca',
  'canada/sainte-julie/home-services/bois-et-tendance',
  'ChIJx4vrVL4ByUwRASmAzWfk3LA',
  45.5728738,
  -73.3191669,
  '15148637556',
  'https://www.kwikr.ca/pictures/profile/pimage-252.jpg',
  'Flooring=>Hardwood Flooring',
  'Pay-as-you-go',
  268,
  'https://www.boisettendance.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Darmaga Hardwood Flooring Ltd',
  '<p>Darmaga Hardwood Flooring Ltd, located at 70 Newkirk Rd in Richmond Hill, Ontario, offers expert wood floor installation services. This family-owned business has served the Greater Toronto Area and beyond since 1940, specializing in hardwood, engineered, laminate, and hand-scraped flooring. With over 78 years of experience, Darmaga has established itself as a leader in the hardwood flooring industry.</p> <p>The company prides itself on its commitment to quality and customer satisfaction. Darmaga Hardwood Flooring employs skilled professionals who ensure precise installations tailored to each client''s needs. The extensive range of flooring options caters to various styles and preferences, making it easy for homeowners to find the perfect fit for their spaces. The longstanding reputation of the Darmaga family reflects their dedication to excellence and craftsmanship.</p> <p>With a focus on innovation and adaptation, Darmaga has grown to become one of the largest hardwood flooring companies in Ontario. The team stays updated with the latest trends and technologies in flooring, ensuring that customers receive modern solutions alongside traditional craftsmanship.</p> <p>Darmaga Hardwood Flooring Ltd continues to deliver exceptional service and quality products to homeowners in Richmond Hill and the surrounding areas. Trust in their expertise for all wood flooring needs. Visit Richmond Hill to explore the offerings of Darmaga Hardwood Flooring Ltd.</p>',
  '70 Newkirk Rd',
  'Canada',
  'ON',
  'Richmond Hill',
  'L4C 3G3',
  'service@eclairagesaran.com',
  'canada/richmond-hill/home-services/darmaga-hardwood-flooring-ltd',
  'ChIJvbX-klcqK4gRbOA7Ztge5Ig',
  43.8802901,
  -79.4279073,
  '19057701900',
  'https://www.kwikr.ca/pictures/profile/pimage-251.jpg',
  'Flooring=>Hardwood Flooring',
  'Pay-as-you-go',
  267,
  'https://darmaga.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Couvre-Planchers de Beauce',
  '<p>Couvre-Planchers de Beauce provides expert wood floor installation services in Saint-Joseph-de-Beauce, Quebec. This local business specializes in a variety of flooring options, including ceramic, carpet, and vinyl. The company also excels in restoration and repair services for residential, commercial, and industrial buildings, ensuring quality and durability in every project.</p><p>The team at Couvre-Planchers de Beauce focuses on delivering high-quality installations tailored to meet customer needs. With a comprehensive selection of materials such as slate, marble, and granite, clients can find the perfect fit for their spaces. The business prides itself on offering practical advice and guidance throughout the installation process, making it easier for customers to make informed decisions.</p><p>Couvre-Planchers de Beauce has established a strong reputation in the community for its reliable services and attention to detail. The company’s commitment to customer satisfaction is evident in its thorough approach to every project. Whether it’s a small residential installation or a large commercial restoration, the team approaches each job with professionalism and expertise.</p><p>This business stands out by providing a diverse range of flooring solutions and exceptional service. Customers can trust Couvre-Planchers de Beauce for all their flooring needs. Connect with Couvre-Planchers de Beauce at 169 Rue du Grand Mont, Saint-Joseph-de-Beauce, Quebec, for top-notch wood floor installation services.</p>',
  '169 Rue du Grand Mont',
  'Canada',
  'QC',
  'Saint-Joseph-de-Beauce',
  'G0S 2V0',
  'support@multiluminaire.ca',
  'canada/saint-joseph-de-beauce/home-services/couvre-planchers-de-beauce',
  'ChIJvQXLTgutuUwRAqJX5uZRJYs',
  46.3069083,
  -70.8752523,
  '14183902050',
  NULL,
  'Flooring=>Hardwood Flooring',
  'Pay-as-you-go',
  266,
  'https://maregion.ca/index.php/couvre-plancher-de-beauce-inc',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Éco Évolution - Sablage de planchers sans poussière',
  '<p>Éco Évolution offers exceptional wood floor installation services in Boisbriand, Quebec. This local business specializes in dust-free sanding, staining, and refinishing of hardwood floors, as well as staircase renovations. With a commitment to quality and customer satisfaction, Éco Évolution has earned a reputation for expertise in ancestral flooring and modern techniques.</p> <p>The team at Éco Évolution utilizes advanced dust-free technology, ensuring a cleaner work environment and minimizing disruptions. This innovative approach not only enhances the quality of the finished product but also promotes a healthier home atmosphere. Skilled professionals handle every project with precision, catering to both residential and commercial needs. The company’s experience in working with various wood types allows for tailored solutions that meet diverse aesthetic preferences.</p> <p>Éco Évolution''s dedication to craftsmanship is evident in every project. The business prides itself on attention to detail and personalized service, ensuring that each client receives the best possible outcome. Whether it''s revitalizing old floors or installing new ones, the results consistently reflect high standards and professionalism.</p> <p>In summary, Éco Évolution excels in providing wood floor installation services, specializing in dust-free sanding and staining. The business''s strengths lie in its innovative techniques, skilled workforce, and commitment to customer satisfaction. Connect with Éco Évolution today at 3638 Rue Charlotte Boisjoli, Boisbriand, Quebec, for top-notch flooring solutions.</p>',
  '3638 Rue Charlotte Boisjoli',
  'Canada',
  'QC',
  'Boisbriand',
  'J7H 1R7',
  'info@gravitytech.ca',
  'canada/boisbriand/home-services/éco-évolution-sablage-de-planchers-sans-poussière',
  'ChIJt-6ZyZopyUwRTMFbzvDcP2I',
  45.6301528,
  -73.8704698,
  '15149519118',
  'https://www.kwikr.ca/pictures/profile/pimage-249.jpg',
  'Flooring=>Hardwood Flooring',
  'Pay-as-you-go',
  265,
  'http://ecoevolutioninc.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Pose de Planchers et Sablage Gilles Quirion & Fils',
  '<p>Pose de Planchers et Sablage Gilles Quirion & Fils offers expert wood floor installation services in Saint-Gédéon-de-Beauce, Quebec. This local business specializes in delivering high-quality flooring solutions tailored to meet the needs of residential and commercial clients. With years of experience, the company has built a reputation for reliability and craftsmanship in the wood flooring industry.</p><p>The team at Pose de Planchers et Sablage Gilles Quirion & Fils utilizes advanced techniques and premium materials to ensure each project meets the highest standards. They provide a comprehensive range of services, including installation, sanding, and refinishing of wood floors. Attention to detail and a commitment to customer satisfaction are evident in every project undertaken.</p><p>This business has successfully completed numerous installations, enhancing the aesthetic appeal and value of homes and businesses in the area. The skilled professionals understand the unique requirements of each client, ensuring personalized service and exceptional results. Their dedication to quality has earned them a loyal customer base within the community.</p><p>Pose de Planchers et Sablage Gilles Quirion & Fils excels in providing reliable wood floor installation services, demonstrating expertise and commitment to quality. The company’s focus on customer satisfaction and craftsmanship positions it as a trusted choice for flooring needs in Saint-Gédéon-de-Beauce. Connect with Pose de Planchers et Sablage Gilles Quirion & Fils for exceptional wood flooring solutions in Quebec.</p>',
  '120 13e Rue S',
  'Canada',
  'QC',
  'Saint-Gédéon-de-Beauce',
  'G0M 1T0',
  'info@danasmarthomes.com',
  'canada/saint-gédéon-de-beauce/home-services/pose-de-planchers-et-sablage-gilles-quirion-fils',
  'ChIJp12q7EbjuUwRc3BccQVHgc4',
  45.8467588,
  -70.636804,
  '14185823102',
  'https://www.kwikr.ca/pictures/profile/pimage-248.jpg',
  'Flooring=>Hardwood Flooring',
  'Pay-as-you-go',
  264,
  'http://www.anugo.ca/fr/entreprise/48278-solution-multi-pub-canada-inc-communication-montreal.html',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'SMNR Flooring',
  '<p>SMNR Flooring specializes in wood floor installation services in Beauharnois, Quebec. This local business offers expertise in the installation, sanding, and finishing of hardwood floors, serving the South Shore of Montreal. With a focus on quality craftsmanship, SMNR Flooring ensures that each project meets high standards and customer satisfaction.</p> <p>The team at SMNR Flooring possesses extensive knowledge of hardwood flooring options. They provide tailored solutions that cater to various styles and preferences. The installation process is efficient, minimizing disruption while maintaining attention to detail. Sourcing high-quality materials is a priority, ensuring durability and aesthetic appeal in every project. Customers appreciate the professionalism and expertise that SMNR Flooring brings to each job.</p> <p>In addition to installation, SMNR Flooring excels in sanding and finishing services. These processes enhance the natural beauty of hardwood floors while extending their lifespan. The company employs modern techniques and equipment to achieve optimal results. Feedback from clients highlights the transformative effect of their services, showcasing floors that are both functional and attractive.</p> <p>SMNR Flooring delivers comprehensive wood floor solutions, emphasizing quality, efficiency, and customer satisfaction. Their commitment to excellence and local expertise positions them as a trusted choice for flooring needs in Beauharnois. Connect with SMNR Flooring today for exceptional wood floor installation services in Quebec.</p>',
  '560 Rue Jeanne-d''Arc',
  'Canada',
  'QC',
  'Beauharnois',
  'J6N 2C8',
  'sales@pureimage.ca',
  'canada/beauharnois/home-services/smnr-flooring',
  'ChIJUVDgAiNByUwRr0FkhpKInz0',
  45.3084651,
  -73.8665839,
  '14383911476',
  NULL,
  'Flooring=>Hardwood Flooring',
  'Pay-as-you-go',
  263,
  'http://www.planchersmnr.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Roj services',
  '<p>Roj Services specializes in wood floor installation in Nepean, Ontario. This local business offers a range of flooring solutions tailored to meet diverse customer needs. With a commitment to quality and customer satisfaction, Roj Services has earned a reputation for excellence in the wood flooring industry.</p><p>The team at Roj Services brings extensive expertise to every project. They provide professional consultations to help clients choose the right wood flooring options, ensuring that each installation aligns with the unique style and functionality required. The installation process is efficient and meticulous, focusing on detail to guarantee a flawless finish.</p><p>Roj Services uses high-quality materials sourced from reputable suppliers. This dedication to quality ensures that every wood floor installed is durable and visually appealing. The business prides itself on its ability to handle projects of all sizes, from residential homes to commercial spaces, adapting to the specific demands of each environment.</p><p>With a strong emphasis on customer service, Roj Services maintains open communication throughout the installation process. This approach fosters trust and ensures that client expectations are met or exceeded. The business has successfully completed numerous projects in the Nepean area, showcasing its reliability and craftsmanship.</p><p>Roj Services offers professional wood floor installation with a focus on quality and customer satisfaction. With a skilled team and a commitment to excellence, this local business is a top choice for flooring needs. Reach out to Roj Services at 1568 Merivale Rd, Nepean, Ontario, for expert wood floor installation services.</p>',
  '1568 Merivale Rd',
  'Canada',
  'ON',
  'Nepean',
  'K2G 5Y7',
  'kenton@aspenautomation.ca',
  'canada/nepean/home-services/roj-services',
  'ChIJoxBf_f8GzkwRSwJpbhNzx4k',
  45.3516109,
  -75.7347955,
  '16132765958',
  NULL,
  'Flooring=>Hardwood Flooring',
  'Pay-as-you-go',
  262,
  'https://rojservices.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Canada West Flooring Solutions Inc',
  '<p>Canada West Flooring Solutions Inc delivers exceptional wood floor installation services in Richmond, British Columbia. This business specializes in a wide range of wood flooring products, including engineered wood, vinyl, and laminate options sourced globally. With a focus on quality, Canada West offers custom-made long-length engineered products featuring vertical grain Douglas Fir, Rift and Quarter Sawn White Oak, NA Walnut, and Maple, among other selected species.</p><p>Canada West Flooring Solutions Inc has established itself as a reliable supplier for both residential and commercial clients. The company provides professional sales and installation services, ensuring that every project meets high standards. As a member of the Better Business Bureau, Canada West prioritizes customer satisfaction and builds trust within the community. The business caters to wood flooring and industry professionals throughout British Columbia and the lower mainland, making it a go-to choice for quality flooring solutions.</p><p>With a commitment to excellence, Canada West Flooring Solutions Inc stands out in the local market. The combination of diverse product offerings and skilled installation services makes this company a leader in the flooring industry. Clients can expect a seamless experience from consultation to installation. For all wood flooring, vinyl, and laminate supply and installation needs, connect with Canada West Flooring Solutions Inc in Richmond, British Columbia.</p>',
  '11180 Voyageur Way #120',
  'Canada',
  'BC',
  'Richmond',
  'V6X 3N9',
  'gordon@weissenterprise.ca',
  'canada/richmond/home-services/canada-west-flooring-solutions-inc',
  'ChIJCRCN9gR1hlQRs4lVA52ZNNo',
  49.191027,
  -123.100266,
  '16042140962',
  'https://www.kwikr.ca/pictures/profile/pimage-245.jpg',
  'Flooring=>Hardwood Flooring',
  'Pay-as-you-go',
  261,
  'http://www.canadawestwood.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Supreme Flooring',
  '<p>Supreme Flooring delivers exceptional wood floor installation services to the Oakville, Burlington, Milton, and Mississauga areas. With over 15 years of experience, this family-owned business specializes in high-quality hardwood flooring and custom stair renovations. Supreme Flooring is committed to transforming spaces through expert craftsmanship and attention to detail.</p><p>The team at Supreme Flooring consists of skilled professionals who excel in hardwood, engineered, and laminate flooring installations. Their expertise extends to stairs renovation and custom wood railings, ensuring that every project meets the highest standards. Serving Oakville and surrounding regions, Supreme Flooring has built a reputation for reliability and quality workmanship.</p><p>Clients appreciate the personalized approach and dedication to customer satisfaction. The company’s extensive experience in the flooring industry enables them to provide tailored solutions to meet individual needs. Supreme Flooring emphasizes quality materials and innovative design, making every installation a lasting investment.</p><p>For over a decade, Supreme Flooring has contributed to the beauty and functionality of homes throughout Oakville and beyond. Their commitment to excellence and customer service has earned them a loyal client base. Supreme Flooring is the go-to choice for anyone seeking reliable wood floor installation and renovation services. Connect with Supreme Flooring today to explore flooring solutions in Oakville, Ontario.</p>',
  '3063 George Savage Ave',
  'Canada',
  'ON',
  'Oakville',
  'L6M 4M2',
  'info@elite-systems.ca',
  'canada/oakville/home-services/supreme-flooring',
  'ChIJTRxyxJ5HK4gRz2MYKx_5c18',
  43.4713888,
  -79.7415826,
  '16478931771',
  'https://www.kwikr.ca/pictures/profile/pimage-244.jpg',
  'Flooring=>Hardwood Flooring',
  'Pay-as-you-go',
  260,
  'https://supremeflooring.ca/oakville/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'TipTop Flooring Inc.',
  '<p>TipTop Flooring Inc. offers exceptional wood floor installation services in Toronto, Ontario. This local business specializes in a range of flooring solutions, including hardwood flooring installation, laminate and luxury vinyl installation, hardwood floor sanding and refinishing, and stairs installation and refinishing. With a commitment to quality and customer satisfaction, TipTop Flooring has built a reputation for delivering superior results using the finest materials.</p><p>The skilled team at TipTop Flooring works closely with clients to understand their vision and ensure that every project meets high standards. Competitive pricing makes these services accessible to a wide range of customers in the Greater Toronto Area. The focus on quality workmanship sets TipTop Flooring apart in the flooring industry. Each installation and refinishing project reflects the dedication to excellence that clients expect.</p><p>TipTop Flooring has established itself as a reliable choice for homeowners seeking to enhance their living spaces. The combination of expertise and customer-oriented service creates a positive experience for all clients. The company’s emphasis on using top-quality materials guarantees durability and aesthetic appeal in all flooring projects.</p><p>Explore the comprehensive flooring services offered by TipTop Flooring Inc., where customer satisfaction and quality craftsmanship are priorities. Connect with TipTop Flooring today for a free consultation and discover how to achieve the perfect floor in Toronto, Ontario.</p>',
  '17 Lascelles Blvd',
  'Canada',
  'ON',
  'Toronto',
  'M4V 2B6',
  'dparadis@mbisystemes.com',
  'canada/toronto/home-services/tiptop-flooring-inc',
  'ChIJXVK4y9YuK4gROSYNQxMUBR0',
  43.6949664,
  -79.3989879,
  '16473170707',
  'https://www.kwikr.ca/pictures/profile/pimage-243.jpg',
  'Flooring=>Hardwood Flooring',
  'Pay-as-you-go',
  259,
  'http://www.tiptopflooring.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Walnut Grove Hardwood Floors',
  '<p>Walnut Grove Hardwood Floors offers expert wood floor installation services in Edmonton, Alberta. With over 20 years of experience and a commitment to quality, this company excels in dust-free sanding and finishing using environmentally friendly products. The team specializes in revitalizing existing hardwood floors and installing new ones, ensuring a sustainable approach to flooring solutions.</p> <p>Providing services for more than two decades, Walnut Grove Hardwood Floors demonstrates extensive knowledge in the hardwood flooring industry. The company is trained and certified by the National Wood Flooring Association (NWFA) and boasts Bona Certified Craftsman credentials. This expertise guarantees high-quality workmanship and adherence to industry standards. Additionally, Walnut Grove Hardwood Floors employs a certified wood flooring inspector to ensure every project meets stringent quality requirements.</p> <p>Customers benefit from a range of services, including sanding existing floors to extend their lifespan and reduce waste. The installation of new hardwood flooring is also available, with a focus on quality materials and finishes. Walnut Grove Hardwood Floors prioritizes customer satisfaction and environmental responsibility, making it a reliable choice for flooring needs in Edmonton.</p> <p>With a strong focus on sustainable practices and industry expertise, Walnut Grove Hardwood Floors provides exceptional wood floor installation services. Trust in their experience and commitment to quality. Contact Walnut Grove Hardwood Floors at 4 Greenoch Crescent NW, Edmonton, Alberta, T6L 1B4 for all hardwood flooring needs.</p>',
  '4 Greenoch Crescent NW',
  'Canada',
  'AB',
  'Edmonton',
  'T6L 1B4',
  'info@can-nor.ca',
  'canada/edmonton/home-services/walnut-grove-hardwood-floors',
  'ChIJZwmvaXmYY0ER2TskIqfrPvY',
  53.4763046,
  -113.4190019,
  '17807007204',
  'https://www.kwikr.ca/pictures/profile/pimage-242.jpg',
  'Flooring=>Hardwood Flooring',
  'Pay-as-you-go',
  258,
  'https://walnutgrovehardwoodfloors.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Mare''s Hardwood Flooring',
  '<p>Mare''s Hardwood Flooring offers expert wood floor installation services in Calgary, Alberta. Established in 2000 by Vadym Yermolenko, this family-owned business has built a strong reputation in the local community. Mare''s Custom Flooring specializes in residential hardwood flooring, ensuring quality workmanship and professional service in every project.</p><p>The company has cultivated solid relationships with renowned renovation and custom home building companies in Calgary. This collaboration enhances the overall service experience for customers. Mare''s Hardwood Flooring prioritizes customer satisfaction, focusing on delivering products that clients can take pride in. The commitment to quality sets Mare''s apart in the competitive flooring market.</p><p.Mare''s Hardwood Flooring employs skilled professionals who understand the nuances of wood floor installation. Each project receives meticulous attention to detail, ensuring that the final result meets the highest standards. The company''s approach combines expertise with a customer-centric focus, making the flooring process seamless and enjoyable.</p><p.With a solid foundation built on trust and quality, Mare''s Hardwood Flooring continues to serve the Calgary area with integrity. The dedication to providing top-notch services and maintaining strong industry partnerships reflects the core values of the business. Explore the range of hardwood flooring options available. Contact Mare''s Hardwood Flooring at 242 St Moritz Dr SW, Calgary, Alberta, for exceptional wood floor installation services.</p>',
  '242 St Moritz Dr SW',
  'Canada',
  'AB',
  'Calgary',
  'T3H 5Y2',
  'services@ips.us',
  'canada/calgary/home-services/mare-s-hardwood-flooring',
  'ChIJ8dY0jMFtcVMRSKoNljCGdcY',
  51.0351152,
  -114.2130828,
  '14036606287',
  'https://www.kwikr.ca/pictures/profile/pimage-241.jpg',
  'Flooring=>Hardwood Flooring',
  'Pay-as-you-go',
  257,
  'http://www.maresflooring.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Team Hardwood Floor Ltd.',
  '<p>TEAM Hardwood Floor Ltd. provides exceptional wood floor installation services in North York, Ontario. This eco-sustainable company specializes in a diverse range of elegant and stylish hardwood flooring options. Noteworthy achievements include a strong reputation for high-quality flooring and stairs renovation products. The business serves customers in Toronto, Whitby, Markham, Mississauga, Ajax, and North York, ensuring a broad reach within the region.</p> <p>The commitment to quality is evident in every project undertaken. TEAM Hardwood Floor Ltd. offers hardwood rejuvenation and repairs, restoring the original beauty of floors through expert renovation and refinishing techniques. Customers can expect to enjoy the luxuries of superior quality hardwood flooring that enhances the aesthetic appeal of their homes. The company recognizes the importance of budget considerations and provides multiple packages tailored to meet varying financial needs.</p> <p>With a focus on delivering high-quality service and products, TEAM Hardwood Floor Ltd. stands as a reliable choice for hardwood flooring solutions. The dedication to eco-sustainability and customer satisfaction further solidifies its position in the market. Explore the range of services offered, from installation to refinishing, and experience the benefits of quality hardwood flooring. Connect with TEAM Hardwood Floor Ltd. at 22 Tavistock Rd, North York, Ontario, M3M 2N6 for exceptional flooring solutions.</p>',
  '22 Tavistock Rd',
  'Canada',
  'ON',
  'North York',
  'M3M 2N6',
  'admin@jtelectric.ca',
  'canada/north-york/home-services/team-hardwood-floor-ltd',
  'ChIJ__9jYKoxK4gRJeChQFNKUjA',
  43.7344019,
  -79.4848488,
  '14168798266',
  'https://www.kwikr.ca/pictures/profile/pimage-240.jpg',
  'Flooring=>Hardwood Flooring',
  'Pay-as-you-go',
  256,
  'http://teamhardwoodfloors.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Meulage Pro Sol - Finition de béton Beauport',
  '<p>Meulage Pro Sol - Finition de béton Beauport provides exceptional floor sanding and polishing services in Québec City, Quebec. Located at 11 Bd Magella-Laforest, this local business specializes in diamond grinding, efficient removal of existing floor coverings, and precise demolition of kitchens and bathrooms. The team utilizes diamond-coated grinding tools to eliminate surface imperfections, ensuring a flat, uniform, and shiny finish.</p><p>The range of services offered includes the removal of various adhesives, cement residues, and paint remnants. Meulage Pro Sol excels in surface correction, leveling, and restoration of concrete surfaces, preparing them for epoxy applications. The business also demonstrates expertise in the careful demolition of walls, floors, ceilings, and existing cabinetry. Such comprehensive services cater to both residential and commercial clients, showcasing a commitment to quality and precision.</p><p>Meulage Pro Sol has built a reputation for reliability and professionalism in the local community. Their skilled team ensures that every project meets high standards of craftsmanship, addressing the specific needs of each client. The combination of advanced techniques and quality materials contributes to lasting results that enhance any space.</p><p>Meulage Pro Sol delivers a wide array of floor sanding and polishing services, emphasizing quality and precision in every project. Connect with Meulage Pro Sol in Québec City to explore their professional services and transform your space.</p>',
  '11 Bd Magella-Laforest',
  'Canada',
  'QC',
  'Québec City',
  'G1C 2B2',
  'miranda@ratech.ca',
  'canada/québec-city/home-services/meulage-pro-sol-finition-de-béton-beauport',
  'ChIJhQb1rarnIAERcILLyqFffZY',
  46.8808862,
  -71.1542785,
  '14184764504',
  'https://www.kwikr.ca/pictures/profile/pimage-239.jpg',
  'Flooring=>Floor Repairs',
  'Pay-as-you-go',
  255,
  'https://www.411habitation.com/fondations-beton-fissures/quebec/beauport-2/fondations-beton-fissures-beauport.htm',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Marble Top Shop - Service',
  '<p>Marble Top Shop offers exceptional floor sanding and polishing services in Richmond Hill, Ontario. This Canadian-owned and operated business specializes in restoring the beauty of marble and natural stone surfaces. With a strong commitment to quality and customer satisfaction, Marble Top Shop provides comprehensive restoration services that include resurfacing, refinishing, honing, polishing, cleaning, sealing, and repair. Their expertise extends to various stone types such as marble, limestone, travertine, and granite.</p><p>The team at Marble Top Shop understands the importance of maintaining the elegance of stone surfaces. They focus on reviving damaged or worn-out areas, ensuring that each restoration project results in a surface that looks better than new. Their dedication to educating clients on proper stone care and maintenance sets them apart in the industry. Fully licensed and insured, the business emphasizes quality workmanship and attention to detail in every project.</p><p>Clients appreciate the professional approach and the noticeable transformation of their stone surfaces. Marble Top Shop has built a reputation for reliability and excellence in Richmond Hill. Their services cater to both residential and commercial properties, making them a versatile choice for any stone restoration needs.</p><p>Marble Top Shop delivers high-quality restoration services with a focus on customer education and satisfaction. Their skilled team ensures that every project enhances the beauty of stone surfaces. Contact Marble Top Shop at 555 Edward Ave Unit 2005, Richmond Hill, Ontario, L4C 5K6 for expert services in stone restoration.</p>',
  '555 Edward Ave Unit 2005',
  'Canada',
  'ON',
  'Richmond Hill',
  'L4C 5K6',
  'careers@canal.ca',
  'canada/richmond-hill/home-services/marble-top-shop-service',
  'ChIJOxGAgcUrK4gR70LBvl_3BzA',
  43.8972469,
  -79.4277071,
  '14169511205',
  'https://www.kwikr.ca/pictures/profile/pimage-238.jpg',
  'Flooring=>Floor Repairs',
  'Pay-as-you-go',
  254,
  'http://marbletopshop.ca/service',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Sc flooring services',
  '<p>Sc Flooring Services offers exceptional floor sanding and polishing services in Guelph, Ontario. This local business specializes in enhancing the beauty and durability of hardwood floors, ensuring every home receives the finest craftsmanship. With a commitment to quality, Sc Flooring Services also provides comprehensive home renovation solutions, including staircase installation, framing, drywall work, painting, and concrete driveways.</p><p>The skilled team at Sc Flooring Services takes pride in their expertise across various trades. Each member brings a unique skill set, ensuring that every project is handled with precision and care. Whether tackling large renovations or smaller updates, the focus remains on delivering high-quality results that meet customer expectations. This dedication to excellence has earned the business a reputation for reliability and professionalism in the Guelph area.</p><p>Sc Flooring Services emphasizes customer satisfaction and quality workmanship. The company utilizes advanced techniques and high-grade materials, resulting in stunning finishes that enhance the overall aesthetic of any space. The commitment to continuous improvement and customer feedback drives the team to maintain high standards in every project.</p><p>Sc Flooring Services provides a range of services from floor sanding to complete home renovations. The team''s specialized skills ensure high-quality installations and a commitment to excellence. For top-notch flooring and renovation solutions in Guelph, connect with Sc Flooring Services at 356 Imperial Rd S.</p>',
  '356 Imperial Rd S',
  'Canada',
  'ON',
  'Guelph',
  'N1K 1L8',
  'info@smeincofseattle.com',
  'canada/guelph/home-services/sc-flooring-services',
  'ChIJm9OAIQuFK4gROexD4CuWJVk',
  43.5236922,
  -80.2761013,
  '12265010987',
  NULL,
  'Flooring=>Floor Repairs',
  'Pay-as-you-go',
  253,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'M C M Planchers INC.',
  '<p>M C M Planchers INC. offers expert floor sanding and polishing services in L''Assomption, Quebec. Established in 1985, this business specializes in sanding, staining, and finishing hardwood floors. MCM Planchers ensures that floors look their best, serving the greater Montreal area, including the North and South Shores.</p> <p>The team at M C M Planchers INC. brings decades of experience to every project. Knowledgeable staff utilize advanced techniques and equipment to deliver high-quality results. Attention to detail remains a priority, ensuring that each floor receives the care it deserves. The company takes pride in its reputation for reliability and professionalism, making it a trusted choice for homeowners and businesses alike.</p> <p.M C M Planchers INC. understands the value of maintaining beautiful hardwood floors. The services provided enhance the aesthetic appeal of any space, increasing property value. Clients appreciate the commitment to excellence and the ability to transform worn floors into stunning surfaces. The company’s dedication to customer satisfaction is evident in every project completed.</p> <p.M C M Planchers INC. stands ready to meet the needs of clients seeking floor sanding and polishing services. With years of experience and a focus on quality, this business continues to be a leader in the industry. Connect with M C M Planchers INC. at 585 Chem. du Golf, L''Assomption, Quebec, for professional floor care services.</p>',
  '585 Chem. du Golf',
  'Canada',
  'QC',
  'L''Assomption',
  'J5W 1K1',
  'matt@potterelectric.ca',
  'canada/l-assomption/home-services/m-c-m-planchers-inc',
  'ChIJQaDrZ0bpyEwRREsWnuvrbTk',
  45.8248753,
  -73.4321606,
  '15148652106',
  'https://www.kwikr.ca/pictures/profile/pimage-236.jpg',
  'Flooring=>Floor Repairs',
  'Pay-as-you-go',
  252,
  'http://www.mcmplanchers.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Meunier et fils sablage de plancher KJM inc.',
  '<p>Meunier et fils sablage de plancher KJM inc. offers expert floor sanding and polishing services in Granby, Quebec. This local business specializes in restoring and enhancing hardwood floors, ensuring a smooth and polished finish that revitalizes any space. With a commitment to quality and customer satisfaction, the company has built a strong reputation in the community.</p><p>The team at Meunier et fils sablage de plancher KJM inc. utilizes advanced techniques and high-quality materials to deliver exceptional results. Each project begins with a thorough assessment of the floor''s condition, allowing for tailored solutions that meet specific needs. The skilled professionals take pride in their craftsmanship, ensuring that every detail is attended to during the sanding and polishing process.</p><p.Customers appreciate the efficiency and reliability of the services provided. The company has successfully completed numerous projects, ranging from residential homes to commercial spaces, demonstrating versatility and expertise in various environments. Positive feedback from satisfied clients highlights the dedication to excellence that defines this business.</p><p.Meunier et fils sablage de plancher KJM inc. combines experience and professionalism to deliver outstanding floor restoration services. The focus on quality and customer care sets this business apart in Granby. Connect with Meunier et fils sablage de plancher KJM inc. for expert floor sanding and polishing services in Quebec. </p>',
  '322 Rue de Strasbourg',
  'Canada',
  'QC',
  'Granby',
  'J2H 0B6',
  'andy@veelectric.ca',
  'canada/granby/home-services/meunier-et-fils-sablage-de-plancher-kjm-inc',
  'ChIJKT2HzynPyUwRTOdg4sdumTw',
  45.3757738,
  -72.733664,
  '14507776744',
  NULL,
  'Flooring=>Floor Repairs',
  'Pay-as-you-go',
  251,
  'https://meunier-sablage.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Majestic Floors',
  '<p>Majestic Floors offers expert floor sanding and polishing services in Saint-Laurent, Quebec. This local business specializes in floor sanding, refinishing, installation, and repair, ensuring high-quality results for both residential and commercial properties. With a commitment to excellence, Majestic Floors has built a solid reputation in the community.</p><p>The team at Majestic Floors utilizes advanced techniques and equipment to enhance the appearance and durability of hardwood floors. This service not only restores the natural beauty of the wood but also extends its lifespan. Clients can expect meticulous attention to detail and a professional approach from start to finish. Each project reflects the company''s dedication to quality craftsmanship and customer satisfaction.</p><p>With years of experience, Majestic Floors has successfully completed numerous projects, earning trust among homeowners and business owners alike. The company prides itself on using eco-friendly products that are safe for families and pets. This commitment to sustainability sets Majestic Floors apart in the competitive flooring industry.</p><p>Majestic Floors delivers reliable floor sanding and polishing services, ensuring beautiful and long-lasting results. The company''s strengths lie in its skilled team, customer-focused approach, and dedication to quality. For exceptional flooring solutions in Saint-Laurent, reach out to Majestic Floors at 3385 Av. Ernest - Hemingway.</p>',
  '3385 Av. Ernest - Hemingway',
  'Canada',
  'QC',
  'Saint-Laurent',
  'H4R 3L1',
  'welcome@ptxelectric.com',
  'canada/saint-laurent/home-services/majestic-floors',
  'ChIJ97w_vq4iyUwRtQs8DZ5Vq7Q',
  45.50508,
  -73.71998,
  '15146612598',
  'https://www.kwikr.ca/pictures/profile/pimage-234.jpg',
  'Flooring=>Floor Repairs',
  'Pay-as-you-go',
  250,
  'https://www.montrealfloorsanding.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Mr.hardwood',
  '<p>Mr.hardwood offers expert floor sanding and polishing services in Cantley, Quebec. With a third generation of experience, this local business excels in sanding both old and new floors. Mr.hardwood specializes in installations and repairs, ensuring each project meets high standards of quality and craftsmanship. The team is dedicated to transforming spaces with their skills in wood floor sanding, finishing, and installation.</p><p>Clients benefit from a comprehensive range of services, including sablage (sanding), vernissage (finishing), and the installation of hardwood floors. Each project showcases the expertise and attention to detail that Mr.hardwood has cultivated over the years. The business prides itself on providing reliable and efficient service, making it a trusted choice for homeowners and businesses alike in the region.</p><p>Mr.hardwood has built a strong reputation for delivering exceptional results. The combination of advanced techniques and traditional craftsmanship ensures that every floor reflects the beauty and durability of quality wood. Customer satisfaction remains a top priority, and the team works diligently to meet the specific needs of each client.</p><p>With a focus on quality service and a commitment to excellence, Mr.hardwood provides outstanding floor sanding and polishing solutions. This business continues to serve the Cantley community with pride. Connect with Mr.hardwood at 16 RUE GODMAIRE, Cantley, Quebec, J8V 3H9 for professional flooring services.</p>',
  '16 RUE GODMAIRE godmaire',
  'Canada',
  'QC',
  'Cantley',
  'J8V 3H9',
  'office@renewablenorth.com',
  'canada/cantley/home-services/mr-hardwood',
  'ChIJRUaB8lsdzkwR8PXs0RbDWO8',
  45.5432901,
  -75.7730038,
  '18196631110',
  'https://www.kwikr.ca/pictures/profile/pimage-233.jpg',
  'Flooring=>Floor Repairs',
  'Pay-as-you-go',
  249,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
);
