INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Nettoyage à Pression d''Eau Pier-Eau Lavage au Jet d''eau',
  '<p>Nettoyage à Pression d''Eau Pier-Eau Lavage au Jet d''eau offers top-tier pressure washing services in Jonquière, Quebec. This local business specializes in cleaning residential and commercial properties, ensuring surfaces are free from dirt, grime, and mold. Equipped with advanced pressure washing technology, the team delivers efficient and effective results.</p> <p>This pressure washing service focuses on customer satisfaction and environmental responsibility. The technicians are trained to handle various surfaces, including driveways, decks, and siding. Clients appreciate the attention to detail and the commitment to restoring the appearance of their properties. The business has built a solid reputation in the community for reliability and quality work.</p><p>Nettoyage à Pression d''Eau Pier-Eau Lavage au Jet d''eau takes pride in using eco-friendly cleaning solutions, making it a responsible choice for homeowners and businesses. The team understands the importance of maintaining property value and enhancing curb appeal. Their services not only improve aesthetics but also extend the lifespan of surfaces.</p><p>This local pressure washing service stands out for its professionalism and dedication. With a focus on delivering high-quality results, Nettoyage à Pression d''Eau Pier-Eau Lavage au Jet d''eau continues to serve Jonquière with pride. Contact this reliable pressure washing service at 1732 Rue Maxwell, Jonquière, Quebec, G7S 3J6 for exceptional cleaning solutions.</p>',
  '1732 Rue Maxwell',
  'Canada',
  'QC',
  'Jonquière',
  'G7S 3J6',
  'info@paritek.ca',
  'canada/jonquière/home-services/nettoyage-à-pression-d-eau-pier-eau-lavage-au-jet-d-eau',
  'ChIJJVVubcIpwEwRI0ntzzg5VvI',
  48.4353293,
  -71.180859,
  '14185400938',
  'https://www.kwikr.ca/pictures/profile/pimage-107.jpg',
  'Cleaning Services=>Pressure Washing',
  'Pay-as-you-go',
  123,
  'https://www.anugo.ca/fr/entreprise/288414-nettoyage-a-pression-d-eau-pierre-eau-nettoyage-vapeur,-chimique-et-sous-pression-jonquiere.html',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Anchor Wash Inc.',
  '<p>Anchor Wash Inc. provides top-notch pressure washing services in Halifax, Nova Scotia, and the surrounding areas. With six years of experience, this professional mobile wash company excels in delivering reliable and trustworthy cleaning solutions. The introduction of Drone Pressure Washing technology allows for efficient cleaning of 10 to 12-story buildings without the need for traditional equipment like swing stages or lifts.</p> <p>Anchor Wash offers comprehensive services including parking lot and parkade cleaning. The company is fully insured and provides water on-site while utilizing eco-friendly soaps for all cleaning tasks. Their mobile, industrial-grade equipment features boilers that heat water for deep cleaning, ensuring a thorough job every time. Client satisfaction remains a priority, with competitive pricing and a commitment to efficiency and safety.</p> <p>Clients benefit from the expertise and dedication of Anchor Wash, which emphasizes quality workmanship and great value. The company’s innovative approach to pressure washing, particularly with drone technology, enhances safety and speed while maintaining high cleaning standards. With a strong focus on customer service, Anchor Wash aims to exceed expectations in every project.</p> <p>Anchor Wash Inc. stands ready to transform homes and equipment with their exceptional pressure washing services. Engage with this local business in Halifax to experience their reliable and effective cleaning solutions.</p>',
  '43 Eastview Dr',
  'Canada',
  'NS',
  'Halifax',
  'B3P 2B5',
  'online.store@krm.ca',
  'canada/halifax/home-services/anchor-wash-inc',
  'ChIJ3yMXAPQhWksR7qaw4X1uvIQ',
  44.6294743,
  -63.6142753,
  '19028805484',
  'https://www.kwikr.ca/pictures/profile/pimage-106.jpg',
  'Cleaning Services=>Pressure Washing',
  'Pay-as-you-go',
  122,
  'http://anchorwash.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Aurora Roofing Lm',
  '<p>Aurora Roofing LM, located at 19427 92 Ave in Surrey, British Columbia, specializes in both commercial and residential roofing services. This local roofing contractor is known for its high-quality installation crews and commitment to customer satisfaction. The company aims to provide durable roofing solutions that stand the test of time, ensuring that every client receives a roof that lasts a lifetime.</p> <p>The expertise of Aurora Roofing LM extends across various roofing types, catering to the diverse needs of the Surrey community. The company prides itself on using top-grade materials and employing skilled installers who adhere to industry standards. This dedication to quality is evident in the positive feedback received from satisfied customers who appreciate the professionalism and reliability of the service.</p> <p>Aurora Roofing LM also emphasizes the importance of maintaining a safe and efficient work environment. The team is trained in the latest safety protocols, ensuring that every project is completed without incident. This focus on safety not only protects the workers but also provides peace of mind to homeowners and business owners alike.</p> <p>This roofing contractor has built a reputation for excellence within the local community. Aurora Roofing LM continues to serve Surrey and surrounding areas with dedication and integrity. For more information about their services and to discuss specific roofing needs, contacting the business directly is recommended.</p>',
  '19427 92 Ave',
  'Canada',
  'BC',
  'Surrey',
  'V4N 4G6',
  'officemanager@parastone.ca',
  'canada/surrey/home-services/aurora-roofing-lm',
  'ChIJyyAXrGnRhVQR_kPAFDy83-4',
  49.1707182,
  -122.684721,
  '16042593922',
  'https://www.kwikr.ca/pictures/profile/pimage-100.jpg',
  'Roofing=>Roof Installation',
  'Pay-as-you-go',
  120,
  'https://www.auroraroofinglm.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Mustang Roofing & Exteriors',
  '<p>Mustang Roofing & Exteriors operates as a roofing contractor, providing essential services to the London area in Ontario, Canada. Established in 1991, the company specializes in roofing, as well as window and door installations, catering to both residential and commercial clients. The business is known for its commitment to quality and customer satisfaction.</p> <p>Located at 2310 Hyde Park Rd, Mustang Roofing & Exteriors has built a reputation for reliability and expertise in the roofing industry. The company’s extensive experience since its inception allows it to address diverse roofing needs, ensuring that each project meets the highest standards. The skilled team is equipped to handle various roofing materials, including shingles, metal, and flat roofing systems.</p> <p>In addition to roofing services, Mustang Roofing & Exteriors also offers window and door solutions, enhancing the aesthetic and energy efficiency of homes and businesses. The focus on using high-quality products and materials sets the business apart in the competitive market. Mustang Roofing & Exteriors emphasizes the importance of customer relationships, aiming to provide personalized service tailored to individual project requirements.</p> <p>A notable achievement includes numerous positive reviews from satisfied customers, reflecting the company’s dedication to excellence. For those seeking reliable roofing and exterior services, contacting Mustang Roofing & Exteriors may provide valuable insights and assistance with any upcoming projects.</p>',
  '2310 Hyde Park Rd',
  'Canada',
  'ON',
  'London',
  'N6H 5K2',
  'vitankservices@shaw.ca',
  'canada/london/home-services/mustang-roofing-exteriors',
  'ChIJS3jEm1jlLogRUddrhSNzztc',
  43.0165744,
  -81.3427141,
  '15194713969',
  'https://www.kwikr.ca/pictures/profile/pimage-101.jpg',
  'Roofing=>Roof Installation',
  'Pay-as-you-go',
  119,
  'http://www.mustangexteriors.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Toitures Premium',
  '<p>Toitures Premium operates as a roofing contractor located at 253 Rue de la Clairière in Rosemère, Quebec. This business specializes in a range of services including roofing, insulation, ventilation, cladding, gutter installation, and snow removal. Toitures Premium serves the local community with a focus on quality and reliability, ensuring that residential and commercial properties are well-protected against the elements.</p> <p>Established with a commitment to excellence, Toitures Premium has garnered a reputation for delivering comprehensive roofing solutions. The company emphasizes the importance of proper insulation and ventilation, which are crucial for maintaining energy efficiency in homes. With a skilled team, the business offers tailored services that address individual client needs. Gutter systems are designed to effectively manage water runoff, while snow removal services ensure safety during winter months.</p> <p>The dedication to customer satisfaction sets Toitures Premium apart in the competitive roofing industry. The local area benefits from the expertise and experience of the team, which is well-versed in the specific challenges posed by the Quebec climate. This knowledge allows the business to provide effective solutions that enhance the durability and longevity of roofs.</p> <p>Recognition in the community reflects the company''s professionalism and quality of work. Engaging with Toitures Premium for roofing needs can lead to informed decisions and reliable results. For more information, contacting the business is recommended.</p>',
  '253 Rue de la Clairière',
  'Canada',
  'QC',
  'Rosemère',
  'J7A 4A5',
  'info@greencleantoronto.com',
  'canada/rosemère/home-services/toitures-premium',
  'ChIJSwcxDTgnyUwRr0NIvylsX6c',
  45.6232537,
  -73.8075989,
  '14504337649',
  'https://www.kwikr.ca/pictures/profile/pimage-102.jpg',
  'Roofing=>Roof Installation',
  'Pay-as-you-go',
  118,
  'http://toiturespremium.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'SMC Group Commercial Roofing Services',
  '<p>SMC Group Commercial Roofing Services operates as a leading roofing contractor in Richmond Hill, Ontario, specializing in comprehensive commercial roofing solutions. The company focuses on the planning, execution, and maintenance of various roofing projects. Services offered include modified bitumen roofing, built-up roofing, TPO roofing, and single-ply roofing, ensuring a wide range of options for clients.</p> <p>Located at 9225 Leslie St #201, SMC Group serves the greater Toronto area, emphasizing the importance of quality materials and proactive maintenance. The business aims to extend the service life of roofs through fast service and stringent safety measures. Clients benefit from the company''s commitment to preventative maintenance, which helps mitigate potential issues before they escalate. This approach not only enhances roof longevity but also contributes to overall building safety.</p> <p>SMC Group''s reputation in the industry is built on reliability and expertise. The team is dedicated to ensuring that every project meets high standards, reflecting their commitment to quality and customer satisfaction. Their proactive maintenance strategies stand out as a key differentiator in the competitive roofing market.</p> <p>The company has garnered positive feedback for its efficient service and knowledgeable staff. Engaging with SMC Group for roofing needs is a decision that aligns with quality and safety. For further information about their services, contacting the business directly is recommended.</p>',
  '9225 Leslie St #201',
  'Canada',
  'ON',
  'Richmond Hill',
  'L4B 3H6',
  'info@pro-clean.ca',
  'canada/richmond-hill/home-services/smc-group-commercial-roofing-services',
  'ChIJ76QgHywrK4gRY71x58-kQWQ',
  43.8614907,
  -79.3858871,
  '19052183507',
  'https://www.kwikr.ca/pictures/profile/pimage-103.jpg',
  'Roofing=>Roof Installation',
  'Pay-as-you-go',
  117,
  'https://www.smcgroup.io/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Metal Roof Canada',
  '<p>Metal Roof Canada, located at 2349 Guenette St in Saint-Laurent, Quebec, specializes in manufacturing, sales, and installation of high-quality metal roofing products. This roofing contractor serves both residential and commercial clients, providing essential protection against the harsh Canadian weather that is prevalent in the region. The focus on durability and quality sets Metal Roof Canada apart in the competitive roofing market.</p> <p>The company is known for its extensive range of metal roofing solutions, designed to withstand extreme weather conditions while ensuring aesthetic appeal. Metal roofs are increasingly favored for their longevity, energy efficiency, and low maintenance requirements. Metal Roof Canada emphasizes the importance of using premium materials, which contribute to the sustainability and resilience of their products.</p> <p>Clients appreciate the comprehensive services offered, from initial consultation through to installation. The knowledgeable team at Metal Roof Canada guides customers through the selection process, ensuring that each roofing solution meets specific needs and preferences. The commitment to customer satisfaction is evident in every project undertaken.</p> <p>Recognized for its quality workmanship and reliability, Metal Roof Canada continues to build a strong reputation in the roofing industry. The business encourages potential clients to reach out for more information regarding their services and solutions tailored to individual requirements.</p>',
  '2349 Guenette St',
  'Canada',
  'QC',
  'Saint-Laurent',
  'H4R 2E9',
  'operations@cleanforgood.ca',
  'canada/saint-laurent/home-services/metal-roof-canada',
  'ChIJ2VRnFAg8yUwR9ymFL0R1dk0',
  45.4998121,
  -73.7268366,
  '15145073332',
  'https://www.kwikr.ca/pictures/profile/pimage-104.jpg',
  'Roofing=>Roof Installation',
  'Pay-as-you-go',
  116,
  'https://metalroofcanada.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Gable Roofing',
  '<p>Gable Roofing, located at 11 Thorncliffe Park Dr unit 1005 in Ontario, Canada, specializes in providing comprehensive roofing solutions. This roofing contractor has established a strong reputation within the community, offering services that ensure homes remain safe and well-maintained throughout the year. With decades of experience, Gable Roofing stands out as a reliable choice for homeowners seeking quality workmanship and dependable service.</p> <p>The company recently transitioned ownership from the previous owners, Jackie and Mike, who retired after years of dedicated service. This change has not affected the commitment to excellence that Gable Roofing embodies. As a family and friend-owned business, it emphasizes a personal touch, ensuring that each project is treated with care and attention to detail. The team understands the importance of maintaining a distraction-free living environment, regardless of the weather conditions.</p> <p>Gable Roofing operates year-round, distinguishing itself from seasonal competitors. This availability allows homeowners to address roofing needs promptly, preventing potential issues from escalating. The focus on customer satisfaction and quality service has solidified Gable Roofing''s position as a trusted roofing contractor in the region.</p> <p>With a legacy of reliability and a commitment to quality, Gable Roofing continues to serve the community effectively. Contacting the business for more information about its services and offerings is encouraged for those in need of roofing solutions.</p>',
  '11 Thorncliffe Park Dr unit 1005',
  'Canada',
  'ON',
  'Toronto',
  'M4H 1P3',
  'jeff.butler@renuesystems.com',
  'canada/home-services/gable-roofing',
  'ChIJTVGq45vO1IkRr2mF8sI6u4s',
  43.7040036,
  -79.349051,
  '14166966880',
  'https://www.kwikr.ca/pictures/profile/pimage-105.jpg',
  'Roofing=>Roof Installation',
  'Pay-as-you-go',
  115,
  'http://www.gableroofing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'FORÈ | GARDEN DESIGN',
  '<p>Forè | Garden Design, located at 327 Bering Ave in Toronto, Ontario, specializes in landscaping services that enhance property value. Established in 2018, this business provides tailored solutions for both residential gardens and commercial spaces. The team focuses on custom designs, selecting plants that thrive in specific environments, and offering comprehensive maintenance services.</p> <p>Forè stands out in the competitive landscaping market due to its commitment to nurturing and caring for clients'' investments. The company understands that a well-designed garden can significantly impact property aesthetics and value. By employing knowledgeable staff, Forè ensures that every project receives the attention it deserves, from initial design to ongoing care. The business has developed a reputation for reliability and quality, making it a preferred choice among local residents and businesses.</p><p>With a focus on sustainability, Forè also emphasizes the importance of selecting plants that are not only beautiful but also suited to the local climate. This approach helps clients maintain lush gardens with minimal environmental impact. The company''s expertise in landscaping has garnered positive feedback from the community, reinforcing its status as a leader in the industry.</p><p>Recognition for exceptional service has been a hallmark of Forè''s journey. Engaging with the team can provide further insights into their landscaping services and how they can transform outdoor spaces effectively.</p>',
  '327 Bering Ave',
  'Canada',
  'ON',
  'Toronto',
  'M8Z 3A5',
  'privacyofficer@servicemasterclean.ca',
  'canada/toronto/home-services/forè-garden-design',
  'ChIJD8-4u7k3K4gRt_d-rqpwsVI',
  43.6374495,
  -79.528473,
  '16479093218',
  NULL,
  'Landscaping=>Seasonal Cleanup',
  'Pay-as-you-go',
  114,
  'https://www.fore.garden/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Epstein Property Care Inc',
  '<p>Epstein Property Care Inc specializes in landscaping, lawn care, and snow removal services in Toronto, Ontario. This business offers a comprehensive range of services, including landscape design and landscape architecture. The team at Epstein Property Care Inc possesses extensive expertise, ensuring each project meets high standards of quality and creativity.</p> <p>Located at 126 Simcoe St, Epstein Property Care Inc has established itself as a trusted provider of landscaping solutions within the local community. The company caters to diverse customer needs, from creating lush garden retreats to maintaining pristine outdoor spaces during winter. The focus on meticulous design and execution sets this business apart in the competitive landscaping market.</p> <p>Epstein Property Care Inc employs skilled professionals who are dedicated to transforming outdoor spaces. The commitment to quality and customer satisfaction is evident in every project undertaken. The company’s approach combines aesthetic appeal with functionality, ensuring that each landscape design not only looks good but also serves the intended purpose effectively.</p> <p>This landscaping company has garnered a positive reputation within Toronto for its reliable services and exceptional results. A strong emphasis on customer service and attention to detail has contributed to its success. For those seeking expert landscaping solutions, contacting Epstein Property Care Inc can provide additional insights into their offerings and expertise.</p>',
  '126 Simcoe St',
  'Canada',
  'ON',
  'Toronto',
  'M5H 4E6',
  'admin@cleanlux.cam',
  'canada/toronto/home-services/epstein-property-care-inc',
  'ChIJJ6L1URk1K4gR1CPUMOktdO0',
  43.6489727,
  -79.3872946,
  '16478684890',
  'https://www.kwikr.ca/pictures/profile/pimage-91.jpg',
  'Landscaping=>Seasonal Cleanup',
  'Pay-as-you-go',
  113,
  'https://epsteinpropertycare.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Mr Landscape',
  '<p>Mr Landscape, located at 299 Kingswood Rd in Toronto, Ontario, specializes in landscape maintenance and planting services. With nearly 40 years of experience, the business has established a strong reputation in Toronto''s premier neighborhoods. The team, led by David Reeder, focuses on delivering exceptional quality and value to clients, which is reflected in the high rate of repeat business.</p><p>The services offered by Mr Landscape include comprehensive landscape maintenance, which ensures that gardens remain healthy and vibrant throughout the seasons. Additionally, the business provides expert planting services, helping to enhance the aesthetic appeal of residential properties. David Reeder''s hands-on approach fosters a personal connection with clients, allowing for tailored solutions that meet individual landscape needs.</p><p>Mr Landscape stands out due to its commitment to quality and customer satisfaction. The team of skilled gardeners is dedicated to maintaining the beauty of each client''s outdoor space, ensuring that the landscapes thrive. This dedication has led to a loyal customer base that values the expertise and reliability of the services provided.</p><p>The business has continually received positive feedback from clients, showcasing its ability to deliver results that exceed expectations. Contacting Mr Landscape for more information about their services and how they can enhance outdoor spaces is encouraged for those seeking reliable landscaping solutions in Toronto.</p>',
  '299 Kingswood Rd',
  'Canada',
  'ON',
  'Toronto',
  'M4E 3N8',
  'info@topmaxcleaning.com',
  'canada/toronto/home-services/mr-landscape',
  'ChIJd2azfPfP1IkRMKKBqgvRPFU',
  43.6812427,
  -79.2860957,
  '14165901067',
  NULL,
  'Landscaping=>Seasonal Cleanup',
  'Pay-as-you-go',
  112,
  'http://mrlandscape.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Wildrose Gardening',
  '<p>Wildrose Gardening operates as a prominent landscaper in Toronto, Ontario, specializing in a range of gardening and landscaping services. This local business offers design, installation, and maintenance for residential and commercial properties. Clients benefit from a focus on sustainable practices and native plant selections, which enhance the local ecosystem. Wildrose Gardening has established a reputation for its expertise in transforming outdoor spaces into vibrant, functional areas.</p><p>Located at 143 York Mills Rd, Wildrose Gardening serves the Greater Toronto Area with a commitment to quality and customer satisfaction. The team comprises experienced professionals who understand the unique climate and soil conditions of Ontario, allowing them to create tailored solutions for each client. Services include garden design, lawn care, and seasonal clean-ups, making it a versatile choice for various landscaping needs.</p><p>The company emphasizes environmentally friendly practices, utilizing organic fertilizers and water-efficient irrigation systems. This approach not only promotes healthy plant growth but also conserves water resources, aligning with modern sustainability goals. Wildrose Gardening''s dedication to quality has garnered positive feedback from clients, contributing to its growing reputation in the landscaping industry.</p><p>Recognition within the community for outstanding service reflects the business''s commitment to excellence. Engaging with Wildrose Gardening can provide further insights into their services and expertise in enhancing outdoor spaces.</p>',
  '143 York Mills Rd',
  'Canada',
  'ON',
  'Toronto',
  'M2L 1K4',
  'office@pbs-corp.ca',
  'canada/toronto/home-services/wildrose-gardening',
  'ChIJ345fCXstK4gRslaf8jBzvy4',
  43.7456987,
  -79.3944643,
  '14167925509',
  NULL,
  'Landscaping=>Seasonal Cleanup',
  'Pay-as-you-go',
  111,
  'https://wildrosegardening.com/?utm_source=GMB&utm_medium=organic',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Ecoman',
  '<p>Ecoman, located at 327 Bering Ave in Toronto, Ontario, specializes in landscaping and gardening services tailored for both private and public spaces. This business focuses on designing, developing, and maintaining green spaces that harmonize with the environment, showcasing a commitment to sustainability. Ecoman''s approach combines natural elements with human creativity, ensuring that each project yields lasting benefits.</p> <p>The unique philosophy of Ecoman emphasizes the importance of balancing ecological practices with aesthetic appeal. The team possesses expertise in creating landscapes that not only enhance the visual appeal of an area but also contribute to environmental health. This dual focus allows Ecoman to cater to a diverse clientele, from homeowners seeking personalized gardens to municipalities aiming to beautify public parks.</p> <p>In Toronto, Ecoman has established a reputation for quality and reliability. The company''s dedication to customer satisfaction is evident in its meticulous attention to detail and innovative design solutions. Ecoman''s services encompass a wide range of landscaping needs, making it a versatile choice for any landscaping project.</p> <p>The commitment to sustainable practices and community enhancement has earned Ecoman recognition in the local industry. Engaging with this business can lead to transformative results for any green space, making it a valuable resource for those interested in landscaping services.</p>',
  '327 Bering Ave',
  'Canada',
  'ON',
  'Toronto',
  'M6P 2E6',
  'info@starteamcleaning.com',
  'canada/toronto/home-services/ecoman',
  'ChIJ-fvpSmc0K4gRsNgqeXVtAW4',
  43.6374495,
  -79.528473,
  '14165355565',
  'https://www.kwikr.ca/pictures/profile/pimage-94.jpg',
  'Landscaping=>Seasonal Cleanup',
  'Pay-as-you-go',
  110,
  'http://ecoman.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Tranquility Garden Design',
  '<p>Tranquility Garden Design, located at 730 Dovercourt Rd Suite 1703 in Toronto, Ontario, specializes in bespoke landscaping solutions tailored for downtown properties. This local business focuses on designing, building, and maintaining gardens throughout the Greater Toronto Area (GTA). Services include the creation of perennial gardens, pollinator gardens, shade gardens, and seasonal urns, alongside low-cost landscaping options.</p> <p>The team at Tranquility Garden Design comprises skilled professionals with extensive knowledge in garden design, native plants, soil health, irrigation, and organic pest control. This expertise allows for the development of gardens that are not only aesthetically pleasing but also environmentally friendly. The use of battery-powered equipment aligns with their commitment to sustainable practices, ensuring minimal impact on the earth while fostering habitats that benefit both wildlife and humans.</p> <p>Tranquility Garden Design emphasizes organic gardening principles, which contribute to healthier ecosystems. Their focus on creating welcoming spaces encourages community interaction with nature. The dedication to their craft and the local environment positions this business as a valuable asset within Toronto’s landscaping sector.</p> <p>A commitment to sustainable practices and community engagement has established a positive reputation for Tranquility Garden Design. For those seeking more information about their services, contacting the business is recommended to explore how they can enhance outdoor spaces. </p>',
  '730 Dovercourt Rd Suite 1703',
  'Canada',
  'ON',
  'Toronto',
  'M6H 2W9',
  'office@bubblesandsqueak.com',
  'canada/toronto/home-services/tranquility-garden-design',
  'ChIJN244J0NNOIoRVe5PK-3cBqU',
  43.6596788,
  -79.4292916,
  '16479149228',
  'https://www.kwikr.ca/pictures/profile/pimage-95.jpg',
  'Landscaping=>Seasonal Cleanup',
  'Pay-as-you-go',
  109,
  'https://www.tranquilitygardendesign.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'MBL Landscaping',
  '<p>MBL Landscaping, located at 864 Tapscott Rd in Toronto, Ontario, specializes in transforming residential landscapes. This local business offers a variety of services, including landscape design, hardscaping, softscaping, and carpentry. MBL Landscaping stands out due to its commitment to client satisfaction and its ability to deliver projects on time and within budget. The company prides itself on assembling a reliable network of professionals, ensuring high standards of quality and workmanship in every project.</p> <p>Since its inception, MBL Landscaping has focused on understanding and meeting client expectations. The emphasis on providing complete one-stop services allows customers to re-imagine their outdoor spaces without the hassle of coordinating multiple contractors. The team’s dedication to exceptional results has established MBL Landscaping as a trusted name in the Toronto area. Clients can expect a seamless experience from initial consultation to project completion, minimizing surprises and maximizing satisfaction.</p> <p>Recognized for its reliable service and quality craftsmanship, MBL Landscaping continues to enhance the beauty and functionality of residential properties. The company’s approach to landscaping not only elevates outdoor aesthetics but also adds value to homes. For those seeking to explore landscaping options, contacting MBL Landscaping can provide valuable insights into potential projects and services available in the Toronto area.</p>',
  '864 Tapscott Rd',
  'Canada',
  'ON',
  'Toronto',
  'M1X 1C3',
  'judy@homehelpers.com',
  'canada/toronto/home-services/mbl-landscaping',
  'ChIJUXyLpynX1IkRNO9C73SMboM',
  43.8223967,
  -79.2423269,
  '14164184389',
  'https://www.kwikr.ca/pictures/profile/pimage-96.jpg',
  'Landscaping=>Seasonal Cleanup',
  'Pay-as-you-go',
  108,
  'http://mbllandscaping.com/?utm_source=GMB&utm_medium=google&utm_campaign=business_listing',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Precision Landscaping',
  '<p>Precision Landscaping operates as a prominent landscaper in Toronto, Ontario, specializing in Design Build projects throughout the Greater Toronto Area (GTA). This business focuses on creating serene outdoor spaces that enhance the aesthetics and functionality of residential properties. Services provided encompass a wide range of offerings, including pools, pergolas, cabanas, outdoor kitchens, and decks, all tailored to meet the specific needs of clients.</p> <p>The company prides itself on its commitment to minimal maintenance designs that respect the local climatic conditions and soil characteristics. Precision Landscaping''s team of professional landscapers conducts thorough assessments of each property, ensuring that their recommendations align with the unique sun and shade requirements of the space. This meticulous approach allows for the development of elegant outdoor environments that not only meet but often exceed client expectations.</p> <p>Precision Landscaping has established a solid reputation within the community for its reliable service and dedication to quality. The company’s emphasis on expert guidance and honest recommendations fosters trust and satisfaction among clients. Engaging with this local business can lead to innovative landscaping solutions that transform outdoor areas into enjoyable retreats. For those seeking to enhance their property’s exterior, contacting Precision Landscaping may provide valuable insights and options tailored to individual needs.</p>',
  '730 Garyray Dr',
  'Canada',
  'ON',
  'Toronto',
  'M9L 1R3',
  'sales@blanco.cleaning',
  'canada/toronto/home-services/precision-landscaping',
  'ChIJZ_M80KsuK4gRLc2X5Xx5sfI',
  43.765713,
  -79.5563954,
  '14167043637',
  'https://www.kwikr.ca/pictures/profile/pimage-97.jpg',
  'Landscaping=>Seasonal Cleanup',
  'Pay-as-you-go',
  107,
  'https://precisionlandscaping.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Under the Sun Ecological Landscaping Inc.',
  '<p>Under the Sun Ecological Landscaping Inc. operates as a full-service landscaping company located at 283 Danforth Ave, Toronto, Ontario. This business specializes in ecological landscaping solutions, catering to the needs of clients in both Toronto and Peterborough. The company emphasizes sustainable practices, providing options that not only enhance the aesthetic appeal of properties but also promote environmental health.</p> <p>The services offered by Under the Sun include landscape design, installation, and maintenance, focusing on native plants and eco-friendly materials. This approach aligns with the growing trend towards sustainability in landscaping, appealing to environmentally conscious homeowners and businesses. The firm’s commitment to ecological practices sets it apart from traditional landscaping companies, making it a notable choice for clients who prioritize environmental stewardship.</p> <p>In addition to its core services, Under the Sun also engages in community initiatives aimed at promoting green spaces within urban settings. This involvement reflects a dedication to enhancing local ecosystems while beautifying neighborhoods. The company’s reputation for quality workmanship and customer satisfaction has contributed to its standing in the competitive landscaping market.</p> <p>Recognition for its ecological initiatives and community contributions has solidified Under the Sun''s position as a leader in sustainable landscaping. Engaging with the business can provide further insights into its services and ecological practices, making it a valuable resource for those interested in enhancing their outdoor spaces responsibly.</p>',
  '283 Danforth Ave',
  'Canada',
  'ON',
  'Toronto',
  'M4K 1N2',
  'accommodations-ext@fb.com',
  'canada/toronto/home-services/under-the-sun-ecological-landscaping-inc',
  'ChIJbapDN5zM1IkRSJgUM_NCpUo',
  43.6768202,
  -79.3544101,
  '14164820097',
  'https://www.kwikr.ca/pictures/profile/pimage-98.jpg',
  'Landscaping=>Seasonal Cleanup',
  'Pay-as-you-go',
  106,
  'http://www.ecologicallandscaping.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Spruced Up Property Beautification Services',
  '<p>Spruced Up Property Beautification Services specializes in landscaping, offering tailored outdoor solutions in Toronto''s East End. This local business provides consultations to discuss clients'' properties and lifestyles, ensuring designs meet specific needs. Services range from refreshing existing gardens to creating entirely new landscapes, enhancing the aesthetic appeal of residential and commercial spaces.</p> <p>Located at 57 Woodycrest Ave, Spruced Up has established itself as a reliable partner for property beautification. The company''s approach combines creativity with practicality, allowing for personalized designs that reflect the unique character of each property. Knowledgeable staff engage clients in meaningful discussions, leading to designs that harmonize with individual preferences and the surrounding environment.</p> <p>Spruced Up''s commitment to quality is evident in their attention to detail and customer satisfaction. The team utilizes a variety of plants, materials, and techniques to create vibrant landscapes that thrive in Ontario''s climate. This dedication to sustainable practices ensures that each project not only enhances beauty but also promotes ecological health.</p> <p>Recognition within the community highlights the positive impact of Spruced Up''s services. The business continues to grow its reputation for excellence, making it a valuable asset in Toronto''s landscaping industry. For those interested in transforming their outdoor spaces, contacting Spruced Up for a consultation can provide valuable insights and options tailored to specific needs.</p>',
  '57 Woodycrest Ave',
  'Canada',
  'ON',
  'Toronto',
  'M4J 3A8',
  'marcus@handimaidsandaman.com',
  'canada/toronto/home-services/spruced-up-property-beautification-services',
  'ChIJd3G24C_N1IkR88Rhnq3JkaQ',
  43.6820342,
  -79.3424654,
  '14169976554',
  'https://www.kwikr.ca/pictures/profile/pimage-99.jpg',
  'Landscaping=>Seasonal Cleanup',
  'Pay-as-you-go',
  105,
  'http://www.spruced-up.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'JSS Lighting',
  '<p>JSS Lighting, located at 1 Hunter St E in Hamilton, Ontario, specializes in landscape lighting design. This local business offers services that enhance outdoor spaces through creative lighting solutions. The company focuses on improving the beauty, safety, and entertainment value of homes by providing tailored landscape lighting systems. JSS Lighting can either upgrade existing setups or create entirely new designs to illuminate properties effectively.</p> <p>As a landscape lighting designer, JSS Lighting understands the importance of blending functionality with aesthetics. The team works closely with clients to ensure that every project meets their specific needs and preferences. The company employs advanced techniques and high-quality materials to deliver durable and visually appealing lighting solutions. This approach not only enhances the property’s curb appeal but also contributes to the overall safety of outdoor areas, making them more inviting during the evening hours.</p> <p>JSS Lighting has established a reputation for excellence in Hamilton, Ontario, thanks to its commitment to customer satisfaction and innovative designs. The business has received positive feedback from numerous clients who appreciate the professional service and expert guidance provided throughout the design process. Engaging with JSS Lighting can lead to a transformed outdoor space that reflects personal style while ensuring safety and functionality. For more information, contacting the business would be beneficial. </p>',
  '1 Hunter St E',
  'Canada',
  'ON',
  'Hamilton',
  'L8N 3W1',
  'matttibbophotography@gmail.com',
  'canada/hamilton/home-services/jss-lighting',
  'ChIJkdqOOXebLIgR9nOMj7fB5ys',
  43.2537753,
  -79.86954,
  '19059308760',
  NULL,
  'Landscaping=>Landscape Lighting',
  'Pay-as-you-go',
  104,
  'http://jsslighting.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Earth Elements - Landscape Irrigation & Lighting',
  '<p>Earth Elements - Landscape Irrigation & Lighting, located at 1131 Millar Hill Rd in Huntsville, Ontario, specializes in landscape lighting design and irrigation systems. This local business serves the Muskoka region, offering tailored solutions that enhance outdoor spaces. With decades of experience, Earth Elements combines expert service with leading technology to meet the unique needs of each property.</p> <p>The company provides custom irrigation solutions that prioritize water conservation and user-friendly technology. This approach ensures that each system is designed specifically for the individual requirements of the landscape, promoting sustainability while maintaining aesthetic appeal. In addition, Earth Elements excels in outdoor lighting systems, creating designs that illuminate the best features of properties, enhancing both landscape and architecture.</p> <p>Furthermore, Earth Elements offers landscape audio systems that integrate high-performance outdoor speakers into the environment. This service enhances outdoor entertainment experiences, allowing clients to enjoy music and ambiance seamlessly. The emphasis on creativity and functionality distinguishes Earth Elements from competitors, making it a valuable resource for property owners in Muskoka.</p> <p>Recognition for quality service and innovative designs is a hallmark of Earth Elements. Engaging with this business can lead to transformative outdoor spaces that reflect individual styles and preferences. For more information, contacting the business is recommended.</p>',
  '1131 Millar Hill Rd',
  'Canada',
  'ON',
  'Huntsville',
  'P1H 2J6',
  'majestichomeservices@bell.net',
  'canada/huntsville/home-services/earth-elements-landscape-irrigation-lighting',
  'ChIJw-uXB151Kk0RqWOOrtY3stE',
  45.3622885,
  -79.0528734,
  '17053804867',
  'https://www.kwikr.ca/pictures/profile/pimage-81.jpg',
  'Landscaping=>Landscape Lighting',
  'Pay-as-you-go',
  103,
  'http://www.earth-elements.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Moonstruck Lighting Ltd.',
  '<p>Moonstruck Lighting Ltd. is a prominent landscape lighting designer located at 1889 York Regional Rd 7 in Concord, Ontario. This business specializes in designing and building landscape lighting systems that enhance the safety, security, and aesthetic appeal of residential and commercial properties. With a focus on innovative solutions, Moonstruck Lighting Ltd. serves the broader Ontario area, providing tailored lighting designs that meet the unique needs of each client.</p><p>The company stands out in the landscape lighting industry due to its commitment to quality and customer satisfaction. Moonstruck Lighting Ltd. employs experienced professionals who understand the importance of effective lighting in creating safe and inviting outdoor spaces. The team collaborates closely with clients to develop customized lighting plans that highlight architectural features and landscaping while ensuring adequate illumination for safety.</p><p>Moonstruck Lighting Ltd. utilizes advanced technology and high-quality materials in their installations, which contributes to their reputation as a reliable provider. The company remains dedicated to sustainability, often incorporating energy-efficient lighting options into their designs. This approach not only reduces energy costs but also minimizes environmental impact.</p><p>The business has gained recognition for its exceptional service and innovative designs, establishing a solid reputation in the local community. Contacting Moonstruck Lighting Ltd. can provide further insights into their services and how they can enhance any property with bespoke landscape lighting solutions.</p>',
  '1889 York Regional Rd 7',
  'Canada',
  'ON',
  'Concord',
  'L4K 1V4',
  'maidtoperfection@outlook.com',
  'canada/concord/home-services/moonstruck-lighting-ltd',
  'ChIJY3-cnIkuK4gRnkxKnSCKslI',
  43.8031276,
  -79.486439,
  '19057617720',
  'https://www.kwikr.ca/pictures/profile/pimage-82.jpg',
  'Landscaping=>Landscape Lighting',
  'Pay-as-you-go',
  102,
  'https://moonstruck.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Surrey Christmas Lights',
  '<p>Surrey Christmas Lights, located at 12156 96 Ave in Surrey, British Columbia, specializes in landscape lighting design. This business provides a range of services including commercial, residential, and strata lighting installations. Known for using only the highest quality commercial-grade LED Christmas lights, Surrey Christmas Lights stands out in the local area for its commitment to excellence and customer satisfaction.</p> <p>The company offers comprehensive design services, assisting clients in creating the perfect lighting displays for various occasions. With a focus on professionalism, Surrey Christmas Lights employs a team that is highly trained, certified, licensed, and insured. This ensures a seamless installation process, allowing customers to enjoy their holiday season without worry.</p> <p>Surrey Christmas Lights takes pride in its WorksafeBC coverage, emphasizing safety and reliability in every project. The company’s dedication to quality and service has earned it a strong reputation within the community. Clients can expect personalized attention and expert guidance throughout their lighting journey.</p> <p>A notable aspect of Surrey Christmas Lights is its ability to transform ordinary spaces into festive environments that evoke joy and celebration. For those interested in elevating their holiday decor, contacting Surrey Christmas Lights for more information is advisable, as the company continues to make a positive impact in the Surrey area.</p>',
  '12156 96 Ave',
  'Canada',
  'BC',
  'Surrey',
  'V3V 1W6',
  'cozyhomemaid@gmail.com',
  'canada/surrey/home-services/surrey-christmas-lights',
  'ChIJkY3jzDXZhVQRTa9aM3ntI64',
  49.1769024,
  -122.8859095,
  '16049994502',
  'https://www.kwikr.ca/pictures/profile/pimage-83.jpg',
  'Landscaping=>Landscape Lighting',
  'Pay-as-you-go',
  101,
  'http://www.surreychristmaslights.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Lights UP Alberta',
  '<p>Lights UP Alberta, located at 4320 75 Ave SE Bay 23 in Calgary, Alberta, specializes in landscape lighting design. This business provides year-round custom lighting solutions suitable for various occasions. With a focus on enhancing outdoor spaces, Lights UP combines functionality with aesthetic appeal to create inviting environments. The company serves the Calgary area, catering to both residential and commercial clients seeking to elevate their properties through professional lighting installation.</p><p>Lights UP stands out for its commitment to quality and customer satisfaction. The team of skilled designers works closely with clients to understand their unique needs and preferences. Each project is approached with a personalized touch, ensuring that the final result aligns with the client''s vision. The use of advanced lighting technology allows for energy-efficient solutions that do not compromise on brightness or style. This approach not only enhances the beauty of outdoor spaces but also contributes to safety and security.</p><p>Recognition in the local community highlights the effectiveness of Lights UP''s services. The positive feedback from clients demonstrates the company''s dedication to excellence in landscape lighting design. For those interested in transforming their outdoor areas, contacting Lights UP for more information could lead to innovative lighting solutions that enhance any setting.</p>',
  '4320 75 Ave SE Bay 23',
  'Canada',
  'AB',
  'Calgary',
  'T2C 2H8',
  'twinpeaks@twinpeakshomecare.com',
  'canada/calgary/home-services/lights-up-alberta',
  'ChIJ9TfFuRB6cVMRUr6FE-iMxDc',
  50.9878908,
  -113.9733005,
  '14032794346',
  NULL,
  'Landscaping=>Landscape Lighting',
  'Pay-as-you-go',
  100,
  'https://www.lightsupalberta.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Abba Landscaping Inc',
  '<p>Abba Landscaping Inc, located at 12222 100 Ave in Surrey, British Columbia, specializes in landscape lighting design. This local business focuses on creating high-quality garden landscapes and outdoor areas, primarily serving the Vancouver area. The company emphasizes customer satisfaction through its diverse range of services, ensuring that each project meets the unique needs of its clients.</p><p>The expertise of Abba Landscaping Inc lies in enhancing outdoor spaces with carefully designed lighting solutions. This approach not only beautifies gardens but also improves safety and usability during nighttime hours. The team employs innovative techniques and high-quality materials to deliver results that stand the test of time. Their commitment to excellence is evident in each completed project, which showcases their attention to detail and artistic vision.</p><p>Abba Landscaping Inc has established a reputation for reliability and professionalism within the community. The company’s focus on customer needs sets it apart from competitors, making it a preferred choice for landscape lighting design in Surrey and the surrounding regions. Collaboration with clients ensures that every design aligns with their vision and enhances the overall aesthetic of their properties.</p><p>Recognition for customer service and quality work contributes to the positive standing of Abba Landscaping Inc in the local market. Engaging with this business could provide valuable insights into landscape lighting solutions tailored to individual preferences and requirements.</p>',
  '12222 100 Ave',
  'Canada',
  'BC',
  'Surrey',
  'V3V 2X1',
  'clients@steamkleen.ca',
  'canada/surrey/home-services/abba-landscaping-inc',
  'ChIJXUbooV7ZhVQRdG1aBBSkXa8',
  49.1841734,
  -122.8838718,
  '17789879018',
  'https://www.kwikr.ca/pictures/profile/pimage-85.jpg',
  'Landscaping=>Landscape Lighting',
  'Pay-as-you-go',
  99,
  'https://www.abbalandscaping.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Oasis Irrigation, éclairage paysager et architectural',
  '<p>Oasis Irrigation, éclairage paysager et architectural, located at 1325 Chem. de Saint-Jean in La Prairie, Quebec, specializes in landscape lighting design. This local business offers customized outdoor lighting solutions that enhance the serenity, security, beauty, and value of properties. With a focus on quality, Oasis utilizes recognized industry products and fixtures, ensuring a wide selection of outdoor lights and garden illumination.</p> <p>The company tailors each lighting system to meet specific client needs while adhering to budget constraints. This personalized approach distinguishes Oasis from competitors in the La Prairie area. Clients can expect professional installation of automatic irrigation systems, delivered discreetly to maintain the aesthetic of outdoor spaces. The dedication to high standards in both product selection and service execution reflects a commitment to quality that resonates within the local community.</p> <p>Oasis Irrigation has built a reputation for excellence in landscape lighting design, contributing positively to the beautification of properties in La Prairie. The business''s reliance on top-tier materials and experienced professionals ensures that every project meets the highest expectations. Engaging with Oasis for landscape lighting needs can lead to enhanced outdoor environments. Contacting the business will provide further insights into their offerings and how they can assist in transforming outdoor spaces.</p>',
  '1325 Chem. de Saint-Jean',
  'Canada',
  'QC',
  'La Prairie',
  'J5R 2L8',
  'cleansceneyellowknife@gmail.com',
  'canada/la-prairie/home-services/oasis-irrigation-éclairage-paysager-et-architectural',
  'ChIJvX5KhOkOyUwRYLwFF4B0xJ4',
  45.4104474,
  -73.4752459,
  '14504443350',
  'https://www.kwikr.ca/pictures/profile/pimage-86.jpg',
  'Landscaping=>Landscape Lighting',
  'Pay-as-you-go',
  98,
  'https://eclairageoasis.com/',
  NULL,
  NULL,
  NULL,
  NULL
);
