INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Polissage Béton Premium Inc.',
  '<p>Polissage Béton Premium Inc. provides expert floor sanding and polishing services in Terrebonne, Quebec. Specializing in water-based polishing techniques for concrete floors, this company serves industrial, commercial, and residential sectors. With 20 years of experience in concrete treatment, Polissage Béton Premium Inc. demonstrates a high level of skill and knowledge in their craft.</p><p>The company employs a unique water polishing method, a specialized service not widely available. This technique not only enhances the aesthetic appeal of concrete floors but also improves their durability. Polissage Béton Premium Inc. understands the specific needs of various environments, ensuring optimal results for each project. Their commitment to quality and customer satisfaction sets them apart in the local market.</p><p>Polissage Béton Premium Inc. operates from 313 Rue Florimond-Gauthier, making it accessible for clients throughout Terrebonne and surrounding areas. The team’s expertise in concrete treatment ensures that every job, whether large or small, receives the same level of attention and care. Their reputation is built on reliability and professionalism, making them a trusted choice for floor polishing services.</p><p>In summary, Polissage Béton Premium Inc. excels in providing high-quality floor sanding and polishing services with a focus on water-based techniques. Their extensive experience and commitment to excellence make them a leader in the industry. Connect with Polissage Béton Premium Inc. in Terrebonne for exceptional concrete floor solutions.</p>',
  '313 Rue Florimond-Gauthier',
  'Canada',
  'QC',
  'Terrebonne',
  'J6W 5K2',
  'brubacherpowerline@gmail.com',
  'canada/terrebonne/home-services/polissage-béton-premium-inc',
  'ChIJZ5t6tyjfyEwRl71kXBx2oT4',
  45.6924519,
  -73.6537551,
  '15144763231',
  'https://www.kwikr.ca/pictures/profile/pimage-232.jpg',
  'Flooring=>Floor Repairs',
  'Pay-as-you-go',
  248,
  'https://www.polissage-beton.ca/?utm_source=GMB-listing&utm_medium=Organic',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Star Planchers - Sablage sans poussière de Plancher à Québec',
  '<p>Star Planchers offers exceptional floor sanding and polishing services in Québec City, Quebec. Specializing in dust-free sanding, the company ensures a clean and efficient process. With a team of passionate professionals, Star Planchers delivers high-quality finishes for oiled, varnished, and stained floors. The business also renovates stairs to create a cohesive interior design.</p> <p>Commitment to health, safety, and environmental respect defines Star Planchers'' operations. Utilizing Bona products, a global leader in floor care, ensures superior quality and durability for every project. The meticulous approach to floor sanding and polishing reflects the company’s dedication to excellence. Star Planchers emphasizes customer satisfaction and strives to meet the unique needs of clients in the local area.</p> <p>Star Planchers has built a reputation for reliability and professionalism in Québec City. The combination of advanced techniques and expert craftsmanship sets the business apart in the flooring industry. Clients appreciate the attention to detail and the transformative results achieved through their services. The focus on sustainable practices and high-quality materials further enhances the appeal of Star Planchers.</p> <p>Experience top-tier floor sanding and polishing with Star Planchers. The commitment to quality and customer satisfaction shines through in every project. Reach out to Star Planchers for outstanding services in Québec City.',
  '2967 Boul. Louis-XIV',
  'Canada',
  'QC',
  'Québec City',
  'G1C 5S6',
  'careers@symtech.com',
  'canada/québec-city/home-services/star-planchers-sablage-sans-poussière-de-plancher-à-québec',
  'ChIJcc_xe3m8uEwREAtXHDty5sU',
  46.8870738,
  -71.1733632,
  '14184408741',
  'https://www.kwikr.ca/pictures/profile/pimage-231.jpg',
  'Flooring=>Floor Repairs',
  'Pay-as-you-go',
  247,
  'http://www.starplanchers.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Valley Stonescapes - Concrete Polishing, Epoxy Flooring, Lime Plaster',
  '<p>Valley Stonescapes, located in Abbotsford, British Columbia, offers expert floor sanding and polishing services. This business specializes in concrete polishing, epoxy flooring, and lime plaster applications. With a focus on quality and customer satisfaction, Valley Stonescapes ensures durable and aesthetically pleasing surfaces for residential and commercial properties.</p> <p>The team at Valley Stonescapes employs advanced techniques and high-quality materials to deliver exceptional results. Concrete polishing enhances the appearance and longevity of floors, making them both functional and attractive. Epoxy coatings provide a seamless finish that is resistant to stains and damage, ideal for garages, warehouses, and showrooms. Additionally, the removal of old epoxy coatings and glue ensures a clean slate for new applications.</p> <p>Valley Stonescapes has built a reputation for reliability and professionalism in the Abbotsford area. The business prioritizes client needs, delivering projects on time and within budget. Their commitment to excellence has earned them numerous positive reviews from satisfied customers, highlighting their attention to detail and expertise in the flooring industry.</p> <p>Valley Stonescapes excels in providing high-quality flooring solutions that meet diverse needs. Their services in concrete polishing and epoxy flooring contribute to beautiful and durable spaces. For those seeking reliable flooring services in Abbotsford, connect with Valley Stonescapes today.',
  '32465 South Fraser Way Suite 151, #4',
  'Canada',
  'BC',
  'Abbotsford',
  'V2T 0C7',
  'emlira.magazine@gmail.com',
  'canada/abbotsford/home-services/valley-stonescapes-concrete-polishing-epoxy-flooring-lime-plaster',
  'ChIJVYbxlxg1hFQR1m7itTpyJ6k',
  49.0522929,
  -122.3253378,
  '16047511456',
  'https://www.kwikr.ca/pictures/profile/pimage-230.jpg',
  'Flooring=>Floor Repairs',
  'Pay-as-you-go',
  246,
  'http://www.valleystonescapes.ca/concrete-polishing-abbotsford',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Arrows Hardwood Floors',
  '<p>Arrows Hardwood Floors specializes in floor refinishing services in Innisfil Beach, Ontario. This local business transforms hardwood floors, enhancing their beauty and extending their lifespan. With a focus on quality craftsmanship, Arrows Hardwood Floors has built a reputation for reliability and excellence in the community.</p><p>The team at Arrows Hardwood Floors utilizes advanced techniques and high-quality materials to restore and revitalize hardwood surfaces. Each project receives careful attention to detail, ensuring a flawless finish that meets customer expectations. The business prioritizes customer satisfaction, providing personalized service tailored to individual needs. Timeliness and professionalism characterize every interaction, reinforcing trust within the community.</p><p>Located at 1098 Kensington St, Arrows Hardwood Floors is easily accessible for residents seeking expert floor refinishing. The company prides itself on its commitment to sustainable practices, using eco-friendly products that are safe for both the environment and families. This dedication to responsible service sets Arrows Hardwood Floors apart in the industry.</p><p>Arrows Hardwood Floors offers exceptional floor refinishing services that enhance the aesthetic appeal and durability of hardwood floors. The combination of skilled craftsmanship and customer-focused service contributes to the business’s success. For those in Innisfil Beach looking to improve their flooring, reach out to Arrows Hardwood Floors for professional assistance.</p>',
  '1098 Kensington St',
  'Canada',
  'ON',
  'Innisfil Beach',
  'L9S 1V1',
  'lukepotter@aquareach.ca',
  'canada/innisfil-beach/home-services/arrows-hardwood-floors',
  'ChIJk0cnuJ-wKogRGNKpwfQua_E',
  44.3178492,
  -79.5588337,
  '17053218492',
  'https://www.kwikr.ca/pictures/profile/pimage-229.jpg',
  'Flooring=>Floor Refinishing',
  'Pay-as-you-go',
  245,
  'https://www.arrowshardwoodfloors.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Jenkyns Coatings',
  '<p>Jenkyns Coatings provides expert floor refinishing services in Winnipeg, Manitoba. Founded by Stephan Jenkyns, the company emerged from a quest for superior construction materials. After extensive research, Stephan specialized in Polytek Coatings, ensuring high-quality solutions for flooring needs. This commitment to quality and value sets Jenkyns Coatings apart in the local market.</p> <p>The company focuses on delivering exceptional floor refinishing services that enhance the durability and aesthetic appeal of residential and commercial spaces. Jenkyns Coatings utilizes advanced techniques and top-grade materials to ensure long-lasting results. The expertise in Polytek Coatings allows for customized solutions tailored to individual project requirements.</p> <p>Serving Winnipeg and surrounding areas, Jenkyns Coatings has built a reputation for reliability and professionalism. The dedication to customer satisfaction drives the team to exceed expectations on every project. Clients benefit from a meticulous approach that prioritizes quality, ensuring floors not only look great but also withstand the test of time.</p> <p>Jenkyns Coatings offers a blend of expertise, quality products, and customer-focused service. The commitment to excellence in floor refinishing makes this company a top choice in Winnipeg. For reliable floor refinishing services, connect with Jenkyns Coatings at 2033 Portage Ave, Winnipeg, Manitoba, R3J 0K8.</p>',
  '2033 Portage Ave',
  'Canada',
  'MB',
  'Winnipeg',
  'R3J 0K8',
  'importdata-184@kwikr.ca',
  'canada/winnipeg/home-services/jenkyns-coatings',
  'ChIJwV7WAalz6lIRphBeHF4uv9k',
  49.8777613,
  -97.2301226,
  '12049903288',
  NULL,
  'Flooring=>Floor Refinishing',
  'Pay-as-you-go',
  244,
  'https://jenkynscoatings.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Mr. Marble and Stone',
  '<p>Mr. Marble and Stone offers exceptional floor refinishing services in West Vancouver, British Columbia. With over 25 years of experience, this local business specializes in restoring and maintaining natural stone surfaces. Expertise in marble polishing, cleaning, and restoration sets Mr. Marble and Stone apart in the competitive landscape of floor care. The company utilizes advanced Epoxy technology, ensuring durable and long-lasting results for residential, commercial, industrial, and institutional clients.</p><p>This business has built a reputation for quality craftsmanship and attention to detail. Each project reflects a commitment to restoring natural stone surfaces to their original beauty. The team at Mr. Marble and Stone understands the unique needs of various clients, ensuring tailored solutions that meet specific requirements. Their extensive experience in the Lower Mainland allows them to tackle a wide range of flooring challenges effectively.</p><p>Customer satisfaction remains a priority, and the company strives to exceed expectations with every service provided. The combination of high standards and innovative techniques positions Mr. Marble and Stone as a trusted choice for floor refinishing in the area. The dedication to quality and service ensures that clients receive the best possible outcomes for their natural stone surfaces.</p><p>Mr. Marble and Stone excels in floor refinishing, stone restoration, and maintenance services. Their expertise and commitment to quality make them a reliable partner for restoring natural stone beauty. Connect with Mr. Marble and Stone at 888 8th St, West Vancouver, British Columbia, to explore their services today.</p>',
  '888 8th St',
  'Canada',
  'BC',
  'West Vancouver',
  'V7T 1S3',
  'rboyer@immacex.ca',
  'canada/west-vancouver/home-services/mr-marble-and-stone',
  'ChIJdYM4A9dxhlQRfbIO2Sg6BOA',
  49.3326153,
  -123.1373355,
  '17783897171',
  'https://www.kwikr.ca/pictures/profile/pimage-227.jpg',
  'Flooring=>Floor Refinishing',
  'Pay-as-you-go',
  243,
  'http://www.mrmarbleandstone.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Forever Epoxy',
  '<p>Forever Epoxy offers exceptional floor refinishing services in Irishtown, New Brunswick. This local business prioritizes quality and customer satisfaction in every project. With a commitment to providing beautiful and functional flooring systems, Forever Epoxy caters to both residential and commercial needs. The team ensures that each installation adheres to the highest standards of workmanship, making them a reliable choice for flooring solutions.</p><p>Established with a clear mission, Forever Epoxy focuses on making quality flooring accessible for all. The skilled professionals bring expertise and attention to detail, transforming spaces with durable and attractive flooring options. Customers can expect a seamless experience from consultation to installation, reflecting the company’s dedication to excellence.</p><p>The company’s location on 119 Daniel Dr in Irishtown positions it well to serve the surrounding community effectively. With a strong reputation for delivering high-quality results, Forever Epoxy has become a trusted name in floor refinishing. Each project showcases the company’s commitment to craftsmanship and customer care. Clients appreciate the personalized approach and the emphasis on meeting individual needs.</p><p>Forever Epoxy specializes in floor refinishing, ensuring that all installations are not only visually appealing but also built to last. The business excels in providing reliable services, making it a go-to choice for flooring projects in the area. Connect with Forever Epoxy today for professional floor refinishing services in Irishtown, New Brunswick.</p>',
  '119 Daniel Dr',
  'Canada',
  'NB',
  'Irishtown',
  'E1H 0B2',
  'dan@danthewindowman.ca',
  'canada/irishtown/home-services/forever-epoxy',
  'ChIJdQJfOkz98QQRTsPa4Rk2o1I',
  46.2079647,
  -64.7864126,
  '15068781444',
  'https://www.kwikr.ca/pictures/profile/pimage-226.jpg',
  'Flooring=>Floor Refinishing',
  'Pay-as-you-go',
  242,
  'https://www.foreverepoxy.ca/?utm_source=google&utm_medium=wix_google_business_profile&utm_campaign=8525444927306745534',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Armor Rock Floor Coatings',
  '<p>Armor Rock Floor Coatings offers exceptional floor refinishing services in Etobicoke, Ontario. This local business specializes in transforming both residential and commercial spaces with high-quality floor coatings. With a commitment to durability and aesthetic appeal, Armor Rock ensures that every project meets the unique needs of its clients.</p> <p>Located at 75 Medulla Ave, Armor Rock Floor Coatings has established a reputation for reliability and excellence in the floor refinishing category. The team utilizes advanced techniques and premium materials to deliver results that stand the test of time. Customers appreciate the attention to detail and the personalized approach taken by the professionals at Armor Rock.</p> <p>Clients benefit from a range of services tailored to various flooring types, including epoxy coatings, concrete sealing, and resurfacing. The company prioritizes customer satisfaction, ensuring that every floor refinishing project is completed on time and within budget. Armor Rock Floor Coatings also emphasizes the importance of safety and environmental responsibility in its operations.</p> <p>With a strong focus on quality and service, Armor Rock Floor Coatings continues to excel in the Etobicoke area. The dedication to enhancing floor longevity and appearance positions the company as a leader in the industry. Reach out to Armor Rock Floor Coatings for professional floor refinishing services in Etobicoke, Ontario.</p>',
  '75 Medulla Ave',
  'Canada',
  'ON',
  'Etobicoke',
  'M8Z 5L6',
  'info@lavagedevitreslp.com',
  'canada/etobicoke/home-services/armor-rock-floor-coatings',
  'ChIJS6G7VQQ4K4gR8Re_ZGIVW9k',
  43.6265576,
  -79.5461186,
  '19058285855',
  'https://www.kwikr.ca/pictures/profile/pimage-225.jpg',
  'Flooring=>Floor Refinishing',
  'Pay-as-you-go',
  241,
  'http://www.armorrock.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'docteur sablage',
  '<p>Docteur Sablage provides expert floor refinishing services in Longueuil, Quebec. This local business specializes in restoring hardwood floors, ensuring they look new and vibrant. With a commitment to quality craftsmanship, Docteur Sablage has built a reputation for excellence in the community. The team utilizes advanced techniques and high-quality materials to deliver outstanding results, making them a preferred choice for homeowners and businesses alike.</p> <p>Floor refinishing requires precision and skill. Docteur Sablage employs knowledgeable professionals who understand the nuances of different flooring types. They assess each project individually, ensuring tailored solutions that meet specific needs. This attention to detail sets the company apart in the competitive floor refinishing market. Customers appreciate the thoroughness and care taken during every step of the refinishing process.</p> <p>The company’s dedication to customer satisfaction is evident in their positive reviews and repeat business. Many clients highlight the prompt service and transparent pricing, which fosters trust and confidence. Docteur Sablage not only enhances the aesthetic appeal of floors but also extends their lifespan, providing significant value to clients.</p> <p>Docteur Sablage excels in delivering quality floor refinishing services in Longueuil, Quebec. Their skilled team, attention to detail, and customer-focused approach contribute to their strong reputation. For professional floor refinishing, connect with Docteur Sablage at Boulevard Pelletier CP 50577 Brossard, Carre CP.</p>',
  'Boulevard Pelletier CP 50577 Brossard, Carre CP',
  'Canada',
  'QC',
  'Longueuil',
  'J4X 2V7',
  'winduckscleaning@gmail.com',
  'canada/longueuil/home-services/docteur-sablage',
  'ChIJ4RR4kTL92kARC9rjfdm4F3c',
  45.4495104,
  -73.4708065,
  '14385208512',
  'https://www.kwikr.ca/pictures/profile/pimage-224.jpg',
  'Flooring=>Floor Refinishing',
  'Pay-as-you-go',
  240,
  'http://docteursablage.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'LB Epoxy Flooring',
  '<p>LB Epoxy Flooring offers top-tier floor refinishing services in Vernon, British Columbia. This local business specializes in high-end, durable epoxy floor coatings, catering to both residential and commercial needs. With a focus on garages, LB Epoxy Flooring also extends its expertise to various concrete-based indoor floors across the Okanagan, Shuswap, and Kamloops areas.</p> <p>The company prides itself on delivering stunning results that enhance the aesthetic and functional qualities of any space. Each project reflects a commitment to quality and customer satisfaction. LB Epoxy Flooring utilizes advanced techniques to ensure long-lasting durability and impressive finishes. The team understands the unique requirements of each client, providing tailored solutions that meet specific needs. This approach fosters strong relationships and builds trust within the community.</p> <p>LB Epoxy Flooring has earned a reputation for excellence in the floor refinishing industry. The skilled professionals bring years of experience to every job, ensuring that every installation meets the highest standards. Clients appreciate the attention to detail and the ability to transform ordinary concrete floors into remarkable surfaces. The business''s dedication to quality and service sets it apart from competitors.</p> <p>LB Epoxy Flooring delivers exceptional epoxy floor coatings, focusing on durability and beauty. Their commitment to customer satisfaction and high-quality results has made them a trusted choice in Vernon. Connect with LB Epoxy Flooring for outstanding floor refinishing services in Vernon, British Columbia.</p>',
  '2200 18 Ave',
  'Canada',
  'BC',
  'Vernon',
  'V1T 6W9',
  'info@mastershine.ca',
  'canada/vernon/home-services/lb-epoxy-flooring',
  'ChIJf5BzjKLgfVMRIMpLFREKitw',
  50.2542637,
  -119.2604252,
  '12509383068',
  'https://www.kwikr.ca/pictures/profile/pimage-223.jpg',
  'Flooring=>Floor Refinishing',
  'Pay-as-you-go',
  239,
  'http://www.lbepoxyflooring.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Prodecor',
  '<p>Prodecor, located at 545 Rte de l''Église in Saint-Jean-Port-Joli, Quebec, specializes in carpet installation and flooring solutions. This local business provides high-quality products and services tailored to meet the needs of residential and commercial clients. With a commitment to excellence, Prodecor has built a reputation for reliability and professionalism in the flooring industry.</p><p>The team at Prodecor focuses on delivering exceptional craftsmanship in every project. They offer a wide range of flooring options, including carpets, that cater to various styles and preferences. Customers appreciate the expert guidance provided during the selection process, ensuring a perfect match for any space. Prodecor''s dedication to customer satisfaction drives them to use only the best materials available in the market.</p><p>Prodecor understands the importance of a well-installed carpet. Their experienced installers work efficiently, minimizing disruption to daily activities while ensuring that every detail is attended to. This approach not only enhances the aesthetic appeal of a space but also contributes to its overall comfort and functionality. The business prides itself on timely project completion and maintaining a clean work environment.</p><p>Prodecor excels in providing quality flooring solutions in Saint-Jean-Port-Joli. Their expertise in carpet installation and commitment to customer service make them a preferred choice for many. Connect with Prodecor today for professional flooring services in Quebec.</p>',
  '545 Rte de l''Église',
  'Canada',
  'QC',
  'Saint-Jean-Port-Joli',
  'G0R 3G0',
  'romanexteriors7@gmail.com',
  'canada/saint-jean-port-joli/home-services/prodecor',
  'ChIJbzLK0qfWvkwRPhcfr9tZGp8',
  47.2027865,
  -70.2524375,
  '14183580999',
  NULL,
  'Flooring=>Carpet Installation',
  'Pay-as-you-go',
  238,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'AAA Carpet Repair',
  '<p>AAA Carpet Repair provides expert carpet installation and repair services in North Vancouver, British Columbia. With over 28 years of experience, this local business specializes in a range of carpet repair solutions, including restretching wrinkled carpets, fixing torn seams, addressing frayed carpets, and removing non-removable stains. Customers can expect a free quote and guaranteed quality in every service.</p> <p>The team at AAA Carpet Repair understands the importance of maintaining a clean and functional carpet. Years of experience have equipped them with the skills necessary to handle various carpet issues efficiently. The business operates in the Greater Vancouver area, ensuring that residents have access to reliable carpet repair services. The commitment to customer satisfaction and high-quality workmanship has built a strong reputation in the community.</p> <p>Services offered include carpet restretching, seam repair, stain removal, and addressing burns on carpets. Each service is performed with attention to detail, ensuring that the results meet customer expectations. AAA Carpet Repair stands out for its dedication to providing effective solutions tailored to individual needs. The team is available for consultations and offers free quotes, making it easy for customers to understand their options.</p> <p>AAA Carpet Repair delivers reliable and professional carpet services. With a focus on customer satisfaction and a wealth of experience, this business is a trusted choice for carpet repair needs in North Vancouver. Reach out to AAA Carpet Repair for expert services in British Columbia.</p>',
  '315 W Kings Rd',
  'Canada',
  'BC',
  'North Vancouver',
  'V7N 2M1',
  'info@myaurum.com',
  'canada/north-vancouver/home-services/aaa-carpet-repair',
  'ChIJzQNh-SFwhlQRUoHnl5pU0Ls',
  49.3372572,
  -123.0776287,
  '16049870030',
  'https://www.kwikr.ca/pictures/profile/pimage-221.jpg',
  'Flooring=>Carpet Installation',
  'Pay-as-you-go',
  237,
  'https://www.aaacarpetrepair.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'AAA Carpet Repair',
  '<p>AAA Carpet Repair offers specialized services in damaged carpet repairs, serving the Metro Vancouver area for over 28 years. Located at 5033 Regent St in Burnaby, British Columbia, this business has developed a reputation for quality craftsmanship and reliable service. The expertise in addressing various carpet issues ensures that customers receive effective solutions tailored to their needs.</p><p>The company focuses on restoring carpets to their original condition, using advanced techniques and high-quality materials. AAA Carpet Repair addresses a range of problems, including burns, stains, and fraying edges. Their skilled team combines experience with a commitment to customer satisfaction, ensuring that every repair meets high standards. This dedication to excellence has established them as a trusted name in the carpet installation industry.</p><p>With a strong presence in Burnaby and the surrounding areas, AAA Carpet Repair has successfully completed numerous projects, earning positive feedback from clients. Their ability to handle both residential and commercial carpet repairs sets them apart from competitors. The focus on detail and quality workmanship contributes to long-lasting results, making them a preferred choice for many.</p><p>AAA Carpet Repair provides expert carpet repair services, emphasizing quality and customer satisfaction. With nearly three decades of experience, the business showcases its strengths in restoring carpets effectively. Connect with AAA Carpet Repair at their location in Burnaby, British Columbia, for reliable carpet solutions.</p>',
  '5033 Regent St',
  'Canada',
  'BC',
  'Burnaby',
  'V5C 4H4',
  'klearview@klearviewwindowcleaning.ca',
  'canada/burnaby/home-services/aaa-carpet-repair',
  'ChIJsc2cPD13hlQRtkgUK0p31yA',
  49.258637,
  -122.991565,
  '16046717847',
  'https://www.kwikr.ca/pictures/profile/pimage-220.jpg',
  'Flooring=>Carpet Installation',
  'Pay-as-you-go',
  236,
  'https://www.aaacarpetrepair.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'AAA Carpet Repair',
  '<p>AAA Carpet Repair provides expert carpet installation and repair services in Duncan, British Columbia. With over 28 years of experience, this local business specializes in a variety of carpet repair solutions, catering to the needs of customers in Greater Vancouver and Vancouver Island.</p> <p>The company excels in restoring carpets to their original condition. Services include restretching wrinkled carpet, repairing torn seams, fixing frayed edges, and addressing non-removable stains and burn marks. AAA Carpet Repair ensures high-quality workmanship and guarantees customer satisfaction with every project.</p> <p>Offering free quotes, AAA Carpet Repair maintains a commitment to transparency and customer service. The team is available to assist clients at any time, making the process seamless and convenient. Trust in their expertise to handle all types of carpet issues efficiently and effectively.</p> <p>AAA Carpet Repair has built a strong reputation in the community for its reliability and professionalism. Customers appreciate the attention to detail and the quality of repairs provided. The business continues to thrive, driven by a passion for carpet restoration and a dedication to meeting the needs of local residents.</p> <p>With a focus on high-quality carpet repair services and a proven track record, AAA Carpet Repair remains a top choice for those in need of carpet solutions in Duncan, British Columbia. Reach out to AAA Carpet Repair for expert assistance with carpet repair needs in the area.',
  '6641 Lakes Rd',
  'Canada',
  'BC',
  'Duncan',
  'V9L 5V9',
  'importdata-175@kwikr.ca',
  'canada/duncan/home-services/aaa-carpet-repair',
  'ChIJWWJuOOtPj1QRdhl4DgbT0eM',
  48.8106429,
  -123.6698911,
  '12505100713',
  NULL,
  'Flooring=>Carpet Installation',
  'Pay-as-you-go',
  235,
  'https://www.aaacarpetrepair.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'White Lamb Finlay Inc.',
  '<p>White Lamb Finlay Inc. provides expert carpet installation services in Etobicoke, Ontario. This local business specializes in transforming spaces with high-quality flooring solutions. With a commitment to customer satisfaction, White Lamb Finlay Inc. has built a reputation for reliability and professionalism in the carpet installation industry.</p><p>The team at White Lamb Finlay Inc. offers a wide range of carpet options, catering to both residential and commercial needs. Utilizing advanced techniques and industry knowledge, they ensure precise installations that enhance the aesthetic appeal of any space. Their attention to detail and dedication to quality results set them apart in the competitive flooring market.</p><p>Located at 107 Woodbine Downs Blvd, this business serves the Etobicoke community and surrounding areas. White Lamb Finlay Inc. understands the importance of a well-installed carpet, contributing to comfort and style in homes and offices. Clients appreciate the seamless experience from consultation to installation, which reflects the company''s commitment to excellence.</p><p>White Lamb Finlay Inc. stands out for its skilled craftsmanship and customer-centric approach. The team prioritizes understanding client needs and delivering tailored solutions. With a focus on quality materials and meticulous workmanship, this carpet installer consistently meets and exceeds expectations in Etobicoke. Connect with White Lamb Finlay Inc. for exceptional carpet installation services in Ontario.</p>',
  '107 Woodbine Downs Blvd',
  'Canada',
  'ON',
  'Etobicoke',
  'M9W 6Y1',
  'kelownawindowcleaners@gmail.com',
  'canada/etobicoke/home-services/white-lamb-finlay-inc',
  'ChIJBwZWUgA7K4gRTxd12gtDngs',
  43.7414779,
  -79.607686,
  '14167412256',
  NULL,
  'Flooring=>Carpet Installation',
  'Pay-as-you-go',
  234,
  'http://www.whitelambfinlay.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'RAZ Flooring',
  '<p>RAZ Flooring provides expert carpet installation services in Edmonton, Alberta. With over 12 years of experience, this flooring company specializes in the installation, replacement, and repair of various flooring types including carpet, vinyl plank, and carpet tiles. RAZ Flooring caters to both new and older homes, ensuring quality service for every project.</p> <p>The team at RAZ Flooring demonstrates a commitment to excellence in every installation. Their expertise extends to all types of stairs, making them a versatile choice for any flooring needs. The company’s reputation for reliability and professionalism has made it a trusted name in the local community. Customers appreciate the attention to detail and the high standards maintained throughout each project.</p> <p>RAZ Flooring prioritizes customer satisfaction, ensuring that every installation meets the specific needs of the client. The company’s extensive knowledge of various flooring materials allows for informed recommendations tailored to individual preferences. With a focus on quality workmanship, RAZ Flooring guarantees durable and aesthetically pleasing results.</p> <p>In summary, RAZ Flooring offers comprehensive flooring solutions in Edmonton, Alberta, with a strong emphasis on customer service and quality. The team''s experience and dedication to their craft make them a reliable choice for all flooring projects. Connect with RAZ Flooring today to explore flooring options and services available in Edmonton.</p>',
  '16003 132 St NW',
  'Canada',
  'AB',
  'Edmonton',
  'T6V 0B5',
  'lambswindowcleaning@gmail.com',
  'canada/edmonton/home-services/raz-flooring',
  'ChIJHeYZiEkloFMROXKN6xrn5OI',
  53.6211885,
  -113.5525751,
  '17806559905',
  'https://www.kwikr.ca/pictures/profile/pimage-217.jpg',
  'Flooring=>Carpet Installation',
  'Pay-as-you-go',
  233,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Dr. Carpet',
  '<p>Dr. Carpet offers expert carpet installation services in Erin, Ontario. This local business specializes in transforming spaces with high-quality carpets tailored to meet individual needs. With a commitment to customer satisfaction, Dr. Carpet has built a reputation for reliability and professionalism in the carpet installation industry.</p> <p>The team at Dr. Carpet possesses extensive experience and knowledge in flooring solutions. They provide a wide range of carpet options, ensuring that every client finds the perfect fit for their home or business. The installation process is efficient and thorough, emphasizing attention to detail and quality workmanship. Clients appreciate the personalized service that Dr. Carpet delivers, making the entire experience seamless and stress-free.</p> <p>Dr. Carpet understands the importance of a well-installed carpet in enhancing the overall aesthetic of a space. The company utilizes top-grade materials and modern techniques to ensure durability and longevity in every project. Many satisfied customers have praised the transformative impact of their new carpets, highlighting the warmth and comfort added to their environments.</p> <p>With a focus on quality and customer care, Dr. Carpet continues to serve Erin and surrounding areas with excellence. Their dedication to providing exceptional carpet installation services makes them a trusted choice for homeowners and businesses alike. Connect with Dr. Carpet today at 4 Wallace St, Erin, Ontario, N0B 1Z0 for professional carpet installation services.</p>',
  '4 Wallace St',
  'Canada',
  'ON',
  'Erin',
  'N0B 1Z0',
  'info@tinmangroup.ca',
  'canada/erin/home-services/dr-carpet',
  'ChIJn8y8NUymK4gR0za1SOuwqx0',
  43.7965168,
  -80.1471901,
  '16478005199',
  NULL,
  'Flooring=>Carpet Installation',
  'Pay-as-you-go',
  232,
  'http://www.drcarpet.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Inter-Pose',
  '<p>Inter-Pose, located in Beloeil, Quebec, specializes in professional carpet installation services. With a commitment to quality, the team ensures that every carpet project meets high standards. The business serves residential and commercial clients, providing tailored solutions for various flooring needs. Inter-Pose has established a reputation for reliability and customer satisfaction in the local area.</p><p>The skilled installers at Inter-Pose bring years of experience to each project. They understand the importance of selecting the right carpet to enhance the aesthetic of any space. The team works closely with clients to offer expert advice on material choices, styles, and installation methods. This personalized approach ensures that each installation reflects the client’s vision and requirements.</p><p>Inter-Pose prides itself on using high-quality materials and modern techniques. This commitment to excellence results in durable and visually appealing flooring solutions. The company’s attention to detail during the installation process guarantees a seamless finish that enhances the overall look of any room.</p><p>With a focus on customer satisfaction and quality craftsmanship, Inter-Pose has become a trusted name in carpet installation in Beloeil, Quebec. The business continues to grow, driven by positive customer feedback and a strong commitment to delivering outstanding results. Engage with Inter-Pose for expert carpet installation services in Beloeil today.</p>',
  '2150 Rue Pierre-Louis-Le Tourneux #130',
  'Canada',
  'QC',
  'Beloeil',
  'J3G 0R5',
  'info@rembourrageautomobile.ca',
  'canada/beloeil/home-services/inter-pose',
  'ChIJq5MJ4eFVyEwRi6uCn5POhZw',
  45.6022708,
  -73.2216919,
  '14504303400',
  'https://www.kwikr.ca/pictures/profile/pimage-215.jpg',
  'Flooring=>Carpet Installation',
  'Pay-as-you-go',
  231,
  'http://www.rxfloor.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Curlys Carpet repair',
  '<p>Curlys Carpet Repair provides expert carpet installation services in Vancouver, British Columbia. This business specializes in repairing, re-stretching, and fixing all types of wall-to-wall carpets. With a commitment to quality and customer satisfaction, Curlys Carpet Repair has established a solid reputation in the local community.</p><p>The team at Curlys Carpet Repair possesses extensive knowledge in the carpet industry. They understand the challenges that come with damaged carpets and offer tailored solutions to meet individual needs. Whether dealing with unsightly wrinkles or tears, the skilled technicians ensure carpets look and feel their best. Using advanced techniques and high-quality materials, the business effectively restores carpets to their original condition.</p><p>Curlys Carpet Repair operates from 1255 Comox St #20 in Vancouver, making it easily accessible for local residents. The business prioritizes efficiency and reliability, aiming to complete repairs promptly without compromising quality. Customers appreciate the straightforward approach and transparent pricing, which fosters trust and loyalty within the community.</p><p>This business excels in providing essential carpet services that enhance the aesthetic and functional aspects of homes and offices. With a focus on customer needs and a dedication to excellence, Curlys Carpet Repair continues to thrive in Vancouver. Reach out to Curlys Carpet Repair for professional carpet repair services in British Columbia. </p>',
  '1255 Comox St #20',
  'Canada',
  'BC',
  'Vancouver',
  'V6E 1K6',
  'scholarship@hallmarkhousekeeping.com',
  'canada/vancouver/home-services/curlys-carpet-repair',
  'ChIJp3UM-yhyhlQRyZOpMTrzCVo',
  49.2839827,
  -123.1318688,
  '16042826630',
  'https://www.kwikr.ca/pictures/profile/pimage-214.jpg',
  'Flooring=>Carpet Installation',
  'Pay-as-you-go',
  230,
  'http://curlyscarpetrepair.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'HMA Carpet',
  '<p>HMA Carpet offers professional carpet sales, installation, and repair services in Ontario, specifically serving the Greater Toronto Area. With over 20 years of experience, this business excels in providing quality solutions for both residential and commercial projects. The skilled team ensures that every job, whether big or small, is handled with professionalism and reliability.</p> <p>Located at 110 Pintail Crescent, HMA Carpet has built a strong reputation in the local community. The company employs in-house installers who bring expertise and dedication to each project. This focus on quality has led to numerous satisfied customers throughout cities like Mississauga, Brampton, Vaughan, North York, Oshawa, Markham, and Richmond Hill. The commitment to customer service and high standards has made HMA Carpet a trusted name in carpet installation.</p> <p>HMA Carpet not only provides installation services but also caters to carpet sales and repair needs. The extensive experience in the industry allows for tailored solutions that meet specific customer requirements. This business thrives on delivering excellent results and ensuring lasting satisfaction. The combination of skilled labor and quality materials sets HMA Carpet apart in the competitive market.</p> <p>Explore the professional carpet services offered by HMA Carpet, including sales, installation, and repair. The company’s strengths lie in its experience, reliability, and commitment to customer satisfaction. Connect with HMA Carpet today for exceptional service in Ontario.</p>',
  '110 Pintail Crescent',
  'Canada',
  'ON',
  NULL,
  'M3A 2Y7',
  'e.l.v.i.s.-treat-me-nice@hotmail.com',
  'canada/home-services/hma-carpet',
  'ChIJo_qXeufT1IkRmS35X32hqVQ',
  43.7601742,
  -79.3181588,
  '16478671938',
  'https://www.kwikr.ca/pictures/profile/pimage-213.jpg',
  'Flooring=>Carpet Installation',
  'Pay-as-you-go',
  229,
  'https://hmacarpet.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'AAA Carpet Repair',
  '<p>AAA Carpet Repair serves the Greater Vancouver area, providing expert carpet installation and repair services for over 26 years. This local business specializes in a range of carpet issues, ensuring quality solutions for residents in Vancouver, British Columbia. Customers can expect free quotes and guaranteed repairs for various carpet problems, including restretching wrinkled carpets, fixing torn seams, addressing frayed areas, removing non-removable stains, and repairing burned carpets.</p> <p>The team at AAA Carpet Repair possesses extensive knowledge and experience in the carpet repair industry. Their commitment to customer satisfaction drives them to deliver reliable and efficient services. With a focus on quality, this business has built a strong reputation among local residents. The technicians utilize advanced techniques and tools to ensure every repair meets high standards. Each project receives personalized attention, ensuring tailored solutions that fit specific needs.</p> <p>AAA Carpet Repair continues to be a trusted choice for carpet repair in the Vancouver area. Their dedication to excellence and customer care sets them apart in the local market. With a long history of successful repairs, this business remains a go-to for residents facing carpet issues. Reach out to AAA Carpet Repair at 1850 Lorne St, Vancouver, British Columbia, for professional carpet repair services today.</p>',
  '1850 Lorne St',
  'Canada',
  'BC',
  'Vancouver',
  'V5T 1C9',
  'info@climaticgroup.com',
  'canada/vancouver/home-services/aaa-carpet-repair',
  'ChIJbYqWkWBxhlQRoEPifZOIfk4',
  49.26827,
  -123.099825,
  '16046717847',
  'https://www.kwikr.ca/pictures/profile/pimage-212.jpg',
  'Flooring=>Carpet Installation',
  'Pay-as-you-go',
  228,
  'https://www.aaacarpetrepair.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Collingwood Christmas Decor',
  '<p>Collingwood Christmas Decor, located at 496895 Grey County Rd 2 in Thornbury, Ontario, specializes in landscape lighting design and holiday decorations. Established in 1986, this company has become a leader in the holiday lighting industry across North America. Recognized for excellence, it has earned spots on the 2021 Franchise Times Top 400 and the 2022 Entrepreneur Top 500 lists. With operations in over 250 markets, Collingwood Christmas Decor offers comprehensive decorating services that include display design, installation, maintenance, and removal of holiday lighting and decorations.</p><p>The team at Collingwood Christmas Decor brings a wealth of experience and expertise to every project. Clients appreciate the meticulous approach to design and the quality of materials used. This commitment to excellence ensures that each display enhances the beauty of homes and businesses during the festive season. The company’s ability to adapt to various styles and preferences sets it apart from competitors. Seasonal decorations are not just installations; they are crafted experiences that create memorable moments for families and communities.</p><p>With a proven track record and numerous accolades, Collingwood Christmas Decor continues to lead in the landscape lighting design sector. Its dedication to customer satisfaction and high-quality service makes it a trusted choice for holiday decorating needs. Reach out to Collingwood Christmas Decor in Thornbury for expert landscape lighting design and holiday decoration services.</p>',
  '496895 Grey County Rd 2',
  'Canada',
  'ON',
  'Thornbury',
  'N0H 2P0',
  'info@signaturecleaning.ca',
  'canada/thornbury/home-services/collingwood-christmas-decor',
  'ChIJ7ZBBHKl1KogRRwTKNr_Duak',
  44.549213,
  -80.433391,
  '17054431536',
  NULL,
  'Electrical=>Outdoor Lighting',
  'Pay-as-you-go',
  227,
  'https://www.christmasdecor.net/canadian-decorators-2/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'NY Landscape & Outdoor Lighting Services',
  '<p>NY Landscape & Outdoor Lighting Services specializes in enhancing outdoor spaces in Richmond Hill, Ontario. This landscape lighting designer focuses on transforming homes with innovative lighting solutions that improve both aesthetics and safety. With a commitment to quality, the company provides a range of outdoor lighting fixtures that elevate curb appeal and create inviting atmospheres.</p> <p>Richmond Hill residents benefit from expert guidance in selecting the right fixtures for their properties. NY Landscape & Outdoor Lighting Services offers tailored solutions that meet individual needs and preferences. The team possesses extensive knowledge about the latest trends in landscape lighting, ensuring clients receive the most effective designs. Safety is a priority, as well-designed outdoor lighting deters intruders and enhances visibility during nighttime hours.</p> <p>The company has gained recognition for its dedication to customer satisfaction and high-quality installations. NY Landscape & Outdoor Lighting Services understands the importance of creating a welcoming outdoor environment, making it an essential partner for homeowners seeking to improve their properties. Each project reflects the unique style and vision of the client while adhering to the highest standards of craftsmanship.</p> <p>Explore the transformative power of landscape lighting with NY Landscape & Outdoor Lighting Services. Their expertise, commitment to quality, and customer-focused approach make them a trusted choice in Richmond Hill. Connect with NY Landscape & Outdoor Lighting Services today to enhance your outdoor space.</p>',
  '106 Betony Dr',
  'Canada',
  'ON',
  'Richmond Hill',
  'L4E 0P5',
  'info@doubleclean.ca',
  'canada/richmond-hill/home-services/ny-landscape-outdoor-lighting-services',
  'ChIJ_-RGjRDXKogRUbsF0jJiS4U',
  43.9382235,
  -79.4775293,
  '16478786814',
  NULL,
  'Electrical=>Outdoor Lighting',
  'Pay-as-you-go',
  226,
  'https://nyservices.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Liteform International Inc',
  '<p>Liteform International Inc offers a wide range of lighting solutions in Mississauga, Ontario. This local lighting store specializes in high-quality fixtures, providing both residential and commercial lighting options. The business prides itself on exceptional customer service and a knowledgeable staff ready to assist with lighting design and selection. Liteform International Inc has become a trusted name in the community for its commitment to quality and innovation.</p><p>Located at 261 Ambassador Dr, Liteform International Inc serves the greater Mississauga area with an extensive inventory of modern and traditional lighting products. The store features a variety of styles, including chandeliers, wall sconces, and outdoor lighting. Customers appreciate the diverse selection and competitive pricing, ensuring that there is something for every budget and taste. The knowledgeable team offers personalized consultations, helping clients find the perfect lighting solutions for their specific needs.</p><p>The success of Liteform International Inc is evident through its loyal customer base and positive reviews. The store''s focus on customer satisfaction and high-quality products has established it as a leader in the local lighting market. With an emphasis on energy-efficient options, the business supports environmentally friendly choices that contribute to sustainability.</p><p>Liteform International Inc continues to provide exceptional lighting solutions in Mississauga, Ontario. The combination of extensive product offerings and expert guidance makes this store a go-to destination for lighting needs. Visit Liteform International Inc today to explore the lighting possibilities available in Mississauga.</p>',
  '261 Ambassador Dr',
  'Canada',
  'ON',
  'Mississauga',
  'L5T 2J2',
  'ritewayfiltration@gmail.com',
  'canada/mississauga/home-services/liteform-international-inc',
  'ChIJK3ID9XY_K4gRVGwooX_gDhY',
  43.6440127,
  -79.6917239,
  '19055642090',
  NULL,
  'Electrical=>Lighting Installation',
  'Pay-as-you-go',
  225,
  'http://www.liteformlighting.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Au Courant Luminaires',
  '<p>Au Courant Luminaires, located at 8455 Decarie Blvd in Mount Royal, Quebec, offers a comprehensive selection of modern lighting fixtures. This lighting store specializes in designer pieces, including pendants, lamps, sconces, and linear lights. With a commitment to quality and style, Au Courant Luminaires serves both residential and commercial clients, providing expert guidance in illuminating spaces effectively.</p> <p>The showroom features an extensive range of contemporary designs that cater to diverse tastes and preferences. Customers can explore various styles, ensuring that every lighting solution meets their specific needs. The knowledgeable staff assists clients in selecting the perfect fixtures that not only enhance aesthetics but also improve functionality. With years of experience in the industry, Au Courant Luminaires has established a reputation for excellence and customer satisfaction.</p> <p>This lighting store stands out in the Mount Royal area for its dedication to providing high-quality products and exceptional service. Clients appreciate the personalized attention and expert advice that help them make informed decisions. The selection of modern lighting options allows for creativity and innovation in home and business design.</p> <p>Au Courant Luminaires delivers a wide array of lighting solutions, emphasizing quality and style. The combination of expert assistance and a diverse product range ensures customer satisfaction. Visit Au Courant Luminaires in Mount Royal for innovative lighting solutions that brighten any space. Connect with this local business today.</p>',
  '8455 Decarie Blvd',
  'Canada',
  'QC',
  'Mount Royal',
  'H4P 2J2',
  'etetreault@rondeaunet.ca',
  'canada/mount-royal/home-services/au-courant-luminaires',
  'ChIJS6gVkDIYyUwR_qXLRn638i8',
  45.5010694,
  -73.6625338,
  '15147332050',
  NULL,
  'Electrical=>Lighting Installation',
  'Pay-as-you-go',
  224,
  'http://aucourantlighting.com/',
  NULL,
  NULL,
  NULL,
  NULL
);
