INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'EverGreen City Floors',
  '<p>EverGreen City Floors operates as a leading flooring contractor in Burnaby, British Columbia, specializing in the supply and installation of a wide range of flooring options. This local business offers solid and engineered hardwood, laminate, cork, vinyl, tile, and marble flooring installation. Additionally, EverGreen City Floors provides hardwood flooring refinishing services for both residential and commercial projects, ensuring high-quality results tailored to client needs.</p> <p>The company prides itself on its extensive selection of flooring materials and professional installation services. With a commitment to quality, EverGreen City Floors guarantees durable and aesthetically pleasing flooring solutions. The team consists of skilled professionals who understand the intricacies of flooring installation and refinishing, ensuring that every project meets the highest standards. Their experience covers a variety of styles and preferences, making them a versatile choice for any flooring project.</p> <p>EverGreen City Floors is known for its customer-centric approach, focusing on delivering exceptional service and satisfaction. The business has established a solid reputation in the Burnaby area, thanks to its attention to detail and commitment to using premium materials. Clients can expect timely project completion and expert guidance throughout the process, making flooring decisions easier.</p> <p>This flooring contractor excels in providing comprehensive flooring solutions that enhance both residential and commercial spaces. With a strong focus on quality and customer satisfaction, EverGreen City Floors remains a trusted choice in Burnaby. Visit EverGreen City Floors at 6544 Silver Ave #301 for flooring needs today.</p>',
  '6544 Silver Ave #301',
  'Canada',
  'BC',
  'Burnaby',
  'V5H 2Y4',
  'info@planchertendancerivesud.ca',
  'canada/burnaby/home-services/evergreen-city-floors',
  'ChIJrWp7AV52hlQRR9ozh_zi5ZM',
  49.223581,
  -123.0070552,
  '17787071730',
  'https://www.kwikr.ca/pictures/profile/pimage-307.jpg',
  'Flooring',
  'Growth Plan',
  323,
  'http://evergreenflooring.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Abba Floorcoverings',
  '<p>Abba Floorcoverings, located at 4376 Boban Dr in Nanaimo, British Columbia, specializes in a wide range of flooring solutions. This flooring store offers hardwood, laminate, carpet, and vinyl options to meet diverse customer needs. Abba Floorcoverings prides itself on providing high-quality products and exceptional service, ensuring every project is completed to satisfaction. The business has built a solid reputation in the local community for its reliability and expertise.</p> <p>With years of experience, Abba Floorcoverings understands the intricacies of flooring installation and maintenance. The knowledgeable staff assists customers in selecting the right materials for their homes or businesses. Each flooring option is carefully curated to provide durability and aesthetic appeal. The store emphasizes the importance of quality, ensuring that every product meets industry standards.</p> <p>Abba Floorcoverings also offers professional installation services, guaranteeing a seamless process from selection to completion. The team is dedicated to customer satisfaction, addressing any concerns promptly. This commitment to service has earned the business numerous positive reviews from satisfied clients. The store’s location in Nanaimo makes it easily accessible for local residents seeking flooring solutions.</p> <p>Abba Floorcoverings delivers a comprehensive range of flooring products and services, showcasing a commitment to quality and customer care. Experience the difference in flooring solutions by visiting Abba Floorcoverings in Nanaimo, British Columbia.</p>',
  '4376 Boban Dr',
  'Canada',
  'BC',
  'Nanaimo',
  'V9T 6A7',
  'info@planchermarceletfils.com',
  'canada/nanaimo/home-services/abba-floorcoverings',
  'ChIJyZcY5wqiiFQR_yazJvIN5TQ',
  49.2091553,
  -124.0373229,
  '12507585588',
  NULL,
  'Flooring=>Vinyl Flooring',
  'Pay-as-you-go',
  322,
  'http://abbafloorcoverings.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Moore Flooring Design',
  '<p>Moore Flooring Design, located at 1525 Hyde Park Rd in London, Ontario, provides a comprehensive range of flooring solutions. Established in 1989, this family-owned business specializes in solid, engineered, and laminate hardwood, as well as carpet, ceramic tile, luxury vinyl tile, and sheet vinyl. The commitment to quality and customer satisfaction drives every aspect of the operation.</p><p>The showroom operates Monday to Friday from 9 am to 6 pm, with Saturday appointments available from 10 am to 3 pm. This flexibility ensures that customers can find the perfect flooring solution at their convenience. The company prioritizes safety with zero-contact interactions during delivery and installation, reflecting a dedication to customer well-being.</p><p>Moore Flooring Design excels in transforming spaces with a focus on quality and craftsmanship. The expert team guides customers through the selection process, ensuring that every choice aligns with individual style and needs. With a rich history in the flooring industry, the business has built a reputation for reliability and excellence. Customer interactions are handled with professionalism, enhancing the overall experience.</p><p>Offering a wide array of flooring options and a commitment to service excellence, Moore Flooring Design continues to meet the needs of the London community. Customers can expect personalized service and high-quality installations. Visit Moore Flooring Design in London, Ontario, to explore flooring solutions today.</p>',
  '1525 Hyde Park Rd',
  'Canada',
  'ON',
  'London',
  'N6H 5L4',
  'info@yfcustomflooring.com',
  'canada/london/home-services/moore-flooring-design',
  'ChIJdYEYDQPwLogRWBggkZKMgZI',
  42.9974521,
  -81.3310116,
  '15196015275',
  NULL,
  'Flooring=>Vinyl Flooring',
  'Pay-as-you-go',
  321,
  'https://www.mooreflooringdesign.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Vintage Hardwood Flooring',
  '<p>Vintage Hardwood Flooring operates as a premier flooring store located at 114 Chain Lake Dr, Beechville, Nova Scotia. This business specializes in high-quality hardwood flooring options, catering to both residential and commercial clients. With a commitment to exceptional service and craftsmanship, Vintage Hardwood Flooring has built a strong reputation in the local community.</p><p>The company offers a diverse range of flooring products, including solid hardwood, engineered wood, and various finishes. Each product is sourced from reliable suppliers, ensuring durability and aesthetic appeal. Customers appreciate the knowledgeable staff, who provide expert guidance throughout the selection process. The showroom features a wide array of samples, allowing clients to visualize how different styles will complement their spaces.</p><p>Vintage Hardwood Flooring also emphasizes installation services. Skilled professionals ensure each floor is installed correctly, enhancing the longevity and performance of the flooring. The team is dedicated to meeting customer needs, providing tailored solutions that fit specific requirements and budgets.</p><p>With a focus on quality and customer satisfaction, Vintage Hardwood Flooring continues to serve the Beechville area effectively. The combination of quality products and expert installation makes this flooring store a reliable choice for flooring solutions. Connect with Vintage Hardwood Flooring today to explore flooring options that elevate any space in Beechville, Nova Scotia.</p>',
  '114 Chain Lake Dr',
  'Canada',
  'NS',
  'Beechville',
  'B3S 1B1',
  'info@boisettendance.com',
  'canada/beechville/home-services/vintage-hardwood-flooring',
  'ChIJJ7at4dIhWksRiz6K7CmDLM4',
  44.6370917,
  -63.6636412,
  '19024505727',
  NULL,
  'Flooring=>Vinyl Flooring',
  'Pay-as-you-go',
  320,
  'http://www.vintageflooring.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Carastan Carpet & Flooring- Floor Materials',
  '<p>Carastan Carpet & Flooring provides a comprehensive range of flooring solutions in Ottawa, Ontario. With 45 years of experience, this flooring store specializes in carpet, hardwood, laminates, vinyl, cork, and marmoleum. The business prides itself on direct partnerships with the world''s finest mills, ensuring top-quality products for every customer. A free shop-at-home service enhances convenience, allowing clients to explore options in the comfort of their own spaces.</p> <p>The extensive selection available at Carastan Carpet & Flooring caters to diverse tastes and needs. From luxurious carpets to durable vinyl, each product meets high standards of quality and performance. The expert sales team offers personalized assistance, guiding customers through the decision-making process. Installation services are also available, ensuring a seamless transition from selection to setup.</p> <p>Carastan Carpet & Flooring has established a strong reputation in the Ottawa area, thanks to its commitment to customer satisfaction and quality craftsmanship. The business is recognized for its reliable service and knowledgeable staff, who are always ready to assist clients in finding the perfect flooring solution. With a focus on quality and convenience, this flooring store continues to meet the needs of homeowners and businesses alike.</p> <p>Explore the wide range of flooring options available at Carastan Carpet & Flooring. With a rich history and dedication to excellence, the business remains a trusted choice for flooring solutions in Ottawa. Visit the store at 2181 Carling Ave to discover the perfect flooring today.</p>',
  '2181 Carling Ave',
  'Canada',
  'ON',
  'Ottawa',
  'K2B 7E8',
  'info@darmaga.com',
  'canada/ottawa/home-services/carastan-carpet-flooring-floor-materials',
  'ChIJfa2ccMsGzkwRXXyJYaTxUfk',
  45.3700968,
  -75.7714737,
  '16137296663',
  NULL,
  'Flooring=>Vinyl Flooring',
  'Pay-as-you-go',
  319,
  'http://carastan.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Rick''s Carpet',
  '<p>Rick''s Carpet, located at 25 Main St W in Norwich, Ontario, has been a trusted flooring store since 1976. This local business specializes in a wide range of flooring solutions, including carpet, vinyl, solid and engineered hardwoods, laminate, area rugs, and luxury tiles. With decades of experience, Rick''s Carpet has established a reputation for quality products and exceptional customer service.</p> <p>The extensive selection of flooring options caters to various styles and preferences, ensuring that every customer finds the perfect fit for their home or business. Rick''s Carpet provides expert guidance throughout the selection process, helping customers make informed decisions based on their needs and budget. The knowledgeable staff understands the importance of durable and aesthetically pleasing flooring, offering insights into the latest trends and materials.</p> <p>Rick''s Carpet has earned its place in the community by consistently delivering value and reliability. The commitment to customer satisfaction is evident in the positive feedback from local residents. This flooring store prioritizes quality and service, making it a go-to destination for flooring solutions in Norwich.</p> <p>With a comprehensive range of products and a strong community presence, Rick''s Carpet continues to serve the flooring needs of Norwich and surrounding areas. Connect with Rick''s Carpet today for quality flooring solutions in Ontario.</p>',
  '25 Main St W',
  'Canada',
  'ON',
  'Norwich',
  'N0J 1P0',
  'ppdusseaultexcavation@bellnet.ca',
  'canada/norwich/home-services/rick-s-carpet',
  'ChIJZ1jeMYObLIgR_57pJ7Yh2L0',
  42.9873482,
  -80.5983638,
  '15198635300',
  NULL,
  'Flooring=>Vinyl Flooring',
  'Pay-as-you-go',
  318,
  'https://www.rickscarpet.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'End Of The Roll Flooring Centres - Kamloops',
  '<p>End Of The Roll Flooring Centres in Kamloops, British Columbia, provides an extensive range of flooring options for residential and commercial needs. This flooring store features a wide selection of brand name products, including carpet, area rugs, luxury vinyl, laminate, tile and stone, decking, athletic flooring, and solid and engineered hardwood. Customers can find everything necessary for installation and maintenance, ensuring a comprehensive shopping experience.</p> <p>The knowledgeable staff at End Of The Roll Flooring Centres offer expert guidance to assist customers in selecting the perfect flooring solution. With a focus on customer satisfaction, the team addresses inquiries related to installation, collaborating with trusted partners to ensure quality service. The store''s commitment to excellence is evident in its vast inventory and dedication to helping customers achieve their desired aesthetic.</p> <p>End Of The Roll Flooring Centres has established a reputation for providing immediate access to high-quality flooring products. The store’s strategic location in Kamloops makes it a convenient choice for local residents seeking reliable flooring solutions. The emphasis on customer service and a wide variety of options positions the store as a leader in the flooring market.</p> <p>End Of The Roll Flooring Centres excels in offering a diverse selection of flooring products, knowledgeable staff, and reliable installation services. This business prioritizes customer experience and satisfaction. Visit End Of The Roll Flooring Centres at 962A Laval Crescent in Kamloops to explore the impressive range of flooring solutions available.</p>',
  '962A Laval Crescent',
  'Canada',
  'BC',
  'Kamloops',
  'V2C 5P5',
  'info@ecoevolutioninc.com',
  'canada/kamloops/home-services/end-of-the-roll-flooring-centres-kamloops',
  'ChIJj3mqcGYsflMRoYILySoPYB4',
  50.6605563,
  -120.3654555,
  '12503721008',
  NULL,
  'Flooring=>Vinyl Flooring',
  'Pay-as-you-go',
  317,
  'https://endoftheroll.com/?location=kamloops',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Westvalley Carpet & Flooring',
  '<p>Westvalley Carpet & Flooring operates as a premier flooring store in Calgary, Alberta, offering a vast range of flooring solutions for both residential and commercial clients. With three locations across North and South Calgary, the business boasts over 90 years of combined experience in design and floor coverings. The team provides free estimates and a convenient shop-at-home service, ensuring customers can explore options from the comfort of their own space.</p><p>This flooring store specializes in a diverse inventory, allowing clients to express their personal style through various materials and designs. Westvalley Carpet & Flooring stands out as Calgary''s exclusive Mohawk Floorscapes Dealer, reflecting a commitment to quality and innovation in flooring solutions. The recent accolade of Retailer of the Year for Canada further emphasizes the company’s dedication to excellence and customer satisfaction.</p><p>Whether renovating a home or outfitting a business, Westvalley Carpet & Flooring delivers tailored solutions to meet specific needs. The knowledgeable staff guides clients through the selection process, ensuring informed decisions are made. The combination of extensive experience and a comprehensive product range positions this flooring store as a leader in the Calgary area.</p><p>Westvalley Carpet & Flooring provides a robust selection of flooring options, expert guidance, and exceptional customer service. Experience the difference in flooring solutions by visiting the store located at 5155 130 Ave SE #411, Calgary, Alberta. Connect with Westvalley Carpet & Flooring today for a consultation.</p>',
  '5155 130 Ave SE #411',
  'Canada',
  'AB',
  'Calgary',
  'T2Z 0N3',
  'reservations@captremblant.com',
  'canada/calgary/home-services/westvalley-carpet-flooring',
  'ChIJT_NVtIN3cVMRKfvLKpGSwHY',
  50.9310135,
  -113.9598567,
  '15874715047',
  NULL,
  'Flooring=>Vinyl Flooring',
  'Pay-as-you-go',
  316,
  'https://www.westvalleyflooring.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Carpets More For Less',
  '<p>Carpets More For Less, located at 670 Nairn Ave in Winnipeg, Manitoba, offers a comprehensive selection of flooring solutions. This flooring store specializes in quality brand name products, ensuring customers have access to one of the largest inventories in the area. The knowledgeable staff provides expert guidance, helping customers make informed choices that fit their needs and budget.</p> <p>The store features a fully stocked warehouse, showcasing a wide range of carpets, hardwood, and laminate flooring options. Each visit promises an informative experience, with staff ready to present various choices that deliver top value. Carpets More For Less prioritizes customer satisfaction through personalized service and extensive product knowledge. The store''s commitment to quality and affordability sets it apart from competitors in Winnipeg.</p> <p>Customers can explore an impressive array of flooring styles and materials, all designed to enhance any space. The store''s inviting atmosphere encourages shoppers to take their time and find the perfect flooring solution. Carpets More For Less combines expertise with a vast selection to ensure every customer leaves satisfied.</p> <p>This flooring store excels in providing quality products and exceptional service. With a focus on value and customer experience, Carpets More For Less remains a top choice for flooring in Winnipeg. Visit the store to discover the best flooring options available in Manitoba.</p>',
  '670 Nairn Ave',
  'Canada',
  'MB',
  'Winnipeg',
  'R2L 0X5',
  'info@planchersmnr.com',
  'canada/winnipeg/home-services/carpets-more-for-less',
  'ChIJlTnGet5w6lIRY89uDT1S5yQ',
  49.9022523,
  -97.093396,
  '12042313337',
  NULL,
  'Flooring=>Vinyl Flooring',
  'Pay-as-you-go',
  315,
  'https://carpetsandmoreforless.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'End Of The Roll Flooring Centres - Kelowna',
  '<p>End Of The Roll Flooring Centres, located at 485 Banks Rd in Kelowna, British Columbia, offers an extensive range of flooring solutions. This flooring store features a large selection of brand name products available for immediate purchase. Customers can find options including carpet, area rugs, luxury vinyl, laminate, tile and stone, decking, athletic flooring, and both solid and engineered hardwood. The store also provides all necessary materials for installation and maintenance.</p> <p>End Of The Roll Flooring Centres emphasizes customer satisfaction and convenience. The knowledgeable staff assists shoppers in selecting the ideal flooring for their homes. Their expertise extends to installation inquiries, facilitated through trusted installation partners. This commitment to service enhances the shopping experience, making it efficient and enjoyable.</p> <p>The store''s reputation in Kelowna is built on quality products and exceptional customer service. With a focus on providing immediate solutions, customers can leave with their flooring the same day. The diverse inventory caters to various styles and preferences, ensuring that every homeowner finds the perfect match for their space.</p> <p>End Of The Roll Flooring Centres excels in offering a comprehensive selection of flooring options and installation support. Their dedication to customer experience remains a priority. Visit End Of The Roll Flooring Centres in Kelowna for all flooring needs and experience the quality and service firsthand.</p>',
  '485 Banks Rd',
  'Canada',
  'BC',
  'Kelowna',
  'V1X 6A2',
  'robert@rojservices.com',
  'canada/kelowna/home-services/end-of-the-roll-flooring-centres-kelowna',
  'ChIJby1DbNqMfVMRjuUQSPsdTtU',
  49.8837441,
  -119.42147,
  '12508682401',
  NULL,
  'Flooring=>Vinyl Flooring',
  'Pay-as-you-go',
  314,
  'https://endoftheroll.com/?location=kelowna',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Fabbri Tile & Carpet Inc.',
  '<p>Fabbri Tile & Carpet Inc. operates as a premier flooring store located in Point Edward, Ontario. This business offers a diverse selection of high-quality flooring products alongside expert installation services. Specializing in various materials, including carpet, luxury vinyl, hardwood, laminate, and ceramic and porcelain tiles, Fabbri Tile caters to both residential and commercial clients.</p> <p>The commitment to quality is evident in every aspect of Fabbri Tile''s operations. The professional team focuses on precise installation, which not only enhances the aesthetic appeal of flooring but also contributes to its longevity. Each flooring option is chosen with care, ensuring that customers have access to durable and stylish products suitable for any space. Fabbri Tile maintains a strong reputation for exceptional customer service, making the flooring selection process smooth and enjoyable.</p><p>Fabbri Tile & Carpet Inc. continues to serve the Point Edward area with dedication and expertise. The extensive range of flooring options allows clients to find the perfect fit for their needs. With a focus on quality and customer satisfaction, Fabbri Tile remains a trusted choice for flooring solutions. Explore the vast selection of flooring products and experience the difference in service. Visit Fabbri Tile at 520 Helena St, Point Edward, Ontario, to engage with their services today.</p>',
  '520 Helena St',
  'Canada',
  'ON',
  'Point Edward',
  'N7V 1R9',
  'mike@canadawestwood.ca',
  'canada/point-edward/home-services/fabbri-tile-carpet-inc',
  'ChIJ5ewQTqOcJYgR4oH1WvKnQ8A',
  42.9919361,
  -82.4068836,
  '15193377589',
  NULL,
  'Flooring=>Vinyl Flooring',
  'Pay-as-you-go',
  313,
  'https://www.fabbritile.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Prosol inc.',
  '<p>Prosol Inc. operates as a leading flooring store located at 12231 Bridgeport Rd Unit 140 in Richmond, British Columbia. This business specializes in a wide range of flooring solutions, including hardwood, laminate, vinyl, and carpet. Prosol Inc. has built a reputation for quality products and exceptional customer service, catering to both residential and commercial clients in the area.</p> <p>The extensive selection of flooring materials ensures that customers find options that match their style and budget. Prosol Inc. sources products from reputable manufacturers, guaranteeing durability and aesthetic appeal. The knowledgeable staff assists clients in making informed decisions, providing insights on the best flooring choices for various applications.</p> <p>Prosol Inc. has received positive feedback for its commitment to quality and service. The company’s expertise in flooring installation further enhances its offerings, ensuring that projects are completed efficiently and to high standards. Customers appreciate the attention to detail and the professional approach taken by the team.</p> <p>This flooring store in Richmond, British Columbia, combines a vast selection of products with expert guidance and installation services. Prosol Inc. continues to meet the needs of the community, ensuring satisfaction with every project. Reach out to Prosol Inc. for reliable flooring solutions in Richmond, British Columbia.</p>',
  '12231 Bridgeport Rd Unit 140',
  'Canada',
  'BC',
  'Richmond',
  'V6V 2J5',
  'info@supremeflooring.ca',
  'canada/richmond/home-services/prosol-inc',
  'ChIJ4Xi3saF1hlQRPMWFchIvldI',
  49.1923058,
  -123.0881377,
  '16042701314',
  NULL,
  'Flooring=>Vinyl Flooring',
  'Pay-as-you-go',
  312,
  'https://www.prosol.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Installs Plus Flooring',
  '<p>Installs Plus Flooring serves Georgetown, Ontario, providing comprehensive flooring solutions for both residential and commercial needs. This flooring store specializes in a wide range of products, including custom area rugs, vinyl plank LVT, carpet, and VCT. The business stands out with its convenient shop-at-home service, bringing samples and expertise directly to customers'' homes across the Greater Toronto Area.</p> <p>Installs Plus Flooring offers professional sales and installation services, ensuring a seamless experience from selection to installation. Customers benefit from free estimates within the GTA and the assurance of no deposits required. The company emphasizes quality and reliability, being fully insured and WSIB compliant. Special pricing on Vinyl Plank SPC adds value to the already competitive offerings.</p> <p>Engagement with the community is evident through active social media presence, particularly on Instagram, where potential customers can explore more about the products and services available. The focus on customer satisfaction and high-quality flooring options positions Installs Plus Flooring as a trustworthy choice for flooring needs in the area.</p> <p>With a commitment to excellence and a wide range of flooring solutions, Installs Plus Flooring meets the diverse needs of its customers. Explore the extensive offerings and professional services available. Visit Installs Plus Flooring at 55 W Branch Dr, Georgetown, Ontario, for all flooring needs.</p>',
  '55 W Branch Dr',
  'Canada',
  'ON',
  'Georgetown',
  'L7G 0J7',
  'info@tiptopflooring.ca',
  'canada/georgetown/home-services/installs-plus-flooring',
  'ChIJOwUDduE-sgQR9nERV5t3wtg',
  43.6366229,
  -79.9040996,
  '14165746306',
  NULL,
  'Flooring=>Vinyl Flooring',
  'Pay-as-you-go',
  311,
  'http://www.installsplus.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Dimensions: Showroom @443#4, Warehouse @445#1A',
  '<p>Dimensions Showroom & Warehouse located at 443 Eastchester Ave. E. #4 and 445 Eastchester Ave E #1A in St. Catharines, Ontario, offers a comprehensive range of flooring solutions. This local flooring store specializes in consulting, sales, and service, catering to both residential and commercial clients. With a focus on quality and customer satisfaction, Dimensions ensures a seamless experience from selection to installation.</p><p>The business excels in providing various flooring options, including hardwood, laminate, vinyl, and tile. Dimensions also offers convenient services such as pickup, delivery, and shipping to enhance customer accessibility. The knowledgeable staff provides expert advice, helping customers make informed decisions tailored to their specific needs. This commitment to service has earned the business a loyal customer base in St. Catharines.</p><p>Dimensions Showroom & Warehouse maintains a strong reputation for reliability and efficiency. The strategic location in St. Catharines allows for easy access to a diverse clientele. The combination of a well-stocked showroom and a fully equipped warehouse supports quick turnaround times for orders. This operational efficiency contributes to the overall customer experience, ensuring satisfaction with every purchase.</p><p>Dimensions Showroom & Warehouse offers a wide array of flooring solutions, exceptional service, and a strong community presence in St. Catharines. Engage with this local business for expert flooring services and quality products in Ontario.</p>',
  'Warehouse @445, Showroom @443 Eastchester Ave. E. #4, Eastchester Ave E #1A',
  'Canada',
  'ON',
  'St. Catharines',
  'L2M 6S2',
  'walnutgrovehardwood@gmail.com',
  'canada/st-catharines/home-services/dimensions-showroom-443-4-warehouse-445-1a',
  'ChIJrXqpkGtR04kRkAzmHa6KqB8',
  43.1688798,
  -79.2071006,
  '19057041664',
  NULL,
  'Flooring=>Vinyl Flooring',
  'Pay-as-you-go',
  310,
  'http://www.carpetone.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Prosol inc.',
  '<p>Prosol Inc. operates as a premier flooring store located in Windsor, Ontario. This business specializes in a wide range of flooring solutions, including hardwood, laminate, vinyl, and tile options. Prosol Inc. has built a reputation for quality products and exceptional customer service, catering to both residential and commercial clients in the local area. With years of experience in the flooring industry, this store provides expert guidance and installation services.</p><p>The team at Prosol Inc. understands the importance of choosing the right flooring. They offer personalized consultations to help clients select materials that match their style and budget. The store showcases various flooring options, ensuring customers can find the perfect fit for their needs. Prosol Inc. also emphasizes durability and sustainability in its product offerings, aligning with modern consumer preferences.</p><p>Prosol Inc. has garnered positive feedback for its commitment to quality and customer satisfaction. The knowledgeable staff assists clients throughout the selection and installation process, ensuring a seamless experience. The business has become a trusted choice for flooring solutions in Windsor, Ontario, thanks to its dedication to excellence.</p><p>Prosol Inc. provides a comprehensive range of flooring options and expert services, making it a go-to destination for flooring needs. The combination of quality products and exceptional customer service ensures a positive experience. Visit Prosol Inc. at 4445 County Rd 42 in Windsor for reliable flooring solutions.</p>',
  '4445 County Rd 42',
  'Canada',
  'ON',
  'Windsor',
  'N9A 6J3',
  'maresflooring@yahoo.com',
  'canada/windsor/home-services/prosol-inc',
  'ChIJU9pdwNIuO4gRnrpR9cjumfs',
  42.2667208,
  -82.9465214,
  '15199461255',
  NULL,
  'Flooring=>Vinyl Flooring',
  'Pay-as-you-go',
  309,
  'http://www.prosol.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Uptown Decor & Finishes Ltd.',
  '<p>Uptown Decor & Finishes Ltd. serves the Parry Sound area of Ontario with a comprehensive selection of flooring options. This flooring store specializes in hardwood, laminate, vinyl, and tile solutions, catering to both residential and commercial needs. With a commitment to quality and customer satisfaction, Uptown Decor & Finishes Ltd. has built a reputation for reliability and expertise in the flooring industry.</p><p>The store offers a wide range of products to suit various styles and budgets. Customers can find expert advice on selecting the right materials for their projects. The knowledgeable staff provides personalized service, ensuring that every client receives the attention they deserve. Uptown Decor & Finishes Ltd. also emphasizes sustainable practices by offering eco-friendly flooring options that contribute to healthier living spaces.</p><p>Located at 75 James St, the company showcases an impressive showroom where customers can view flooring samples and visualize their choices in real-life settings. This hands-on approach enhances the shopping experience, allowing individuals to make informed decisions. Uptown Decor & Finishes Ltd. continuously updates its inventory to keep up with the latest trends and technologies in flooring.</p><p>Uptown Decor & Finishes Ltd. excels in providing quality flooring solutions and exceptional customer service in Parry Sound. The store''s commitment to sustainability and variety makes it a go-to destination for flooring needs. Connect with Uptown Decor & Finishes Ltd. at their location in Parry Sound for expert flooring services.</p>',
  '75 James St',
  'Canada',
  'ON',
  'Parry Sound',
  'P2A 1T7',
  'admin@teamhardwoodfloors.ca',
  'canada/parry-sound/home-services/uptown-decor-finishes-ltd',
  'ChIJZd5qLJC7K00RtGEgzWhYMr4',
  45.3457535,
  -80.0333935,
  '17057468922',
  NULL,
  'Flooring=>Vinyl Flooring',
  'Pay-as-you-go',
  308,
  'https://uptowndecor.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Carrelage Design Plus',
  '<p>Carrelage Design Plus provides expert tile contracting services in Delson, Quebec. Specializing in both residential and commercial ceramic tile installation, this local business has built a reputation for quality workmanship and reliable service. Located at 125 Rue Delaware, the company caters to various client needs, ensuring each project meets high standards of durability and aesthetics.</p> <p>With years of experience in the tile contracting industry, Carrelage Design Plus showcases a commitment to customer satisfaction. The team possesses extensive knowledge of different tile materials and installation techniques, making them a trusted choice for diverse projects. Clients appreciate the attention to detail and the ability to bring design visions to life. Whether it’s a kitchen renovation or a commercial space upgrade, the expertise offered ensures optimal results.</p> <p>Carrelage Design Plus understands the importance of timely project completion and adheres to deadlines without compromising quality. The business has successfully completed numerous installations, earning positive feedback from the community. Their focus on creating functional and beautiful spaces resonates with homeowners and business owners alike.</p> <p>This tile contractor emphasizes professionalism and craftsmanship in every job. With a solid portfolio and a proven track record, Carrelage Design Plus stands ready to assist with any tile installation needs. Contact Carrelage Design Plus in Delson for exceptional tile contracting services today.</p>',
  '125 Rue Delaware',
  'Canada',
  'QC',
  'Delson',
  'J5B 2J5',
  'soumission@glclimatisationchauffage.ca',
  'canada/delson/home-services/carrelage-design-plus',
  'ChIJ8daTVs4NyUwRjkloG5sQgac',
  45.3773559,
  -73.5563698,
  '15148344382',
  NULL,
  'Flooring=>Tile Flooring',
  'Pay-as-you-go',
  307,
  'http://cdpceramique.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Céramique Pavia Inc',
  '<p>Céramique Pavia Inc, located at 8350 Rue Ernest-Ouimet in Montreal, Quebec, specializes in tile contracting. This business has built an impeccable reputation for the quality of its work, focusing on ceramic, marble, and granite installations. Céramique Pavia also excels in renovation projects, ensuring efficient service and timely execution.</p> <p>The company’s commitment to quality and customer satisfaction sets it apart in the competitive tile contracting industry. Céramique Pavia utilizes top-grade materials and skilled craftsmanship to deliver outstanding results. The team is knowledgeable about the latest trends and techniques in tile installation, which enhances the aesthetic appeal and durability of each project. Clients appreciate the attention to detail and the ability to meet tight deadlines without compromising quality.</p> <p>Céramique Pavia has successfully completed numerous projects across Montreal, earning praise from homeowners and businesses alike. The company’s focus on customer service ensures that clients receive personalized attention throughout the process. Feedback highlights the professionalism and expertise of the staff, reinforcing the trust clients place in Céramique Pavia for their tiling needs.</p> <p>Offering reliable and high-quality services in ceramic, marble, granite, and renovations, Céramique Pavia Inc remains a top choice for tile contracting in Montreal. The dedication to excellence and speed in execution makes this company a valuable partner for any project. Connect with Céramique Pavia Inc today in Montreal for exceptional tile contracting services.</p>',
  '8350 Rue Ernest-Ouimet',
  'Canada',
  'QC',
  'Montreal',
  'H1E 7H2',
  'sales@marbletopshop.ca',
  'canada/montreal/home-services/céramique-pavia-inc',
  'ChIJVVVJ-SoeyUwR6qf8GknB-kg',
  45.631537,
  -73.5804721,
  '15145078891',
  NULL,
  'Flooring=>Tile Flooring',
  'Pay-as-you-go',
  306,
  'http://www.ceramiquepavia.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Thiessen Trades',
  '<p>Thiessen Trades offers expert tile contracting services in Campbell River, British Columbia. With over 20 years of experience, Les Thiessen specializes in both commercial and residential projects, including new installations and renovations. The business is known for its professionalism and quality craftsmanship in tile installation and full bathroom renovations.</p><p>Les Thiessen brings significant expertise to every project, ensuring that clients receive top-notch service from start to finish. The extensive portfolio available showcases a variety of completed projects, reflecting the versatility and skill of the team. This allows potential customers to see the quality of work that Thiessen Trades consistently delivers.</p><p>Clients appreciate the attention to detail and commitment to excellence. Whether it’s a simple tile installation or a comprehensive bathroom renovation, Thiessen Trades handles every aspect with care and precision. The focus on customer satisfaction is evident in the positive feedback received from previous clients. Each project is approached with a clear understanding of the client''s needs and preferences, leading to successful outcomes.</p><p>Thiessen Trades is dedicated to providing reliable and efficient tile contracting services in Campbell River. The combination of experience, professionalism, and a commitment to quality makes this business a preferred choice for tile projects. Connect with Thiessen Trades today to discuss tile installation or bathroom renovation needs in Campbell River, British Columbia.</p>',
  '2420 Quinsam Rd',
  'Canada',
  'BC',
  'Campbell River',
  'V9W 4N2',
  'importdata-253@kwikr.ca',
  'canada/campbell-river/home-services/thiessen-trades',
  'ChIJ-3wzqWWvYlQR3Rss4wioa2g',
  50.0334036,
  -125.2844077,
  '16043789727',
  NULL,
  'Flooring=>Tile Flooring',
  'Pay-as-you-go',
  305,
  'https://www.thiessentrades.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Céramique DPlex Inc.',
  '<p>Céramique DPlex Inc. operates as a premier tile contractor located in Longueuil, Quebec. The company specializes in high-quality tiling services for both residential and commercial clients. With a strong commitment to customer satisfaction, Céramique DPlex has built a reputation for excellence in the local community. The business is dedicated to meeting the specific needs of Longueuil residents and businesses.</p><p>Céramique DPlex offers a range of services, including complete tile installations and repairs. The team possesses extensive knowledge and expertise in the tiling industry, ensuring that every project is executed with precision and care. The focus on quality and attention to detail sets this business apart from competitors. Clients receive transparent pricing, allowing for informed decisions without unexpected costs.</p><p>The local expertise of Céramique DPlex enhances its ability to deliver tailored solutions that suit individual preferences. The company prides itself on exceptional customer service, fostering lasting relationships with clients. Each project reflects the unique style and requirements of the customer, ensuring satisfaction every time.</p><p>Céramique DPlex Inc. provides reliable tiling services in Longueuil, emphasizing quality and client satisfaction. The combination of local knowledge, superior craftsmanship, and transparent pricing creates a trustworthy choice for tiling needs. Reach out to Céramique DPlex for expert tiling services in Longueuil, Quebec.</p>',
  '1651 Av. de l''Église',
  'Canada',
  'QC',
  'Longueuil',
  'J4P 2C7',
  'info@mcmplanchers.com',
  'canada/longueuil/home-services/céramique-dplex-inc',
  'ChIJHf30bEkFyUwRfBGjEPeR7aI',
  45.5063702,
  -73.4943814,
  '14383469065',
  NULL,
  'Flooring=>Tile Flooring',
  'Pay-as-you-go',
  304,
  'https://www.ceramiquedplex.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'FGS Tile and Grout Professional Restoration Services',
  '<p>FGS Tile and Grout Professional Restoration Services operates as a dedicated tile contractor in Oshawa, Ontario. This local business specializes in a broad range of services including tile and grout cleaning, repair, replacement, re-caulking around showers, natural stone maintenance, and shower repair and renovation. With extensive experience and expertise, FGS Tile and Grout ensures high-quality and detailed solutions for all tiled spaces.</p><p>The team at FGS Tile and Grout understands the importance of maintaining clean and functional bathrooms. They offer tailored solutions that meet the unique needs of every client. The company focuses on delivering exceptional results, transforming bathrooms into beautiful and functional spaces. Their commitment to quality service is evident in every project completed.</p><p>FGS Tile and Grout utilizes advanced techniques and equipment to achieve the best outcomes for tile and grout restoration. Their skilled professionals take pride in their work, ensuring that each job meets high standards of excellence. Clients appreciate the attention to detail and the dedication to customer satisfaction that FGS Tile and Grout consistently demonstrates.</p><p>FGS Tile and Grout Professional Restoration Services provides comprehensive tile and grout solutions that enhance the beauty and functionality of bathrooms. Their reputation for quality and client satisfaction is well-established in Oshawa. Engage with FGS Tile and Grout today for expert tile restoration services in Oshawa, Ontario.</p>',
  '447 Bader Ave',
  'Canada',
  'ON',
  'Oshawa',
  'L1J 3E9',
  'mariomeunier-sablage@outlook.com',
  'canada/oshawa/home-services/fgs-tile-and-grout-professional-restoration-services',
  'ChIJ0SxBqPId1YkRe1F0FfFY58k',
  43.9103035,
  -78.8873904,
  '16477105076',
  NULL,
  'Flooring=>Tile Flooring',
  'Pay-as-you-go',
  303,
  'https://fgstileandgrout.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Classic Tile & Interior Design Ltd',
  '<p>Classic Tile & Interior Design Ltd offers exceptional tile contracting services in Calgary, Alberta. This business specializes in transforming homes with stylish and classy interior designs. With a commitment to quality and customer satisfaction, Classic Tile & Interior Design Ltd employs skilled general contractors dedicated to delivering outstanding results.</p> <p>Located at 431 Glamorgan Pl SW, this local business has established a reputation for excellence in the tile contracting industry. The team focuses on creating spaces that reflect the homeowner''s vision while ensuring functionality and aesthetics. From kitchen backsplashes to luxurious bathroom renovations, Classic Tile & Interior Design Ltd provides a range of services tailored to meet diverse needs. Their attention to detail and commitment to using high-quality materials set them apart in the competitive Calgary market.</p> <p>Classic Tile & Interior Design Ltd prioritizes customer collaboration throughout the redesign process. The experienced contractors work closely with clients to understand their preferences and requirements, ensuring that each project aligns with their unique style. This approach has garnered positive feedback from homeowners who appreciate the personalized service and exceptional craftsmanship.</p> <p>Classic Tile & Interior Design Ltd excels in delivering stylish interior redesigns, making homes in Calgary more beautiful and functional. Their dedication to quality and customer satisfaction shines through every project. Reach out to Classic Tile & Interior Design Ltd today to explore how they can enhance residential spaces in Calgary, Alberta.</p>',
  '431 Glamorgan Pl SW',
  'Canada',
  'AB',
  'Calgary',
  'T3E 6M1',
  'montrealfloors@gmail.com',
  'canada/calgary/home-services/classic-tile-interior-design-ltd',
  'ChIJW3HpZ_pxcVMRqyPHjdOpbe8',
  51.0146501,
  -114.1539858,
  '14032400868',
  NULL,
  'Flooring=>Tile Flooring',
  'Pay-as-you-go',
  302,
  'http://classictileltd.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Hi! Neighbor Floor Covering Company',
  '<p>Hi! Neighbor Floor Covering Company, located at 2610 Pillette Rd in Windsor, Ontario, excels in providing a wide range of flooring solutions. This flooring store offers high fashion flooring choices that are both affordable and trendy. With over one million square feet of warehouse space, Hi! Neighbor stands as one of Windsor''s largest in-stock flooring warehouse merchants, ensuring instant delivery of various flooring options.</p> <p>The business prioritizes personalized service, fostering a family-like atmosphere that enhances customer satisfaction. Hi! Neighbor''s commitment to quality products sets it apart in the competitive flooring market. Customers can find an extensive selection of flooring materials, including hardwood, laminate, vinyl, and carpet, all readily available for immediate purchase. The knowledgeable staff assists clients in making informed decisions that suit both their style and budget.</p> <p>Community engagement remains a core value, as Hi! Neighbor actively participates in local events and initiatives, strengthening its ties within Windsor. The store’s reputation for reliability and customer service has earned it a loyal customer base. Hi! Neighbor Floor Covering Company delivers not only products but also an experience that reflects care and attention to detail.</p> <p>Explore the diverse flooring options at Hi! Neighbor, where quality meets affordability. The store''s dedication to service and extensive inventory ensures a satisfying shopping experience. Visit Windsor for exceptional flooring solutions today.</p>',
  '2610 Pillette Rd',
  'Canada',
  'ON',
  'Windsor',
  'N8T 1R1',
  'importdata-249@kwikr.ca',
  'canada/windsor/home-services/hi-neighbor-floor-covering-company',
  'ChIJd8pnb-EsO4gRpDTklS8RgwQ',
  42.3013416,
  -82.9633038,
  '15192584481',
  'https://www.kwikr.ca/pictures/profile/pimage-285.jpg',
  'Flooring=>Laminate Flooring',
  'Pay-as-you-go',
  301,
  'https://www.hineighborflooring.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Whelan''s Flooring Centre',
  '<p>Whelan''s Flooring Centre, located at 2512 Chemong Rd in Peterborough, Ontario, serves as the leading flooring store in the region. Established in 1985, this business has built a strong reputation for quality and service. Notable achievements include winning the Peterborough Business Excellence Award in 2009 for commercial restoration and renovation. The stunning transformation of the Chemong Road location showcases the commitment to excellence.</p> <p>The showroom at Whelan''s Flooring Centre features a wide array of flooring options, catering to diverse customer needs. From hardwood to laminate and carpet, the selection meets various aesthetic preferences and budgets. The knowledgeable staff provides expert advice, ensuring customers make informed decisions. This dedication to customer service has resulted in multiple Examiner Reader''s Choice Awards, affirming the business''s status within the community.</p> <p>Whelan''s Flooring Centre continues to prioritize quality and innovation in the flooring industry. The transformation of their location not only enhances the shopping experience but also reflects the business''s commitment to the local community. The combination of exceptional products and customer service solidifies Whelan''s position as a trusted flooring provider in Peterborough and the Kawarthas.</p> <p>Explore the extensive selection of flooring options and experience top-notch service at Whelan''s Flooring Centre. Visit the store in Peterborough to discover how to enhance any space with quality flooring solutions.</p>',
  '2512 Chemong Rd',
  'Canada',
  'ON',
  'Peterborough',
  'K9J 6X2',
  'info@polissage-beton.ca',
  'canada/peterborough/home-services/whelan-s-flooring-centre',
  'ChIJBZjt89OL1YkR4oh9514m79M',
  44.3667271,
  -78.3785855,
  '17052929565',
  'https://www.kwikr.ca/pictures/profile/pimage-284.jpg',
  'Flooring=>Laminate Flooring',
  'Pay-as-you-go',
  300,
  'http://www.whelansflooring.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Couvre-Plancher Chapdelaine',
  '<p>Couvre-Plancher Chapdelaine, located at 1145 Bd Lemire in Drummondville, Quebec, specializes in high-quality flooring solutions. This flooring store offers a wide range of products, including hardwood, laminate, vinyl, and tile flooring. With a commitment to customer satisfaction, Couvre-Plancher Chapdelaine has built a strong reputation in the local community for its exceptional service and expertise in flooring installation.</p><p>The store features a diverse selection of flooring options that cater to various styles and budgets. Knowledgeable staff members provide personalized consultations to help customers choose the right materials for their homes or businesses. Couvre-Plancher Chapdelaine ensures that each project meets high standards of quality and durability. The company also emphasizes eco-friendly options, making it a responsible choice for environmentally conscious consumers.</p><p>Couvre-Plancher Chapdelaine has achieved numerous accolades for its outstanding service and product offerings. The store''s dedication to excellence has earned the trust of many residents in Drummondville and surrounding areas. Customers appreciate the seamless installation process and the attention to detail that the team brings to every project.</p><p>This flooring store provides a comprehensive range of services, including consultations, product sales, and professional installations. Couvre-Plancher Chapdelaine is a reliable choice for anyone looking to enhance their space with quality flooring. Visit Drummondville today to explore the options available at Couvre-Plancher Chapdelaine.</p>',
  '1145 Bd Lemire',
  'Canada',
  'QC',
  'Drummondville',
  'J2C 7X7',
  'starplanchers@gmail.com',
  'canada/drummondville/home-services/couvre-plancher-chapdelaine',
  'ChIJtUyGwuUTyEwRarEPys5abVw',
  45.8757738,
  -72.521223,
  '18194779410',
  'https://www.kwikr.ca/pictures/profile/pimage-283.jpg',
  'Flooring=>Laminate Flooring',
  'Pay-as-you-go',
  299,
  'http://www.cpchapdelaine.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);
