INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Action Roofing Ltd.',
  '<p>Action Roofing Ltd. provides exceptional roofing services in Calgary, Alberta. With over 38 years of experience, this roofing contractor specializes in high-quality exterior installations. The team combines extensive knowledge and expertise to ensure each customer receives top-notch service. Action Roofing Ltd. has built a reputation for reliability and excellence in the local community.</p> <p>The company has been a key player in the roofing industry since 1986. Action Roofing Ltd. focuses on delivering quality installations that meet the highest standards. The commitment to using the best products and practices sets this business apart from the competition. Customers benefit from a team that prioritizes safety and quality in every project.</p> <p>Memberships and qualifications within the industry reflect the dedication to professional standards. Action Roofing Ltd. maintains strong relationships with suppliers and industry partners, ensuring access to the latest innovations in roofing technology. This commitment to moving the industry forward enhances the overall customer experience.</p> <p>Action Roofing Ltd. consistently delivers quality, safety, and customer satisfaction. The company’s long-standing presence in Calgary showcases its reliability and expertise. For anyone seeking roofing solutions, Action Roofing Ltd. stands ready to assist. Visit Calgary''s trusted roofing contractor at 1936 27 Ave NE Unit 100 for quality service and installations. Connect with Action Roofing Ltd. today for all roofing needs in Calgary.</p>',
  '1936 27 Ave NE Unit 100',
  'Canada',
  'AB',
  'Calgary',
  'T2E 7A5',
  'info@integrityroofers.ca',
  'canada/calgary/home-services/action-roofing-ltd',
  'ChIJV0_JGSBlcVMR_5n6zXPE-9c',
  51.0771062,
  -114.0120262,
  '14032930497',
  'https://www.kwikr.ca/pictures/profile/pimage-926.jpg',
  'Roofing',
  'Growth Plan',
  923,
  'https://www.actionroofing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Integrity Roofers',
  '<p>Integrity Roofers operates as a premier roofing contractor in Toronto, Ontario, delivering exceptional roofing services tailored to both residential and commercial needs. This company excels in a variety of services including flat roof repairs, roof replacement, attic air sealing, attic ventilation, and infrared thermal imaging. Integrity Roofers also offers siding, skylight installation, eavestrough cleaning and repair, and gutter filter solutions, ensuring a comprehensive approach to roofing.</p> <p>With a commitment to quality, Integrity Roofers maintains a strong reputation in the Greater Toronto Area. The company is licensed, certified, and insured, which provides clients with peace of mind. An emphasis on safety and high-quality workmanship sets this business apart from competitors. Customers benefit from three different types of warranties, showcasing the company''s confidence in its services.</p> <p>Expert professionals at Integrity Roofers prioritize customer satisfaction and convenience. The focus on affordable pricing without compromising service quality attracts a diverse clientele. Whether addressing a minor repair or a major roof replacement, Integrity Roofers stands ready to meet the needs of its clients efficiently and effectively.</p> <p>Integrity Roofers offers a wide range of roofing solutions, ensuring quality and safety for every project. The combination of expertise, affordability, and comprehensive warranties enhances the overall experience for clients in Toronto. Connect with Integrity Roofers today for reliable roofing services in Ontario.</p>',
  '237 Sheppard Ave W ground floor, unit#1',
  'Canada',
  'ON',
  'Toronto',
  'M2N 1N2',
  'centralroofing@eastlink.ca',
  'canada/toronto/home-services/integrity-roofers',
  'ChIJJSRYIngyK4gRUrhQM-RJUG0',
  43.7587888,
  -79.4223168,
  '16475594751',
  'https://www.kwikr.ca/pictures/profile/pimage-925.jpg',
  'Roofing',
  'Growth Plan',
  922,
  'https://www.integrityroofers.com/?utm_source=google&utm_medium=organic&utm_campaign=gmb',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Central Roofing Services Ltd',
  '<p>Central Roofing Services Ltd provides expert roofing solutions in Halifax, Nova Scotia. This roofing contractor specializes in asphalt shingling and flat roofing, ensuring quality workmanship and reliability. With a commitment to customer satisfaction, the company has built a strong reputation in the local area.</p> <p>Central Roofing Services Ltd has established itself as a trusted name in the roofing industry. The team possesses extensive knowledge and experience, which is evident in every project completed. This business focuses on using high-quality materials, ensuring durability and longevity for each roofing system installed. Whether it’s a residential or commercial project, the company delivers tailored solutions that meet specific needs.</p> <p>The expertise in asphalt shingling allows for a wide range of design options, enhancing the aesthetic appeal of any property. Flat roofing services cater to various building types, providing efficient solutions for water drainage and insulation. The attention to detail and adherence to safety standards further underscore the professionalism of Central Roofing Services Ltd.</p> <p>Quality service and customer-centric approach define Central Roofing Services Ltd. The business excels in providing reliable roofing solutions that stand the test of time. For those seeking roofing expertise in Halifax, this company offers a solid choice. Reach out to Central Roofing Services Ltd at 287 Lacewood Dr Unit 103 - Suite 270, Halifax, Nova Scotia, B3M 3Y7 for exceptional roofing services.</p>',
  '287 Lacewood Dr Unit 103 - Suite 270eHalifax',
  'Canada',
  'NS',
  'Halifax',
  'B3M 3Y7',
  'info@toituresthermotech.ca',
  'canada/halifax/home-services/central-roofing-services-ltd',
  'ChIJAQDA3FkgWksRScCq5bchyQY',
  44.6633769,
  -63.6577891,
  '19028301800',
  'https://www.kwikr.ca/pictures/profile/pimage-924.jpg',
  'Roofing',
  'Growth Plan',
  921,
  'http://www.centralroofing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Toitures Thermotech',
  '<p>Toitures Thermotech serves Charette, Quebec, specializing in roofing solutions. This roofing contractor provides a range of services including roof installation, repair, and maintenance. The company prides itself on quality craftsmanship and customer satisfaction, making it a reliable choice for local residents. With a commitment to using high-quality materials, Toitures Thermotech ensures durability and longevity in every project.</p><p>Established in Charette, Toitures Thermotech has built a reputation for excellence in the roofing industry. The team consists of skilled professionals dedicated to delivering top-notch services. Whether it is a residential or commercial roofing project, the company approaches each job with attention to detail and a focus on the client''s needs. Their extensive experience allows them to handle various roofing materials, including shingles, metal, and flat roofs.</p><p>Toitures Thermotech emphasizes safety and efficiency, adhering to industry standards. Clients appreciate the transparent communication and timely project completion. The company’s strong work ethic and dedication to quality have earned it numerous positive reviews from satisfied customers. Their local presence fosters a sense of community, as they understand the unique roofing needs of Charette residents.</p><p>Toitures Thermotech offers reliable roofing services, showcasing strengths in quality and customer care. Their achievements reflect a commitment to the community and the industry. Connect with Toitures Thermotech at 25 Rue Notre Dame, Charette, Quebec, for exceptional roofing solutions.</p>',
  '25 Rue Notre Dame',
  'Canada',
  'QC',
  'Charette',
  'G0X 1E0',
  'jbreidenbach@tremcoinc.com',
  'canada/charette/home-services/toitures-thermotech',
  'ChIJS5deyYE3xkwRI6XPbpFmg-o',
  46.4391837,
  -72.9279194,
  '18192212125',
  'https://www.kwikr.ca/pictures/profile/pimage-922.jpg',
  'Roofing',
  'Growth Plan',
  920,
  'https://www.toituresthermotech.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Tremco Roofing & Building Maintenance',
  '<p>Tremco Roofing & Building Maintenance operates as a leading roofing contractor in East York, Ontario. This company specializes in providing comprehensive roofing solutions, including installation, repair, and maintenance services. With a focus on quality and reliability, Tremco has earned a solid reputation in the local community. Their commitment to customer satisfaction and industry standards sets them apart in the competitive roofing market.</p><p>The team at Tremco Roofing & Building Maintenance brings extensive experience and expertise to each project. They understand the unique challenges faced by property owners in East York. This knowledge enables them to deliver tailored solutions that meet specific needs. Whether addressing a minor leak or undertaking a complete roof replacement, the company ensures high-quality workmanship and materials.</p><p>Tremco emphasizes the importance of regular maintenance to extend the lifespan of roofing systems. Preventative measures can save property owners significant costs in the long run. Their proactive approach to building maintenance reflects an understanding of both residential and commercial needs in the area.</p><p>Tremco Roofing & Building Maintenance remains dedicated to providing exceptional service and quality roofing solutions in East York. Their focus on customer care and industry expertise makes them a reliable choice for roofing needs. Reach out to Tremco Roofing & Building Maintenance for efficient and effective roofing services in East York, Ontario.</p>',
  '50 Beth Nealson Dr',
  'Canada',
  'ON',
  'East York',
  'M4H 1M6',
  'customersroofing@yahoo.ca',
  'canada/east-york/home-services/tremco-roofing-building-maintenance',
  'ChIJDS8VRf3M1IkR62--BLDfghQ',
  43.7119248,
  -79.3465522,
  '18006689879',
  NULL,
  'Roofing',
  'Growth Plan',
  919,
  'https://www.tremcoroofing.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Customersroofing',
  '<p>Customersroofing, a reliable roofing contractor located at 412 Queen St W in Cambridge, Ontario, specializes in high-quality roofing solutions. This business excels in residential and commercial roofing services, ensuring durability and aesthetic appeal for every project. Customersroofing has built a reputation for excellence, focusing on customer satisfaction and using top-grade materials.</p> <p>Offering a range of services, Customersroofing handles everything from roof installations to repairs and maintenance. The team of skilled professionals brings extensive experience to each job, ensuring that every roofing project meets industry standards. With a commitment to safety and efficiency, Customersroofing prioritizes timely project completion without compromising quality.</p> <p>In addition to their roofing services, Customersroofing provides consultations to help clients choose the best roofing solutions for their needs. This approach fosters informed decision-making, empowering customers to select options that enhance their property''s value and curb appeal. The business''s dedication to transparency and integrity has made it a trusted name in the Cambridge area.</p> <p>Customersroofing delivers exceptional roofing services, emphasizing quality and customer care. This company has established itself as a leader in the local roofing industry, consistently meeting the needs of its clients. For reliable roofing solutions in Cambridge, Ontario, reach out to Customersroofing today.',
  '412 Queen St W',
  'Canada',
  'ON',
  'Cambridge',
  'N3C 1H1',
  'accurateroofingns@gmail.com',
  'canada/cambridge/home-services/customersroofing',
  'ChIJ30KVQWuJK4gRNhXr1YiO_0U',
  43.4213234,
  -80.3258885,
  '15195735286',
  'https://www.kwikr.ca/pictures/profile/pimage-920.jpg',
  'Roofing',
  'Growth Plan',
  918,
  'https://customersroofing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Accurate Roofing',
  '<p>Accurate Roofing, located at 30 Mohawk St, Hammonds Plains, Nova Scotia, specializes in high-quality roofing services for both residential and commercial properties. This roofing contractor prides itself on delivering reliable solutions, from roof repairs to complete installations. With a commitment to excellence, Accurate Roofing has built a solid reputation in the community, ensuring that every project meets the highest standards of durability and aesthetics.</p><p>The team at Accurate Roofing consists of experienced professionals who understand the unique needs of Hammonds Plains residents. They utilize top-grade materials and modern techniques to ensure that each roofing project withstands the local climate. Customer satisfaction remains a top priority, with a focus on timely service and clear communication throughout the roofing process. The company’s dedication to quality workmanship has earned it numerous positive reviews from satisfied clients.</p><p>Accurate Roofing also emphasizes safety and compliance with local regulations, ensuring that every job is completed to code. The company offers a range of services, including roof inspections, maintenance, and emergency repairs, making it a comprehensive choice for roofing needs. Its expertise in various roofing systems allows for tailored solutions that fit each client''s specific requirements.</p><p>Accurate Roofing provides essential roofing services with a focus on quality and customer satisfaction. The skilled team ensures reliable solutions for every project. Reach out to Accurate Roofing in Hammonds Plains for expert roofing services.',
  '30 Mohawk St',
  'Canada',
  'NS',
  'Hammonds Plains',
  'B4B 1M7',
  'serviceca@aclark.ca',
  'canada/hammonds-plains/home-services/accurate-roofing',
  'ChIJv5dwEJiIWUsR6csonVseYr8',
  44.7401121,
  -63.7963437,
  '19028171967',
  'https://www.kwikr.ca/pictures/profile/pimage-919.jpg',
  'Roofing',
  'Growth Plan',
  917,
  'https://www.accurateroofingns.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'A. Clark Roofing & Siding LP',
  '<p>A. Clark Roofing & Siding LP serves the Calgary and Edmonton areas with reliable roofing and siding solutions. With 70 years of experience, this roofing contractor delivers meticulous attention to detail and innovative techniques. The company has built a reputation for quality and reliability, making it a preferred choice among homeowners.</p> <p>The firm integrates modern technology with extensive industry knowledge to create thorough roofing methods. A. Clark Roofing & Siding LP has successfully completed numerous projects, ensuring that each homeowner receives the best service possible. The company''s commitment to quality is evident in its A rating with the Better Business Bureau, showcasing its dedication to customer satisfaction. As the oldest member of the Better Business Bureau in Northern Alberta, A. Clark Roofing & Siding LP demonstrates a long-standing commitment to excellence.</p><p>Membership in the Canadian Home Builders Association, as well as the Edmonton Executives Association and the Edmonton and Calgary Construction Associations, further highlights the company''s credibility and expertise in the roofing sector. This extensive network underlines A. Clark Roofing & Siding LP''s commitment to maintaining high industry standards and fostering strong community ties.</p><p>A. Clark Roofing & Siding LP offers exceptional roofing and siding services backed by decades of experience and a strong reputation. The company''s focus on quality and customer satisfaction sets it apart in the industry. Connect with A. Clark Roofing & Siding LP at 2816 21 St NE #9, Calgary, Alberta, T2E 6Z2 for reliable roofing solutions.</p>',
  '2816 21 St NE #9',
  'Canada',
  'AB',
  'Calgary',
  'T2E 6Z2',
  'careers@stybek.ca',
  'canada/calgary/home-services/a-clark-roofing-siding-lp',
  'ChIJ_1zACqplcVMR1wJ69052EbE',
  51.0773273,
  -114.0085399,
  '14032645556',
  'https://www.kwikr.ca/pictures/profile/pimage-917.jpg',
  'Roofing',
  'Growth Plan',
  916,
  'https://www.aclark.ca/?utm_source=organic&utm_medium=gbp&utm_campaign=gbp-link',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Stybek Commercial Roofing Kitchener',
  '<p>Stybek Commercial Roofing Kitchener provides essential roofing services in Kitchener, Ontario. This roofing contractor specializes in thorough roof assessments, ensuring clients understand the condition of their roofing assets. With a focus on quality and reliability, the company offers solutions tailored to both residential and commercial needs, enhancing the longevity and safety of roofs.</p><p>In the competitive landscape of roofing services, Stybek Commercial Roofing Kitchener distinguishes itself through its commitment to comprehensive evaluations. The experienced team conducts detailed inspections, identifying potential issues before they escalate. This proactive approach not only saves clients money but also extends the lifespan of their roofs. The company’s reputation for excellence is built on transparency and thoroughness, ensuring that clients are well-informed about their roofing conditions.</p><p>Serving the Kitchener community, Stybek Commercial Roofing Kitchener emphasizes the importance of regular roof maintenance. Their assessments provide valuable insights, allowing property owners to make informed decisions regarding repairs or replacements. The contractors utilize industry-leading techniques and materials, ensuring each project meets high standards of safety and durability.</p><p>For those seeking reliable roofing solutions, Stybek Commercial Roofing Kitchener offers expertise and dedication. Their focus on detailed assessments and quality service positions them as a trusted partner in roofing projects. Contact Stybek Commercial Roofing Kitchener at 64 Dumart Pl, Kitchener, Ontario, for professional roofing services today.</p>',
  '64 Dumart Pl',
  'Canada',
  'ON',
  'Kitchener',
  'N2K 3C7',
  'newheightsroofingandexteriors@gmail.com',
  'canada/kitchener/home-services/stybek-commercial-roofing-kitchener',
  'ChIJt8G6JEzzK4gRFuiXOExp8Go',
  43.4816649,
  -80.4598665,
  '15198889676',
  'https://www.kwikr.ca/pictures/profile/pimage-916.jpg',
  'Roofing',
  'Growth Plan',
  915,
  'http://www.stybek.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'New Heights Roofing & Exteriors',
  '<p>New Heights Roofing & Exteriors offers comprehensive roofing solutions in Winnipeg, Manitoba. This roofing contractor specializes in residential and commercial roofing services, including installations, repairs, and maintenance. With a commitment to quality and customer satisfaction, New Heights Roofing has built a solid reputation in the local community.</p><p>The team at New Heights Roofing & Exteriors brings years of experience and expertise to every project. They utilize high-quality materials and advanced techniques to ensure durability and longevity in all roofing systems. The company also provides free estimates, allowing clients to make informed decisions without hidden costs. Their focus on safety and efficiency sets them apart in the roofing industry.</p><p>New Heights Roofing has successfully completed numerous projects, showcasing their ability to handle various roofing styles and challenges. The company emphasizes the importance of regular maintenance to extend the lifespan of roofs, providing valuable tips and services to homeowners. Their customer-centric approach fosters trust and loyalty, making them a preferred choice for many in Winnipeg.</p><p>With a strong emphasis on quality workmanship and reliable service, New Heights Roofing & Exteriors remains dedicated to enhancing the roofing experience for clients. Their commitment to excellence and community engagement highlights their role as a leading roofing contractor in Winnipeg. Connect with New Heights Roofing & Exteriors today at 756 Manhattan Ave, Winnipeg, Manitoba, R2L 1B8 for exceptional roofing services.</p>',
  '756 Manhattan Ave',
  'Canada',
  'MB',
  'Winnipeg',
  'R2L 1B8',
  'metalshop@transconaroofing.ca',
  'canada/winnipeg/home-services/new-heights-roofing-exteriors',
  'ChIJZTAO9-dw6lIR5NPaOxpK61Y',
  49.905289,
  -97.0881561,
  '12042970336',
  'https://www.kwikr.ca/pictures/profile/pimage-915.jpg',
  'Roofing',
  'Growth Plan',
  914,
  'http://newheightsroofingandexteriors.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Transcona Roofing',
  '<p>Transcona Roofing, located at 992 Dugald Rd in Winnipeg, Manitoba, has been a reliable roofing contractor since 1959. This company specializes in roofing and waterproofing services for industrial, commercial, and institutional buildings. Known for its commitment to customer satisfaction, Transcona Roofing emphasizes long-term relationships built through quality service and expert craftsmanship.</p><p>The company offers a comprehensive range of services, including installation, repair, and maintenance of roofing systems. With a focus on creative problem-solving, Transcona Roofing delivers solutions tailored to meet the unique needs of each client. This dedication to exceeding expectations sets a high standard in the commercial roofing industry.</p><p>Transcona Roofing prides itself on unmatched customer service. The team consists of experienced professionals who understand the complexities of roofing projects. They ensure a hassle-free experience from start to finish, making the process efficient and straightforward. Regular inspections and maintenance services help prolong the lifespan of roofs, providing peace of mind to building owners.</p><p>With a proven track record and a commitment to quality, Transcona Roofing stands as a trusted partner in the Winnipeg area. The company’s focus on building lasting relationships and delivering excellent results has earned it a solid reputation. For expert roofing services, reach out to Transcona Roofing in Winnipeg, Manitoba. </p>',
  '992 Dugald Rd',
  'Canada',
  'MB',
  'Winnipeg',
  'R2J 0G9',
  'info@roofsofsteel.ca',
  'canada/winnipeg/home-services/transcona-roofing',
  'ChIJ0xATpcxw6lIR3V0LOuZslsA',
  49.8857092,
  -97.0772056,
  '12042333716',
  'https://www.kwikr.ca/pictures/profile/pimage-913.jpg',
  'Roofing',
  'Growth Plan',
  913,
  'http://www.transconaroofing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Roofs of Steel',
  '<p>Roofs of Steel serves North Gower, Ontario, as a premier roofing contractor specializing in high-quality metal roofing installations, supplies, and shingles. This company focuses on delivering exceptional products and expert installation, ensuring customer satisfaction throughout the process. Roofs of Steel guarantees top-notch metal roofs that withstand extreme weather conditions, making them a reliable choice for homeowners in the Ottawa Valley Region and surrounding areas.</p><p>The company’s metal roofing solutions come with a lifetime guarantee and a transferable warranty, reflecting confidence in their craftsmanship. Roofs of Steel prioritizes durability, offering roofs that resist wind, rust, and hail, while maintaining color fastness over time. Their commitment to quality and affordable pricing positions them as a trusted provider in the local roofing industry.</p><p>Expert installation is a hallmark of Roofs of Steel, with a team dedicated to applying the highest standards in roofing. Their focus on customer service complements their product offerings, ensuring a seamless experience from consultation to installation. The company caters to clients within a 1.5-hour radius of Ottawa, enhancing accessibility for those in need of roofing solutions.</p><p>Roofs of Steel combines quality materials with expert installation to provide reliable roofing solutions. The company''s strengths lie in their commitment to customer service and the durability of their products. For those seeking an efficient and trustworthy roofing contractor in North Gower, connecting with Roofs of Steel for a free quote is essential.</p>',
  '5520 Fourth Line Rd',
  'Canada',
  'ON',
  'North Gower',
  'K0A 2T0',
  'pbussell@londonecoroof.com',
  'canada/north-gower/home-services/roofs-of-steel',
  'ChIJA8ZErZLvzUwReCkGzq_xDz8',
  45.1863958,
  -75.7852579,
  '16132909607',
  'https://www.kwikr.ca/pictures/profile/pimage-912.jpg',
  'Roofing',
  'Growth Plan',
  912,
  'https://www.roofsofsteel.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Metal Roof Ottawa',
  '<p>Metal Roof Ottawa operates as a reliable roofing contractor located in Nepean, Ontario. This business specializes in high-quality metal roofing solutions designed to enhance durability and aesthetic appeal. With a focus on residential and commercial projects, Metal Roof Ottawa provides expert installation and repair services. The company has built a strong reputation for its commitment to quality and customer satisfaction, making it a preferred choice in the local area.</p> <p>Metal Roof Ottawa offers a range of services including metal roof installation, maintenance, and repair. The team consists of skilled professionals who understand the unique needs of the community. They utilize advanced techniques and high-grade materials to ensure every project meets industry standards. This commitment to excellence has earned the business numerous positive reviews and a loyal customer base.</p> <p>Customers appreciate the transparency and professionalism exhibited by Metal Roof Ottawa. The company provides detailed estimates and timelines, ensuring clients are informed throughout the process. This approach fosters trust and confidence in the services offered. Additionally, the team remains accessible for any questions or concerns, reinforcing their dedication to customer service.</p> <p>Metal Roof Ottawa delivers exceptional roofing solutions that prioritize quality and reliability. Their expertise in metal roofing sets them apart in the Nepean area. For those in need of roofing services, connect with Metal Roof Ottawa at 18 Enterprise Ave Unit J, Nepean, Ontario, K2G 0A6.</p>',
  '18 Enterprise Ave Unit J',
  'Canada',
  'ON',
  'Nepean',
  'K2G 0A6',
  'info@toitureshogue.com',
  'canada/nepean/home-services/metal-roof-ottawa',
  'ChIJTaXF6JUHzkwRZOkHJ9-B4lg',
  45.3288066,
  -75.7237611,
  '16139788644',
  'https://www.kwikr.ca/pictures/profile/pimage-911.jpg',
  'Roofing',
  'Growth Plan',
  911,
  'http://www.metalroofottawa.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Les Toitures Hogue Inc',
  '<p>Les Toitures Hogue Inc provides expert roofing solutions in Blainville, Quebec. This roofing contractor specializes in residential and commercial roofing services, ensuring high-quality installations and repairs. With a commitment to customer satisfaction, the company has built a strong reputation in the local area for reliability and professionalism.</p><p>Founded with the goal of delivering exceptional roofing services, Les Toitures Hogue Inc focuses on using durable materials and innovative techniques to enhance the longevity of roofs. The team possesses extensive knowledge of various roofing systems, including asphalt shingles, metal roofs, and flat roofing solutions. This expertise allows the company to address diverse roofing needs effectively.</p><p>Les Toitures Hogue Inc emphasizes safety and efficiency in every project. The skilled professionals are trained to handle complex roofing tasks, ensuring all work meets industry standards. The company also prioritizes clear communication, keeping clients informed throughout the process. Numerous satisfied customers attest to the quality of service and workmanship provided.</p><p>Les Toitures Hogue Inc stands as a reliable choice for roofing services in Blainville, Quebec. The combination of expertise, quality materials, and customer-focused approach contributes to the business’s success. For roofing needs, reach out to Les Toitures Hogue Inc at their location in Blainville.',
  '745 Bd Industriel',
  'Canada',
  'QC',
  'Blainville',
  'J7C 3V3',
  'infobelmarroofing@gmail.com',
  'canada/blainville/home-services/les-toitures-hogue-inc',
  'ChIJe3FngiEoyUwR73287P6U9eA',
  45.6694803,
  -73.8592173,
  '14504356336',
  NULL,
  'Roofing',
  'Growth Plan',
  910,
  'http://www.toitureshogue.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Belmar Roofing',
  '<p>Belmar Roofing, located at 295 Sheldon Dr in Cambridge, Ontario, offers comprehensive roofing solutions for both residential and commercial properties. Since 2010, this locally-owned roofing contractor has focused on new roof construction, re-roofing, and emergency repairs, ensuring worry-free service for homeowners and businesses alike. With a commitment to quality and customer satisfaction, Belmar Roofing has earned a solid reputation in the Hespeler area and beyond.</p><p>Specializing in a variety of roofing services, Belmar Roofing provides expertise in flat roofing, shingled roofs, and sidings. The team understands the importance of a reliable roof and works diligently to meet the needs of every client. With a strong focus on safety and professionalism, the company carries $10 million in liability insurance, ensuring peace of mind during any installation or repair process.</p><p>Belmar Roofing’s dedication to quality craftsmanship and customer service sets it apart in the competitive roofing industry. The experienced team tackles projects of all sizes, offering tailored solutions that address specific roofing challenges. Clients benefit from the company’s extensive knowledge and commitment to using high-quality materials, which enhances durability and longevity.</p><p>Belmar Roofing provides essential roofing services, ensuring satisfaction and reliability for clients in Cambridge and Hespeler. Trust in their expertise and commitment to excellence. Visit Belmar Roofing in Cambridge for all roofing needs.</p>',
  '295 Sheldon Dr',
  'Canada',
  'ON',
  'Cambridge',
  'N1T 1A7',
  'reception@templemetalroofs.com',
  'canada/cambridge/home-services/belmar-roofing',
  'ChIJc9OPeWuJK4gRFZfEVkXc1aM',
  43.4067286,
  -80.3018542,
  '15192676707',
  'https://www.kwikr.ca/pictures/profile/pimage-909.jpg',
  'Roofing',
  'Growth Plan',
  909,
  'http://www.belmarroofing.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Temple Metal Roofs',
  '<p>Temple Metal Roofs operates as a reputable roofing contractor in Grande Pointe, Manitoba, specializing in Architectural Sheet Metal installations. With over 15 years of experience, this local business emphasizes excellence in every project. The team is dedicated to providing high-quality service and ensuring customer satisfaction through continuous training and resource allocation.</p> <p>Temple Metal Roofs prioritizes quality and precision in roofing solutions. The skilled professionals understand the complexities involved in metal roofing and apply their extensive knowledge to each task. This commitment to craftsmanship has earned the company a solid reputation in the community. Clients appreciate the attention to detail and the ability to meet diverse roofing needs effectively.</p> <p>Customer feedback highlights the professionalism and reliability of Temple Metal Roofs. The team’s approach combines technical expertise with a customer-focused mindset, resulting in successful project outcomes. The business remains committed to using the best materials and techniques in the industry, ensuring long-lasting and durable roofing solutions.</p> <p>In summary, Temple Metal Roofs excels in providing top-tier roofing services in Grande Pointe, Manitoba. Their dedication to quality and customer satisfaction sets them apart in the roofing contractor category. Connect with Temple Metal Roofs today to explore exceptional roofing solutions tailored to specific needs in Grande Pointe.</p>',
  '633 Petit Rd',
  'Canada',
  'MB',
  'Grande Pointe',
  'R5A 1H2',
  'sales@greatwestroof.ca',
  'canada/grande-pointe/home-services/temple-metal-roofs',
  'ChIJZaYKVfPZwVIRNxHBc0rFxKg',
  49.750988,
  -97.0233,
  '12042540072',
  'https://www.kwikr.ca/pictures/profile/pimage-907.jpg',
  'Roofing',
  'Growth Plan',
  908,
  'https://www.templemetalroofs.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Great West Enterprises Ltd',
  '<p>Great West Enterprises Ltd, located in Langley, British Columbia, specializes in roofing services tailored for homeowners, managers, and engineers throughout the Lower Mainland. This roofing contractor has established a strong reputation for prompt and professional service, quality workmanship, and a commitment to total customer satisfaction. With a focus on new construction, re-roofing, roofing repairs, and installation of gutters and downpipes, Great West Enterprises has become a trusted name in the local community.</p> <p>The company''s growth reflects its dedication to core values that prioritize client needs. Each project showcases a commitment to quality, ensuring that all roofing solutions meet the highest standards. Experienced professionals handle every job, from minor repairs to large-scale installations, ensuring efficiency and reliability. The team understands the unique climate challenges in British Columbia and offers tailored solutions that enhance the longevity of roofs.</p> <p>Great West Enterprises Ltd has built a portfolio of satisfied clients who appreciate the attention to detail and the assurance of guaranteed workmanship. The company’s success stems from its ability to adapt to diverse roofing needs while maintaining a focus on customer care. This dedication to excellence has made Great West a preferred choice in Langley.</p> <p>Explore the roofing services provided by Great West Enterprises Ltd, where quality meets professionalism. Contact this trusted roofing contractor in Langley, British Columbia, for reliable roofing solutions today.</p>',
  '20641 Logan Ave # 206',
  'Canada',
  'BC',
  'Langley',
  'V3A 7R3',
  'tiffany@amroofingltd.ca',
  'canada/langley/home-services/great-west-enterprises-ltd',
  'ChIJy6v36RTPhVQRRROBzEjdW2Y',
  49.1054647,
  -122.6507249,
  '17786548615',
  'https://www.kwikr.ca/pictures/profile/pimage-906.jpg',
  'Roofing',
  'Growth Plan',
  907,
  'https://greatwestroof.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'A & M Roofing LTD Fort Mcmurray',
  '<p>A & M Roofing LTD provides expert roofing solutions in Fort McMurray, Alberta. This roofing contractor specializes in residential and commercial roofing services, including installations, repairs, and maintenance. With a commitment to quality workmanship and customer satisfaction, A & M Roofing LTD has established a reputation for reliability and professionalism in the local area.</p><p>The company operates from 141 Fontaine Cres #11, making it accessible for residents and businesses in Fort McMurray. A & M Roofing LTD employs skilled professionals who utilize high-quality materials to ensure durable and long-lasting roofing systems. Their experience in the industry allows them to address various roofing needs effectively, from minor repairs to complete roof replacements.</p><p>A & M Roofing LTD emphasizes safety and compliance with local building codes. The team''s dedication to ongoing training and staying updated with industry standards ensures that customers receive the best possible service. This commitment has led to numerous successful projects and satisfied clients throughout Fort McMurray.</p><p>Offering a range of services, A & M Roofing LTD stands ready to tackle any roofing challenge. Their strengths include attention to detail, timely project completion, and a customer-first approach. The positive sentiment surrounding their work reflects their dedication to the community. Visit A & M Roofing LTD in Fort McMurray for reliable roofing services that meet all needs. Reach out to this trusted roofing contractor today.</p>',
  '141 Fontaine Cres #11',
  'Canada',
  'AB',
  'Fort McMurray',
  'T9H 0C9',
  'advan_roofing@live.ca',
  'canada/fort-mcmurray/home-services/a-m-roofing-ltd-fort-mcmurray',
  'ChIJa5ueE_cFsFMR2IR_4RCB3wc',
  56.7103492,
  -111.339218,
  '17808809540',
  'https://www.kwikr.ca/pictures/profile/pimage-905.jpg',
  'Roofing',
  'Growth Plan',
  906,
  'https://www.amroofingltd.ca/fort-mcmurray-roofing-company/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Advantage Roofing Ltd.',
  '<p>Advantage Roofing Ltd. provides expert roofing contractor services in Blind Bay, British Columbia. With a decade of experience, this team of roofing professionals focuses on protecting homes and businesses. The company offers top-notch service, impressive warranties, and financing options to meet diverse customer needs.</p> <p>Advantage Roofing Ltd. prioritizes quality and reliability. The skilled team understands the importance of a sturdy roof in safeguarding properties from the elements. They utilize the latest techniques and materials to ensure durable and long-lasting results. Customers appreciate the commitment to excellence that has been a hallmark of the business since its inception.</p> <p>Serving the surrounding areas, Advantage Roofing Ltd. has built a reputation for outstanding customer service. The company’s knowledgeable staff provides clear communication throughout each project, ensuring that clients are informed every step of the way. This transparency fosters trust and satisfaction among clients.</p> <p>The company’s financing options make it easier for homeowners and businesses to access necessary roofing services without financial strain. The combination of quality workmanship and flexible payment plans demonstrates Advantage Roofing Ltd.''s dedication to meeting customer needs.</p> <p>Advantage Roofing Ltd. excels in providing roofing solutions that protect valuable assets. With a focus on quality, customer service, and accessibility, this company remains a reliable choice in Blind Bay. Connect with Advantage Roofing Ltd. for exceptional roofing services in British Columbia.</p>',
  '2417 Golf Course Dr #3',
  'Canada',
  'BC',
  'Blind Bay',
  'V0E 1H2',
  'info@flatroofers.ca',
  'canada/blind-bay/home-services/advantage-roofing-ltd',
  'ChIJ2cjW0dj7flMRA8ePekZTQ44',
  50.8720962,
  -119.3837466,
  '12502537663',
  'https://www.kwikr.ca/pictures/profile/pimage-904.jpg',
  'Roofing',
  'Growth Plan',
  905,
  'https://advantageroofingltd.ca/?utm_campaign=gmb',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Flat Roofers Commerical Roofing',
  '<p>Flat Roofers Commercial Roofing provides expert roofing solutions in Tottenham, Ontario. Specializing in various flat roofing systems, the company offers services such as roof repair, maintenance, replacement, and retrofitting. With a history dating back to 1985, Flat Roofers emphasizes cost-effective solutions to extend the life of roofs while minimizing unnecessary expenses.</p><p>This roofing contractor addresses a wide range of roofing materials, including Tar and Gravel, BUR, 2 Ply and 4 Ply Built-up roofs, Rolled Asphalt, Single Ply PVC, TPO, EPDM, Steel, Metal, and Tin. The team evaluates each roof''s condition, determining the best approach to repairs or retrofitting. The expertise in salvaging roofs through retrofit systems helps clients avoid the high costs associated with complete replacements.</p><p>Flat Roofers serves not only Tottenham but also extends its services throughout Ontario, Saskatchewan, Alberta, Quebec, and most of Canada. The commitment to quality and customer satisfaction has established the company as a reliable choice for commercial roofing needs. The managing partners bring extensive experience and a strong belief in the benefits of retrofitting, contributing to the sustainability of roofing solutions.</p><p>Flat Roofers Commercial Roofing delivers essential services, combining experience with a focus on cost-effective solutions. The dedication to quality and longevity in roofing systems makes this company a valuable partner for any commercial roofing project. Contact Flat Roofers Commercial Roofing in Tottenham for expert assistance with roofing needs.</p>',
  '6154 5th Line',
  'Canada',
  'ON',
  'Tottenham',
  'L0G 1W0',
  'pontrouge.recrutement@bpcan.com',
  'canada/tottenham/home-services/flat-roofers-commerical-roofing',
  'ChIJc93z1ILnKogR1oL6XebGal4',
  44.0428633,
  -79.7768493,
  '14163463166',
  'https://www.kwikr.ca/pictures/profile/pimage-903.jpg',
  'Roofing',
  'Growth Plan',
  904,
  'https://www.flatroofers.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Building Products of Canada Corp. (BP Canada)',
  '<p>Building Products of Canada Corp. (BP Canada) specializes in asphalt shingle manufacturing and building envelope materials distribution. Located at 9510 Saint-Patrick St. in Lasalle, Quebec, this roofing contractor serves the local community with a commitment to quality and reliability. BP Canada has established a strong reputation for providing durable roofing solutions that meet the needs of various projects.</p> <p>As a manufacturer of asphalt shingles, BP Canada ensures that each product meets high standards for performance and longevity. The company’s extensive range of building envelope materials supports both residential and commercial construction. This focus on quality materials helps clients achieve optimal results in their roofing projects.</p> <p>BP Canada is dedicated to customer satisfaction and offers expert guidance on material selection and installation processes. The knowledgeable team understands the unique challenges faced by builders and homeowners in the Lasalle area. By providing tailored solutions, BP Canada ensures that every project is completed efficiently and effectively.</p> <p>With a focus on innovation and quality, Building Products of Canada Corp. continues to lead in the roofing industry. The combination of manufacturing expertise and distribution capabilities positions BP Canada as a reliable partner for all roofing needs. Connect with Building Products of Canada Corp. for top-notch roofing solutions in Lasalle, Quebec.</p>',
  '9510 Saint-Patrick St.',
  'Canada',
  'QC',
  'Lasalle',
  'H8R 1R9',
  'info@gerrysroofing.ca',
  'canada/lasalle/home-services/building-products-of-canada-corp-bp-canada',
  'ChIJwUCWzc0WyUwRdVgIH6ctvE4',
  45.4384535,
  -73.6490138,
  '15143640161',
  'https://www.kwikr.ca/pictures/profile/pimage-902.jpg',
  'Roofing',
  'Growth Plan',
  903,
  'https://bpcan.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Gerry''s Roofing & Siding Inc',
  '<p>Gerry''s Roofing & Siding Inc offers reliable roofing and siding services in Hamilton, Ontario. The company has built a solid reputation for quality workmanship and customer satisfaction. Founded by Gerry St. Germain, the business transitioned from a summer job to a trusted local contractor. With the recent leadership change to long-time employee Joel Knight and his wife Karena, the company maintains its commitment to excellence.</p> <p>Gerry''s Roofing & Siding specializes in a range of services including roof installation, repairs, and siding solutions. The team focuses on using high-quality materials to ensure durability and aesthetics. The experience of the staff contributes to efficient project completion, providing clients with peace of mind. The company has served the Hamilton area for years, establishing a loyal customer base through dedication and hard work.</p> <p>Customer testimonials highlight the professionalism and attention to detail that Gerry''s Roofing & Siding brings to every project. The business emphasizes clear communication and transparency, ensuring clients understand the process from start to finish. The transition of leadership has not altered the core values that have driven success over the years.</p> <p>Gerry''s Roofing & Siding Inc continues to provide exceptional roofing and siding services in Hamilton, Ontario. The dedication to quality and customer service remains a priority. Reach out to Gerry''s Roofing & Siding Inc for reliable roofing solutions in Hamilton. </p>',
  '49 Morley St',
  'Canada',
  'ON',
  'Hamilton',
  'L8H 3R6',
  'info@realblueroofing.ca',
  'canada/hamilton/home-services/gerry-s-roofing-siding-inc',
  'ChIJu_tpRNaYLIgRkbFJ_KTHfDk',
  43.2506161,
  -79.7829945,
  '19055497112',
  'https://www.kwikr.ca/pictures/profile/pimage-901.jpg',
  'Roofing',
  'Growth Plan',
  902,
  'https://gerrysroofing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Real Blue Roofing Services Inc - Mississauga',
  '<p>Real Blue Roofing Services Inc, located at 2255 Dundas St W in Mississauga, Ontario, specializes in comprehensive roofing solutions. This roofing contractor provides honest and authentic guidance for all roofing needs, ensuring quality service throughout Mississauga and surrounding areas, including Oakville, Brampton, Milton, and Georgetown. The focus remains on customer satisfaction and reliable roofing expertise.</p><p>With a commitment to excellence, Real Blue Roofing Services Inc addresses various roofing challenges. The team offers services ranging from roof inspections to installations and repairs. Each project reflects a dedication to using high-quality materials and skilled craftsmanship. This business has built a reputation for transparency and reliability, essential traits in the roofing industry. Clients appreciate the straightforward approach and the emphasis on providing clear, actionable advice regarding roofing options.</p><p>The company’s extensive knowledge of roofing systems sets it apart in the competitive Mississauga market. Real Blue Roofing Services Inc understands the unique weather conditions in Ontario, allowing them to recommend the best solutions for durability and performance. This local contractor not only meets the needs of homeowners but also supports businesses in the area with professional roofing services.</p><p>Real Blue Roofing Services Inc delivers trustworthy roofing solutions and maintains a strong presence in Mississauga. The combination of expertise and commitment to quality assures clients of dependable service. Contact Real Blue Roofing Services Inc for reliable roofing services in Mississauga, Ontario.</p>',
  '2255 Dundas St W',
  'Canada',
  'ON',
  'Mississauga',
  'L5K 1R6',
  'info@torontoroofrepairs.ca',
  'canada/mississauga/home-services/real-blue-roofing-services-inc-mississauga',
  'ChIJ7yRVvk9DK4gRS6RLmvC2l4c',
  43.5333532,
  -79.6713478,
  '14378265225',
  'https://www.kwikr.ca/pictures/profile/pimage-900.jpg',
  'Roofing',
  'Growth Plan',
  901,
  'http://www.realblueroofing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Toronto Roof Repairs Inc',
  '<p>Toronto Roof Repairs Inc operates as a premier roofing contractor located in Mississauga, Ontario. This business specializes in providing high-quality roofing solutions across the Greater Toronto Area and Central Ontario. Noteworthy services include free, no-obligation roofing estimates and on-site consultations, ensuring customers receive expert advice tailored to their needs.</p> <p>With a commitment to durability and quality, Toronto Roof Repairs Inc offers a comprehensive range of services. These include roof replacements, professional roof repairs for both shingle and flat roofing, roof maintenance, and gutter cleaning. The company also excels in roof vent installations, eavestrough repairs, and gutter installations. Additional services encompass bathroom exhaust vent installations and solar vent installations, demonstrating a versatile skill set in roofing solutions.</p> <p>Toronto Roof Repairs Inc has established a reputation for fast, reliable service throughout Mississauga, Etobicoke, and other Central Ontario neighborhoods. Their motto, ''Your Roof, Our Mission,'' reflects a dedication to customer satisfaction and quality workmanship. The company''s experienced team ensures that every project meets high standards of excellence.</p> <p>Toronto Roof Repairs Inc provides essential roofing services with a focus on quality and customer care. Their expertise in various roofing solutions positions them as a trusted choice in the local area. Connect with Toronto Roof Repairs Inc for professional roofing services in Mississauga, Ontario.</p>',
  '2175 Dunwin Dr unit 6',
  'Canada',
  'ON',
  'Mississauga',
  'L5L 1X2',
  'toitureshp@videotron.ca',
  'canada/mississauga/home-services/toronto-roof-repairs-inc',
  'ChIJKd0ZnXc4K4gRdsk4qWaGZHo',
  43.5354055,
  -79.6714765,
  '14162472769',
  'https://www.kwikr.ca/pictures/profile/pimage-899.jpg',
  'Roofing',
  'Growth Plan',
  900,
  'http://www.torontoroofrepairs.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Toitures H.P. inc.',
  '<p>Toitures H.P. inc. serves Saint-Jean-sur-Richelieu, Quebec, as a trusted roofing contractor since 1970. This company specializes in the installation of asphalt shingles and elastomeric membranes, catering to both residential and commercial sectors. With decades of experience, Toitures H.P. inc. has built a reputation for quality workmanship and reliable service.</p><p>The team at Toitures H.P. inc. focuses on delivering durable roofing solutions that meet the specific needs of each client. The expertise in asphalt shingle installation ensures that homes receive protection from the elements while enhancing curb appeal. The use of elastomeric membranes provides long-lasting coverage for commercial buildings, making them a preferred choice for business owners.</p><p>Toitures H.P. inc. emphasizes customer satisfaction and quality control. Each project receives careful attention to detail, ensuring that all installations meet industry standards. The company’s commitment to excellence has led to numerous successful projects across the region, establishing a loyal customer base. Reliability and professionalism define their approach, making them a go-to option for roofing needs in the area.</p><p>Toitures H.P. inc. offers a range of roofing services that prioritize quality and durability. Their extensive experience in both residential and commercial roofing sets them apart. For reliable roofing solutions in Saint-Jean-sur-Richelieu, connect with Toitures H.P. inc. at 845 Rue Gaudette, Quebec, J3B 7S7.</p>',
  '845 Rue Gaudette',
  'Canada',
  'QC',
  'Saint-Jean-sur-Richelieu',
  'J3B 7S7',
  'aspectroofing@ymail.com',
  'canada/saint-jean-sur-richelieu/home-services/toitures-h-p-inc',
  'ChIJU5HetHihyUwRCg00LVb7Zy4',
  45.3215275,
  -73.2923024,
  '14503492662',
  'https://www.kwikr.ca/pictures/profile/pimage-898.jpg',
  'Roofing',
  'Growth Plan',
  899,
  'http://toitureshp.com/',
  NULL,
  NULL,
  NULL,
  NULL
);
