INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Spark Power',
  '<p>Spark Power offers reliable electrical installation services in Edmonton, Alberta. The company specializes in residential and commercial electrical projects, ensuring safety and efficiency in every task. With a commitment to high-quality workmanship, Spark Power has built a reputation for delivering exceptional results.</p><p>The team at Spark Power consists of experienced electricians who understand the complexities of electrical systems. They provide a range of services, including wiring, lighting installation, and electrical upgrades. Each project receives careful attention to detail, ensuring compliance with local safety codes and regulations. Spark Power prioritizes customer satisfaction, making it a trusted choice for many in the Edmonton area.</p><p>Investing in modern electrical solutions is crucial for both homes and businesses. Spark Power stays updated with the latest industry trends and technologies. This commitment to innovation allows them to offer energy-efficient options that can reduce utility costs while enhancing overall functionality. Clients appreciate the transparency and professionalism displayed throughout the project lifecycle.</p><p>With a focus on quality service and customer care, Spark Power continues to thrive in the competitive electrical installation market. Their skilled team and dedication to excellence contribute to their strong reputation in Edmonton. For those seeking reliable electrical solutions, Spark Power remains a top choice. Connect with Spark Power today for expert electrical installation services in Edmonton, Alberta.</p>',
  '9404 41 Ave NW #300',
  'Canada',
  'AB',
  'Edmonton',
  'T6E 6G8',
  'info@ableelectricco.ca',
  'canada/edmonton/home-services/spark-power',
  'ChIJzbEcpXgZoFMRVrzCUzBVJBU',
  53.476812,
  -113.4741719,
  '18337757697',
  'https://www.kwikr.ca/pictures/profile/pimage-538.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  548,
  'https://sparkpowercorp.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'BEQ Technology',
  '<p>BEQ Technology specializes in electrical installation services in Sherbrooke, Quebec. This company focuses on providing top-quality electric vehicle charging stations for residential, multi-unit, and commercial properties. With a commitment to customer satisfaction, BEQ Technology boasts a remarkable 98% satisfaction rate, making it a leading choice in Quebec''s electrical installation market.</p><p>Established to meet the growing demand for electric vehicle infrastructure, BEQ Technology offers comprehensive solutions tailored to various needs. The company provides financing options to ensure accessibility for all customers. With 21 dealerships across Quebec, BEQ Technology ensures that residents and businesses can easily access their services. The key selling point is the emphasis on turnkey solutions, which simplifies the installation process for clients.</p><p>The company has earned a reputation for reliability and expertise in electrical installations. Their team is dedicated to providing efficient service while maintaining high standards of safety and quality. The focus on electric vehicle charging stations aligns with the increasing shift towards sustainable transportation, making BEQ Technology a relevant player in the industry.</p><p>In summary, BEQ Technology offers expert electrical installation services, particularly in electric vehicle charging solutions for residential and commercial clients in Sherbrooke, Quebec. Their commitment to customer satisfaction and extensive network of dealerships enhances their service delivery. Contact BEQ Technology today for professional installation services in Sherbrooke, Quebec.</p>',
  '6484 Boul Bourque',
  'Canada',
  'QC',
  'Sherbrooke',
  'J1N 1H3',
  'bryan@1and2electric.com',
  'canada/sherbrooke/home-services/beq-technology',
  'ChIJ_1jG8xtLtkwRzGxkRBbvVzk',
  45.3522978,
  -72.0218706,
  '18444277800',
  'https://www.kwikr.ca/pictures/profile/pimage-537.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  547,
  'https://beqtechnology.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Pronghorn Controls Ltd',
  '<p>Pronghorn Controls Ltd, located at 1101 9 Ave W in Kindersley, Saskatchewan, offers comprehensive electrical installation services. This local business specializes in delivering high-quality solutions for residential and commercial electrical needs. With a commitment to safety and efficiency, Pronghorn Controls Ltd has built a strong reputation within the community for reliable service and skilled workmanship.</p> <p>The team at Pronghorn Controls Ltd is equipped to handle a variety of electrical projects, from new installations to upgrades and repairs. Their expertise includes wiring, lighting installations, and panel upgrades, ensuring that every project meets the highest standards. This company prioritizes customer satisfaction and adheres to all safety regulations, making it a trusted choice for electrical services in Kindersley.</p> <p>Pronghorn Controls Ltd has achieved numerous successful projects, showcasing its dedication to quality and professionalism. The skilled technicians possess extensive knowledge in electrical systems, which allows them to provide effective solutions tailored to individual needs. This focus on detail and commitment to excellence has earned them a loyal customer base in the area.</p> <p>For those seeking reliable electrical installation services, Pronghorn Controls Ltd offers a strong combination of expertise and community trust. Their commitment to quality and customer service sets them apart. Visit Kindersley to engage with Pronghorn Controls Ltd for all electrical installation needs.</p>',
  '1101 9 Ave W',
  'Canada',
  'SK',
  'Kindersley',
  'S0L 1S2',
  'jschlamp@apolloec.ca',
  'canada/kindersley/home-services/pronghorn-controls-ltd',
  'ChIJa7WtxQJADlMR3Dv0egF4DxU',
  51.4727679,
  -109.1783766,
  '13064636262',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  546,
  'https://www.pronghorn.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Ryans Electrical & Security Services',
  '<p>Ryans Electrical & Security Services, located at 77 Parade St Suite #2 in Yarmouth, Nova Scotia, provides comprehensive electrical installation services. This business serves the Tri counties, specializing in residential and commercial electrical work, security systems, propane installation, and refrigeration and heat pump solutions. With a commitment to quality and customer satisfaction, Ryans Electrical & Security Services addresses a wide range of needs for both homeowners and businesses.</p> <p>Expertise in electrical installations ensures that all projects meet safety standards and regulations. The team is equipped to handle complex electrical systems, making them a reliable choice for various installations. Security services protect properties with advanced systems tailored to individual requirements. Propane installation services provide safe and efficient solutions for heating and cooking needs. Additionally, the refrigeration and heat pump offerings enhance energy efficiency and comfort in homes and commercial spaces.</p> <p>Ryans Electrical & Security Services has built a reputation for professionalism and reliability within the Yarmouth community. The focus on customer needs drives the team to deliver high-quality workmanship and prompt service. This business not only meets the demands of electrical and security installations but also ensures that each client receives tailored solutions that fit their specific requirements.</p> <p>Ryans Electrical & Security Services offers a broad range of services, including electrical installations, security systems, propane installation, and refrigeration solutions. The commitment to quality and customer satisfaction is evident in every project. Connect with Ryans Electrical & Security Services in Yarmouth for expert assistance with electrical needs.</p>',
  '77 Parade St Suite #2',
  'Canada',
  'NS',
  'Yarmouth',
  'B5A 3B3',
  'admin@apluselectric.ca',
  'canada/yarmouth/home-services/ryans-electrical-security-services',
  'ChIJWd8eYk0RVksROJgti3v9vcc',
  43.836322,
  -66.109049,
  '19027493661',
  'https://www.kwikr.ca/pictures/profile/pimage-535.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  545,
  'http://ryanselectrical.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'FlexiSnap',
  '<p>FlexiSnap, located in Montreal, Quebec, specializes in electrical installation services, offering innovative solutions for home access needs. The standout product, the FlexiSnap Magnetic Access Panel, effectively conceals water inlets, wiring, and plumbing, ensuring a clean and organized look in any room. This service enhances the aesthetics of homes while providing practical access to essential components.</p> <p>The FlexiSnap Magnetic Access Panel is designed for easy removal, allowing homeowners quick access to critical elements hidden behind walls or ceilings. This functionality saves time and effort during maintenance or repairs. The panel''s seamless integration into various decors ensures it remains unobtrusive, making it a practical choice for modern homes. FlexiSnap offers this product in three formats, catering to diverse customer needs and preferences.</p> <p>FlexiSnap has established itself as a reliable provider of electrical installation services in Montreal, focusing on customer satisfaction and innovative solutions. The ease of use and aesthetic appeal of the FlexiSnap Magnetic Access Panel demonstrates the company’s commitment to quality and functionality. The combination of practicality and design makes this service a valuable addition to any home.</p> <p>FlexiSnap provides effective electrical installation services, including the innovative magnetic access panel that simplifies home maintenance. The company’s dedication to quality and customer satisfaction is evident in its product offerings. Connect with FlexiSnap in Montreal for expert electrical installation services and innovative access solutions.</p>',
  '11303 26e Avenue',
  'Canada',
  'QC',
  'Montreal',
  'H1E 6N6',
  'automatisation@mjlelectrique.com',
  'canada/montreal/home-services/flexisnap',
  'ChIJ339yHCweyUwR-MdtypXLrx4',
  45.627817,
  -73.5794108,
  '18004791489',
  'https://www.kwikr.ca/pictures/profile/pimage-534.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  544,
  'http://flexisnap.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'PTW Energy Services',
  '<p>PTW Energy Services Ltd. provides top-tier electrical installation services in Bonnyville, Alberta. This private company, headquartered in Calgary, excels in delivering industry-leading solutions that include fabrication, construction, and maintenance services. With a robust network that spans Canada, the United States, the Middle East, and the Asia Pacific, PTW Energy Services has established a reputation for reliability and expertise.</p> <p>The company specializes in comprehensive electrical installation, ensuring that projects meet stringent safety and quality standards. PTW Energy Services employs skilled technicians who are trained to handle various electrical systems, making them a preferred choice for both residential and commercial needs. Their commitment to excellence has earned them a loyal client base in Bonnyville and beyond.</p> <p>PTW Energy Services remains dedicated to innovation and efficiency. The company utilizes advanced technology and best practices to enhance service delivery. This focus on continuous improvement contributes to their success in the competitive electrical installation sector. Clients appreciate the company’s ability to adapt to unique project requirements while maintaining high levels of service quality.</p> <p>In summary, PTW Energy Services Ltd. offers reliable electrical installation services in Bonnyville, Alberta, backed by a strong commitment to quality and safety. Their extensive experience and skilled workforce position them as a leader in the industry. Contact PTW Energy Services at 5718 54 Ave, Bonnyville, Alberta, for professional electrical solutions.</p>',
  '5718 54 Ave',
  'Canada',
  'AB',
  'Bonnyville',
  'T9N 0E4',
  'devin.mckay@elworthy.bc.ca',
  'canada/bonnyville/home-services/ptw-energy-services',
  'ChIJe6NFgAwHp1MRHtQ0ANvnhMk',
  54.2717224,
  -110.7647231,
  '17808264227',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  543,
  'http://www.ptwenergy.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'PTW Energy Services',
  '<p>PTW Energy Services, located at 11201 84 Ave, Fort Saskatchewan, Alberta, specializes in electrical installation services. This company delivers industry-leading solutions in fabrication, construction, and maintenance. With a network that spans Canada, the United States, the Middle East, and Asia Pacific, PTW Energy Services has built a strong reputation for reliability and expertise.</p> <p>Established in Calgary, Alberta, PTW Energy Services Ltd. focuses on providing top-notch electrical installation services tailored to meet diverse client needs. The company understands the importance of safety and efficiency in electrical projects, ensuring all work complies with industry standards. Their skilled team possesses extensive knowledge and experience, making them a trusted partner for various electrical needs.</p> <p>PTW Energy Services has achieved significant milestones in the electrical installation sector, consistently delivering projects on time and within budget. Their commitment to quality and customer satisfaction has earned them a loyal clientele in Fort Saskatchewan and beyond. The company emphasizes continuous improvement and innovation, adapting to the ever-changing demands of the industry.</p> <p>In summary, PTW Energy Services offers comprehensive electrical installation services, backed by a strong commitment to quality and safety. Their extensive experience and proven track record make them a reliable choice for clients. Connect with PTW Energy Services in Fort Saskatchewan for professional electrical installation solutions.</p>',
  '11201 84 Ave',
  'Canada',
  'AB',
  'Fort Saskatchewan',
  'T8L 4L1',
  'info@brantelectriclimited.ca',
  'canada/fort-saskatchewan/home-services/ptw-energy-services',
  'ChIJwTKp3gtHoFMRfmaZmSF3HV8',
  53.704677,
  -113.188626,
  '17809921399',
  'https://www.kwikr.ca/pictures/profile/pimage-532.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  542,
  'https://www.ptwenergy.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Spark Power',
  '<p>Spark Power offers reliable electrical installation services in Calgary, Alberta. This local business specializes in providing comprehensive solutions for residential and commercial electrical needs. With a commitment to quality and safety, Spark Power delivers professional installations that meet industry standards. The experienced team ensures that every project is completed efficiently and effectively, enhancing the electrical systems of homes and businesses alike.</p><p>Located at 5830 86 Ave SE, Spark Power serves the Calgary community with a focus on customer satisfaction. The company has built a reputation for its expertise in various electrical installations, including lighting systems, wiring, and panel upgrades. Each service is tailored to meet the unique requirements of clients, ensuring that all electrical installations are both functional and aesthetically pleasing.</p><p>With a proven track record of successful projects, Spark Power emphasizes the importance of safety and compliance in every job. The team stays updated on the latest electrical codes and technologies, providing clients with modern solutions that improve energy efficiency. The dedication to quality workmanship and customer care sets Spark Power apart in the electrical installation industry.</p><p>Spark Power delivers essential electrical installation services with a strong focus on safety and customer satisfaction. Their commitment to quality and expertise ensures reliable solutions for electrical needs. Connect with Spark Power in Calgary for professional electrical installation services.',
  '5830 86 Ave SE',
  'Canada',
  'AB',
  'Calgary',
  'T2C 4L7',
  'info@chermik.net',
  'canada/calgary/home-services/spark-power',
  'ChIJxTdfEvN5cVMRT4C2b-hEN7E',
  50.9765637,
  -113.9520295,
  '18337757697',
  'https://www.kwikr.ca/pictures/profile/pimage-531.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  541,
  'https://sparkpowercorp.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'FiberEx Electric',
  '<p>FiberEx Electric provides comprehensive electrical installation services in Newmarket, Ontario. This licensed electrical contractor, certified by the Electrical Safety Authority (ESA), specializes in residential, commercial, and industrial electrical solutions. Services include pot light installation, 200 amp panel upgrades, electrical service installation, diagnosis and repair, wiring, and EV car charger installations.</p> <p>FiberEx Electric has built a strong reputation for delivering reliable and professional electrical services. The team focuses on safety and compliance, ensuring that all work meets industry standards. With a commitment to quality, FiberEx Electric addresses the diverse needs of its clients, whether they require simple repairs or complex installations. The business prides itself on its ability to diagnose issues quickly and implement effective solutions, minimizing downtime for customers.</p> <p>The company''s expertise extends beyond basic installations. FiberEx Electric excels in modern electrical upgrades, including energy-efficient solutions that cater to the growing demand for electric vehicle charging stations. This forward-thinking approach positions the company as a leader in the electrical installation sector in Newmarket.</p> <p>FiberEx Electric remains dedicated to providing excellent service and innovative solutions for all electrical needs. Their licensed professionals ensure customer satisfaction through quality workmanship. For all electrical installation services in Newmarket, contact FiberEx Electric on Bob Gapp Dr, Ontario. </p>',
  'Bob Gapp Dr',
  'Canada',
  'ON',
  'Newmarket',
  'L3X 0C9',
  'info@stinsonelectrical.com',
  'canada/newmarket/home-services/fiberex-electric',
  'ChIJW1HAOs_TKogRAPIhU5OLtp0',
  44.0349806,
  -79.4162568,
  '14372548390',
  'https://www.kwikr.ca/pictures/profile/pimage-529.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  540,
  'https://fiberexelectric.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'BV Electric Ltd',
  '<p>BV Electric Ltd provides high-quality electrical installation services in Telkwa, British Columbia. This local business specializes in residential and commercial electrical work, ensuring safety and reliability for every project. With a commitment to excellence, BV Electric Ltd has built a reputation for professionalism and timely service.</p> <p>The team at BV Electric Ltd consists of skilled electricians who possess extensive knowledge and expertise in the electrical field. They handle a variety of services, including wiring, lighting installation, and electrical upgrades. Each project receives careful attention, ensuring compliance with local codes and standards. Customers appreciate the transparent communication and detailed consultations that help clarify project scopes and timelines.</p> <p>BV Electric Ltd prioritizes customer satisfaction, which is evident in their repeat business and positive testimonials. The business invests in ongoing training to keep up with the latest industry trends and technologies, ensuring they deliver modern solutions to meet diverse needs. This dedication to continuous improvement sets BV Electric Ltd apart in the competitive electrical installation market.</p> <p>With a strong focus on quality workmanship and customer service, BV Electric Ltd is a trusted choice for electrical installation services in Telkwa, British Columbia. Their expertise and commitment to excellence make them a reliable partner for any electrical project. Contact BV Electric Ltd at 2400 Telkwa High Rd, Telkwa, British Columbia, V0J 2X1 for professional electrical services.</p>',
  '2400 Telkwa High Rd',
  'Canada',
  'BC',
  'Telkwa',
  'V0J 2X1',
  'smiley.n@mjelectricalltd.com',
  'canada/telkwa/home-services/bv-electric-ltd',
  'ChIJfwMEMsygdVQRomDixzqX1m4',
  54.719526,
  -127.0556587,
  '12508779642',
  'https://www.kwikr.ca/pictures/profile/pimage-528.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  539,
  'http://www.bvelectric.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'EV TEC BC Pros',
  '<p>EV TEC BC Pros delivers expert electrical installation services focused on electric vehicle charger installation. Serving Burnaby and the Greater Vancouver area, this company addresses the growing demand for EV infrastructure. Founded by a licensed master electrician, EV TEC BC Pros aims to enhance public and private charging solutions for electric vehicles.</p> <p>The company specializes in providing tailored installation services for homeowners, businesses, and municipalities. EV TEC BC Pros understands the importance of reliable and efficient charging systems. Each installation is executed with precision, ensuring that clients receive high-quality service that meets their specific needs. The team is committed to creating a sustainable future by facilitating the transition to electric vehicles.</p> <p>With a focus on building a stable infrastructure, EV TEC BC Pros contributes to the community''s shift towards environmentally friendly transportation. The company’s reputation is built on professionalism and expertise in the electrical installation sector. Clients appreciate the attention to detail and commitment to safety during every project. The licensed master electrician leads the team, ensuring compliance with all regulations and standards.</p> <p>EV TEC BC Pros provides valuable services that support the growth of electric vehicle usage in Burnaby and Greater Vancouver. The company’s dedication to quality and sustainability makes it a key player in the local market. Connect with EV TEC BC Pros for expert electric vehicle charger installation in Burnaby, British Columbia. </p>',
  '722-6540 Hastings St',
  'Canada',
  'BC',
  'Burnaby',
  'V5B 4Z5',
  'info@donaldsonelectric.ca',
  'canada/burnaby/home-services/ev-tec-bc-pros',
  'ChIJ2_TvIAZvhlQRdhxnMapxMag',
  49.2794309,
  -122.968424,
  '17788914005',
  'https://www.kwikr.ca/pictures/profile/pimage-527.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  538,
  'https://evtec.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Pronghorn Controls Ltd',
  '<p>Pronghorn Controls Ltd offers specialized electrical installation services in Rocky Mountain House, Alberta. This local business excels in providing reliable solutions for residential and commercial electrical needs. With a focus on quality and safety, Pronghorn Controls ensures that each project meets industry standards while delivering efficient results.</p> <p>The team at Pronghorn Controls brings extensive experience in various electrical installations, including wiring, lighting, and control systems. This expertise allows them to handle complex projects with precision. Their commitment to customer satisfaction drives them to complete projects on time and within budget, making them a trusted choice in the community.</p> <p>Pronghorn Controls Ltd prioritizes safety and compliance, adhering to all relevant codes and regulations. This dedication to quality has earned them a reputation for excellence in the area. They utilize modern techniques and equipment, ensuring that installations are not only effective but also energy-efficient. Their approach combines technical knowledge with practical solutions, catering to the unique needs of each client.</p> <p>In summary, Pronghorn Controls Ltd provides top-notch electrical installation services in Rocky Mountain House, Alberta. Their strengths lie in their experienced team, commitment to safety, and customer-focused approach. For reliable electrical solutions, connect with Pronghorn Controls Ltd at 4427 47 St, Rocky Mountain House, Alberta.',
  '4427 47 St',
  'Canada',
  'AB',
  'Rocky Mountain House',
  'T4T 1A3',
  'qmasonelectrical@eastlink.ca',
  'canada/rocky-mountain-house/home-services/pronghorn-controls-ltd',
  'ChIJJUsXRCXZdVMRbbQttsP-w5s',
  52.3700074,
  -114.9066937,
  '14038455822',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  537,
  'https://www.pronghorn.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'SLE Enterprises Inc.',
  '<p>SLE Enterprises Inc. offers reliable electrical installation services in Sherbrooke, Quebec. This local business specializes in residential and commercial electrical work, ensuring that all installations meet the highest safety standards. With a commitment to quality and customer satisfaction, SLE Enterprises Inc. has built a strong reputation in the community.</p> <p>The team at SLE Enterprises Inc. possesses extensive expertise in various electrical systems. They handle everything from lighting installations to complete wiring solutions. Their technicians are trained to assess specific needs and provide tailored solutions that enhance both functionality and safety. This focus on detail ensures that all projects are completed efficiently and effectively.</p> <p>In addition to standard installation services, SLE Enterprises Inc. also offers emergency electrical repairs. This capability allows them to address urgent issues promptly, minimizing downtime for both homes and businesses. Their dedication to customer service has resulted in numerous positive reviews from satisfied clients in Sherbrooke.</p> <p>SLE Enterprises Inc. remains committed to providing exceptional electrical installation services that prioritize safety and reliability. The combination of skilled technicians and a customer-centric approach positions this business as a trusted choice for electrical needs in the region. Contact SLE Enterprises Inc. at 1837 Chem. Édouard-Roy, Sherbrooke, Quebec, for expert electrical services today.</p>',
  '1837 Chem. Édouard-Roy',
  'Canada',
  'QC',
  'Sherbrooke',
  'J1N 0G4',
  'sales@rtsservices.ca',
  'canada/sherbrooke/home-services/sle-enterprises-inc',
  'ChIJC5_7PmJKtkwRBmsvA4jHDio',
  45.3568337,
  -72.0500938,
  '18196120738',
  'https://www.kwikr.ca/pictures/profile/pimage-525.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  536,
  'http://lesentreprisessle.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Smith and Long (Head Office)',
  '<p>Smith and Long, located at 115 Idema Rd in Markham, Ontario, specializes in electrical installation services, HVAC/R solutions, and multi-trade engineering. With over 90 years of experience, this reputable company has consistently provided exceptional service and quick response times to customers throughout Canada.</p><p>The expertise of Smith and Long encompasses a wide range of electrical services, ensuring reliable installations and maintenance for both residential and commercial clients. Their commitment to quality and safety is evident in every project undertaken. The company’s skilled technicians are equipped to handle complex electrical systems and HVAC/R needs, delivering efficient solutions tailored to client specifications.</p><p>Smith and Long has built a strong reputation in the Markham area, recognized for its dedication to customer satisfaction and technical proficiency. This business not only meets but often exceeds industry standards, reflecting its long-standing presence in the electrical installation sector. Continuous training and adherence to the latest technologies ensure that Smith and Long remains at the forefront of the industry.</p><p>Offering a comprehensive range of services, Smith and Long stands as a reliable partner for electrical and HVAC/R needs. Their extensive experience and commitment to excellence make them a preferred choice for many. For quality electrical installation services in Markham, Ontario, connect with Smith and Long today.</p>',
  '115 Idema Rd',
  'Canada',
  'ON',
  'Markham',
  'L3R 1A9',
  'webmaster@northridgeelectric.net',
  'canada/markham/home-services/smith-and-long-head-office',
  'ChIJxcu974LU1IkRkYEV0L9Bb7k',
  43.8156187,
  -79.352664,
  '14163910443',
  'https://www.kwikr.ca/pictures/profile/pimage-524.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  535,
  'http://www.smithandlong.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Olds Electric & Lighting Ltd',
  '<p>Olds Electric & Lighting Ltd provides top-notch electrical installation services in Olds, Alberta. With a focus on residential and commercial projects, this local business excels in delivering safe and efficient electrical solutions. The skilled team at Olds Electric & Lighting Ltd ensures that every installation meets the highest standards of quality and safety, contributing to the well-being of the community.</p> <p>The company specializes in a range of services, including wiring, lighting installation, and electrical upgrades. Each project reflects a commitment to professionalism and customer satisfaction. Olds Electric & Lighting Ltd has built a reputation for reliability and expertise in the electrical installation sector. Their technicians are trained to handle various electrical systems, ensuring that all installations are performed with precision.</p> <p>Located at 6319 Imperial Way, Olds Electric & Lighting Ltd serves the surrounding areas with dedication. The company’s focus on innovative solutions and adherence to safety regulations sets it apart in the electrical installation industry. Clients appreciate the transparent communication and timely service provided by the team.</p> <p>Olds Electric & Lighting Ltd offers comprehensive electrical installation services tailored to meet diverse needs. Their commitment to quality and customer care solidifies their position as a trusted provider in Olds, Alberta. Connect with Olds Electric & Lighting Ltd for reliable electrical installation services today.</p>',
  '6319 Imperial Way',
  'Canada',
  'AB',
  'Olds',
  'T4H 1M5',
  'info@brahmatech.ca',
  'canada/olds/home-services/olds-electric-lighting-ltd',
  'ChIJgZumYe0QdFMRVjDKIJTYqVs',
  51.798751,
  -114.128784,
  '14035560192',
  'https://www.kwikr.ca/pictures/profile/pimage-523.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  534,
  'http://www.oldselectric.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Ryman Plumbing & Electrical',
  '<p>Ryman Plumbing & Electrical provides top-tier electrical installation services in Parry Sound, Ontario. Located at 1 Glenrock Rd, this business specializes in residential and commercial electrical solutions. With a commitment to quality and safety, Ryman Plumbing & Electrical has built a reputation for reliability and excellence in the local community.</p> <p>The team at Ryman Plumbing & Electrical consists of certified professionals with extensive experience in various electrical installations. Services include wiring upgrades, lighting installations, and circuit repairs. The company ensures adherence to all safety regulations and industry standards, which enhances customer trust. Ryman Plumbing & Electrical also offers emergency services, addressing urgent electrical issues promptly and efficiently.</p> <p>Customer satisfaction remains a core value for Ryman Plumbing & Electrical. The business has received numerous positive testimonials from clients who appreciate the professionalism and expertise displayed during every project. Their dedication to timely service and quality workmanship distinguishes them in the competitive electrical installation sector.</p> <p>Ryman Plumbing & Electrical serves the Parry Sound area with a focus on delivering exceptional electrical solutions. Their skilled team is equipped to handle a wide range of electrical needs. The commitment to quality and customer service has established a strong presence in the community. Contact Ryman Plumbing & Electrical at 1 Glenrock Rd, Parry Sound, Ontario, for reliable electrical installation services.</p>',
  '1 Glenrock Rd',
  'Canada',
  'ON',
  'Parry Sound',
  'P2A 2W9',
  'estimates@littleelectric.ca',
  'canada/parry-sound/home-services/ryman-plumbing-electrical',
  'ChIJW41ThGO5K00Rp8kygsGa9g4',
  45.4114441,
  -80.0858261,
  '17057739191',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  533,
  'http://ryman.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Pronghorn Controls Ltd',
  '<p>Pronghorn Controls Ltd provides top-notch electrical installation services in Redcliff, Alberta. With over 40 years of industry experience, this company has established itself as a reliable partner for clients in various sectors, including industrial, agricultural, mining, oil and gas, pipeline, and petrochemical industries. Since its incorporation in 1981, Pronghorn has focused on delivering high-quality instrumentation and electrical services that meet the diverse needs of its clientele across Western Canada.</p><p>The organization operates with a commitment to core values such as safety, integrity, performance, learning, and teamwork. These principles guide daily operations and decision-making processes, ensuring that clients receive the best possible service. Pronghorn''s forward-looking growth strategy opens new avenues for career advancement, making it an attractive employer in the region. The emphasis on communication and employee development has contributed to its reputation as an employer of choice.</p><p>Pronghorn Controls Ltd excels in providing essential electrical installation services tailored to the unique requirements of various industries. With a strong foundation built on decades of experience, the company continues to grow and adapt to changing market demands. The focus on safety and quality ensures that clients can trust Pronghorn for their electrical needs. Visit Pronghorn Controls Ltd in Redcliff to explore their comprehensive services and industry expertise.</p>',
  '1801 Broadway Ave E',
  'Canada',
  'AB',
  'Redcliff',
  'T0J 2P0',
  'info@schultz-electric.ca',
  'canada/redcliff/home-services/pronghorn-controls-ltd',
  'ChIJ6yspPTAtE1MRyQJ531RgSzE',
  50.0773619,
  -110.7600488,
  '14035273955',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  532,
  'https://pronghorn.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'PTW Energy Services',
  '<p>PTW Energy Services Ltd. offers comprehensive electrical installation services from its base in Redcliff, Alberta. This private company, with a strong presence across Canada, the United States, the Middle East, and Asia Pacific, specializes in fabrication, construction, and maintenance solutions. The expertise and reliability of PTW Energy Services have made it a notable player in the electrical installation sector.</p><p>With a commitment to quality and safety, PTW Energy Services ensures that all projects meet industry standards. The team employs advanced techniques and state-of-the-art technology to deliver efficient and effective electrical installations. Their well-trained professionals bring extensive experience to each project, ensuring timely completion and customer satisfaction.</p><p>PTW Energy Services has established a reputation for excellence in the electrical installation service category. The company''s operational reach and diverse capabilities enable it to cater to various sectors, including commercial, industrial, and residential projects. Clients benefit from a tailored approach that addresses specific needs and requirements, ensuring optimal results.</p><p>In summary, PTW Energy Services Ltd. provides top-notch electrical installation services in Redcliff, Alberta. The company''s strengths lie in its extensive network, skilled workforce, and commitment to quality. For reliable electrical solutions, connect with PTW Energy Services at 170 Saskatchewan Dr NE, Redcliff, Alberta, T0J 2P0.</p>',
  '170 Saskatchewan Dr NE',
  'Canada',
  'AB',
  'Redcliff',
  'T0J 2P0',
  'blair@net-electric.com',
  'canada/redcliff/home-services/ptw-energy-services',
  'ChIJhT2DXy0tE1MRvM5VtYaigG4',
  50.0798116,
  -110.7607004,
  '14035267325',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  531,
  'http://www.ptwenergy.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Rob''s Electric',
  '<p>Rob''s Electric provides comprehensive electrical installation services in Chatham, Ontario. This local business specializes in a wide range of electrical solutions, including emergency services, panel upgrades, and home renovations. With a focus on quality and compliance, Rob''s Electric ensures that all work meets the highest standards of safety and efficiency.</p><p>As a certified electrical contractor, Rob''s Electric excels in both residential and industrial electrical services. The team is skilled in troubleshooting, repairs, and installations, ensuring that clients receive reliable and prompt assistance. Services include the installation of electric car chargers, outdoor lighting, security systems, and more. The company prioritizes customer satisfaction, offering 24/7 emergency services to address urgent electrical issues.</p><p>Rob''s Electric is recognized for its commitment to excellence and professionalism. Each electrician is trained and experienced, providing peace of mind to homeowners and businesses alike. The company’s focus on code compliance and safety ensures that all installations and repairs adhere to local regulations.</p><p>Rob''s Electric stands as a trusted provider of electrical solutions in Chatham. With a wide range of services, a dedicated team, and a commitment to quality, this business meets the diverse needs of its customers. Contact Rob''s Electric today for expert electrical services in Chatham, Ontario.</p>',
  '869 Park Ave W',
  'Canada',
  'ON',
  'Chatham',
  'N7M 0N1',
  'webmaster@thinkgreenelectrical.com',
  'canada/chatham/home-services/rob-s-electric',
  'ChIJqcMW1LrhL4gRRoJx8nfhZCQ',
  42.378219,
  -82.204471,
  '15193512265',
  'https://www.kwikr.ca/pictures/profile/pimage-519.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  530,
  'http://robselectric.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'SNF Electrical Services Inc.',
  '<p>SNF Electrical Services Inc. provides comprehensive electrical installation services in Dartmouth, Nova Scotia. This company specializes in residential and commercial projects, including heat pumps, service entrance upgrades, new wiring, and renovations. Fully insured, bonded, and licensed, SNF Electrical Services Inc. employs Red Seal electricians and Red Seal HVAC technicians, ensuring quality and compliance with industry standards.</p><p>The expertise of SNF Electrical Services Inc. extends to panel changes and water heater installations, making it a reliable choice for various electrical needs. As a secondary service provider with Nova Scotia Power, the company guarantees efficient and effective service delivery. The team is committed to maintaining high safety standards while meeting the unique requirements of each project.</p><p>Clients appreciate the professionalism and skill demonstrated by the technicians at SNF Electrical Services Inc. Their ability to handle both small and large-scale jobs sets them apart in the Dartmouth area. The company’s dedication to customer satisfaction is evident in its attention to detail and commitment to timely project completion.</p><p>SNF Electrical Services Inc. excels in providing a range of electrical installation services for both residential and commercial clients. Their licensed professionals ensure quality workmanship and adherence to safety regulations. Engage with SNF Electrical Services Inc. for reliable electrical solutions in Dartmouth, Nova Scotia.',
  '462 Arklow Dr',
  'Canada',
  'NS',
  'Dartmouth',
  'B2W 4S4',
  'service@jmlelectric.ca',
  'canada/dartmouth/home-services/snf-electrical-services-inc',
  'ChIJC3qbK24lWksRFfhvHgyvWo4',
  44.6778354,
  -63.4836303,
  '19022194645',
  'https://www.kwikr.ca/pictures/profile/pimage-518.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  529,
  'https://www.snfelectric.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'ABIXÉL',
  '<p>ABIXÉL provides comprehensive electrical installation services in Amos, Quebec. Specializing in electric vehicle charging station installations, residential wiring, instrumentation and control, and renewable energy solutions, this business meets the growing demand for sustainable energy practices. ABIXÉL is committed to enhancing energy efficiency and promoting clean energy alternatives through solar panels and battery systems.</p> <p>With a focus on quality and reliability, ABIXÉL ensures that each project adheres to the highest industry standards. The team possesses extensive knowledge in electrical systems, making them a trusted choice for both residential and commercial clients. Their expertise in electric vehicle charging solutions positions them as a leader in the transition towards greener transportation options. The company also emphasizes the importance of renewable energy, providing clients with innovative solutions that reduce their carbon footprint.</p> <p>ABIXÉL’s dedication to customer satisfaction and sustainable practices has earned them a reputable standing in the Amos community. The business not only installs electrical systems but also educates clients on the benefits of renewable energy and electric vehicle infrastructure. Their commitment to excellence and community engagement reflects a strong local presence.</p> <p>ABIXÉL offers essential electrical installation services, focusing on electric vehicle charging stations, home wiring, and renewable energy solutions. Their expertise and commitment to quality make them a valuable resource in Amos. Connect with ABIXÉL for reliable electrical installation services in Quebec. </p>',
  '92 Rue Beaudry',
  'Canada',
  'QC',
  'Amos',
  'J9T 3V2',
  'sweeneyelectric@sasktel.net',
  'canada/amos/home-services/abixél',
  'ChIJl4-_cE2NIE0Rx-4TRI1JFjA',
  48.5629235,
  -78.1120016,
  '18194448947',
  'https://www.kwikr.ca/pictures/profile/pimage-517.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  528,
  'http://abixel.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'ConstCorp Electric',
  '<p>ConstCorp Electric provides top-notch electrical installation services in North York, Ontario. This local business emphasizes quality service and expertise for both residential and commercial customers. With a strong commitment to family values and ethical business practices, ConstCorp Electric has built a reputable presence in the community.</p><p>The company prides itself on its customer-centric approach. When contacting ConstCorp Electric, knowledgeable representatives assess the job immediately, determining if an on-site estimate is necessary. This no-cost assessment provides transparency and builds trust with clients. Whether addressing new installations or troubleshooting existing electrical issues, ConstCorp Electric offers tailored solutions to meet diverse needs.</p><p>With over ten years of continuous experience, ConstCorp Electric has developed a solid foundation in the electrical service industry. Certified electricians work under the guidance of a master licensed and insured company, ensuring high standards of safety and professionalism. The team''s expertise spans various electrical tasks, making them a reliable choice for any project.</p><p>ConstCorp Electric excels in delivering quality service, ethical practices, and customer satisfaction. Their commitment to excellence and community values sets them apart. For reliable electrical services in North York, Ontario, reach out to ConstCorp Electric for expert assistance.',
  NULL,
  'Canada',
  'ON',
  'North York',
  'M2M 2C6',
  'brad.carter@vicarelectric.com',
  'canada/north-york/home-services/constcorp-electric',
  'ChIJJfK7YnPNKogRP8GXGu4m7HQ',
  43.7913788,
  -79.3920839,
  '16477875704',
  'https://www.kwikr.ca/pictures/profile/pimage-516.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  527,
  'http://constcorp.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Current Electric Services',
  '<p>Current Electric Services provides top-notch electrical installation services in Oakville, Ontario. This reliable electrical contractor caters to commercial, residential, and industrial sectors, ensuring safe and efficient electrical solutions. With a strong commitment to quality and customer satisfaction, Current Electric Services has built a reputation for excellence in the local community.</p> <p>Current Electric Services emphasizes professionalism and expertise in every project. The skilled team handles various electrical installations, from wiring and lighting to complex industrial systems. This company prioritizes safety and adheres to all local regulations, making it a trusted choice for clients in Oakville and surrounding areas. The diverse experience in different sectors allows Current Electric Services to tackle projects of any scale with confidence.</p> <p>Customer feedback highlights the company''s dedication to timely service and transparent communication. Clients appreciate the straightforward approach taken by the team, which fosters trust and reliability. Current Electric Services remains focused on delivering high-quality work while maintaining competitive pricing. The team''s extensive knowledge ensures that all electrical needs are met efficiently and effectively.</p> <p>Current Electric Services stands ready to meet the electrical needs of the Oakville community. With a strong emphasis on quality, safety, and customer satisfaction, this electrical installation service excels in various sectors. Contact Current Electric Services at 2379 Royal Windsor Dr, Oakville, Ontario, for exceptional electrical solutions.</p>',
  '2379 Royal Windsor Dr',
  'Canada',
  'ON',
  'Oakville',
  'L6J 7X6',
  'office@haltonelectric.com',
  'canada/oakville/home-services/current-electric-services',
  'ChIJZco8TCa6Vq8RnsobrZM_k2o',
  43.4925202,
  -79.6504959,
  '14169953424',
  'https://www.kwikr.ca/pictures/profile/pimage-515.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  526,
  'http://www.currentelectricservices.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Westshore Electrical Ltd.',
  '<p>Westshore Electrical Ltd. provides reliable electrical installation services in Nanaimo, British Columbia. This local business specializes in residential and commercial electrical projects, ensuring safety and efficiency in every job. With a team of skilled electricians, Westshore Electrical Ltd. has built a reputation for quality workmanship and attention to detail. Their services include wiring, lighting installation, and electrical upgrades, catering to the diverse needs of the community.</p> <p>The experienced professionals at Westshore Electrical Ltd. prioritize customer satisfaction and adhere to all safety regulations. They understand the importance of timely service and work diligently to complete projects on schedule. This commitment to excellence has earned them a loyal customer base in Nanaimo and surrounding areas. Each project reflects their dedication to quality, from small repairs to large installations.</p> <p.Westshore Electrical Ltd. stands out with its transparent pricing and thorough consultations. Their knowledgeable team guides clients through the electrical installation process, ensuring clarity and understanding at every stage. This approach fosters trust and reliability, making them a preferred choice for electrical services in the region.</p> <p.Westshore Electrical Ltd. offers comprehensive electrical installation services, emphasizing quality and customer care. Their skilled team consistently delivers exceptional results, making them a trusted partner for electrical needs in Nanaimo. Connect with Westshore Electrical Ltd. for professional electrical installation services in Nanaimo, British Columbia.</p>',
  NULL,
  'Canada',
  'BC',
  'Nanaimo',
  NULL,
  'careers@seacliffelectric.ca',
  'canada/nanaimo/home-services/westshore-electrical-ltd',
  'ChIJpS5H0kWfiFQRyITOOGE8KJ0',
  49.2361632,
  -124.0100546,
  '12507136074',
  'https://www.kwikr.ca/pictures/profile/pimage-514.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  525,
  'https://westshoreelectrical.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Donovan Associates Inc.',
  '<p>Donovan Associates Inc. provides reliable electrical installation services in Saint John, New Brunswick. With a commitment to quality and safety, this company ensures that all electrical systems meet industry standards. Their expertise spans residential and commercial projects, making them a versatile choice for various electrical needs.</p> <p>The team at Donovan Associates Inc. brings years of experience to the table. They handle everything from basic wiring to complex electrical installations. Clients appreciate the attention to detail and adherence to timelines. This company prioritizes customer satisfaction, which reflects in their growing list of successful projects and positive feedback.</p> <p>Donovan Associates Inc. operates with a strong focus on safety and compliance. Each project undergoes thorough inspections to guarantee reliability and performance. Their technicians are well-trained and equipped with the latest tools and technology. This ensures that all installations not only meet but exceed expectations.</p> <p>In addition to electrical installations, Donovan Associates Inc. offers maintenance services to keep systems running smoothly. This proactive approach helps prevent issues before they arise, saving clients time and money in the long run. Their reputation in Saint John as a dependable electrical service provider continues to grow.</p> <p>Donovan Associates Inc. delivers quality electrical installation and maintenance services, ensuring customer satisfaction and safety. Their commitment to excellence makes them a trusted partner in the local community. Connect with Donovan Associates Inc. at 2151 Loch Lomond Rd, Saint John, New Brunswick, E2N 1A1 for professional electrical solutions.</p>',
  '2151 Loch Lomond Rd',
  'Canada',
  'NB',
  'Saint John',
  'E2N 1A1',
  'info@ospreyelectric.com',
  'canada/saint-john/home-services/donovan-associates-inc',
  'ChIJAX3VqBuyp0wR0KQ1CxrZRcI',
  45.3161588,
  -65.9627868,
  '15066968356',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  524,
  'http://donovanassociates.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);
