INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Alcor Management Inc',
  '<p>Alcor Management Inc operates as a reliable general contractor in Fort McMurray, Alberta. This company specializes in a variety of construction services, including residential and commercial projects. With a focus on quality and customer satisfaction, Alcor Management Inc has built a strong reputation in the local community.</p><p>The team at Alcor Management Inc brings extensive experience to every project. They manage everything from renovations to new builds, ensuring that all work meets industry standards. Clients appreciate the attention to detail and the commitment to timelines. This dedication has earned Alcor Management Inc numerous positive reviews and repeat business from satisfied customers.</p><p>In addition to construction, Alcor Management Inc offers consultation services. Their expertise helps clients navigate the complexities of building regulations and project management. This guidance proves invaluable for those unfamiliar with the construction process. The firm emphasizes transparency and communication, which fosters trust and collaboration with clients.</p><p>Alcor Management Inc is not just a construction company; it is a partner in turning visions into reality. The blend of skilled craftsmanship and professional service sets this business apart in Fort McMurray. Clients can rely on Alcor Management Inc for timely and efficient project completion.</p><p>Explore the comprehensive services offered by Alcor Management Inc, including construction and consultation. Their strong reputation and commitment to quality make them a preferred choice in Fort McMurray. Connect with Alcor Management Inc today for all general contracting needs in Alberta.</p>',
  '305 Macdonald Crescent',
  'Canada',
  'AB',
  'Fort McMurray',
  'T9H 4B7',
  'shawn@alp2017.ca',
  'canada/fort-mcmurray/home-services/alcor-management-inc',
  'ChIJ46wImH0GsFMRbhRaIWmhe90',
  56.6688352,
  -111.3415167,
  '17807431343',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  848,
  'https://alcorfacilities.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Alberta Lightning Protection 2017 Ltd.',
  '<p>Alberta Lightning Protection 2017 Ltd. serves Parkland County, Alberta, as a reliable general contractor specializing in lightning protection systems. The company provides essential services to homeowners and businesses, ensuring safety and compliance with industry standards. With a strong reputation for quality workmanship, Alberta Lightning Protection has become a trusted name in the local community.</p> <p>As an experienced general contractor, Alberta Lightning Protection offers comprehensive solutions tailored to the unique needs of each client. The team focuses on delivering efficient installations and maintenance of lightning protection systems, which are crucial for safeguarding properties against the dangers of lightning strikes. The company prides itself on using high-quality materials and adhering to strict safety protocols.</p> <p>The commitment to customer satisfaction sets Alberta Lightning Protection apart. Clients benefit from personalized service, prompt responses, and expert advice throughout the project. The company has successfully completed numerous projects, showcasing its expertise in lightning protection systems. Alberta Lightning Protection is dedicated to educating clients about the importance of lightning safety and the benefits of professional installations.</p> <p>Alberta Lightning Protection 2017 Ltd. delivers essential services in lightning protection, emphasizing quality and safety. The company’s strong local presence and commitment to excellence make it a top choice for general contracting needs in Parkland County. Reach out to Alberta Lightning Protection for professional lightning protection services in Alberta.</p>',
  '20 53302 Range Rd 12',
  'Canada',
  'AB',
  'Parkland County',
  'T7Y 0B9',
  'dkuschminder@chandos.com',
  'canada/parkland-county/home-services/alberta-lightning-protection-2017-ltd',
  'ChIJj2v_8Mibn1MRp02WtuX4gEg',
  53.5890021,
  -114.0566912,
  '17807194505',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  847,
  'http://www.albertalightningprotection.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Chandos Construction Calgary Yard',
  '<p>Chandos Construction Calgary Yard operates as a general contractor in Calgary, Alberta, providing a range of construction services. This company specializes in residential and commercial projects, ensuring high-quality workmanship and timely completion. With a focus on client satisfaction, Chandos Construction has built a strong reputation in the local community.</p><p>Established in Calgary, Chandos Construction Calgary Yard has become a trusted name in the construction industry. The team consists of experienced professionals who understand the complexities of building and renovation projects. They prioritize safety and adhere to all local regulations, ensuring that every project meets industry standards. The company has successfully completed numerous projects, showcasing their ability to handle diverse construction needs.</p><p>Chandos Construction offers services that include project management, renovations, and new builds. The company collaborates closely with clients to ensure their vision becomes a reality. Each project is approached with attention to detail, and the team remains accessible throughout the construction process. Their commitment to excellence has led to numerous satisfied clients in Calgary.</p><p>In summary, Chandos Construction Calgary Yard provides comprehensive general contracting services in Calgary, Alberta. Their expertise, dedication to quality, and strong community ties make them a reliable choice for construction needs. Connect with Chandos Construction Calgary Yard at 7287 106 Ave SE for professional construction services in Calgary.</p>',
  '7287 106 Ave SE',
  'Canada',
  'AB',
  'Calgary',
  'T2C 4Z8',
  'info@morinvilleflooring.ca',
  'canada/calgary/home-services/chandos-construction-calgary-yard',
  'ChIJ8cyl-hl5cVMRfPGaWP5AJaw',
  50.96228,
  -113.92972,
  '14032060150',
  'https://www.kwikr.ca/pictures/profile/pimage-845.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  846,
  'http://www.chandos.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Morinville Flooring Centre Ltd',
  '<p>Morinville Flooring Centre Ltd, located at 10310 101 Ave in Morinville, Alberta, has been a trusted general contractor for over 20 years. This local business specializes in providing high-quality floor coverings, ensuring a positive customer experience through exceptional products and friendly service. The commitment to excellence is evident in every project, from initial consultation to final installation.</p> <p>Offering free, no-obligation estimates, Morinville Flooring prioritizes customer satisfaction. Knowledgeable staff members are always available to address any questions or concerns, making the process seamless for homeowners and businesses alike. The company prides itself on integrity, never cutting corners, and delivering the best possible results. The focus remains on providing top-tier products and installation services, ensuring that every client receives outstanding value.</p> <p>Morinville Flooring Centre is also recognized for its expertise in luxury vinyl plank flooring, catering to diverse design preferences and practical needs. With a second location in Edmonton, the business expands its reach while maintaining its commitment to quality and service. The dedication to doing things right has earned Morinville Flooring a loyal customer base in the community.</p> <p>Overall, Morinville Flooring Centre Ltd excels in delivering quality flooring solutions and customer service. The long-standing reputation and commitment to excellence make it a reliable choice for flooring needs in Morinville and surrounding areas. Visit Morinville Flooring Centre Ltd in Morinville for exceptional flooring options and services.</p>',
  '10310 101 Ave',
  'Canada',
  'AB',
  'Morinville',
  'T8R 1T4',
  'greg@alliance-renovations.com',
  'canada/morinville/home-services/morinville-flooring-centre-ltd',
  'ChIJpzeCjnctoFMRgW1CncZZI38',
  53.8039054,
  -113.6524689,
  '17809397212',
  'https://www.kwikr.ca/pictures/profile/pimage-844.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  845,
  'https://www.morinvilleflooring.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Alliance Renovations',
  '<p>Alliance Renovations operates as a general contractor in East Gwillimbury, Ontario, providing comprehensive renovation services for over 20 years. This experienced team specializes in various projects, ranging from bathroom remodels to complete home renovations. The commitment to quality and customer satisfaction has established a strong reputation in the local community.</p><p>With a focus on efficiency and reliability, Alliance Renovations ensures that every project meets high standards. The skilled professionals are equipped to handle diverse renovation needs, allowing homeowners to transform their spaces seamlessly. The company emphasizes clear communication and transparency throughout the renovation process, which builds trust with clients.</p><p>Alliance Renovations takes pride in its ability to simplify complex renovation tasks. Each project is approached with meticulous attention to detail, ensuring that the final outcome aligns with the homeowner''s vision. The team works diligently to minimize disruption and deliver results on time.</p><p>East Gwillimbury residents benefit from the extensive expertise offered by Alliance Renovations. The company’s long-standing presence in the area has fostered strong relationships with local suppliers and contractors, enhancing the overall service provided to clients. The dedication to quality craftsmanship and customer care sets Alliance Renovations apart in the competitive renovation market.</p><p>Alliance Renovations delivers exceptional renovation services, showcasing strengths in project management and customer satisfaction. The commitment to excellence is evident in every completed project. Reach out to Alliance Renovations for reliable renovation solutions in East Gwillimbury, Ontario.</p>',
  '154 Countryman Rd',
  'Canada',
  'ON',
  'East Gwillimbury',
  'L9N 0N8',
  'imignault@mcfinc.ca',
  'canada/east-gwillimbury/home-services/alliance-renovations',
  'ChIJL_kPBHgpK4gR1JN22PSxKW4',
  44.10835,
  -79.4470599,
  '16475283373',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  844,
  'http://www.alliance-renovations.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Marcel Charest Et Fils',
  '<p>Marcel Charest Et Fils operates as a general contractor in Saint-Pascal, Quebec. This business specializes in delivering high-quality construction and renovation services tailored to meet the needs of residential and commercial clients. With a strong commitment to excellence, Marcel Charest Et Fils has established a reputation for reliability and skilled craftsmanship in the local area.</p><p>The company offers a range of services including home renovations, commercial construction, and project management. Each project is approached with a focus on detail and customer satisfaction. Experienced professionals handle every aspect of construction, ensuring that timelines and budgets are respected. The team utilizes quality materials and innovative techniques to achieve durable and aesthetically pleasing results.</p><p>Marcel Charest Et Fils has successfully completed numerous projects throughout Saint-Pascal and surrounding regions. Clients appreciate the transparent communication and dedicated service provided by the team. The business prioritizes building lasting relationships with customers, which contributes to its strong reputation in the community.</p><p>With a focus on quality, reliability, and customer satisfaction, Marcel Charest Et Fils continues to excel in the general contracting field. The company’s expertise makes it a preferred choice for construction and renovation needs in Saint-Pascal. Reach out to Marcel Charest Et Fils for professional general contracting services in Quebec.</p>',
  '997, 230 RTE E',
  'Canada',
  'QC',
  'Saint-Pascal',
  'G0L 3Y0',
  'admin@arwestcoastcontracting.ca',
  'canada/saint-pascal/home-services/marcel-charest-et-fils',
  'ChIJn8egGYP2vkwREhpHCx_efxg',
  47.5462053,
  -69.7777334,
  '14184925911',
  'https://www.kwikr.ca/pictures/profile/pimage-842.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  843,
  'http://mcfinc.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'A & R West Coast Contracting Ltd.',
  '<p>A & R West Coast Contracting Ltd. operates as a premier general contractor in North Vancouver, British Columbia. This company specializes in residential luxury renovations, including single-family homes and mixed-use projects. A & R provides a comprehensive range of services, from home repairs and additions to new builds. Their expertise extends to essential maintenance tasks such as framing, roofing, siding, flooring, decks, fences, and demolition.</p><p>The team at A & R West Coast Contracting Ltd. consists of highly skilled tradesmen dedicated to transforming client visions into reality. Whether upgrading a bathroom, executing a full home makeover, or remodeling a kitchen, the team ensures a seamless process. Clients receive thorough guidance, with every scenario considered and questions answered throughout the construction journey.</p><p>Serving both Metro Vancouver and the Sea-to-Sky Corridor, A & R West Coast Contracting Ltd. has established a reputation for reliability and quality. The company''s commitment to excellence is evident in every project, ensuring that renovations meet the highest standards. With a focus on customer satisfaction, A & R prioritizes clear communication and professionalism, making them a trusted choice for any construction needs.</p><p>A & R West Coast Contracting Ltd. delivers exceptional general contracting services, specializing in luxury renovations and essential home improvements. Their experienced team guarantees a smooth process from start to finish. Connect with A & R West Coast Contracting Ltd. in North Vancouver for expert construction services.</p>',
  '4417 Glencanyon Dr',
  'Canada',
  'BC',
  'North Vancouver',
  'V7N 4B4',
  'corpaffairs@aecon.com',
  'canada/north-vancouver/home-services/a-r-west-coast-contracting-ltd',
  'ChIJP0RNqt9vhlQRUmTHPqg0gAg',
  49.3515075,
  -123.0854507,
  '16043415069',
  'https://www.kwikr.ca/pictures/profile/pimage-841.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  842,
  'https://arwestcoastcontracting.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Aecon Group Inc.',
  '<p>Aecon Group Inc. operates as a leading general contractor in Etobicoke, Ontario. This company specializes in providing construction management, design-build, and project management services. With a commitment to quality and efficiency, Aecon Group Inc. has successfully completed numerous projects across various sectors, showcasing its versatility and expertise in the construction industry.</p><p.The company is located at 20 Carlson Ct, allowing it to serve the Greater Toronto Area effectively. Aecon Group Inc. prides itself on its skilled workforce and innovative approaches to construction challenges. The team utilizes advanced technologies and sustainable practices to ensure projects meet modern standards while minimizing environmental impact.</p><p.Aecon Group Inc. has established a reputation for delivering projects on time and within budget. The company’s portfolio includes residential, commercial, and infrastructure projects, demonstrating its capability to handle diverse construction needs. Client satisfaction remains a priority, with a strong focus on communication and collaboration throughout the project lifecycle.</p><p.Aecon Group Inc. continues to contribute to the growth and development of Etobicoke and surrounding regions. Its dedication to excellence and community engagement sets it apart in the competitive construction landscape. For reliable general contracting services that prioritize quality and efficiency, Aecon Group Inc. remains a top choice. Visit Etobicoke to explore how Aecon Group Inc. can assist with construction needs.',
  '20 Carlson Ct',
  'Canada',
  'ON',
  'Etobicoke',
  'M9W 7K6',
  'info@redstonecontracting.com',
  'canada/etobicoke/home-services/aecon-group-inc',
  'ChIJb-In-Iw5K4gR_McKr_qCNFc',
  43.6900498,
  -79.5854128,
  '14162972600',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  841,
  'http://www.aecon.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Home Renovation Contractors By Red Stone Contracting',
  '<p>Home Renovation Contractors By Red Stone Contracting operates as a reputable general contractor in Oakville, Ontario. This family-owned construction company specializes in a variety of renovation services, including kitchen renovations, basement renovations, home additions, and landscaping. Red Stone Contracting serves not only Oakville but also Burlington and the entire Greater Toronto Area (GTA), ensuring quality and reliability in every project.</p><p>The commitment to budget-friendly and cost-effective kitchen renovations sets Red Stone Contracting apart. The skilled team members focus on delivering high-quality work while adhering to clients'' budgets and timelines. Fast support from the office enhances the customer experience, ensuring that all inquiries and needs are addressed promptly. The use of high-quality materials guarantees durability and satisfaction in every renovation project.</p><p>Red Stone Contracting has built a reputation for excellence in home renovations. The family-oriented approach fosters trust and peace of mind for clients, knowing their homes are in capable hands. The company prioritizes clear communication and transparency throughout the renovation process, making it easy for clients to stay informed and engaged.</p><p>With a strong emphasis on quality, affordability, and customer service, Red Stone Contracting excels in providing comprehensive renovation solutions. Reach out to Red Stone Contracting at 1040 Speers Rd, Oakville, Ontario, to explore their services today.</p>',
  '1040 Speers Rd',
  'Canada',
  'ON',
  'Oakville',
  'L6L 2X4',
  'basconst@nbnet.nb.ca',
  'canada/oakville/home-services/home-renovation-contractors-by-red-stone-contracting',
  'ChIJoRfvSvlgK4gRWKAdaBDoHqQ',
  43.4323022,
  -79.7027606,
  '19059011006',
  'https://www.kwikr.ca/pictures/profile/pimage-839.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  840,
  'http://redstonecontracting.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Basque Construction Ltee Ltd',
  '<p>Basque Construction Ltee Ltd operates as a reliable general contractor in Tracadie-Sheila, New Brunswick. This company specializes in a variety of construction services, including residential renovations, commercial builds, and custom projects. With a strong commitment to quality and customer satisfaction, Basque Construction has established a solid reputation in the local community.</p> <p>Experience defines Basque Construction Ltee Ltd. The team brings extensive knowledge to every project, ensuring that all construction needs are met efficiently. Attention to detail remains a priority, resulting in structures that not only meet but exceed client expectations. The company employs skilled professionals who work diligently to provide timely and effective solutions in building and renovation.</p> <p>Basque Construction''s approach emphasizes collaboration with clients. This method fosters clear communication and understanding of project goals. The team utilizes high-quality materials and modern techniques, ensuring durability and aesthetic appeal in every project. Their successful track record highlights numerous completed projects that showcase their expertise and dedication to excellence.</p> <p>With a focus on quality craftsmanship and customer service, Basque Construction Ltee Ltd continues to thrive in the competitive construction market. Their ability to adapt to various project demands sets them apart. For those seeking reliable construction services in Tracadie-Sheila, reach out to Basque Construction Ltee Ltd at 4116 Rue Principale, New Brunswick. </p>',
  '4116 Rue Principale',
  'Canada',
  'NB',
  'Tracadie-Sheila',
  'E1X 1B8',
  'inquiries@karlenkada.com',
  'canada/tracadie-sheila/home-services/basque-construction-ltee-ltd',
  'ChIJx1o0Vh1Jn0wRdBfsnz0jNJc',
  47.4875679,
  -64.9188889,
  '15063956339',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  839,
  'https://basqueconstructionltee.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Karlen Group',
  '<p>Karlen Group operates as a leading general contractor in Edmonton, Alberta, with a rich history dating back to 1967. This well-established company offers a comprehensive range of services, including new construction, building envelopes, mold and asbestos abatement, restorations, and specialized electrical and mechanical contracting. Karlen Group serves both residential and commercial clients, ensuring quality workmanship and adherence to safety standards.</p><p>The General Contracting Division showcases expertise in managing diverse construction projects, delivering results that meet client expectations. With a focus on quality and efficiency, the team handles everything from initial planning to final execution. The Electrical Contracting Division emphasizes the importance of reliable electrical installations and upgrades, alongside robust fire safety systems that protect properties and lives.</p><p>In addition, the Mechanical Division stands out with its proficiency in sprinkler design and installation, plumbing, and heating services. This division also excels in delivering advanced electronic systems, including commercial audio and video solutions, intercom systems, and closed circuit video surveillance. Each project reflects the company’s commitment to innovation and safety.</p><p>Karlen Group maintains a strong reputation within the Edmonton community for its dedication to quality and service. The combination of experienced professionals and a broad service offering positions the company as a trusted partner for any construction need. Engage with Karlen Group for expert contracting services in Edmonton, Alberta.</p>',
  '14620 118 Ave NW',
  'Canada',
  'AB',
  'Edmonton',
  'T5L 2M8',
  'estimating@espositobros.com',
  'canada/edmonton/home-services/karlen-group',
  'ChIJ4xPIB0whoFMRZS3scWQNrWw',
  53.570699,
  -113.5740423,
  '17804531362',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  838,
  'https://www.karlengroup.ca/home',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Esposito Bros Construction',
  '<p>Esposito Bros. Construction Ltd. (EBC) operates as a prominent general contractor in Bolton, Ontario. Established in 1981, the company initially focused on concrete curb and sidewalk projects. Over the years, EBC expanded its expertise to encompass a wide range of heavy civil and road building services, showcasing a strong commitment to quality and reliability in construction.</p> <p>EBC has successfully executed numerous contracts, demonstrating proficiency in reconstructing major arterial roadways and large structural culvert installations. The company excels in mass excavations and the installation of kilometers of sewer and water mains, ensuring essential infrastructure development. Rehabilitation and replacement of bridges and other structures are also key services that highlight EBC''s capabilities. The team is skilled in site works for new building construction, as well as the fabrication and installation of concrete noise barrier walls and retaining walls.</p> <p>With a rich history and extensive experience in the construction industry, Esposito Bros. Construction maintains a reputation for delivering high-quality results. The company''s commitment to safety, efficiency, and client satisfaction sets it apart in the competitive landscape of general contracting. EBC’s track record of successful project completion speaks volumes about its expertise and dedication. Contact Esposito Bros. Construction in Bolton for reliable construction services that meet community needs.</p>',
  '290 Healey Rd',
  'Canada',
  'ON',
  'Bolton',
  'L7E 1C9',
  'mail@peakgrp.com',
  'canada/bolton/home-services/esposito-bros-construction',
  'ChIJeUctj3zfKogRy2a4Trc0Ltk',
  43.8619372,
  -79.7288141,
  '19058571191',
  'https://www.kwikr.ca/pictures/profile/pimage-836.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  837,
  'https://espositobros.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Peak Construction Group',
  '<p>Peak Construction Group operates as a reliable general contractor in Surrey, British Columbia. This company specializes in residential and commercial construction projects, delivering high-quality workmanship and exceptional customer service. With a strong focus on client satisfaction, Peak Construction Group has built a solid reputation in the local community.</p><p>Established in Surrey, Peak Construction Group provides comprehensive construction services, including renovations, new builds, and project management. The team of skilled professionals ensures that each project meets strict standards and is completed on time and within budget. Their attention to detail and commitment to quality sets them apart in the competitive construction industry.</p><p>The company prioritizes communication and collaboration, working closely with clients to understand their needs and vision. This approach fosters trust and ensures that the final product aligns with client expectations. Peak Construction Group also emphasizes sustainability, incorporating eco-friendly practices and materials wherever possible.</p><p>Peak Construction Group has successfully completed numerous projects throughout Surrey, showcasing their versatility and expertise. Their portfolio reflects a wide range of styles and functions, catering to diverse client preferences. The company’s dedication to excellence has earned them numerous accolades and positive reviews from satisfied customers.</p><p>Offering a full suite of construction services, Peak Construction Group demonstrates reliability and professionalism in every project. Their commitment to quality and customer satisfaction is evident in their work. Connect with Peak Construction Group at 15315 31st Ave #100, Surrey, British Columbia, for exceptional general contracting services.',
  '15315 31st Ave #100',
  'Canada',
  'BC',
  'Surrey',
  'V3Z 6X2',
  'info@constructionpforand.com',
  'canada/surrey/home-services/peak-construction-group',
  'ChIJg-cfjpfEhVQROJRsm2GLkks',
  49.0585155,
  -122.7981352,
  '16045316998',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  836,
  'http://peakgrp.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Construction P. Forand',
  '<p>Construction P. Forand operates as a general contractor in Québec City, Quebec, specializing in construction and renovation projects. This company offers competitive pricing, whether billed hourly or by contract. With a commitment to customer satisfaction, the team ensures that all work is completed meticulously while maintaining cleanliness at the job site. Additionally, the company emphasizes sustainability by recycling materials to protect future generations.</p><p>Services include new construction and renovation for residential, commercial, and industrial sectors. Construction P. Forand has built a reputation for delivering quality results across various project types, showcasing expertise in managing both small and large-scale undertakings. The team of skilled professionals is dedicated to guiding clients through each step of their projects, ensuring that every detail aligns with customer expectations.</p><p>In the greater Québec region, Construction P. Forand stands ready to tackle diverse construction challenges. Their knowledgeable staff provides insights and support, making the process seamless and efficient. Clients appreciate the transparent communication and reliability that come with each project engagement. The focus remains on achieving high standards while respecting timelines and budgets.</p><p>Construction P. Forand offers a comprehensive range of construction and renovation services, prioritizing quality and environmental responsibility. Trust this company for reliable solutions tailored to specific needs. Connect with Construction P. Forand at 1265-A de la Jonquière St, Québec City, Quebec, G1N 3X1 for expert assistance on your next project.</p>',
  '1265-A de la Jonquière St',
  'Canada',
  'QC',
  'Québec City',
  'G1N 3X1',
  'mickael@zerounzero.com',
  'canada/québec-city/home-services/construction-p-forand',
  'ChIJj9qaZtG9uEwRr8d0VbePWxc',
  46.8056373,
  -71.2632843,
  '14186606392',
  'https://www.kwikr.ca/pictures/profile/pimage-834.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  835,
  'https://constructionpforand.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Productions Bel-Co Inc (Les)',
  '<p>Productions Bel-Co Inc, located in Terrebonne, Quebec, specializes in residential construction with over 25 years of experience. This general contractor offers customizable new homes based on unique plans, catering to various needs. Services extend to building on personal land or within established projects across the North Shore, from Laval to Saint-Sauveur. Productions Bel-Co also engages in renovation projects and provides rental units, including 4½ and 5½ apartments in the Ste-Rose area of Laval.</p><p>The company showcases notable projects such as the new townhouses for sale in Terrebonne, available in a turnkey format without condominium fees. Additionally, the Domaine des Châteaux de Brisach features upscale new homes for sale in Lorraine, set on spacious wooded lots. Productions Bel-Co emphasizes quality construction and customer satisfaction, ensuring each project meets the highest standards.</p><p>With a focus on innovation and personalization, Productions Bel-Co remains committed to delivering exceptional residential solutions. Their extensive experience in the industry supports a strong reputation within the community. The combination of new constructions, renovations, and rental options makes this company a versatile choice for various housing needs.</p><p>Productions Bel-Co Inc offers comprehensive residential construction services, including customizable homes and renovation projects. Their dedication to quality and customer satisfaction has contributed to their success. Reach out to Productions Bel-Co Inc in Terrebonne for expert construction services.</p>',
  '74 Rue Marie Josée',
  'Canada',
  'QC',
  'Terrebonne',
  'J6Y 1K6',
  'terry.castlerock@shaw.ca',
  'canada/terrebonne/home-services/productions-bel-co-inc-les',
  'ChIJe7qPjeAmyUwRjkepRDT7E8o',
  45.6959794,
  -73.805271,
  '15148092526',
  'https://www.kwikr.ca/pictures/profile/pimage-833.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  834,
  'https://bel-co.com/?utm_source=google&utm_medium=organic&utm_campaign=ProductionsBelCo-GMB',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Castlerock Construction',
  '<p>Castlerock Construction operates as a reliable general contractor in Lloydminster, Alberta, specializing in commercial projects. This company focuses on delivering high-quality construction services tailored to meet the specific needs of local businesses. With a commitment to excellence, Castlerock Construction has built a solid reputation in the community.</p><p>Experience in the industry allows Castlerock Construction to manage diverse commercial projects efficiently. The team possesses the skills necessary to handle everything from initial planning to final execution. This includes project management, budgeting, and compliance with local regulations. The company''s attention to detail and adherence to timelines have resulted in numerous successful projects throughout Lloydminster.</p><p>Castlerock Construction prioritizes customer satisfaction, ensuring that each project aligns with client expectations. The team collaborates closely with clients to understand their vision and deliver results that enhance business operations. This approach not only fosters strong relationships but also contributes to the company''s growing list of satisfied customers.</p><p>With a focus on quality and reliability, Castlerock Construction continues to be a preferred choice for commercial contracting in Lloydminster. The company’s dedication to professionalism and efficiency has established it as a key player in the local construction landscape. Connect with Castlerock Construction for expert general contracting services in Lloydminster, Alberta.',
  '6309 43 St',
  'Canada',
  'AB',
  'Lloydminster',
  'T9V 2W9',
  'info@pvcorp.ca',
  'canada/lloydminster/home-services/castlerock-construction',
  'ChIJVVVVVWGyCVMRC8-fJP3V_5k',
  53.276386,
  -110.03953,
  '17808757337',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  833,
  'http://www.castlerock-construction.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Pine Valley Corporation',
  '<p>Pine Valley Corporation serves as a reliable general contractor in Concord, Ontario. This business specializes in delivering high-quality construction services, including residential and commercial projects. With a strong commitment to client satisfaction, Pine Valley Corporation has established itself as a trusted name in the local construction industry.</p><p>The team at Pine Valley Corporation possesses extensive experience in various construction disciplines. They handle projects from concept to completion, ensuring that every detail aligns with client expectations. Their portfolio showcases a range of successful builds, demonstrating versatility and expertise in both large-scale and small projects. The company prioritizes safety and adheres to all local regulations, which enhances its reputation within the community.</p><p>Pine Valley Corporation has earned recognition for its professionalism and dedication to quality. The business employs skilled tradespeople who are committed to delivering exceptional craftsmanship. Timely project completion and effective communication with clients further contribute to the company’s positive standing in Concord.</p><p>This general contractor provides a comprehensive suite of services that cater to diverse construction needs. With a focus on quality, safety, and customer satisfaction, Pine Valley Corporation continues to thrive in the competitive construction landscape. For those seeking reliable construction services in Concord, reach out to Pine Valley Corporation at 125 Edilcan Dr, Ontario, L4K 3S6.</p>',
  '125 Edilcan Dr',
  'Canada',
  'ON',
  'Concord',
  'L4K 3S6',
  'accounts@elevationelevator.ca',
  'canada/concord/home-services/pine-valley-corporation',
  'ChIJ4SRLqPUsK4gRnWXKaZZsis0',
  43.8159969,
  -79.5242494,
  '19057602215',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  832,
  'http://pinevalleylandscapes.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Elevation Elevator Inc',
  '<p>Elevation Elevator Inc operates as a general contractor in Ottawa, Ontario, providing a range of construction services. The company specializes in elevator installations, maintenance, and repairs, ensuring that clients receive reliable and efficient solutions. With a strong commitment to quality, Elevation Elevator Inc has built a reputation for excellence in the local construction industry.</p> <p>The team at Elevation Elevator Inc brings extensive experience to every project, focusing on customer satisfaction and safety. They utilize modern techniques and high-quality materials to deliver durable and functional elevator systems. The company serves a diverse clientele, including residential, commercial, and industrial sectors, adapting services to meet specific needs.</p> <p>Elevation Elevator Inc has achieved notable milestones in the construction sector, demonstrating a clear understanding of the complexities involved in elevator systems. Their dedication to ongoing training ensures that all staff members remain updated on the latest industry standards and technologies. This proactive approach enhances the overall service quality and reliability for clients.</p> <p>Offering comprehensive services in elevator installation and maintenance, Elevation Elevator Inc continues to contribute positively to Ottawa’s construction landscape. Their focus on quality, safety, and customer satisfaction makes them a preferred choice for clients seeking dependable elevator solutions. Connect with Elevation Elevator Inc today for expert services in Ottawa, Ontario.</p>',
  '2615 Lancaster Rd unit 17',
  'Canada',
  'ON',
  'Ottawa',
  'K1B 5N2',
  'info@canamark.ca',
  'canada/ottawa/home-services/elevation-elevator-inc',
  'ChIJix7s-A0PzkwRuru4E-zy7FA',
  45.3993383,
  -75.6098737,
  '16137366663',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  831,
  'http://www.elevationelevator.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Canamark Property Services Ltd',
  '<p>Canamark Property Services Ltd delivers comprehensive general contracting services in Port Moody, British Columbia. This local business excels in complete building maintenance, repairs, and renovations for both commercial and residential properties. With a focus on tailored solutions, Canamark meets the unique needs of each client, ensuring satisfaction with every project.</p><p>The team at Canamark has built a reputation for reliability and quality. They handle projects ranging from minor repairs to extensive renovations, demonstrating versatility and expertise in the field. Clients can expect a professional approach, with each task completed efficiently and effectively. The commitment to customer service sets Canamark apart in the competitive market of general contracting.</p><p>Canamark Property Services Ltd operates from 3009 Murray St unit 6, providing services throughout Port Moody and surrounding areas. The company prioritizes clear communication and transparency, offering free estimates to potential clients. This practice helps clients make informed decisions about their property needs. Canamark''s skilled team ensures that every project is executed with precision, enhancing the value and functionality of properties.</p><p>With a strong emphasis on quality and customer satisfaction, Canamark Property Services Ltd stands ready to assist with all building maintenance, repair, and renovation needs. Their dedication to tailored solutions and professional service makes them a trusted choice in Port Moody. Contact Canamark today for expert general contracting services in British Columbia.</p>',
  '3009 Murray St unit 6',
  'Canada',
  'BC',
  'Port Moody',
  'V3H 1X3',
  'gerald@northfieldbuilders.com',
  'canada/port-moody/home-services/canamark-property-services-ltd',
  'ChIJi13t6914hlQRMozQEahs6AQ',
  49.2784906,
  -122.8441733,
  '16045522115',
  'https://www.kwikr.ca/pictures/profile/pimage-829.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  830,
  'http://canamark.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Northfield Builders Inc',
  '<p>Northfield Builders Inc operates as a reliable general contractor in Happy Valley-Goose Bay, Newfoundland and Labrador. With years of dedicated service, this company has earned a solid reputation by consistently delivering exceptional construction projects tailored to meet community needs. The commitment to quality and client satisfaction distinguishes Northfield Builders from competitors.</p> <p>Northfield Builders Inc focuses on a variety of construction projects, ensuring that each one meets the highest standards. Their expertise spans residential and commercial construction, renovations, and custom builds. The team prides itself on understanding the unique requirements of each client, allowing for personalized service that addresses specific needs. This dedication to craftsmanship and attention to detail results in completed projects that reflect the vision of the clients.</p> <p>With a strong presence in Happy Valley-Goose Bay, Northfield Builders has cultivated lasting relationships within the community. Their approach emphasizes open communication and collaboration, ensuring that clients remain informed throughout the construction process. This transparency fosters trust and confidence, making Northfield Builders a preferred choice for many in the area.</p> <p>The combination of experience, commitment to quality, and community focus makes Northfield Builders Inc a standout general contractor in Newfoundland and Labrador. For those seeking reliable construction services, connecting with Northfield Builders at 128 Corte Real Rd is a strategic choice for any project.',
  '128 Corte Real Rd',
  'Canada',
  'NL',
  'Happy Valley-Goose Bay',
  'A0P 1C0',
  'careers@newdawndevelopments.com',
  'canada/happy-valley-goose-bay/home-services/northfield-builders-inc',
  'ChIJwx9J_5N5e0wRQ45vtld6aww',
  53.3144654,
  -60.2894065,
  '17098963112',
  'https://www.kwikr.ca/pictures/profile/pimage-828.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  829,
  'http://northfieldbuilders.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'New Dawn Developments Ltd.',
  '<p>New Dawn Developments Ltd. operates as a general contractor in Cranbrook, British Columbia. This company specializes in residential and commercial construction projects, showcasing a commitment to quality and customer satisfaction. With years of experience, New Dawn Developments Ltd. has successfully completed numerous projects, earning a reputation for reliability and professionalism in the local construction industry.</p><p>The services offered by New Dawn Developments Ltd. include project management, renovations, and new builds. The team emphasizes attention to detail and adheres to industry standards. Each project receives personalized service, ensuring that client needs and expectations are met. The company utilizes high-quality materials and skilled labor, contributing to the durability and aesthetics of every construction endeavor.</p><p>New Dawn Developments Ltd. has established itself as a trusted name in Cranbrook. The company’s portfolio reflects a diverse range of projects, from residential homes to commercial spaces. The dedication to sustainable practices and efficient project execution sets New Dawn Developments apart in the competitive market. Clients appreciate the transparent communication and collaborative approach throughout the construction process.</p><p>New Dawn Developments Ltd. delivers comprehensive general contracting services with a focus on customer satisfaction and quality workmanship. This company is well-equipped to handle various construction needs in Cranbrook, British Columbia. Reach out to New Dawn Developments Ltd. for expert construction services in the area.',
  '1524 Industrial Road 2',
  'Canada',
  'BC',
  'Cranbrook',
  'V1C 6R2',
  'info@habitationsboies.com',
  'canada/cranbrook/home-services/new-dawn-developments-ltd',
  'ChIJMwZNXbzYZFMRjOrEVXc2V4U',
  49.531308,
  -115.764269,
  '12504891519',
  'https://www.kwikr.ca/pictures/profile/pimage-827.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  828,
  'http://www.newdawndevelopments.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Habitations Boies Inc',
  '<p>Habitations Boies Inc, located in Mont-Saint-Hilaire, Quebec, operates as a reputable general contractor specializing in innovative and rigorous construction techniques. This family-owned business, backed by four generations of skilled carpenters and joiners, offers clients a wide selection of land and the ability to design custom plans. The company has gained recognition among industry professionals, including the Canada Mortgage and Housing Corporation (CMHC) and the Residential Construction Guarantee (GCR), for its product quality and market adaptability.</p><p>Habitations Boies Inc focuses on delivering exceptional residential construction services. Each project reflects a commitment to high standards and craftsmanship, ensuring that homes are built to last. The direct interaction with the builder allows for personalized services that cater to specific client needs. This approach fosters trust and transparency throughout the construction process.</p><p>Clients appreciate the extensive options available, from land selection to tailored architectural designs. The company’s ability to adapt quickly to market demands distinguishes it from competitors. With a strong reputation for financial stability and reliability, Habitations Boies Inc remains a top choice for homeowners in the region.</p><p>In summary, Habitations Boies Inc offers comprehensive general contracting services characterized by quality, customization, and a strong industry reputation. The focus on client satisfaction and innovative building techniques positions the company as a leader in Mont-Saint-Hilaire. Contact Habitations Boies Inc for expert construction services in Mont-Saint-Hilaire, Quebec.</p>',
  '840 Chem. Benoît',
  'Canada',
  'QC',
  'Mont-Saint-Hilaire',
  'J3H 0L8',
  'info@cadacon.ca',
  'canada/mont-saint-hilaire/home-services/habitations-boies-inc',
  'ChIJ46fQl-pUyEwRpHaOaiDrNUc',
  45.5876729,
  -73.1494464,
  '14504461922',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  827,
  'https://habitationsboies.com/maisons/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Cada Construction',
  '<p>Cada Construction serves Ottawa, Ontario, as a reliable general contractor specializing in residential and commercial projects. This local business prides itself on delivering high-quality construction services, including renovations, new builds, and custom projects. With a commitment to customer satisfaction, Cada Construction has built a strong reputation in the community.</p><p>Founded with the goal of providing exceptional construction solutions, Cada Construction employs skilled professionals who ensure every project meets industry standards. The team focuses on understanding client needs and delivering tailored services that align with their vision. Each project reflects meticulous attention to detail and a dedication to quality craftsmanship.</p><p>Operating from 850 Boyd Ave, Cada Construction has completed numerous projects across Ottawa, showcasing their versatility and expertise. The company emphasizes transparency and communication throughout the construction process, fostering trust with clients. Their portfolio includes a range of successful renovations and builds, demonstrating their ability to handle diverse construction challenges.</p><p>Cada Construction stands out for its commitment to using quality materials and sustainable practices. The team continuously seeks innovative solutions to enhance project efficiency and effectiveness. Their strong local presence and community involvement further solidify their position as a trusted contractor in Ottawa.</p><p>Quality construction services are the hallmark of Cada Construction, supported by a dedicated team and a proven track record. Engage with this reputable general contractor to explore construction options in Ottawa, Ontario.',
  '850 Boyd Ave',
  'Canada',
  'ON',
  'Ottawa',
  'K2A 2E1',
  'mireille.laporte@demonfort.ca',
  'canada/ottawa/home-services/cada-construction',
  'ChIJuXORq74GzkwR1Aqw2e0DO-I',
  45.3764737,
  -75.7512564,
  '16137291073',
  'https://www.kwikr.ca/pictures/profile/pimage-825.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  826,
  'http://www.cadacon.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Dafimmo et Demonfort',
  '<p>Dafimmo et Demonfort operates as a reliable general contractor in Outremont, Quebec. This company excels in delivering high-quality construction services tailored to residential and commercial projects. With a commitment to excellence, Dafimmo et Demonfort has built a reputation for completing projects on time and within budget. The team combines expertise with a customer-focused approach, ensuring satisfaction at every stage of the construction process.</p><p>The company offers a wide range of services, including renovations, new constructions, and project management. Their skilled professionals oversee every detail, from initial planning to final execution. Clients benefit from personalized service and a transparent process, which fosters trust and collaboration. The location at 5100 Rue Hutchison Bureau 300 positions them conveniently for clients throughout the Outremont area.</p><p>Dafimmo et Demonfort emphasizes quality craftsmanship and adherence to safety standards. Their experienced team utilizes modern techniques and high-grade materials, resulting in durable and aesthetically pleasing structures. Client testimonials highlight the company’s dedication to meeting specific needs and delivering exceptional results.</p><p>This general contractor stands out for its commitment to quality and customer satisfaction in Outremont. With a focus on effective communication and project efficiency, Dafimmo et Demonfort ensures a smooth construction experience. For reliable construction services, connect with Dafimmo et Demonfort in Outremont, Quebec.</p>',
  '5100 Rue Hutchison Bureau 300',
  'Canada',
  'QC',
  'Outremont',
  'H2V 4A9',
  'jturner@citycorecommercial.com',
  'canada/outremont/home-services/dafimmo-et-demonfort',
  'ChIJoWt5M50ZyUwRue1DgHvOexo',
  45.5187828,
  -73.596996,
  '15143030788',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  825,
  'http://www.demonfort.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Create. Construction Management Group',
  '<p>Create. Construction Management Group operates as a general contractor in Calgary, Alberta, providing comprehensive construction services. This company specializes in project management, ensuring that each project is completed on time and within budget. With a focus on quality and efficiency, Create. Construction Management Group has built a reputation for reliability in the local construction industry.</p><p>The team at Create. Construction Management Group brings extensive experience to every project. They handle residential and commercial builds, renovations, and custom projects. Their expertise includes planning, design, and execution, ensuring that client visions become reality. The company prioritizes communication, keeping clients informed throughout the construction process.</p><p>Create. Construction Management Group emphasizes sustainable building practices, promoting environmentally friendly materials and methods. This commitment to sustainability aligns with the growing demand for eco-conscious construction solutions. The company’s portfolio showcases a variety of successful projects, reflecting their adaptability and skill in diverse building environments.</p><p.With a commitment to excellence, Create. Construction Management Group serves the Calgary area with integrity and professionalism. Their dedication to customer satisfaction and high-quality workmanship sets them apart in the competitive construction landscape. Engage with a team that values transparency and collaboration in every project. Reach out to Create. Construction Management Group at their Calgary location for expert construction management services.</p>',
  '1925 10 Ave SW',
  'Canada',
  'AB',
  'Calgary',
  'T3C 0K3',
  'cdafoe@westmarkconstruction.ca',
  'canada/calgary/home-services/create-construction-management-group',
  'ChIJAZh8dNBvcVMRyMLwbRISR44',
  51.0443998,
  -114.1056532,
  '14032449030',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  824,
  'http://createprojects.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);
