INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Canadian Contractor Services',
  '<p>Canadian Contractor Services, located in Sherwood Park, Alberta, specializes in general contracting for both commercial and residential spaces. This business focuses on delivering personalized service, ensuring that clients receive exceptional workmanship and timely communication. CCS handles a wide range of tasks, from minor repairs to major renovations, addressing all building issues effectively.</p> <p>CCS has established a strong reputation in the renovation, building, and maintenance industry. The team consists of skilled professionals dedicated to optimizing the functionality and longevity of properties. Each project receives attention to detail, ensuring that clients can trust in the quality of work provided. The commitment to customer satisfaction sets CCS apart, as they prioritize the needs of their clients throughout every phase of a project.</p> <p>With a focus on both commercial and residential services, CCS is equipped to manage various maintenance needs. The company''s proven track record demonstrates reliability and expertise in the field. Clients appreciate the straightforward communication and the dedication to completing projects on time and within budget.</p> <p>Canadian Contractor Services offers a comprehensive range of contracting solutions tailored to meet the specific needs of its clients. The combination of skilled professionals and a commitment to quality ensures that properties remain in excellent condition. Reach out to Canadian Contractor Services in Sherwood Park for expert assistance with all contracting needs. </p>',
  '26 Cranford Way Unit 3181',
  'Canada',
  'AB',
  'Sherwood Park',
  'T8H 2T2',
  'constructionrenovationsauclair@hotmail.com',
  'canada/sherwood-park/home-services/canadian-contractor-services',
  'ChIJFXuqQyAXoFMRpg9zrJ399CQ',
  53.542345,
  -113.2898764,
  '17809305380',
  'https://www.kwikr.ca/pictures/profile/pimage-669.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  673,
  'https://www.canadiancontractorservices.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Construction Rénovation S. Auclair Lac-Beauport',
  '<p>Construction Rénovation S. Auclair, located at 158 Chem. du Bord de l''Eau in Lac-Beauport, Quebec, has been a trusted name in general contracting for over 19 years. This established business specializes in high-quality construction and renovation services. A skilled team of professionals is dedicated to delivering exceptional results for a variety of projects.</p> <p>With a strong presence in Quebec and Lévis, Construction Rénovation S. Auclair has built a reputation for reliability and expertise in the construction industry. The company prioritizes customer satisfaction and ensures that each project is tailored to meet specific needs. From residential renovations to commercial builds, the team approaches every task with professionalism and attention to detail.</p> <p>The company’s commitment to quality is evident in every completed project. Experienced professionals work closely with clients to provide guidance and support throughout the construction process. Timely project completion and effective communication remain key strengths of Construction Rénovation S. Auclair. The business also emphasizes the importance of using quality materials to ensure lasting results.</p> <p>Construction Rénovation S. Auclair offers comprehensive general contracting services that cater to both residential and commercial clients in Lac-Beauport and surrounding areas. With a focus on quality and customer care, the company continues to excel in the construction field. Reach out to Construction Rénovation S. Auclair for all construction and renovation needs in Lac-Beauport, Quebec.</p>',
  '158 Chem. du Bord de l''Eau',
  'Canada',
  'QC',
  'Lac-Beauport',
  'G3B 0C2',
  'info@novaxionconstruction.com',
  'canada/lac-beauport/home-services/construction-rénovation-s-auclair-lac-beauport',
  'ChIJt93eidqluEwR59h0grCl1cg',
  46.9876888,
  -71.3000543,
  '14182651350',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  672,
  'https://www.constructionrenovationsauclair.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Novaxion Construction',
  '<p>Novaxion Construction operates as a reliable general contractor in L''Ancienne-Lorette, Quebec. This business specializes in delivering high-quality construction services, including residential and commercial projects. With a commitment to excellence, Novaxion Construction has built a reputation for timely project completion and customer satisfaction.</p> <p>The team at Novaxion Construction brings years of experience to each project, ensuring that every detail is handled with precision. This company utilizes modern techniques and quality materials to deliver durable and aesthetically pleasing results. From renovations to new builds, Novaxion Construction manages all aspects of construction with professionalism and expertise.</p> <p>Clients appreciate the transparent communication and dedication to meeting deadlines. The company emphasizes safety and compliance with local regulations, which enhances its credibility in the industry. Novaxion Construction also values sustainable practices, integrating eco-friendly solutions into its projects whenever possible. This commitment to sustainability resonates with environmentally conscious clients.</p> <p>With a focus on quality craftsmanship and customer service, Novaxion Construction continues to grow its presence in the local market. The combination of skilled labor and effective project management sets this general contractor apart. For those seeking reliable construction services in L''Ancienne-Lorette, Novaxion Construction offers a strong choice. Contact Novaxion Construction at 1749 Rte de l''Aéroport, L''Ancienne-Lorette, Quebec for expert construction services.</p>',
  '1749 Rte de l''Aéroport',
  'Canada',
  'QC',
  'L''Ancienne-Lorette',
  'G2G 2P5',
  'frontend@superiordesign.ltd',
  'canada/l-ancienne-lorette/home-services/novaxion-construction',
  'ChIJvXdQ0kuZuEwRGArkjznMqB0',
  46.8049527,
  -71.3779795,
  '15819855964',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  671,
  'http://novaxionconstruction.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Tonda Construction',
  '<p>Tonda Construction operates as a reliable general contractor located in London, Ontario. With over 28 years of experience, this company specializes in both interior and exterior construction and renovation projects. Tonda Construction serves commercial, industrial, and institutional properties throughout South-Western Ontario, ensuring quality and efficiency in every project.</p><p>The team at Tonda Construction focuses on delivering seamless development processes, regardless of the project''s size or complexity. Their extensive experience allows them to tackle a wide range of construction challenges, meeting the diverse needs of their clients. This commitment to excellence has earned Tonda Construction a positive reputation in the local community.</p><p>Clients benefit from a comprehensive approach that includes meticulous planning, skilled craftsmanship, and timely project completion. Tonda Construction prioritizes communication and collaboration, ensuring that every aspect of the project aligns with client expectations. The company’s portfolio showcases a variety of successful projects, reflecting their versatility and dedication to quality.</p><p>Tonda Construction offers a strong combination of experience, reliability, and expertise in the construction industry. Their focus on commercial, industrial, and institutional renovations positions them as a leader in the local market. For those seeking a dependable general contractor in London, Ontario, engaging Tonda Construction will ensure a successful project outcome. Connect with Tonda Construction today for expert construction services in London, Ontario.</p>',
  '1085 Wilton Grove Rd',
  'Canada',
  'ON',
  'London',
  'N6N 1C9',
  'info@furtahgc.ca',
  'canada/london/home-services/tonda-construction',
  'ChIJfbLf62vzLogRJX3Vgz8zYrs',
  42.9279112,
  -81.1902749,
  '15196865200',
  'https://www.kwikr.ca/pictures/profile/pimage-666.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  670,
  'http://www.tonda.on.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Furtah General Contracting',
  '<p>Furtah General Contracting operates as a reliable general contractor in West Lorne, Ontario. This business specializes in various construction services, including residential renovations, commercial builds, and project management. With a commitment to quality and customer satisfaction, Furtah General Contracting has built a strong reputation in the local community.</p> <p>The company emphasizes efficiency and precision in every project. Skilled professionals ensure that each task meets high standards. Furtah General Contracting''s team possesses extensive knowledge of construction codes and regulations, which enhances the safety and quality of their work. This expertise leads to successful project completions on time and within budget.</p> <p>Furtah General Contracting also values open communication with clients. Regular updates and consultations keep clients informed throughout the construction process. This approach fosters trust and builds lasting relationships with customers. The business takes pride in its ability to adapt to individual client needs, ensuring personalized service that aligns with specific project goals.</p> <p>Overall, Furtah General Contracting provides essential services in general contracting, focusing on quality, efficiency, and client satisfaction. The company''s commitment to excellence and community engagement sets it apart in West Lorne. Connect with Furtah General Contracting to discuss construction needs in Ontario.',
  '217 Wood St',
  'Canada',
  'ON',
  'West Lorne',
  'N0L 2P0',
  'general@automationnow.ca',
  'canada/west-lorne/home-services/furtah-general-contracting',
  'ChIJ4aGPuie0L4gR7RJBk0lPyjA',
  42.6062177,
  -81.6015439,
  '12269274238',
  'https://www.kwikr.ca/pictures/profile/pimage-665.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  669,
  'http://www.furtahgc.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Automation Now Inc',
  '<p>Automation Now Inc, located at 1531 Rosslyn Rd in Thunder Bay, Ontario, provides expert electrical installation services. This company specializes in electrical, instrumentation, and process control solutions. With a focus on quality and efficiency, Automation Now Inc serves both residential and commercial clients in the region, ensuring reliable and safe electrical systems.</p> <p>The team at Automation Now Inc consists of skilled professionals dedicated to delivering high standards of service. Their expertise in electrical installations covers a wide range of applications, from residential wiring to complex industrial systems. The company has built a reputation for timely project completion and adherence to safety regulations, making it a trusted partner in Thunder Bay.</p> <p>Automation Now Inc emphasizes customer satisfaction through transparent communication and tailored solutions. The business understands the unique needs of each client, providing customized services that align with specific requirements. Their commitment to ongoing training and industry best practices ensures that the team remains at the forefront of technological advancements in electrical installation.</p> <p>With a strong presence in Thunder Bay, Automation Now Inc continues to excel in delivering high-quality electrical services. The company’s focus on safety, efficiency, and customer satisfaction sets it apart in the competitive landscape. For reliable electrical installation services in Thunder Bay, connect with Automation Now Inc today.</p>',
  '1531 Rosslyn Rd',
  'Canada',
  'ON',
  'Thunder Bay',
  'P7E 6W2',
  'info@surgeelektrikal.com',
  'canada/thunder-bay/home-services/automation-now-inc',
  'ChIJiZQkhcwhWU0ReFe8UBaJbfI',
  48.3628892,
  -89.329156,
  '18076265590',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  668,
  'https://www.automationnow.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Surge Elektrikal 309A Ltd',
  '<p>Surge Elektrikal 309A Ltd provides comprehensive electrical installation services in Ontario, ensuring safety and efficiency in every project. This local business specializes in residential and commercial electrical work, including wiring, lighting, and panel upgrades. With a commitment to quality and customer satisfaction, Surge Elektrikal has built a reputation for reliability in the community.</p><p>The skilled team at Surge Elektrikal 309A Ltd possesses extensive knowledge of electrical systems and adheres to all safety regulations. Each project receives meticulous attention to detail, ensuring that installations meet both client needs and industry standards. The company’s experience in handling various electrical tasks makes it a go-to choice for many in Ontario seeking professional service.</p><p>Surge Elektrikal also emphasizes the importance of energy efficiency, offering solutions that help reduce energy consumption and lower utility bills. The business stays updated with the latest technologies and practices in the electrical industry, ensuring clients receive the best possible service. Testimonials from satisfied customers highlight the team''s professionalism and commitment to excellence.</p><p>Overall, Surge Elektrikal 309A Ltd stands ready to assist with all electrical installation needs in Ontario. The business''s expertise, customer-focused approach, and dedication to quality make it a reliable partner for any electrical project. Contact Surge Elektrikal 309A Ltd at 1311 Weston Rd, Ontario, for all electrical installation services. </p>',
  '1311 Weston Rd',
  'Canada',
  'ON',
  NULL,
  'M6M 4R6',
  'cmorrison@pronghor.ca',
  'canada/home-services/surge-elektrikal-309a-ltd',
  'ChIJ-8CqQXrL1IkRYyhcCRXUXVw',
  43.689776,
  -79.4965188,
  '14164798716',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  667,
  'http://surgeelektrikal.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Pronghorn Controls Ltd',
  '<p>Pronghorn Controls Ltd, located at 250 N Service Rd in Moose Jaw, Saskatchewan, offers exceptional electrical installation services with over 40 years of industry experience. Established in 1981, this company provides high-quality instrumentation and electrical services tailored to various sectors, including industrial, agricultural, mining, oil and gas, pipeline, and petrochemical industries across Western Canada. Pronghorn''s commitment to safety, integrity, performance, learning, and teamwork drives its success.</p> <p>Pronghorn Controls Ltd has established itself as a leader in the electrical installation service industry. The organization prides itself on its dedication to quality and professionalism. Clients benefit from a wide range of services, ensuring their specific needs are met efficiently. The company’s experienced team possesses the technical expertise required to handle complex projects, ensuring timely and safe execution.</p> <p>With a forward-looking growth strategy, Pronghorn Controls Ltd continues to expand its reach and capabilities. The organization emphasizes employee development, creating a positive workplace culture that attracts top talent. This focus on communication and continuous improvement has positioned Pronghorn as an employer of choice in the electrical service sector.</p> <p>Pronghorn Controls Ltd delivers reliable electrical installation services backed by decades of experience. The company’s strengths lie in its commitment to quality and employee development. The positive reputation within the industry reflects its dedication to client satisfaction. Connect with Pronghorn Controls Ltd in Moose Jaw for expert electrical installation services. </p>',
  '250 N Service Rd',
  'Canada',
  'SK',
  'Moose Jaw',
  'S6H 2T9',
  'info@ipec-systems.com',
  'canada/moose-jaw/home-services/pronghorn-controls-ltd',
  'ChIJASQ3Zj_dG1MRR3E76EWdI5Y',
  50.42668,
  -105.5426342,
  '13066240623',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  666,
  'https://pronghorn.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'IPEC Systems',
  '<p>IPEC Systems provides comprehensive electrical installation services in Edmonton, Alberta. This local business specializes in electrical power and control systems, offering a full range of solutions from design to installation. With a focus on quality and customer satisfaction, IPEC Systems ensures that every project meets the highest standards.</p> <p>The company excels in power and control system designs, creating detailed drawings that guide the installation process. Clients benefit from a seamless transition from concept to completion. IPEC Systems takes pride in its ability to manage projects efficiently, ensuring timely start-up and commissioning. The after-installation support further enhances the customer experience, providing peace of mind.</p> <p>IPEC Systems has established a reputation for reliability and expertise within the electrical installation service industry. The team is equipped with the knowledge and skills necessary to handle a variety of projects, regardless of complexity. This adaptability allows IPEC Systems to serve diverse client needs effectively.</p> <p>By prioritizing quality and customer service, IPEC Systems continues to grow and thrive in the competitive market of Edmonton. The commitment to excellence in electrical power and control systems design sets this company apart. For those seeking dependable electrical installation services, IPEC Systems remains a top choice in the area. Visit IPEC Systems at 9429 41 Ave NW, Edmonton, Alberta, T6E 6B9 for exceptional service and support.</p>',
  '9429 41 Ave NW',
  'Canada',
  'AB',
  'Edmonton',
  'T6E 6B9',
  'info@nicolasfilteau.com',
  'canada/edmonton/home-services/ipec-systems',
  'ChIJ5Vz_rdcZoFMRuePyiSWhB-Y',
  53.4759022,
  -113.4744365,
  '15874048445',
  'https://www.kwikr.ca/pictures/profile/pimage-661.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  665,
  'http://www.ipec-systems.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'NF ELECTRICAL AND EVENT PRODUCTION LTD.',
  '<p>NF Electrical and Event Production Ltd. provides comprehensive electrical installation services in Haines Junction, Yukon. This local business specializes in the installation and integration of audio-visual, electrical, home automation, security, and network systems. The company caters to both residential and commercial clients, offering customized solutions that address specific needs.</p><p>NF Electrical and Event Production Ltd. excels in enhancing events through professional lighting design and video production services. With a focus on creating stunning visual experiences, the team collaborates closely with clients to transform their visions into reality. Whether it is a corporate gathering or a live performance, the company utilizes cutting-edge technology to ensure seamless execution and impressive results.</p><p>The commitment to delivering high-quality service sets NF Electrical and Event Production Ltd. apart in the Yukon Territory. The team’s expertise in various systems ensures that every project is handled with precision and care. Customers appreciate the tailored solutions that meet their unique requirements, enhancing both residential and commercial environments.</p><p>NF Electrical and Event Production Ltd. stands out for its dedication to excellence in electrical installation and event production services. The combination of technical expertise and a customer-focused approach contributes to the success of each project. Reach out to NF Electrical and Event Production Ltd. in Haines Junction for exceptional service and innovative solutions.</p>',
  '108 Spruce Street Unit 2017',
  'Canada',
  'YT',
  'Haines Junction',
  'Y0B 1L0',
  'info@curriecreek.com',
  'canada/haines-junction/home-services/nf-electrical-and-event-production-ltd',
  'ChIJcZF79vpJU1ERVu8GFVjQajI',
  60.7593364,
  -137.5095456,
  '18673348237',
  'https://www.kwikr.ca/pictures/profile/pimage-660.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  664,
  'http://www.nfeep.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Currie Creek Electric',
  '<p>Currie Creek Electric provides top-notch electrical installation services in Chilliwack, British Columbia. This local business specializes in residential and commercial electrical work, ensuring safety and efficiency in every project. With a commitment to quality, Currie Creek Electric has built a reputation for reliability and expertise in the community.</p><p>The team at Currie Creek Electric possesses extensive knowledge of electrical systems, making them well-equipped to handle various installation needs. Services include wiring, lighting installation, and electrical panel upgrades. The business emphasizes customer satisfaction by delivering projects on time and within budget. Their focus on safety standards ensures that all installations comply with local regulations and codes.</p><p>Currie Creek Electric has earned trust within the Chilliwack area through consistent performance and positive customer feedback. Their experienced electricians demonstrate professionalism and attention to detail, making them a preferred choice for many residents and businesses. The company understands the importance of energy efficiency and offers solutions that help clients save on utility bills while enhancing the functionality of their spaces.</p><p>In summary, Currie Creek Electric excels in providing reliable electrical installation services in Chilliwack, British Columbia. With a strong focus on customer service and safety, the business continues to grow and serve the community effectively. Reach out to Currie Creek Electric for expert electrical solutions today in Chilliwack. </p>',
  '44431 Yale Rd',
  'Canada',
  'BC',
  'Chilliwack',
  'V2R 3J2',
  'info@rkselectricinc.ca',
  'canada/chilliwack/home-services/currie-creek-electric',
  'ChIJO0V71v0whFQRAwdZAmxbOqU',
  49.1451855,
  -121.9939472,
  '16048265097',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  663,
  'http://www.curriecreek.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'RKS Electric (2015) Inc.',
  '<p>RKS Electric (2015) Inc. delivers comprehensive electrical installation services in Walkerton, Ontario, and surrounding areas. With 35 years of experience, this established electrical contracting company excels in residential, commercial, and industrial sectors. RKS Electric specializes in new construction, renovations, and electrical upgrades, ensuring customer satisfaction through quality workmanship.</p> <p>The company operates a fleet equipped with a line truck, aerial lifts, skid steer, and mini excavators, enabling efficient service delivery from the street to the end-user. This capability allows RKS Electric to respond effectively to various electrical needs, including 24-hour emergency services across Huron, Bruce, and Grey Counties. The team of skilled electricians is dedicated to resolving electrical issues promptly and professionally.</p> <p>RKS Electric has built a solid reputation based on reliability and excellence. The commitment to customer satisfaction is evident in every project undertaken. Whether it’s a small residential job or a large industrial installation, RKS Electric maintains high standards of service and attention to detail. The company’s extensive experience ensures that all electrical installations meet safety regulations and industry standards.</p> <p>RKS Electric (2015) Inc. offers a wide range of electrical services backed by a strong commitment to quality and customer care. The company''s expertise and reliable service make it a valuable resource for electrical needs in Walkerton, Ontario. Connect with RKS Electric today for professional electrical installation services in the area.</p>',
  '964 Old Durham Rd',
  'Canada',
  'ON',
  'Walkerton',
  'N0G 2V0',
  'info@encoreelectrical.ca',
  'canada/walkerton/home-services/rks-electric-2015-inc',
  'ChIJKe4iws6YKYgRPIdHmG5iJUA',
  44.13683,
  -81.134869,
  '15198810727',
  'https://www.kwikr.ca/pictures/profile/pimage-658.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  662,
  'http://www.rkselectricinc.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Encore Electrical Services Inc.',
  '<p>Encore Electrical Services Inc. offers top-notch electrical installation services in Calgary, Alberta. With a commitment to quality and safety, this local business provides residential and commercial electrical solutions. The team at Encore Electrical Services Inc. is skilled in various electrical tasks, ensuring reliable and efficient installations for every client. This company has earned a reputation for timely service and adherence to industry standards.</p> <p>Located at 11547 42 St SE, Encore Electrical Services Inc. serves the Calgary area with expertise in a wide range of electrical services. The company specializes in new installations, upgrades, and repairs, making it a go-to choice for both homeowners and businesses. With a focus on customer satisfaction, the team works diligently to meet specific needs and preferences. Their knowledgeable staff ensures that every project is completed with precision, using high-quality materials and modern techniques.</p> <p>Encore Electrical Services Inc. has built a strong client base through consistent performance and a dedication to excellence. This business not only meets but exceeds expectations in electrical service delivery. Their professionalism and attention to detail set them apart in the competitive market. With a strong emphasis on safety and compliance, clients can trust their electrical projects are in good hands.</p> <p>Encore Electrical Services Inc. provides reliable electrical installation services, ensuring quality and safety for all clients. Their commitment to excellence and customer satisfaction makes them a preferred choice in Calgary. Connect with Encore Electrical Services Inc. today for expert electrical solutions in Calgary, Alberta.</p>',
  '11547 42 St SE',
  'Canada',
  'AB',
  'Calgary',
  'T2Z 4K4',
  'info@longhouseelectric.ca',
  'canada/calgary/home-services/encore-electrical-services-inc',
  'ChIJWZBqCGR3cVMR6ln64cG1nkA',
  50.9484149,
  -113.9757318,
  '14039938140',
  'https://www.kwikr.ca/pictures/profile/pimage-657.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  661,
  'http://encoreelectricalservices.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Longhouse Electric',
  '<p>Longhouse Electric provides top-notch electrical installation services in Mississauga, Ontario. This certified electrician specializes in both electrical and HVAC contracting, ensuring homes and businesses benefit from reliable and efficient systems. With a commitment to quality and safety, Longhouse Electric serves the local community and surrounding areas with expertise and professionalism.</p><p>Operating from 5370 Longhouse Crescent, the company has established a reputation for delivering exceptional service. Longhouse Electric focuses on meeting the diverse needs of residential and commercial clients. Their skilled team handles a variety of projects, from simple installations to complex electrical systems. The expertise in HVAC contracting also allows for seamless integration of heating and cooling solutions, enhancing overall comfort for clients.</p><p>Longhouse Electric emphasizes customer satisfaction and safety in every project. The technicians are trained and certified, ensuring compliance with industry standards. This dedication to professionalism and quality workmanship has led to numerous successful projects in the Mississauga area. Clients can trust Longhouse Electric to provide reliable solutions tailored to their specific needs.</p><p>With a strong focus on electrical installation and HVAC services, Longhouse Electric demonstrates a commitment to excellence in the industry. Their knowledgeable team and dedication to customer service make them a valuable resource for electrical needs. Reach out to Longhouse Electric for reliable electrical installation services in Mississauga, Ontario.</p>',
  '5370 Longhouse Crescent',
  'Canada',
  'ON',
  'Mississauga',
  'L5R 4A5',
  'gary.jackson@pyramidcorporation.com',
  'canada/mississauga/home-services/longhouse-electric',
  'ChIJAQCEK-RAK4gRIt6_aO53Fj8',
  43.5980458,
  -79.6786701,
  '16475888120',
  'https://www.kwikr.ca/pictures/profile/pimage-656.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  660,
  'https://longhouseelectric.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'PTW Energy Services',
  '<p>PTW Energy Services Ltd. offers comprehensive electrical installation services in Rainbow Lake, Alberta. This private company, headquartered in Calgary, excels in providing industry-leading solutions that encompass fabrication, construction, and maintenance. With a robust network spanning Canada, the United States, the Middle East, and Asia Pacific, PTW Energy Services delivers reliable and efficient electrical solutions tailored to various needs.</p> <p>Established with a focus on quality and safety, PTW Energy Services remains committed to meeting the demands of its diverse clientele. The team consists of highly skilled professionals who ensure that all projects adhere to stringent industry standards. This dedication to excellence has earned the company a reputation for being a trusted partner in electrical installation and maintenance.</p> <p>PTW Energy Services specializes in serving both commercial and industrial sectors, providing customized solutions that enhance operational efficiency. The company’s extensive experience allows it to manage projects of varying sizes, ensuring timely completion without compromising quality. Clients benefit from the company’s proactive approach to problem-solving and commitment to customer satisfaction.</p> <p>Through its innovative practices and expert knowledge, PTW Energy Services continues to strengthen its position in the electrical installation sector. The company’s focus on safety, quality, and efficiency makes it a reliable choice for electrical needs. Contact PTW Energy Services at 33 Imperial Dr, Rainbow Lake, Alberta, T0H 2Y0 for exceptional electrical installation services.</p>',
  '33 Imperial Dr',
  'Canada',
  'AB',
  'Rainbow Lake',
  'T0H 2Y0',
  'operations@aggelectric.ca',
  'canada/rainbow-lake/home-services/ptw-energy-services',
  'ChIJpUCy1dyP6lMRRebWSS3u7TA',
  58.4936225,
  -119.4078869,
  '17809562249',
  'https://www.kwikr.ca/pictures/profile/pimage-655.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  659,
  'http://www.ptwenergy.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Aggregate Electrical Services - AB Inc',
  '<p>Aggregate Electrical Services - AB Inc provides comprehensive electrical installation services in Acheson, Alberta. This business specializes in serving the aggregate industry, offering a wide range of services including custom builds, hydraulic troubleshooting, and installations. The company supplies most electrical and pneumatic parts and accessories, ensuring clients receive top-quality support.</p> <p>With a commitment to excellence, Aggregate Electrical Services operates 24/7, addressing urgent electrical needs at any time. The team''s expertise allows for efficient installation and repair processes, catering specifically to the unique demands of the aggregate sector. Clients benefit from tailored solutions that enhance operational efficiency and safety.</p> <p>Noteworthy achievements include a strong reputation for reliability and quality in Western Canada. Aggregate Electrical Services has established itself as a trusted partner for businesses requiring specialized electrical installations and repairs. The focus on customer satisfaction drives the team to deliver prompt and effective service, ensuring minimal downtime for clients.</p> <p>Aggregate Electrical Services - AB Inc excels in providing electrical solutions that meet industry standards and client expectations. The company’s dedication to quality and service positions it as a leader in the electrical installation sector. Reach out to Aggregate Electrical Services - AB Inc in Acheson for expert electrical installations and repairs. </p>',
  '26656 111 Ave NW #100',
  'Canada',
  'AB',
  'Acheson',
  'T7X 6E1',
  'info@auroraelectrical.ca',
  'canada/acheson/home-services/aggregate-electrical-services-ab-inc',
  'ChIJ7XFPKpKJn1MRZM6v8gCcaCI',
  53.5586929,
  -113.7686613,
  '17804056315',
  'https://www.kwikr.ca/pictures/profile/pimage-653.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  658,
  'http://aggelectric.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Aurora Electrical Technologies',
  '<p>Aurora Electrical Technologies operates as a premier electrical installation service in Calgary, Alberta. This local electrical contractor specializes in residential electrical services, focusing on the latest advancements in smart and efficient electrical technologies. With a commitment to staying current with industry trends, Aurora Electrical Technologies enhances homes with cutting-edge solutions.</p><p>The company offers a range of services including electrical installations, upgrades, and repairs. Knowledgeable technicians ensure that all work meets safety standards and customer expectations. Attention to detail and a focus on efficiency make this business a trusted choice for homeowners seeking reliable electrical services. Their expertise in modern technologies means clients benefit from energy-efficient and innovative solutions.</p><p>Located at 825 8 Ave SW, Aurora Electrical Technologies has built a strong reputation in Calgary. The team prides itself on delivering high-quality workmanship and exceptional customer service. Clients appreciate the professionalism and commitment to excellence that defines every project. The company’s dedication to using the newest technologies ensures that homes are equipped with the best electrical systems available.</p><p>Aurora Electrical Technologies provides essential electrical services that enhance residential safety and convenience. Their focus on modern technology and customer satisfaction sets them apart in the local market. For efficient and reliable electrical solutions in Calgary, reach out to Aurora Electrical Technologies today.</p>',
  '825 8 Ave SW',
  'Canada',
  'AB',
  'Calgary',
  'T2P 2T4',
  'vonavolts@gmail.com',
  'canada/calgary/home-services/aurora-electrical-technologies',
  'ChIJRVQxSitvcVMRql-Qj6zADbY',
  51.0457187,
  -114.0805283,
  '14038881754',
  'https://www.kwikr.ca/pictures/profile/pimage-651.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  657,
  'https://www.auroraelectrical.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Vona Electric Inc',
  '<p>Vona Electric Inc. offers comprehensive electrical installation services in Wellesley, Ontario. This fully insured and ECRA/ESA licensed electrical contractor specializes in a range of electrical solutions tailored to meet diverse customer needs. From residential projects to commercial installations, Vona Electric Inc. accommodates all project sizes with professionalism and expertise.</p> <p>The company prides itself on high-quality workmanship and strong professional relationships with its clients. Each project reflects a commitment to excellence and a focus on customer satisfaction. Vona Electric Inc. has built a reputation for reliability and efficiency, ensuring that every electrical installation is completed to the highest standards. Their team of skilled electricians is equipped to handle various tasks, including wiring, lighting installations, and electrical upgrades.</p> <p>Customer satisfaction remains the core mission of Vona Electric Inc. Every project aims for 100% satisfaction, ensuring clients feel valued and supported throughout the process. The business has successfully completed numerous projects, demonstrating its capability and dedication to the community. Clients appreciate the personalized service and attention to detail that Vona Electric Inc. provides.</p> <p>Vona Electric Inc. excels in delivering tailored electrical services while maintaining strong customer relationships. The company’s commitment to quality and satisfaction ensures a positive experience for all clients. Contact Vona Electric Inc. for reliable electrical installation services in Wellesley, Ontario.</p>',
  '147 Ferris Dr',
  'Canada',
  'ON',
  'Wellesley',
  'N0B 2T0',
  'contactus@hottubguys.ca',
  'canada/wellesley/home-services/vona-electric-inc',
  'ChIJVVXZoI7-K4gRfoOj1enwFEM',
  43.4793043,
  -80.7591355,
  '15195009176',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  656,
  'http://vonaelectric.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'HotTubGuys',
  '<p>HotTubGuys provides expert electrical installation services for hot tubs and pools in Carleton Place, Ontario. This Ottawa-based company excels in both residential and large commercial projects, ensuring top-notch service for all clients. Recognized as the largest contractor for pool and hot tub electrical installations in the area, HotTubGuys is a trusted choice for many. With a commitment to quality, they handle over 1000 hot tub moves each year, catering to homeowners and retail stores alike.</p><p>Clients rely on HotTubGuys for their extensive experience and efficient service. When purchasing a new pool or hot tub, many local retailers recommend this company for installation. The process begins with a free onsite quote, allowing clients to understand the scope and cost of the project upfront. This approach builds trust and ensures satisfaction from the very start.</p><p>The team at HotTubGuys is dedicated to providing reliable and timely services. Their expertise in electrical installations guarantees safety and compliance with local regulations. Each project is handled with care, ensuring that every hot tub and pool installation meets the highest standards. The company’s reputation is built on professionalism and customer satisfaction, making them a preferred choice in the region.</p><p>HotTubGuys offers comprehensive electrical installation services for hot tubs and pools, demonstrating strengths in reliability and expertise. Their commitment to quality service and customer care has earned them a solid reputation in Carleton Place. Contact HotTubGuys for expert installation services in Ontario. </p>',
  '520 High St',
  'Canada',
  'ON',
  'Carleton Place',
  'K7C 3P1',
  'richard.perri@sparkpowercorp.com',
  'canada/carleton-place/home-services/hottubguys',
  'ChIJ609aTUgJ0kwRznsn75GXLE0',
  45.1302217,
  -76.1672887,
  '16132533000',
  'https://www.kwikr.ca/pictures/profile/pimage-649.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  655,
  'http://www.hottubguys.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Spark Power',
  '<p>Spark Power delivers comprehensive electrical installation services in London, Ontario. This company specializes in end-to-end electrical contracting, operations and maintenance services, and energy sustainability solutions. With a commitment to quality and efficiency, Spark Power has built a reputation for reliability in the local market.</p><p>The team at Spark Power is skilled and knowledgeable, ensuring that all electrical installations meet the highest standards. They focus on safety and compliance, which is crucial in the electrical industry. Their operations extend beyond mere installation; they also provide ongoing maintenance to ensure systems function optimally over time.</p><p>Energy sustainability is a priority for Spark Power. They offer innovative solutions that help businesses and homeowners reduce their energy consumption and lower costs. This focus on sustainability not only benefits clients but also contributes positively to the environment. The company''s dedication to customer satisfaction is evident in their approach to each project, ensuring tailored solutions that meet specific needs.</p><p>With a strong presence in London, Ontario, Spark Power is well-equipped to handle various electrical projects, from residential to commercial. Their expertise in electrical contracting and maintenance, combined with a commitment to sustainability, positions them as a trusted partner in the community. Reach out to Spark Power for reliable electrical installation services in London, Ontario.</p>',
  '3820 Commerce Rd',
  'Canada',
  'ON',
  'London',
  'N6N 1P6',
  'info@steveetfils.com',
  'canada/london/home-services/spark-power',
  'ChIJl2-aijPzLogRHlDehTbpczQ',
  42.9353739,
  -81.1677348,
  '18337757697',
  'https://www.kwikr.ca/pictures/profile/pimage-648.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  654,
  'https://sparkpowercorp.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Spark Power',
  '<p>Spark Power, located at 333 Centennial Pkwy N in Hamilton, Ontario, provides top-notch electrical installation services. This business specializes in electrical contracting, operations, and maintenance for industrial facilities, renewable asset owners, and OEMs. Spark Power has earned a reputation for reliability and efficiency in the electrical services sector.</p> <p>The company also features Spark Testing Services, a NETA accredited provider. This division focuses on electrical engineering, commissioning, and preventative maintenance. Customized testing and maintenance programs ensure that clients receive tailored solutions that meet their specific needs. Spark Power’s commitment to quality and safety reflects its dedication to the industry and the communities it serves.</p> <p>With a strong emphasis on operational excellence, Spark Power stands out in Hamilton and surrounding areas. The team of skilled professionals brings extensive experience and knowledge to every project, ensuring that all electrical installations and maintenance tasks are completed to the highest standards. The focus on renewable energy assets highlights the company’s forward-thinking approach in a rapidly evolving industry.</p> <p>Spark Power delivers comprehensive electrical services, including installation, maintenance, and testing. The combination of industry expertise and a commitment to customer satisfaction positions the business as a leader in the electrical installation service category. Connect with Spark Power in Hamilton for reliable and professional electrical solutions. </p>',
  '333 Centennial Pkwy N',
  'Canada',
  'ON',
  'Hamilton',
  'L8E 2X6',
  'info@lakesideelectrical.net',
  'canada/hamilton/home-services/spark-power',
  'ChIJifnfL7-YLIgRVOCuEEWFAEQ',
  43.2402961,
  -79.7601219,
  '19055612808',
  'https://www.kwikr.ca/pictures/profile/pimage-647.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  653,
  'https://sparkpowercorp.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Steve & Fils Electrique Inc',
  '<p>Steve & Fils Électrique Inc. offers expert electrical installation services in Lasalle, Quebec, and surrounding areas, including Greater Montreal, West Island, Laval, and the South Shore. Established in 2003, this master electrician certified company specializes in delivering high-quality electrical solutions for homeowners and home-builders. With extensive experience across various sectors of the electrical industry, the company has built a reputation for reliability and excellence.</p> <p>As a leading electrical contracting company in Montreal, Steve & Fils Électrique Inc. ensures that every project meets the highest standards. Skilled electricians handle installations with precision and care, focusing on safety and efficiency. The team understands the unique needs of each client, providing tailored solutions that enhance the functionality and aesthetics of residential spaces. From new constructions to renovations, the company addresses all electrical needs effectively.</p> <p>Commitment to quality service has solidified Steve & Fils Électrique Inc.''s position in the market. The company continuously updates its knowledge and skills to keep pace with industry advancements. This dedication results in innovative solutions that cater to modern demands while ensuring compliance with safety regulations.</p> <p>Steve & Fils Électrique Inc. remains a trusted choice for quality electrical installation services in Lasalle, Quebec. Their experience, commitment to customer satisfaction, and professionalism drive their success. Contact Steve & Fils Électrique Inc. today for reliable electrical services in Lasalle.</p>',
  '8477 Rue Cordner',
  'Canada',
  'QC',
  'Lasalle',
  'H8N 2X2',
  'info@electricpotential.ca',
  'canada/lasalle/home-services/steve-fils-electrique-inc',
  'ChIJM0dyqToXyUwRBmv1a74caP0',
  45.4354822,
  -73.6376843,
  '15144810303',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  652,
  'http://www.steveetfils.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Lakeside Electrical',
  '<p>Lakeside Electrical provides comprehensive electrical installation services in Thorold, Ontario. Since 2004, this business has catered to residential, commercial, and construction electrical needs. With a commitment to quality and safety, Lakeside Electrical has built a reputation for reliability and excellence in the local area.</p><p>This electrical installation service specializes in a wide range of offerings, including wiring, lighting installation, and electrical upgrades. The team of skilled electricians ensures that all projects meet industry standards and local codes. Lakeside Electrical prioritizes customer satisfaction and delivers efficient solutions tailored to each client''s specific requirements.</p><p>The business serves both new construction projects and existing properties, providing essential electrical services that enhance functionality and safety. Lakeside Electrical''s experience in the field allows for effective troubleshooting and maintenance, ensuring that electrical systems operate smoothly. The company also emphasizes the importance of energy efficiency, helping clients reduce their energy consumption through modern solutions.</p><p>Lakeside Electrical remains dedicated to serving the Thorold community with integrity and professionalism. The company’s long-standing presence in the industry reflects its commitment to excellence and customer care. For those seeking reliable electrical installation services, Lakeside Electrical offers a strong choice in Thorold, Ontario. Connect with Lakeside Electrical today to explore their services and ensure safe, effective electrical solutions for any project.</p>',
  '106 Ormond St S',
  'Canada',
  'ON',
  'Thorold',
  'L2V 3W1',
  'rharris@melloninc.ca',
  'canada/thorold/home-services/lakeside-electrical',
  'ChIJzcKJPBBP04kRiR9dD1_cZmM',
  43.1153069,
  -79.1981932,
  '12893026855',
  'https://www.kwikr.ca/pictures/profile/pimage-645.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  651,
  'http://lakesideelectrical.net/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Electric Potential',
  '<p>Electric Potential is a leading electrical installation service located in Mississauga, Ontario. This electrical contractor specializes in delivering high-quality electrical solutions for residential and commercial clients. With a commitment to safety and efficiency, Electric Potential offers a range of services including wiring, lighting installation, and electrical panel upgrades. The company has built a strong reputation in the local area by consistently meeting customer needs and adhering to industry standards.</p> <p>The team at Electric Potential possesses extensive knowledge and experience in the electrical field. They utilize the latest technology and techniques to ensure each project is completed on time and within budget. Clients appreciate the transparent communication and professional approach that Electric Potential maintains throughout the entire process. Their dedication to customer satisfaction has resulted in numerous positive reviews from the community.</p> <p>Electric Potential''s commitment to excellence is evident in their attention to detail and adherence to safety regulations. The company actively participates in ongoing training to stay updated with industry advancements. This focus on continuous improvement ensures that clients receive the most effective and reliable electrical services available.</p> <p>In summary, Electric Potential provides exceptional electrical installation services in Mississauga, Ontario. The company''s expertise, customer-centric approach, and commitment to safety make it a preferred choice for electrical needs. Connect with Electric Potential today to experience their top-notch services in Mississauga.</p>',
  '2146 Robinwood Ct',
  'Canada',
  'ON',
  'Mississauga',
  'L5M 5H8',
  'estimating@pronghorn.ca',
  'canada/mississauga/home-services/electric-potential',
  'ChIJJXspF69BK4gRl-yLAfrHajc',
  43.5725457,
  -79.7062878,
  '14168877233',
  'https://www.kwikr.ca/pictures/profile/pimage-644.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  650,
  'https://electricpotential.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Mellon Inc. Electrical Contractor & Engineering Sarnia',
  '<p>Mellon Inc. Electrical Contractor & Engineering operates in Sarnia, Ontario, delivering top-notch electrical installation services. This company specializes in a wide range of solutions, including electrical, communications, instrumentation, and engineering needs. With a focus on various industries such as manufacturing, power generation, oil and gas, and telecommunications, Mellon Inc. has established itself as a reliable partner for diverse projects.</p><p>The team at Mellon Inc. brings extensive expertise and resources to every project. Their commitment to quality and safety ensures that all installations meet industry standards. The company prides itself on its ability to adapt to the unique requirements of each client, providing tailored solutions that enhance operational efficiency. With a strong emphasis on reliability, Mellon Inc. delivers projects on time and within budget, making it a preferred choice for many businesses in the region.</p><p>Recognized for its professionalism and technical proficiency, Mellon Inc. has built a solid reputation in Sarnia and beyond. The company’s dedication to customer satisfaction is evident in its approach to every engagement, ensuring that all clients receive the highest level of service. Their comprehensive understanding of various sectors allows them to address complex challenges effectively.</p><p>Mellon Inc. Electrical Contractor & Engineering offers unparalleled electrical installation services, backed by years of experience and a commitment to excellence. For reliable electrical solutions in Sarnia, reach out to Mellon Inc. at 800 Upper Canada Dr, Ontario, N7W 1A4.</p>',
  '800 Upper Canada Dr',
  'Canada',
  'ON',
  'Sarnia',
  'N7W 1A4',
  'info@eprocanada.com',
  'canada/sarnia/home-services/mellon-inc-electrical-contractor-engineering-sarnia',
  'ChIJH9ZGtquDJYgRfnDs5wYWSvM',
  42.9608336,
  -82.3417928,
  '15193320211',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  649,
  'https://melloninc.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);
