INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Aspect Roofing',
  '<p>Aspect Roofing, a reputable roofing contractor located in Uxbridge, Ontario, provides exceptional roofing services to residential and commercial clients. This local business specializes in roof installations, repairs, and maintenance, ensuring that every project meets high-quality standards. With years of experience, Aspect Roofing has built a strong reputation for reliability and expertise in the roofing industry.</p> <p>The company employs skilled professionals who utilize advanced techniques and quality materials. This commitment to excellence ensures durability and longevity in every roofing project. Aspect Roofing understands the unique weather challenges in Ontario and designs solutions that withstand harsh conditions. Customer satisfaction remains a top priority, with a focus on clear communication throughout the project.</p> <p>Aspect Roofing has successfully completed numerous projects in Uxbridge and surrounding areas, gaining trust through consistent performance. The company offers free estimates, allowing clients to make informed decisions without financial pressure. This transparency fosters strong relationships with customers, who appreciate the honest approach and quality workmanship.</p> <p>In summary, Aspect Roofing provides comprehensive roofing solutions tailored to the needs of the Uxbridge community. The company’s dedication to quality, customer service, and expert craftsmanship sets it apart in the competitive roofing market. For reliable roofing services, contact Aspect Roofing at 5549 Durham Regional Hwy 47, Uxbridge, Ontario, L9P 1R1.</p>',
  '5549 Durham Regional Hwy 47',
  'Canada',
  'ON',
  'Uxbridge',
  'L9P 1R1',
  'info@malartech.ca',
  'canada/uxbridge/home-services/aspect-roofing',
  'ChIJD5Ton7o-1YkRt7moU4KKYGk',
  44.0728129,
  -79.1580431,
  '19058521557',
  NULL,
  'Roofing',
  'Growth Plan',
  898,
  'http://aspectroofing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Malartech',
  '<p>Malartech provides expert roofing contractor services in Mirabel, Quebec. This company specializes in a range of roofing solutions, including installations, repairs, and maintenance. Malartech has built a reputation for quality workmanship and reliability in the local area. With a commitment to using high-quality materials and skilled labor, this business ensures that roofs withstand the test of time and weather.</p><p>Malartech operates from 10130, # 310, Boulevard de St Canut, offering services tailored to both residential and commercial clients. The team understands the unique roofing needs of the Mirabel community and delivers customized solutions that meet those demands. Clients appreciate the transparency in pricing and the thorough approach to each project, which includes detailed assessments and consultations.</p><p>The company prioritizes customer satisfaction and safety, adhering to all industry standards and regulations. Malartech''s experienced professionals stay updated on the latest roofing technologies and trends, ensuring that clients receive the best options available. Their dedication to excellence has earned them numerous positive reviews from satisfied customers.</p><p>Malartech excels in providing reliable roofing services that enhance property value and curb appeal. The company’s strengths lie in its commitment to quality, customer service, and industry expertise. For roofing needs in Mirabel, reach out to Malartech for dependable solutions.',
  '10130, # 310, Boulevard de St Canut',
  'Canada',
  'QC',
  'Mirabel',
  'J7N 0G3',
  'yourhomeroofing@gmail.com',
  'canada/mirabel/home-services/malartech',
  'ChIJV38dVvsrz0wRS6LYeLR2y0Y',
  45.7111514,
  -74.0892581,
  '18553638097',
  NULL,
  'Roofing',
  'Growth Plan',
  897,
  'https://malartech.ca/fr/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'HOMERUN ROOFING Inc.',
  '<p>HOMERUN ROOFING Inc. operates as a reliable roofing contractor in Kelowna, British Columbia, providing exceptional roofing services to the Central Okanagan area. The company specializes in delivering high-quality roofing solutions, ensuring that every project is completed right the first time. HOMERUN ROOFING Inc. prioritizes customer satisfaction by offering free detailed quotes and employing professional qualified installers who maintain a clean and safe work environment.</p> <p>Clients in Lake Country, Oyama, Kelowna, West Kelowna, Peachland, and Summerland benefit from the expertise of this local business. The commitment to a stress-free roofing experience sets HOMERUN ROOFING apart from competitors. Customers appreciate the attention to detail and dedication to quality that the company brings to each job. The team works diligently to ensure that every roofing project meets the highest standards, making clients proud of their choice in contractors.</p> <p>HOMERUN ROOFING Inc. stands out for its professionalism and efficiency in the roofing industry. Achievements include a growing reputation for reliability and quality service in the region. The focus on providing peace of mind through expert installation and customer care solidifies the company’s position as a trusted roofing contractor. Contact HOMERUN ROOFING Inc. for roofing services in Kelowna and the surrounding areas. </p>',
  '1420 Terai Rd #110',
  'Canada',
  'BC',
  'Kelowna',
  'V1X 7H3',
  'roofingbin@gmail.com',
  'canada/kelowna/home-services/homerun-roofing-inc',
  'ChIJZ6I8IGONfVMRrHeqVLgxFRY',
  49.8883114,
  -119.415866,
  '12508624663',
  'https://www.kwikr.ca/pictures/profile/pimage-895.jpg',
  'Roofing',
  'Growth Plan',
  896,
  'http://www.homerunroofing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Bin Roofing',
  '<p>Bin Roofing provides expert roofing services to the Markham area in Ontario. This roofing contractor specializes in residential and commercial roofing solutions, including installations, repairs, and maintenance. With a strong focus on quality and customer satisfaction, Bin Roofing has built a reputation for reliability and professionalism. The team is skilled in various roofing materials and techniques, ensuring that each project meets the highest standards.</p> <p>Located at 42 Pettigrew Ct, Bin Roofing serves the local community with dedication. The company prides itself on using top-quality materials and modern equipment. Each roofing project is approached with attention to detail, ensuring durability and aesthetic appeal. The experienced staff understands the unique needs of Markham''s climate, providing tailored solutions that withstand the elements.</p> <p>Bin Roofing''s commitment to excellence is evident in its numerous successful projects throughout the region. The company has received positive feedback from clients, highlighting the efficient service and knowledgeable staff. This roofing contractor also offers free estimates, enabling customers to make informed decisions without financial pressure. Bin Roofing remains dedicated to enhancing the safety and beauty of homes and businesses in Markham.</p> <p>With a strong emphasis on quality workmanship and customer satisfaction, Bin Roofing stands ready to assist with all roofing needs. The company’s expertise and local knowledge ensure reliable solutions for every project. Reach out to Bin Roofing for professional roofing services in Markham, Ontario.</p>',
  '42 Pettigrew Ct',
  'Canada',
  'ON',
  'Markham',
  'L3S 1K3',
  'service@centuryroofing.ca',
  'canada/markham/home-services/bin-roofing',
  'ChIJq6q2maHW1IkRTG1MatOq0Js',
  43.8371463,
  -79.2857844,
  '16478877066',
  NULL,
  'Roofing',
  'Growth Plan',
  895,
  'https://www.roofingbin.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Century Roofing Ltd',
  '<p>Century Roofing Ltd operates as a reliable roofing contractor in Calgary, Alberta, delivering exceptional roofing solutions for both residential and commercial properties. This business specializes in new construction, flat roofing, metal roofing, and emergency roofing services, ensuring comprehensive coverage for diverse roofing needs in Southern Alberta.</p> <p>Established with a commitment to quality and customer satisfaction, Century Roofing Ltd has built a strong reputation in the local community. The experienced team focuses on precision and durability, using high-quality materials for every project. This approach guarantees that roofs withstand the elements while maintaining aesthetic appeal. The company’s expertise in various roofing types allows it to cater to unique client requirements effectively.</p> <p>Century Roofing Ltd also prioritizes safety and compliance with industry standards, ensuring that all work meets regulatory guidelines. The team is equipped to handle projects of any scale, from small residential repairs to large commercial installations. Emergency roofing services provide peace of mind, addressing urgent issues promptly and efficiently.</p> <p>With a focus on quality workmanship and customer care, Century Roofing Ltd remains a trusted choice for roofing in Calgary and surrounding areas. The combination of specialized services and a dedicated team positions the company as a leader in the roofing industry. Connect with Century Roofing Ltd today for expert roofing solutions in Calgary, Alberta.</p>',
  '4204 10 St NE',
  'Canada',
  'AB',
  'Calgary',
  'T2E 6K3',
  'desisroofingwest@yahoo.ca',
  'canada/calgary/home-services/century-roofing-ltd',
  'ChIJu-pKEAZlcVMRv7KyIorPQgE',
  51.0895657,
  -114.0373259,
  '14032355457',
  'https://www.kwikr.ca/pictures/profile/pimage-893.jpg',
  'Roofing',
  'Growth Plan',
  894,
  'http://centuryroofing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Desi''s Roofing West Inc.',
  '<p>Desi''s Roofing West Inc. provides expert roofing solutions to the Binbrook area in Ontario. This roofing contractor specializes in residential and commercial roofing services, ensuring quality workmanship and customer satisfaction. With a strong reputation built on reliability and professionalism, Desi''s Roofing West Inc. has become a trusted name for roofing needs in the community.</p><p>The company offers a variety of services, including roof repairs, installations, and maintenance. Their experienced team utilizes high-quality materials to deliver durable and long-lasting roofs. Desi''s Roofing West Inc. understands the importance of a secure roof over one’s head, which is why they prioritize both functionality and aesthetics in their projects. Clients appreciate the thorough consultations and transparent pricing that the company provides, making the roofing process straightforward and stress-free.</p><p>Desi''s Roofing West Inc. has achieved numerous successful projects, earning positive reviews from satisfied customers. The commitment to excellence and attention to detail sets this roofing contractor apart in the competitive market. The team is dedicated to meeting the unique needs of each client, ensuring that every roofing project is completed to the highest standards.</p><p>With a focus on quality services and customer care, Desi''s Roofing West Inc. remains a reliable choice for roofing solutions in Binbrook, Ontario. Engage with this reputable roofing contractor for expert assistance with all roofing needs.',
  '2630 Binbrook Rd',
  'Canada',
  'ON',
  'Binbrook',
  'L0R 1C0',
  'cmarriott@marriottsroofing.ca',
  'canada/binbrook/home-services/desi-s-roofing-west-inc',
  'ChIJsZlnEJSWLIgRqjczzjdQkTc',
  43.1205631,
  -79.802571,
  '19055744178',
  'https://www.kwikr.ca/pictures/profile/pimage-892.jpg',
  'Roofing',
  'Growth Plan',
  893,
  'http://www.desisroofingwest.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Marriott''s Roofing',
  '<p>Marriott''s Roofing, located at 143 Garinger Crescent in Hamilton, Ontario, has been a trusted roofing contractor since 2004. This local business specializes in providing high-quality roofing solutions for both residential and commercial properties. With a commitment to excellence, Marriott''s Roofing employs skilled installers who prioritize workmanship and customer satisfaction. The company utilizes top-grade materials that are specifically designed to withstand the Canadian climate, ensuring durability and protection for homes.</p><p>Marriott''s Roofing has developed a strong reputation in Hamilton and surrounding areas for reliability and quality service. The team understands the unique challenges posed by the local weather, making them a preferred choice for homeowners seeking effective roofing solutions. Each project is approached with meticulous attention to detail, guaranteeing a roof that not only looks great but also performs well over time.</p><p>Customer feedback highlights the professionalism and efficiency of Marriott''s Roofing. Many clients appreciate the transparent communication and the thoroughness of the work performed. The company’s focus on using only the best products assures homeowners that their investment is secure. This dedication to quality has resulted in numerous satisfied customers throughout the region.</p><p>Marriott''s Roofing offers a range of services, including roof installation, repair, and maintenance. The company’s strengths lie in its experienced team, high-quality materials, and commitment to customer service. For reliable roofing solutions in Hamilton, reach out to Marriott''s Roofing today.',
  '143 Garinger Crescent',
  'Canada',
  'ON',
  'Hamilton',
  'L0R 1C0',
  'armyroofing@gmail.com',
  'canada/hamilton/home-services/marriott-s-roofing',
  'ChIJsYzBUryWLIgRTiaGhsyQD08',
  43.1255043,
  -79.8076633,
  '19058692524',
  NULL,
  'Roofing',
  'Growth Plan',
  892,
  'https://www.marriottsroofing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Army Roofing Inc.',
  '<p>Army Roofing Inc. operates as a reliable roofing contractor in Delta, British Columbia, providing expert services to Vancouver, Surrey, and surrounding areas. This company specializes in residential roofing, commercial roofing, roof repair, and metal roofing. Customers appreciate the comprehensive roof warranties and affordable financing options that Army Roofing Inc. offers. With affiliations and certifications from industry leaders like GAF and CertainTeed, the company demonstrates a commitment to quality and professionalism.</p> <p>In Delta and its neighboring regions, Army Roofing Inc. delivers exceptional roofing solutions tailored to meet diverse client needs. The team focuses on high-quality materials and skilled workmanship, ensuring roofs withstand the harshest elements. The company’s motto, ''Waging war against the elements,'' reflects its dedication to providing durable and reliable roofing systems. Clients benefit from the extensive experience and knowledge of the staff, who are committed to ensuring customer satisfaction.</p> <p>The business has built a strong reputation in the community, thanks to its focus on quality service and customer care. Army Roofing Inc. stands out for its competitive pricing and flexible financing options, making it accessible for homeowners and businesses alike. The commitment to excellence and industry standards reinforces trust among clients.</p> <p>Army Roofing Inc. offers a range of roofing services, ensuring quality and satisfaction in every project. The company’s strengths lie in its warranties and financing options. For reliable roofing solutions in Delta, contact Army Roofing Inc. today.',
  '4921 Coleman Pl',
  'Canada',
  'BC',
  'Delta',
  'V4K 3H8',
  'supertoitures@live.ca',
  'canada/delta/home-services/army-roofing-inc',
  'ChIJiyx7UXrmhVQRcM_UdGCLPoA',
  49.0924292,
  -123.0618248,
  '17786867663',
  'https://www.kwikr.ca/pictures/profile/pimage-890.jpg',
  'Roofing',
  'Growth Plan',
  891,
  'https://armyroofing.com/?utm_source=google&utm_medium=organic&utm_campaign=gmb',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Toitures Super Fernand Hamel',
  '<p>Toitures Super Fernand Hamel provides top-quality roofing services in Shawinigan, Quebec. This roofing contractor specializes in residential and commercial roofing solutions, ensuring durability and reliability for every project. With a focus on customer satisfaction and a commitment to excellence, Toitures Super Fernand Hamel has built a solid reputation in the local community.</p> <p>The company offers a range of services, including roof installation, repair, and maintenance. Skilled professionals handle each project with precision, utilizing high-grade materials to ensure long-lasting results. Toitures Super Fernand Hamel prioritizes safety and adheres to industry standards, making it a trusted choice for roofing needs. The team’s extensive experience allows for efficient project completion, minimizing disruption to clients'' daily lives.</p> <p>Toitures Super Fernand Hamel has achieved numerous successful projects across Shawinigan. The business prides itself on its transparent pricing and clear communication, ensuring clients understand every aspect of their roofing project. Positive reviews from satisfied customers highlight the company’s reliability and professionalism. The commitment to quality workmanship sets Toitures Super Fernand Hamel apart in the competitive roofing market.</p> <p>Toitures Super Fernand Hamel delivers exceptional roofing services, focusing on quality and customer care. The company’s dedication to excellence and safety makes it a reliable choice for any roofing project in Shawinigan. Reach out to Toitures Super Fernand Hamel for expert roofing services in Shawinigan, Quebec.</p>',
  '4485 Rue Georges Bornais',
  'Canada',
  'QC',
  'Shawinigan',
  'G9N 6T5',
  'toiture@toitureprohd.ca',
  'canada/shawinigan/home-services/toitures-super-fernand-hamel',
  'ChIJ-RFw8I5LxkwR-VQ-ByLcQwo',
  46.5042478,
  -72.7140617,
  '18195376742',
  'https://www.kwikr.ca/pictures/profile/pimage-889.jpg',
  'Roofing',
  'Growth Plan',
  890,
  'http://www.supertoituresfernandhamel.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Toiture prohd & Excavation',
  '<p>Toiture prohd & Excavation provides comprehensive roofing and excavation services in Shawinigan, Quebec. This local business specializes in various areas, including waterproofing foundations, French drains, and interior and exterior renovations. With a commitment to quality and customer satisfaction, Toiture prohd & Excavation has built a strong reputation in the community.</p><p>The company offers a range of services tailored to meet the needs of both residential and commercial clients. Roofing projects are executed with precision, ensuring durability and aesthetic appeal. The team also addresses foundational issues, offering waterproofing solutions that protect properties from water damage. French drain installations are expertly handled, enhancing drainage systems to prevent flooding.</p><p>Interior renovations, including flooring and window installations, are part of the service portfolio. The skilled professionals at Toiture prohd & Excavation ensure that every project aligns with the specific requirements of clients. The focus on quality materials and workmanship sets the business apart in the competitive market.</p><p>Toiture prohd & Excavation excels in delivering reliable and efficient services. Their extensive experience and dedication to quality have made them a trusted choice for many in Shawinigan. From roofing to excavation, the company offers a comprehensive solution for property improvement. Connect with Toiture prohd & Excavation today for exceptional service in Shawinigan, Quebec.</p>',
  '892 Prom Du St Maurice',
  'Canada',
  'QC',
  'Shawinigan',
  'G9N 1L7',
  'vente@toituresummum.com',
  'canada/shawinigan/home-services/toiture-prohd-excavation',
  'ChIJIyNlTtpNxkwR7paPd2Cvxbk',
  46.5401312,
  -72.7533446,
  '18199893147',
  'https://www.kwikr.ca/pictures/profile/pimage-888.jpg',
  'Roofing',
  'Growth Plan',
  889,
  'http://toitureprohd.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Toitures Summum',
  '<p>Toitures Summum, located in Saint-Adolphe-d''Howard, Quebec, offers specialized roofing services since 2008. This roofing contractor focuses on flat roofs, providing expertise in elastomeric membrane, TPO, and EPDM systems for both residential and commercial buildings. With over 15 years of experience, Toitures Summum has established a reputation for quality and reliability on the North Shore.</p> <p>The company’s commitment to excellence is evident in every project. Toitures Summum ensures that clients receive top-notch roofing solutions tailored to their specific needs. The skilled team utilizes advanced techniques and high-quality materials, ensuring durability and performance. Each roofing installation or repair is executed with precision, reflecting the company''s dedication to customer satisfaction.</p> <p>Free estimates are available, allowing potential clients to assess the value of services without obligation. This approach builds trust and transparency, essential components of Toitures Summum''s business philosophy. The company’s extensive knowledge in the roofing industry enables it to tackle various challenges, making it a go-to choice for many in the region.</p> <p>Toitures Summum excels in providing reliable roofing solutions for residential and commercial properties. With a strong track record and a focus on customer service, the company continues to be a trusted name in the area. Reach out to Toitures Summum for expert roofing services in Saint-Adolphe-d''Howard, Quebec.</p>',
  '1570 Chem. Cailloux',
  'Canada',
  'QC',
  'Saint-Adolphe-d''Howard',
  'J0T 2B0',
  'excavationportneuf@gmail.com',
  'canada/saint-adolphe-d-howard/home-services/toitures-summum',
  'ChIJz2kFq8Msz0wRFOCRmiXzg6g',
  45.9232993,
  -74.2910082,
  '14506027669',
  'https://www.kwikr.ca/pictures/profile/pimage-887.jpg',
  'Roofing',
  'Growth Plan',
  888,
  'http://www.toituresummum.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Les Toitures MR inc Couvreur Toiture Lévis',
  '<p>Les Toitures MR inc Couvreur Toiture Lévis specializes in residential and commercial roofing renovation in Lévis, Quebec. This company has received recommendations from CAA-Québec and holds certifications from Reno maître and BP. Their commitment to quality, efficiency, and budget-friendly solutions makes them a reliable choice for roofing needs.</p> <p>Les Toitures MR inc offers a comprehensive range of services that cater to both residential and commercial clients. The team excels in creating tailored roofing renovation plans that align with customer expectations. Their process ensures that clients receive guidance from the initial consultation through to the completion of the project. The focus remains on delivering dependable results that meet high standards.</p> <p>Operating primarily in Lévis and Quebec City, Les Toitures MR inc has established a reputation for its exceptional service. The company''s dedication to customer satisfaction reflects in their approach to every project. They prioritize understanding client needs and providing solutions that are both effective and affordable.</p> <p>With a strong track record and numerous certifications, Les Toitures MR inc continues to excel in the roofing industry. Their focus on quality and customer service positions them as a preferred choice for roofing renovations. Connect with Les Toitures MR inc for reliable roofing services in Lévis, Quebec.</p>',
  '3077 Chem. Vanier',
  'Canada',
  'QC',
  'Levis',
  'G6Z 2A3',
  'info@selecttoiture.com',
  'canada/levis/home-services/les-toitures-mr-inc-couvreur-toiture-lévis',
  'ChIJeVPucSSTuEwRibIVyz8aOfc',
  46.7232907,
  -71.1899822,
  '15819981109',
  'https://www.kwikr.ca/pictures/profile/pimage-886.jpg',
  'Roofing',
  'Growth Plan',
  887,
  'http://lestoituresmrinc.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Select Toiture Inc.',
  '<p>Select Toiture Inc. provides expert roofing services in Levis, Quebec. This roofing contractor specializes in residential and commercial roofing solutions, ensuring high-quality workmanship and customer satisfaction. With a strong focus on durability and aesthetics, Select Toiture Inc. has built a reputation for reliability and excellence in the local area.</p> <p.The team at Select Toiture Inc. is dedicated to using top-grade materials. They offer a variety of roofing options, including asphalt shingles, metal roofing, and flat roofs. Each project is approached with meticulous attention to detail, ensuring that every installation meets industry standards. The company also provides roof repair and maintenance services, addressing issues promptly to extend the life of roofs.</p> <p.Select Toiture Inc. has achieved numerous accolades for its commitment to quality and service. The company’s skilled professionals bring years of experience to the table, allowing them to tackle projects of any size. Clients appreciate the transparent communication and thorough consultations that help in making informed decisions about their roofing needs.</p> <p.Select Toiture Inc. excels in delivering reliable roofing solutions tailored to client specifications. Their dedication to quality, combined with a strong local presence, makes them a preferred choice in Levis. Contact Select Toiture Inc. today for comprehensive roofing services in Quebec. </p>',
  '1255 Rue J. A. Bombardier',
  'Canada',
  'QC',
  'Levis',
  'G7A 2P4',
  'info@fourcornerroofing.com',
  'canada/levis/home-services/select-toiture-inc',
  'ChIJRVx9GbaNuEwRcCPX0bQlqQI',
  46.6742231,
  -71.3381163,
  '14188343808',
  'https://www.kwikr.ca/pictures/profile/pimage-885.jpg',
  'Roofing',
  'Growth Plan',
  886,
  'http://www.selecttoiture.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Four Corner Roofing Ltd',
  '<p>Four Corner Roofing Ltd operates as a reliable roofing contractor in Surrey, British Columbia. This business specializes in residential and commercial roofing solutions, offering services that include roof installations, repairs, and maintenance. With a commitment to quality and customer satisfaction, Four Corner Roofing Ltd has established a strong reputation in the local community.</p> <p>The company utilizes high-quality materials and skilled craftsmanship to ensure durable and long-lasting roofs. Attention to detail is evident in every project, whether it involves a simple repair or a complete roof replacement. Four Corner Roofing Ltd prioritizes safety and adheres to all industry standards, making it a trustworthy choice for roofing needs.</p> <p>Customers appreciate the transparent communication and timely service provided by the team. The business has successfully completed numerous projects across Surrey, showcasing its ability to handle various roofing styles and challenges. Four Corner Roofing Ltd also offers competitive pricing, making quality roofing accessible to a wider audience.</p> <p>In summary, Four Corner Roofing Ltd delivers exceptional roofing services in Surrey, British Columbia, with a focus on quality, safety, and customer satisfaction. The company’s achievements reflect its dedication to the community and the roofing industry. Engage with Four Corner Roofing Ltd for reliable roofing solutions in Surrey.</p>',
  '12167 78 Ave #101',
  'Canada',
  'BC',
  'Surrey',
  'V3W 5B6',
  'roofproplus@yahoo.ca',
  'canada/surrey/home-services/four-corner-roofing-ltd',
  'ChIJqQuZ22_ZhVQRftflNI6ozyo',
  49.1450211,
  -122.885422,
  '16046144710',
  NULL,
  'Roofing',
  'Growth Plan',
  885,
  'http://fourcornerroofing.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Roof Pro Plus Home Improvements',
  '<p>Roof Pro Plus Home Improvements provides comprehensive roofing services in Georgina, Ontario. This family-owned business boasts over 20 years of experience in the industry. Services include complete re-roofing, new build roofing, flat roofing, and composite roofing. Additionally, the company specializes in vinyl and wood siding installation, soffit, fascia, seamless eavestrough, skylights, and attic insulation. Fully insured, Roof Pro Plus also offers a 10-year workmanship warranty alongside manufacturers'' warranties that can extend up to 50 years.</p> <p>As a local insider, the importance of quality roofing cannot be overstated. Roof Pro Plus Home Improvements has built a solid reputation in the community for reliability and expertise. The team approaches each project with a commitment to excellence, ensuring that every installation meets high standards. Homeowners benefit from personalized service tailored to their specific needs, which fosters trust and satisfaction. With a focus on exterior solutions, the company addresses the diverse needs of residential properties.</p> <p>The combination of extensive experience, a wide range of services, and strong warranties sets Roof Pro Plus apart in the competitive roofing market. Their dedication to customer satisfaction and quality workmanship has made them a preferred choice for many in the area. Engage with Roof Pro Plus Home Improvements for all roofing needs in Georgina, Ontario, and experience the difference in service and quality.</p>',
  '26943 ON-48',
  'Canada',
  'ON',
  'Georgina',
  'L0E 1R0',
  'toddroofworx@gmail.com',
  'canada/georgina/home-services/roof-pro-plus-home-improvements',
  'ChIJ6Rf3PSJN1YkR-EbXSfsmQZQ',
  44.30623,
  -79.32075,
  '19057223121',
  NULL,
  'Roofing',
  'Growth Plan',
  884,
  'https://roofproplus.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'TRW Roofworx Inc',
  '<p>TRW Roofworx Inc provides exceptional roofing services in Sutton West, Ontario. This reliable roofing contractor specializes in a range of services, ensuring quality and durability for every project. With a commitment to customer satisfaction, TRW Roofworx addresses all roofing needs efficiently and effectively.</p><p>Founded with a vision to deliver top-notch roofing solutions, TRW Roofworx has built a reputation for excellence in Sutton West. The team possesses extensive knowledge and experience in the roofing industry, allowing them to tackle projects of any size. From residential to commercial roofing, this contractor offers comprehensive services that include installation, repair, and maintenance. Clients appreciate the attention to detail and the high-quality materials used in every project.</p><p>TRW Roofworx prioritizes safety and adheres to all industry standards, ensuring peace of mind for customers. The company’s dedication to transparency and integrity reflects in its business practices. Clients can expect timely project completion and clear communication throughout the process. Positive feedback from satisfied customers highlights the reliability and professionalism of TRW Roofworx.</p><p>With a focus on quality workmanship and customer care, TRW Roofworx Inc stands as a leading roofing contractor in Sutton West, Ontario. The company’s extensive range of services and commitment to excellence make it a top choice for roofing needs. Contact TRW Roofworx today for reliable roofing solutions in Sutton West.</p>',
  '25178 Valleyview Dr',
  'Canada',
  'ON',
  'Sutton West',
  'L0E 1R0',
  'dan@dmexteriorcontracting.ca',
  'canada/sutton-west/home-services/trw-roofworx-inc',
  'ChIJj2rBJGBL1YkRclE3juQc-ts',
  44.2779747,
  -79.355955,
  '14168824675',
  'https://www.kwikr.ca/pictures/profile/pimage-882.jpg',
  'Roofing',
  'Growth Plan',
  883,
  'http://roofworxinc.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'D M Contracting',
  '<p>D M Contracting operates as a reliable roofing contractor in Langton, Ontario, providing exceptional services to both residential and agricultural clients. This family-owned business specializes in durable exterior renovations, ensuring that homes and properties maintain their value and aesthetic appeal.</p> <p>The range of services offered includes a variety of roofing solutions, such as asphalt shingles and shakes, tailored to meet the specific needs of each client. In addition to roofing, D M Contracting enhances properties by constructing pole barns and garages, as well as installing high-quality windows and doors. Each project reflects a commitment to quality and customer satisfaction.</p> <p>With a strong reputation in the local community, D M Contracting has garnered trust through years of dedicated service. The team prioritizes using top-grade materials and skilled craftsmanship, ensuring that every renovation withstands the test of time. Clients appreciate the attention to detail and professionalism demonstrated throughout each project.</p> <p>The business continues to grow, driven by a passion for improving the homes and properties in Langton. D M Contracting’s expertise in roofing and renovations positions it as a go-to choice for those seeking reliable and efficient service. Explore the various services offered by this local contractor to enhance any property. Visit Langton today for expert renovations and roofing solutions from D M Contracting.</p>',
  '963 5th Concession Rd Enr RR 4',
  'Canada',
  'ON',
  'Langton',
  'N0E 1G0',
  'info@cplusroofing.com',
  'canada/langton/home-services/d-m-contracting',
  'ChIJp5__yrDNLYgRIVSVESjB8Wc',
  42.6560593,
  -80.6296073,
  '15198751823',
  'https://www.kwikr.ca/pictures/profile/pimage-881.jpg',
  'Roofing',
  'Growth Plan',
  882,
  'http://www.dmexteriorcontracting.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'C Plus Roofing',
  '<p>C Plus Roofing operates as a trusted roofing contractor in Markham, Ontario, delivering exceptional roofing services to homeowners in Toronto and the Greater Toronto Area (GTA). With over 10 years of experience, this company specializes in both roof repairs and replacements, ensuring quality workmanship and customer satisfaction.</p><p>The team at C Plus Roofing emphasizes reliability and professionalism in every project. They understand the importance of a sturdy roof and work diligently to meet the needs of their clients. By offering fair pricing, the company builds long-term relationships with customers, who appreciate the transparency and integrity of their service. C Plus Roofing has established a reputation for excellence in the local community, which speaks to their commitment to quality.</p><p>Utilizing high-quality materials and skilled craftsmanship, C Plus Roofing tackles various roofing issues, from minor repairs to complete replacements. Homeowners benefit from personalized service and thorough consultations, allowing for informed decision-making. The company’s attention to detail ensures that each project meets industry standards and enhances the overall value of the property.</p><p>C Plus Roofing stands as a reliable choice for roofing needs in Markham and surrounding areas. Their experience, commitment to quality, and customer-first approach make them a preferred option for homeowners. Contact C Plus Roofing today for a free estimate and discover the difference in service quality in Markham, Ontario.</p>',
  '66 Norbury Dr',
  'Canada',
  'ON',
  'Markham',
  'L3S 3V2',
  'info@www.unitedroofing.ca',
  'canada/markham/home-services/c-plus-roofing',
  'ChIJa-bUbKrX1IkR7ygbz6K0YBs',
  43.8543743,
  -79.2408856,
  '14169179622',
  'https://www.kwikr.ca/pictures/profile/pimage-880.jpg',
  'Roofing',
  'Growth Plan',
  881,
  'https://www.cplusroofing.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'United Roofing',
  '<p>United Roofing Edmonton Inc. operates as a reliable roofing contractor in Edmonton, Alberta, specializing in commercial roofing, building envelope solutions, below-ground services, and waterproofing. Established in 2014, this company has built a strong reputation for quality and professionalism in the local area.</p> <p>The team at United Roofing brings extensive knowledge and experience to each project, ensuring that every roofing need is met with precision. Their expertise in commercial roofing sets them apart, making them a go-to choice for businesses looking for durable and effective roofing solutions. The commitment to quality workmanship and customer satisfaction has led to numerous successful projects throughout Edmonton.</p> <p>In addition to commercial roofing, United Roofing excels in building envelope services, which enhance the energy efficiency and durability of structures. Their below-ground and waterproofing services protect properties from water damage, ensuring long-lasting integrity. Each service is tailored to meet the specific needs of clients, demonstrating a customer-centric approach that fosters trust and reliability.</p> <p>United Roofing Edmonton Inc. delivers comprehensive roofing solutions with a focus on quality and efficiency. Their achievements in the industry reflect a commitment to excellence. For reliable roofing services in Edmonton, connect with United Roofing today at their location on 21104 107 Ave NW, T5S 1X2.</p>',
  '21104 107 Ave NW',
  'Canada',
  'AB',
  'Edmonton',
  'T5S 1X2',
  'bcote@roofingrbm.com',
  'canada/edmonton/home-services/united-roofing',
  'ChIJe0dqmAkZoFMRZs9xr7OJnwo',
  53.552214,
  -113.6826003,
  '17802452753',
  'https://www.kwikr.ca/pictures/profile/pimage-879.jpg',
  'Roofing',
  'Growth Plan',
  880,
  'https://www.unitedroofing.ca/edmonton/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Roofing RBM',
  '<p>Roofing RBM offers premier roofing services in Edmonton, Alberta, specializing in quality roof installations and repairs. This local roofing contractor understands the unique challenges posed by Edmonton''s extreme weather conditions. With a focus on protecting homes, Roofing RBM ensures that every roofing project meets high standards of quality and craftsmanship.</p> <p>The team at Roofing RBM possesses extensive experience in handling various roofing projects. From the removal of old shingles to the careful replacement of damaged plywood, the skilled crew manages every detail with precision. This commitment to quality workmanship results in roofs that stand the test of time and weather. Homeowners can trust Roofing RBM to provide expert advice on shingle selection, ensuring that the right materials are chosen for durability and performance.</p> <p>In addition to their roofing expertise, Roofing RBM prioritizes customer satisfaction. The company has built a reputation for reliability and professionalism in the Edmonton area. Each project is approached with a dedication to excellence, ensuring that clients receive the best possible service from start to finish.</p> <p>Roofing RBM delivers quality roofing solutions tailored to the needs of Edmonton residents. With a focus on craftsmanship and customer care, they have established themselves as a trusted name in the industry. Connect with Roofing RBM today at 10744 180 St NW, Edmonton, Alberta, T5S 2S4 for expert roofing services.</p>',
  '10744 180 St NW',
  'Canada',
  'AB',
  'Edmonton',
  'T5S 2S4',
  'sales@allproroofing.ca',
  'canada/edmonton/home-services/roofing-rbm',
  'ChIJw6jp3kAloFMR25FbrsogPJ8',
  53.554271,
  -113.631025,
  '17806803801',
  'https://www.kwikr.ca/pictures/profile/pimage-878.jpg',
  'Roofing',
  'Growth Plan',
  879,
  'https://roofingrbm.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'All Pro Roofing & SheetMetal Ltd.',
  '<p>All Pro Roofing & SheetMetal Ltd. delivers expert roofing solutions in London, Ontario. This roofing contractor specializes in flat roof repair and custom sheet metal projects, serving a diverse range of buildings including hospitals, schools, and residential homes. With a strong focus on quality and customer satisfaction, All Pro Roofing has established itself as a reliable choice in SouthWestern Ontario.</p><p>The company excels in servicing, repairing, and replacing flat roofs across various sectors. Apartment buildings, shopping malls, and medical facilities benefit from All Pro Roofing''s expertise. Each project receives careful attention, ensuring durability and compliance with industry standards. The skilled team utilizes modern techniques and high-quality materials, guaranteeing long-lasting results.</p><p>All Pro Roofing''s commitment to excellence is evident in their numerous successful projects. The company prioritizes safety and efficiency, making them a preferred contractor for both commercial and residential clients. Their ability to handle complex roofing challenges sets them apart in the competitive roofing market.</p><p>With a reputation built on reliability and professionalism, All Pro Roofing & SheetMetal Ltd. remains dedicated to enhancing the integrity of flat roofs in the region. Their extensive experience and customer-focused approach make them an ideal partner for any roofing needs. Contact All Pro Roofing today for top-notch roofing services in London, Ontario.</p>',
  '3090 Colonel Talbot Rd #36002',
  'Canada',
  'ON',
  'London',
  'N6P 0C4',
  'info@alfaexteriors.ca',
  'canada/london/home-services/all-pro-roofing-sheetmetal-ltd',
  'ChIJoyItEoPxLogRjjqFOrazVm4',
  42.9343006,
  -81.3164442,
  '15198529269',
  'https://www.kwikr.ca/pictures/profile/pimage-877.jpg',
  'Roofing',
  'Growth Plan',
  878,
  'http://www.allproroofing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Alfa Roofing & Siding Ltd',
  '<p>Alfa Roofing & Siding Ltd offers comprehensive exterior solutions in Calgary, Alberta. This roofing contractor specializes in repairs and replacements, addressing issues caused by hail damage and wind storms. Established in 1991, Alfa Roofing & Siding emerged from the vision of two skilled installers focused on enhancing customer service standards in the roofing industry. The company has built a reputation for reliability and quality workmanship.</p><p>The expertise of Alfa Roofing & Siding extends to a broad range of exterior services, ensuring that each project meets the highest standards. The commitment to treating customers, employees, and installers with respect fosters loyalty and satisfaction. This approach has resulted in a strong client base that values the quality and integrity of services provided. Fair labor rates for dedicated installers reflect the company''s dedication to both its team and its clients.</p><p>Alfa Roofing & Siding Ltd excels in delivering efficient and effective solutions for all exterior needs. The combination of experience, commitment to quality, and customer-centric practices positions the company as a leader in the Calgary area. With a focus on professionalism and respect, Alfa Roofing & Siding ensures that each project is handled with care and expertise. Visit Calgary for reliable exterior services that prioritize quality and customer satisfaction. Contact Alfa Roofing & Siding Ltd today for expert assistance in Calgary.</p>',
  '6159 6 St SE',
  'Canada',
  'AB',
  'Calgary',
  'T2H 1L9',
  'info@vitaroofs.com',
  'canada/calgary/home-services/alfa-roofing-siding-ltd',
  'ChIJ-zmuXGZwcVMR3vBdIyJNNQA',
  50.9967781,
  -114.0521953,
  '14032517155',
  'https://www.kwikr.ca/pictures/profile/pimage-876.jpg',
  'Roofing',
  'Growth Plan',
  877,
  'https://alfaexteriors.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Vitaroofs International Inc.',
  '<p>Vitaroofs International Inc. provides exceptional roofing solutions in Oakville, Ontario. This roofing contractor specializes in residential and commercial roofing services, ensuring quality and durability in every project. With a strong commitment to customer satisfaction, Vitaroofs International Inc. has established a reputation for reliability and expertise in the roofing industry.</p><p>The team at Vitaroofs International Inc. brings years of experience to the table, utilizing the latest techniques and materials to deliver superior results. Services include roof installation, repair, and maintenance, catering to various roofing styles and needs. The company focuses on using high-quality materials that withstand the Canadian climate, ensuring long-lasting protection for properties.</p><p>Vitaroofs International Inc. emphasizes safety and efficiency in all projects. The skilled professionals prioritize customer communication, keeping clients informed throughout the roofing process. This dedication to service has earned the company numerous positive reviews from satisfied customers in the Oakville area.</p><p>With a commitment to excellence, Vitaroofs International Inc. stands ready to tackle any roofing challenge. Their focus on quality workmanship and customer service sets them apart in the competitive roofing market. Vitaroofs International Inc. offers comprehensive roofing solutions that meet diverse client needs. Contact Vitaroofs International Inc. at 1276 Elgin Crescent, Oakville, Ontario, for reliable roofing services today.</p>',
  '1276 Elgin Crescent',
  'Canada',
  'ON',
  'Oakville',
  'L6H 2J7',
  'info@robsqualityroofing.com',
  'canada/oakville/home-services/vitaroofs-international-inc',
  'ChIJ_2pUajo_K4gRRxTAw_OJes4',
  43.477659,
  -79.683754,
  '19055659669',
  'https://www.kwikr.ca/pictures/profile/pimage-875.jpg',
  'Roofing',
  'Growth Plan',
  876,
  'http://www.vitaroofs.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Rob''s Quality Roofing - Shingle Roof Replacement & Installation',
  '<p>Rob''s Quality Roofing, located at 3275 Pierce Rd in North Gower, Ontario, specializes in shingle roof replacement and installation. This roofing contractor has served the Ottawa region since 2004, providing reliable residential roofing repair and installation services. With a focus on asphalt shingles, the company has built a reputation for quality workmanship and customer satisfaction.</p><p>The company prides itself on having the owner present on-site for all jobs, ensuring high standards are met. Rob''s Quality Roofing is fully licensed and insured, which adds to its credibility in the roofing industry. The small, dedicated team offers personalized service, making sure that every project receives the attention it deserves. Customers appreciate the straightforward approach and commitment to getting the job done right the first time.</p><p>Rob''s Quality Roofing has successfully completed numerous projects, showcasing their expertise in asphalt shingles. The emphasis on quality materials and skilled labor results in roofs that not only enhance the aesthetic appeal of homes but also provide long-lasting protection against the elements. This commitment to excellence has earned the trust of homeowners in North Gower and the surrounding areas.</p><p>Rob''s Quality Roofing offers exceptional roofing services, focusing on asphalt shingles and customer satisfaction. With a dedicated team and years of experience, this business meets the roofing needs of the local community. Contact Rob''s Quality Roofing in North Gower for reliable roofing solutions.</p>',
  '3275 Pierce Rd',
  'Canada',
  'ON',
  'North Gower',
  'K0A 2T0',
  'info@royalyorkroofing.ca',
  'canada/north-gower/home-services/rob-s-quality-roofing-shingle-roof-replacement-installation',
  'ChIJYaDCOsvtzUwROO726O3ZaYI',
  45.0819534,
  -75.7740129,
  '16132236467',
  'https://www.kwikr.ca/pictures/profile/pimage-874.jpg',
  'Roofing',
  'Growth Plan',
  875,
  'http://robsqualityroofing.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Royal York Roofing Ltd.',
  '<p>Royal York Roofing Ltd. operates as a leading roofing contractor in Etobicoke, Ontario. This company specializes in various roofing services, including residential, commercial, industrial, and institutional new roof installations and repairs. With a commitment to timely and experienced service, Royal York Roofing ensures every project meets high standards of quality and craftsmanship.</p> <p>The company boasts a diverse portfolio, showcasing a range of successful roofing projects. Each completed job reflects the expertise and dedication of the seasoned roofers who work with a focus on customer needs. Royal York Roofing understands the importance of tailored solutions, providing options that cater specifically to each client’s requirements. This approach builds trust and satisfaction among customers.</p> <p>Royal York Roofing emphasizes quality and reliability in every aspect of its operations. The team’s extensive experience in the roofing industry allows for efficient project management and execution. Clients can expect clear communication and professional service throughout the roofing process. The company’s reputation is built on a foundation of hard work and commitment to excellence.</p> <p>Offering a comprehensive range of roofing services, Royal York Roofing Ltd. demonstrates its strengths in craftsmanship and customer service. The company’s achievements in the local area highlight its dedication to quality work. Connect with Royal York Roofing for expert roofing solutions in Etobicoke, Ontario.</p>',
  '30 Plywood Pl #2',
  'Canada',
  'ON',
  'Etobicoke',
  'M8Z 5J2',
  'info@vandutchexteriors.ca',
  'canada/etobicoke/home-services/royal-york-roofing-ltd',
  'ChIJMXIUC9k3K4gRm5tGS_qVcjM',
  43.6186699,
  -79.5298997,
  '14167607663',
  'https://www.kwikr.ca/pictures/profile/pimage-873.jpg',
  'Roofing',
  'Growth Plan',
  874,
  'https://www.royalyorkroofing.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);
