INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Arevco Lighting Ottawa',
  '<p>Arevco Lighting Ottawa serves the vibrant community of Ottawa, Ontario, offering a comprehensive range of lighting solutions. Established in 2001 by Hera Arevian, this lighting store began as a small boutique in the trendy Westboro area. Over the years, it has expanded into a spacious 3000 sq. ft. showroom, showcasing an extensive selection of lighting products. The business has gained recognition for its exceptional customer service, extensive lighting expertise, and reliable consultation and repair work.</p><p>The team at Arevco Lighting Ottawa possesses in-depth knowledge of various lighting options, ensuring customers receive tailored solutions to meet their specific needs. From modern fixtures to classic designs, the store features a diverse inventory that caters to both residential and commercial clients. The commitment to quality and service has established Arevco as a trusted name in the local lighting industry.</p><p>Customer satisfaction remains a priority, with Hera and her qualified team working diligently to provide a welcoming shopping experience. The store’s reputation is built on attentive service and a passion for lighting innovation. Arevco Lighting Ottawa not only enhances spaces but also educates clients on the best lighting practices.</p><p>With a strong focus on quality, expertise, and customer service, Arevco Lighting Ottawa continues to be a preferred destination for lighting needs in Ottawa. Visit the store located at 915 B Clyde Avenue facing Laperriere Ave to explore the impressive selection of lighting solutions.</p>',
  '915 B Clyde Avenue facing, Laperriere Ave',
  'Canada',
  'ON',
  'Ottawa',
  'K1Z 5A6',
  'chad@goldenenviro.ca',
  'canada/ottawa/home-services/arevco-lighting-ottawa',
  'ChIJnfy95AIEzkwRE0ArnjaA0z8',
  45.3754271,
  -75.7475944,
  '16137292725',
  'https://www.kwikr.ca/pictures/profile/pimage-207.jpg',
  'Electrical=>Lighting Installation',
  'Pay-as-you-go',
  223,
  'https://lightingcanada.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Espace Lumi Décor',
  '<p>Espace Lumi Décor operates as a premier lighting store located at 1146 Bd Saint-Luc in Saint-Jean-sur-Richelieu, Quebec. This retailer specializes in providing a wide range of indoor and outdoor lighting solutions. Customers can find an extensive inventory that includes both new and liquidated items, catering to various styles and budgets.</p><p>The store emphasizes quality and variety, ensuring that every customer finds the perfect lighting fixture for their needs. From elegant chandeliers to practical outdoor lights, Espace Lumi Décor covers every aspect of lighting design. The knowledgeable staff assists in selecting the right products, providing expert advice on installation and maintenance.</p><p>Espace Lumi Décor has built a reputation for reliability and customer satisfaction in the local community. The commitment to offering diverse lighting options sets this store apart from competitors. Customers appreciate the blend of affordability and quality that the store provides, making it a go-to destination for lighting solutions in Saint-Jean-sur-Richelieu.</p><p>The focus on both indoor and outdoor lighting ensures that every space can be illuminated effectively. With a strong inventory of liquidated items, Espace Lumi Décor offers unique choices that are often hard to find elsewhere. This retailer excels in meeting the lighting needs of the community while maintaining high standards of service. Visit Espace Lumi Décor in Saint-Jean-sur-Richelieu for exceptional lighting solutions.</p>',
  '1146 Bd Saint-Luc',
  'Canada',
  'QC',
  'Saint-Jean-sur-Richelieu',
  'J2W 2G6',
  'inquiry@smottawa.com',
  'canada/saint-jean-sur-richelieu/home-services/espace-lumi-décor',
  'ChIJmwu66fsJyUwRGq-W32LL1ZA',
  45.3744375,
  -73.3672608,
  '14503591441',
  'https://www.kwikr.ca/pictures/profile/pimage-206.jpg',
  'Electrical=>Lighting Installation',
  'Pay-as-you-go',
  222,
  'https://www.lumidecor.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Royce Lighting, Guelph | Lighting store in Canada',
  '<p>Royce Lighting, located at 221 Woodlawn Rd W in Guelph, Ontario, offers an impressive selection of lighting fixtures designed to elevate any space. This lighting store specializes in a variety of styles, ensuring that customers find the perfect match for their aesthetic needs. With a focus on quality and innovative design, Royce Lighting has become a trusted resource for homeowners and businesses alike.</p><p>The store features a wide range of products, including contemporary, traditional, and unique lighting solutions. Each fixture is carefully selected to meet high standards of craftsmanship and style. Customers appreciate the knowledgeable staff who provide expert guidance, helping to navigate the diverse collection available. Royce Lighting also emphasizes the importance of ambiance, understanding that the right lighting can dramatically alter the atmosphere of a room.</p><p>Royce Lighting has established a reputation in Guelph for its commitment to customer satisfaction and quality service. The store regularly updates its inventory to include the latest trends and timeless classics, ensuring that there is always something new to discover. This dedication to excellence has garnered a loyal customer base that values both aesthetic appeal and functionality in lighting.</p><p>Explore the extensive range of lighting options at Royce Lighting, where design meets quality. Discover how lighting can transform spaces and enhance environments. Visit Royce Lighting in Guelph, Ontario, to experience exceptional lighting solutions firsthand.</p>',
  '221 Woodlawn Rd W',
  'Canada',
  'ON',
  'Guelph',
  'N1H 8P4',
  'quotes@cityproparkade.ca',
  'canada/guelph/home-services/royce-lighting-guelph-lighting-store-in-canada',
  'ChIJS6SkbYGRK4gRdN52tMhWOFA',
  43.5547823,
  -80.292092,
  '12896237244',
  NULL,
  'Electrical=>Lighting Installation',
  'Pay-as-you-go',
  221,
  'https://www.roycelight.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Lights by HomeOne Lethbridge',
  '<p>Lights by HomeOne Lethbridge offers innovative lighting solutions in Lethbridge, Alberta. Specializing in permanent LED lighting setups, this lighting store transforms spaces with vibrant illumination. The business focuses on enhancing both residential and commercial environments, ensuring each installation celebrates life with light. Located at 1602 3 Ave S, the store is easily accessible for local customers seeking quality lighting options.</p> <p>The expertise of Lights by HomeOne Lethbridge lies in providing durable and energy-efficient LED lighting that meets diverse needs. With a commitment to customer satisfaction, the team works closely with clients to deliver tailored solutions that elevate any property. The permanent installations are designed to withstand the elements, ensuring longevity and consistent performance. This approach not only enhances aesthetics but also contributes to energy savings.</p> <p>Recognized for its reliability and quality, Lights by HomeOne Lethbridge has become a preferred choice for lighting solutions in the community. Customers appreciate the professional service and attention to detail provided during the installation process. The store''s dedication to celebrating life through innovative lighting makes it a vital part of the local landscape.</p> <p>Lights by HomeOne Lethbridge delivers exceptional LED lighting solutions, combining quality and expertise. With a focus on customer satisfaction and energy efficiency, the business enhances spaces across Lethbridge. Connect with Lights by HomeOne Lethbridge today for transformative lighting services in Alberta.</p>',
  '1602 3 Ave S',
  'Canada',
  'AB',
  'Lethbridge',
  'T1J 0L2',
  'info@firstgeneralniagara.com',
  'canada/lethbridge/home-services/lights-by-homeone-lethbridge',
  'ChIJrXRLLHrhk4kRumUtGWrubpI',
  49.6961449,
  -112.8182453,
  '14034016583',
  NULL,
  'Electrical=>Lighting Installation',
  'Pay-as-you-go',
  220,
  'https://homeonelights.com/permanent-outdoor-lights-lethbridge/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Union Luminaires & Décor Liquidation Warehouse',
  '<p>Union Luminaires & Décor Liquidation Warehouse serves Montreal, Quebec, offering a wide range of lighting solutions, furniture, and home decor from top brands. This lighting store features products from Visual Comfort, Arteriors, and Fine Arts, ensuring high quality and style at unbeatable prices. Customers can find everything they need to enhance their home environment.</p><p>This warehouse specializes in liquidation sales, providing significant savings on premium lighting and decor items. The extensive inventory includes modern and traditional lighting fixtures, stylish furniture, and unique decorative pieces. Shoppers appreciate the opportunity to discover exceptional products at reduced prices, making it an ideal destination for homeowners and interior designers alike.</p><p>The knowledgeable staff at Union Luminaires & Décor Liquidation Warehouse assists customers in selecting the right products for their spaces. The focus on customer service and satisfaction sets this business apart in the competitive lighting store market. With a commitment to quality and affordability, this warehouse has built a solid reputation in the local community.</p><p>Union Luminaires & Décor Liquidation Warehouse provides a diverse selection of lighting, furniture, and home decor, catering to various tastes and budgets. The combination of top brands and competitive pricing makes it a go-to destination for many. Visit 5330 Royalmount Ave., Montreal, Quebec, to explore the impressive offerings and find the perfect pieces for any home. Connect with Union Luminaires & Décor Liquidation Warehouse today.</p>',
  '5330 Royalmount Ave.',
  'Canada',
  'QC',
  'Montreal',
  'H4P 2P5',
  'customerservice@pinnaclehygiene.ca',
  'canada/montreal/home-services/union-luminaires-décor-liquidation-warehouse',
  'ChIJD7qOpGIZyUwRmmb8-EbcnF4',
  45.4979794,
  -73.6611682,
  '15147883646',
  'https://www.kwikr.ca/pictures/profile/pimage-203.jpg',
  'Electrical=>Lighting Installation',
  'Pay-as-you-go',
  219,
  'https://unionlighting.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'ILLIGHTS',
  '<p>ILLIGHTS, located at 168 Kennedy Rd S #3 in Brampton, Ontario, offers a diverse range of lighting solutions. This lighting store specializes in chandeliers, ceiling lights, pot lights, slim panels, and bathroom vanity lights. With a commitment to quality and affordability, ILLIGHTS serves the local community by providing exceptional service and a wide selection of products tailored to various home lighting needs.</p> <p>This business prioritizes customer satisfaction through its extensive inventory and knowledgeable staff. ILLIGHTS understands the importance of finding the right lighting to enhance any space. Each product is selected for its quality and style, ensuring that customers can achieve their desired ambiance without overspending. The store''s competitive pricing makes it accessible for various budgets, appealing to both homeowners and interior designers alike.</p> <p>ILLIGHTS has established a reputation in Brampton for its reliable service and quality offerings. Customers appreciate the personalized attention they receive, making the shopping experience more enjoyable and efficient. This focus on customer experience has led to numerous positive reviews and a loyal customer base.</p> <p>Explore the extensive range of lighting solutions at ILLIGHTS. The store''s commitment to quality and affordability makes it a top choice for lighting needs in Brampton. Visit ILLIGHTS today to find the perfect lighting solutions for any space in your home.</p>',
  '168 Kennedy Rd S #3',
  'Canada',
  'ON',
  'Brampton',
  'L6W 3G6',
  'admin@pearlcleaninginc.ca',
  'canada/brampton/home-services/illights',
  'ChIJAc39ViU-K4gRhTRBkz-lLZU',
  43.68122,
  -79.72931,
  '14162773979',
  NULL,
  'Electrical=>Lighting Installation',
  'Pay-as-you-go',
  218,
  'http://www.illights.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Lightdepot Canada Inc.',
  '<p>Lightdepot Canada Inc. serves Scarborough, Ontario, as a premier lighting store specializing in a wide range of lighting solutions. The business offers automotive LED lights, HID kits, LED strip lights, emergency warning lights, and more. With a focus on quality and innovation, Lightdepot Canada Inc. caters to both home and commercial lighting needs, ensuring customers find the perfect lighting products for their requirements.</p> <p>The extensive selection includes tow truck lights and volunteer firefighter green strobe lights, highlighting a commitment to safety and functionality. The store also provides LED work lights and a variety of LED light bulbs suitable for various applications. Each product is designed to enhance visibility and efficiency, making Lightdepot Canada Inc. a trusted choice for consumers and professionals alike.</p> <p>Located at 4465 Sheppard Ave E #9, this lighting store combines expertise with a customer-focused approach. The knowledgeable staff assists clients in identifying the best lighting solutions tailored to their specific needs. Lightdepot Canada Inc. has established a reputation for reliability and quality, contributing to the local community''s lighting needs.</p> <p>In summary, Lightdepot Canada Inc. offers a comprehensive range of lighting products, emphasizing safety and efficiency. The store''s dedication to customer service and quality products makes it a valuable resource in Scarborough. Visit Lightdepot Canada Inc. today for all lighting needs in Ontario.</p>',
  '4465 Sheppard Ave E #9',
  'Canada',
  'ON',
  'Scarborough',
  'M1S 5H9',
  'hello@cleananswers.ca',
  'canada/scarborough/home-services/lightdepot-canada-inc',
  'ChIJY3ETGg3R1IkRDJ5gxud0ElY',
  43.787836,
  -79.2661286,
  '14167239229',
  'https://www.kwikr.ca/pictures/profile/pimage-201.jpg',
  'Electrical=>Lighting Installation',
  'Pay-as-you-go',
  217,
  'https://www.lightdepot.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'ECLAIRAGE DIODE',
  '<p>ECLAIRAGE DIODE serves Laval, Quebec, as a premier lighting store specializing in high-quality lighting solutions for residential and commercial needs. The store offers a diverse range of products, including LED fixtures, decorative lighting, and energy-efficient options. ECLAIRAGE DIODE emphasizes exceptional customer service and expert guidance, helping clients select the right lighting for their spaces.</p><p>The store is known for its extensive inventory, which caters to various styles and preferences. ECLAIRAGE DIODE understands the importance of lighting in enhancing environments, whether it’s for a cozy home or a bustling business. The knowledgeable staff provides insights into the latest lighting trends and technologies, ensuring customers make informed choices.</p><p>Located at 1204 Rue Bergar, ECLAIRAGE DIODE is conveniently accessible for local residents and businesses. The commitment to quality and innovation sets the store apart in the competitive lighting market. Customers benefit from personalized consultations, ensuring that their specific lighting needs are met effectively.</p><p>ECLAIRAGE DIODE excels in providing a wide array of lighting solutions, backed by a dedication to customer satisfaction and expertise in the field. The store''s reputation for reliability and quality makes it a go-to destination for lighting needs in Laval. Visit ECLAIRAGE DIODE today to explore the extensive selection of lighting products available in Laval, Quebec.</p>',
  '1204 Rue Bergar',
  'Canada',
  'QC',
  'Laval',
  'H7L 4Z7',
  'jpetersen@mulberrymc.com',
  'canada/laval/home-services/eclairage-diode',
  'ChIJ8eoff0QhyUwRrfK9flh11eE',
  45.5926727,
  -73.7470235,
  '14506679410',
  NULL,
  'Electrical=>Lighting Installation',
  'Pay-as-you-go',
  216,
  'http://www.eclairagediode.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Mclaren Lighting',
  '<p>Mclaren Lighting, located at 2520 Bowen Rd in Nanaimo, British Columbia, offers an extensive selection of lighting solutions for residential and commercial needs. For over 60 years, this family-owned and operated lighting showroom has served the communities of Vancouver Island, providing exceptional customer service and unique products that cannot be found in big box stores. The commitment to ensuring customers never get left in the dark is evident in every interaction.</p><p>This lighting store prides itself on delivering an outstanding customer experience. Mclaren Lighting features a diverse range of lighting options, catering to various styles and preferences. The knowledgeable team of expert lighting consultants offers personalized assistance, addressing questions and providing insights that enhance the shopping experience. This level of expertise is difficult to replicate in larger retail environments.</p><p>With a mission focused on customer satisfaction, Mclaren Lighting stands out by offering value through quality products and expert guidance. The store''s dedication to the local community and its rich history in the industry contribute to its reputation as a trusted resource for lighting solutions. Customers can expect not only a wide selection but also a supportive team ready to help illuminate their spaces.</p><p>Mclaren Lighting excels in providing unique lighting options and exceptional customer service. The combination of experience and community focus makes this store a go-to destination for lighting needs in Nanaimo. Visit Mclaren Lighting today to explore the extensive selection available in British Columbia.</p>',
  '2520 Bowen Rd',
  'Canada',
  'BC',
  'Nanaimo',
  'V9T 3L3',
  'sales@lowfaremaintenance.ca',
  'canada/nanaimo/home-services/mclaren-lighting',
  'ChIJqREjdtOjiFQRM56PhdBtIgE',
  49.2014417,
  -123.9999084,
  '12507580138',
  'https://www.kwikr.ca/pictures/profile/pimage-199.jpg',
  'Electrical=>Lighting Installation',
  'Pay-as-you-go',
  215,
  'https://mclarenlighting.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Éclairage ETC',
  '<p>Éclairage ETC, located at 1149 Rue des Foreurs in Val-d''Or, Quebec, specializes in commercial lighting solutions for the Abitibi-Témiscamingue region. This modern lighting store serves as a professional reference for designers, architects, engineers, master electricians, general contractors, and electrical supply distributors. With a focus on innovative lighting solutions, Éclairage ETC is committed to enhancing the functionality and aesthetics of commercial spaces.</p><p>This local business offers a wide range of products and services tailored to meet the unique needs of each client. Éclairage ETC provides expert guidance on lighting design, ensuring that every project receives the attention it deserves. The knowledgeable staff understands the technical requirements of various lighting systems and can recommend the best options for any commercial application. This commitment to expertise positions Éclairage ETC as a vital resource in the community.</p><p>Éclairage ETC also emphasizes the importance of quality and sustainability in its product offerings. By partnering with reputable manufacturers, the store ensures that clients have access to the latest technologies and energy-efficient solutions. This dedication to excellence has earned Éclairage ETC a strong reputation in the local industry.</p><p>In summary, Éclairage ETC delivers exceptional lighting solutions for commercial needs in Val-d''Or. Its expertise, quality products, and commitment to customer satisfaction make it a key player in the lighting market. Connect with Éclairage ETC for all lighting needs in Val-d''Or, Quebec.</p>',
  '1149 Rue des Foreurs',
  'Canada',
  'QC',
  'Val-d''Or',
  'J9P 6X9',
  'importdata-154@kwikr.ca',
  'canada/val-d-or/home-services/éclairage-etc',
  'ChIJJ_9pTwtT30wRF8HkztX8l0Y',
  48.1120567,
  -77.7922189,
  '18198253036',
  'https://www.kwikr.ca/pictures/profile/pimage-198.jpg',
  'Electrical=>Lighting Installation',
  'Pay-as-you-go',
  214,
  'http://eclairageetc.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'ROBINSON | Lighting & Bath Showroom',
  '<p>ROBINSON | Lighting & Bath Showroom in Vancouver, British Columbia, offers a wide range of lighting solutions and bath fixtures. This local lighting store specializes in providing quality products that enhance both aesthetics and functionality in homes and businesses. With a focus on customer satisfaction, ROBINSON showcases an extensive collection of modern and traditional lighting options, catering to diverse tastes and styles.</p> <p>The showroom features products from renowned brands, ensuring customers access to the latest trends and technologies in lighting design. Knowledgeable staff members assist clients in selecting the right fixtures to complement their spaces, promoting a seamless shopping experience. ROBINSON also emphasizes energy-efficient lighting solutions, supporting sustainable practices while reducing utility costs.</p> <p>Located at 2912 Granville St, this Vancouver-based store is easily accessible for local residents and businesses. The commitment to quality and service has earned ROBINSON a reputation as a trusted destination for lighting and bath needs. Customers can explore a variety of options, from elegant chandeliers to practical bathroom lighting, all under one roof.</p> <p>ROBINSON | Lighting & Bath Showroom delivers exceptional products and service in Vancouver, British Columbia. The focus on quality, style, and sustainability makes it an ideal choice for anyone looking to enhance their space. Visit the showroom today to discover the perfect lighting solutions for any project. Connect with ROBINSON in Vancouver for expert assistance and quality products.</p>',
  '2912 Granville St',
  'Canada',
  'BC',
  'Vancouver',
  'V6H 3J7',
  'commcorporate_addressercial@servicemaster.ca',
  'canada/vancouver/home-services/robinson-lighting-bath-showroom',
  'ChIJb8oCNdxzhlQRhEAqh4CUoLI',
  49.2595635,
  -123.1384268,
  '16048796847',
  'https://www.kwikr.ca/pictures/profile/pimage-197.jpg',
  'Electrical=>Lighting Installation',
  'Pay-as-you-go',
  213,
  'http://robinsonco.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Eclairage Moderne Saran',
  '<p>Eclairage Moderne Saran is a premier lighting store located at 582 Bd du Séminaire N in Saint-Jean-sur-Richelieu, Quebec. This local business specializes in a wide range of lighting solutions, catering to both residential and commercial needs. With a commitment to quality and customer satisfaction, Eclairage Moderne Saran provides expert advice and innovative products that enhance any space.</p><p>The extensive selection includes modern fixtures, energy-efficient options, and unique designs that suit various styles and preferences. Customers can find everything from chandeliers to outdoor lighting, all crafted to meet high standards of durability and aesthetics. The knowledgeable staff offers personalized service, ensuring that each customer finds the perfect lighting solution for their specific requirements.</p><p>Eclairage Moderne Saran has built a reputation for excellence in the local community. The business prioritizes customer engagement, making sure that every interaction is informative and helpful. With a focus on quality and innovation, this lighting store remains a trusted source for residents and businesses in Saint-Jean-sur-Richelieu and surrounding areas.</p><p>Offering a diverse range of products and expert guidance, Eclairage Moderne Saran continues to illuminate spaces with style and functionality. Explore the impressive collection of lighting options available. Visit Eclairage Moderne Saran in Saint-Jean-sur-Richelieu for exceptional service and quality lighting solutions.</p>',
  '582 Bd du Séminaire N',
  'Canada',
  'QC',
  'Saint-Jean-sur-Richelieu',
  'J3B 7E3',
  'hello@ehmaids.ca',
  'canada/saint-jean-sur-richelieu/home-services/eclairage-moderne-saran',
  'ChIJvzYTp8ujyUwROcSYspnAZGA',
  45.3181612,
  -73.2645584,
  '14503484049',
  NULL,
  'Electrical=>Lighting Installation',
  'Pay-as-you-go',
  212,
  'https://eclairagesaran.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Multi Luminaire Laval',
  '<p>Multi Luminaire Laval provides a diverse selection of indoor and outdoor lighting fixtures, catering to various styles and preferences. Located at 2591 Bd Daniel-Johnson in Laval, Quebec, this lighting store serves the local community with quality products and expert advice. The store is known for its extensive inventory, ensuring customers find the perfect lighting solutions for their homes and businesses.</p> <p>The range of lighting options includes modern, traditional, and contemporary designs, allowing for seamless integration into any décor. Multi Luminaire Laval emphasizes customer satisfaction by offering personalized service and knowledgeable staff who assist in selecting the ideal fixtures. This commitment to quality and service has established the store as a reliable source for lighting needs in Laval.</p> <p>In addition to a wide variety of products, Multi Luminaire Laval focuses on providing energy-efficient lighting solutions. These options not only enhance the aesthetic appeal of spaces but also contribute to sustainability efforts. The store regularly updates its inventory to feature the latest trends and technologies in lighting, ensuring customers have access to innovative products.</p> <p>Multi Luminaire Laval excels in delivering quality lighting solutions with a focus on customer care and energy efficiency. Explore the extensive selection of indoor and outdoor lighting fixtures available. Visit Laval to experience the exceptional service and products offered by this local lighting store.</p>',
  '2591 Bd Daniel-Johnson',
  'Canada',
  'QC',
  'Laval',
  'H7T 1S8',
  'menagebonheur@gmail.com',
  'canada/laval/home-services/multi-luminaire-laval',
  'ChIJVfTmfxAjyUwR0MYRTAnKsfM',
  45.5699394,
  -73.7572151,
  '14506813939',
  'https://www.kwikr.ca/pictures/profile/pimage-195.jpg',
  'Electrical=>Lighting Installation',
  'Pay-as-you-go',
  211,
  'https://www.multiluminaire.ca/?utm_source=google&utm_medium=organic&utm_campaign=myBusiness&utm_term=Daniel-Johnson-Laval&utm_content=Laval',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Gravity Tech',
  '<p>Gravity Tech delivers comprehensive home automation solutions in Ancaster, Ontario. This company specializes in smart technology, multi-room audio and video systems, security and networking, as well as custom home theater and media solutions. Catering to both residential and commercial clients, Gravity Tech extends its services throughout the Greater Toronto Area, including cottage country.</p><p>Home automation is a growing trend that enhances convenience and security. Gravity Tech''s expertise in smart technology allows homeowners to manage their devices seamlessly. The multi-room audio and video systems create immersive entertainment experiences throughout the home. Security solutions ensure peace of mind, allowing clients to monitor their properties effectively.</p><p>Gravity Tech also excels in networking and wiring, providing reliable connections for all devices. Custom home theater solutions are tailored to individual preferences, ensuring an enjoyable viewing experience. The company’s commitment to quality service has earned it a strong reputation in the community.</p><p>With a focus on innovation and customer satisfaction, Gravity Tech continues to lead in the home automation sector. Their team of experts works diligently to meet the unique needs of each client. From installation to support, the company ensures a smooth experience for all customers.</p><p>Gravity Tech offers a range of services that enhance the quality of life through technology. Their strengths lie in their expertise and dedication to client satisfaction. Engage with Gravity Tech for all home automation needs in Ancaster, Ontario.</p>',
  '738 Shaver Rd unit c',
  'Canada',
  'ON',
  'Ancaster',
  'L9G 3K9',
  'info@womanstouchcleaning.com',
  'canada/ancaster/home-services/gravity-tech',
  'ChIJq6oV6LKILIgRa9edAQRCjJ4',
  43.1910246,
  -80.0107092,
  '19053041216',
  NULL,
  'Electrical=>Home Automation',
  'Pay-as-you-go',
  210,
  'https://www.gravitytech.ca/?utm_source=google&utm_medium=wix_google_business_profile&utm_campaign=9720640280577862432',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Dana Smart Homes',
  '<p>Dana Smart Homes is a premier home automation company located in Vaughan, Ontario, specializing in smart home technology. As an authorized Control4 dealer, this business serves the Greater Toronto Area, offering comprehensive solutions that enhance home security, lighting, climate control, and entertainment systems. Dana Smart Homes combines modern technology with expert knowledge to deliver tailored automation services.</p><p>The range of services includes advanced security systems equipped with smart door locks and live video doorbells, ensuring safety and convenience. Smart lighting solutions allow homeowners to control ambiance effortlessly, while media systems enable seamless music and movie management. Climate control features maintain optimal home temperatures, contributing to energy efficiency and comfort. Video surveillance options provide peace of mind, allowing homeowners to monitor their properties remotely.</p><p>Dana Smart Homes distinguishes itself with a commitment to customer satisfaction and quality service. A free site visit allows for personalized quotes, ensuring that each project meets the specific needs of the homeowner. The team''s expertise and dedication to innovation position Dana Smart Homes as a leader in home automation in Vaughan and the surrounding areas.</p><p>With a focus on enhancing daily living through technology, Dana Smart Homes provides essential services that transform houses into smart homes. Explore the benefits of smart home technology and connect with Dana Smart Homes in Vaughan today.</p>',
  '7250 Keele St #234',
  'Canada',
  'ON',
  'Vaughan',
  'L4K 1Z8',
  'info.cleanvictoria@gmail.com',
  'canada/vaughan/home-services/dana-smart-homes',
  'ChIJKQB9IdYtK4gRUBp7UAOnncs',
  43.7872488,
  -79.497802,
  '14167779990',
  NULL,
  'Electrical=>Home Automation',
  'Pay-as-you-go',
  209,
  'http://www.danasmarthomes.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'PureImage Technology',
  '<p>PureImage Technology offers comprehensive home automation solutions in Victoria, British Columbia. Specializing in leading brands like Control4, Crestron, Lutron, and Savant Systems, this company delivers advanced technology to enhance residential living. Services include custom home cinemas, distributed network solutions, motorized window coverings, and security systems.</p> <p>PureImage Technology prides itself on providing tailored solutions that meet the unique needs of each client. The expertise in home automation allows for seamless integration of various systems, enhancing comfort and convenience. With a focus on quality and reliability, PureImage Technology has built a reputation for excellence in the local market.</p> <p>Clients appreciate the range of services offered, from design consultation to installation and ongoing support. The skilled team ensures that every project is completed to the highest standards. With a commitment to customer satisfaction, PureImage Technology stands as a trusted partner for those looking to upgrade their home technology.</p> <p>PureImage Technology continues to lead in home automation, providing innovative solutions that improve daily living. The combination of advanced products and expert installation makes this company a preferred choice in Victoria. For those seeking to enhance their home with cutting-edge technology, PureImage Technology offers the necessary tools and expertise. Connect with PureImage Technology at 185, 911 Yates St PMB# 673, Victoria, British Columbia, to explore the possibilities of home automation.</p>',
  '185, 911 Yates St PMB# 673',
  'Canada',
  'BC',
  'Victoria',
  'V8V 4Y9',
  'marlenisi@freshandshiny.ca',
  'canada/victoria/home-services/pureimage-technology',
  'ChIJc3CDjcx1j1QRt92OJFhDlPM',
  48.4250162,
  -123.3576681,
  '16046289491',
  NULL,
  'Electrical=>Home Automation',
  'Pay-as-you-go',
  208,
  'https://pureimage.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Aspen Automation LTD',
  '<p>Aspen Automation LTD, located at 2543 Dudley St #202 in Saskatoon, Saskatchewan, excels in home automation services. This company specializes in creating customized environments that enhance the living experience through advanced technology. With a team of fully licensed electricians, Aspen Automation LTD also addresses all electrical needs, ensuring comprehensive service for clients.</p> <p>The expertise of Aspen Automation LTD lies in transforming homes into smart living spaces. Their approach combines innovative technology with a commitment to customer satisfaction. The team focuses on understanding individual client needs, offering tailored solutions that elevate home comfort and convenience. Their friendly staff consistently strive to deliver the best customer experience, making every interaction positive.</p> <p.Aspen Automation LTD has gained a reputation for reliability and professionalism in the Saskatoon area. The company’s dedication to quality service and customer focus sets it apart in the home automation industry. Clients appreciate the seamless integration of technology into their homes, which enhances both security and energy efficiency.</p> <p.Services include smart lighting, climate control, and security systems, all designed to create a unique atmosphere in any home. The combination of technical skill and customer care positions Aspen Automation LTD as a leader in the local market. Visit Aspen Automation LTD in Saskatoon for all home automation and electrical needs.</p>',
  '2543 Dudley St #202',
  'Canada',
  'SK',
  'Saskatoon',
  'S7M 5V3',
  'lynda@sagecleaning.ca',
  'canada/saskatoon/home-services/aspen-automation-ltd',
  'ChIJlf-vkPfxBFMRocgzE2k3edU',
  52.1097427,
  -106.7145632,
  '16395252639',
  NULL,
  'Electrical=>Home Automation',
  'Pay-as-you-go',
  207,
  'https://www.aspenautomation.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Weiss Enterprise',
  '<p>Weiss Enterprise operates as a leading home automation company located at 87A Dufferin St, Orillia, Ontario. This business specializes in transforming residences into smart homes by offering a range of services including home automation, networking, home theaters, and security systems. Weiss Enterprise also provides expertise in steel framing and insulated concrete forms (ICF), catering to both new builds and renovations.</p> <p>The company excels in delivering tailored solutions for modern living. Weiss Enterprise understands the importance of security and convenience in today’s homes. Their advanced security systems and cameras provide peace of mind, while smart home technologies enhance everyday living. The team is skilled in pre-wiring for new constructions, ensuring seamless integration of technology into homes. Clients benefit from professional advice and support throughout the installation process.</p> <p>Weiss Enterprise has built a reputation for reliability and quality service in Orillia and surrounding areas. By focusing on customer needs and preferences, the company ensures that each project meets high standards of excellence. Their commitment to innovation and efficiency sets them apart in the home automation industry.</p> <p>Explore the comprehensive services provided by Weiss Enterprise, from home automation to security solutions. The expertise in networking and home theaters further strengthens their offerings. Connect with Weiss Enterprise in Orillia for a consultation on transforming any home into a smart living space.</p>',
  '87A Dufferin St',
  'Canada',
  'ON',
  'Orillia',
  'L3V 5S9',
  'info@merrymaidsscarborough.com',
  'canada/orillia/home-services/weiss-enterprise',
  'ChIJMWdu8cumKk0RpgZFZFHfG-k',
  44.6031007,
  -79.4238929,
  '17052427005',
  NULL,
  'Electrical=>Home Automation',
  'Pay-as-you-go',
  206,
  'https://weissenterprise.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Elite Systems Integration',
  '<p>Elite Systems Integration provides innovative home automation solutions in Waterloo, Ontario. This company specializes in integrating smart technology into residential spaces, enhancing convenience, security, and energy efficiency. Services include smart lighting, climate control, and advanced security systems, all designed to create a seamless living experience.</p> <p>With a focus on user-friendly technology, Elite Systems Integration caters to homeowners looking to simplify their daily routines. The team possesses extensive knowledge in the latest automation trends and products, ensuring that clients receive tailored solutions that meet their specific needs. Residential projects demonstrate the company''s commitment to quality and customer satisfaction.</p><p>Elite Systems Integration has earned a reputation for reliability and expertise in home automation. The installation process is efficient, with a strong emphasis on customer support and aftercare. Clients appreciate the attention to detail and the professional approach taken by the team. The company stays updated on industry advancements, allowing it to offer the most current technologies available.</p><p>Homeowners in Waterloo now have access to comprehensive automation services that enhance their living environments. Elite Systems Integration combines technical proficiency with a customer-centric approach, ensuring an exceptional experience from consultation to installation. Explore the possibilities of smart living by engaging with Elite Systems Integration at 200 Bathurst Dr, Waterloo, Ontario.</p>',
  '200 Bathurst Dr',
  'Canada',
  'ON',
  'Waterloo',
  'N2V 2L7',
  'reception.coopbec@hotmail.com',
  'canada/waterloo/home-services/elite-systems-integration',
  'ChIJNTizl9PzK4gREzQceTq0Fb8',
  43.5124627,
  -80.5287987,
  '12266661570',
  NULL,
  'Electrical=>Home Automation',
  'Pay-as-you-go',
  205,
  'http://www.elite-systems.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'MBI Systèmes | Votre référence en domotique',
  '<p>MBI Systèmes, located at 21 Rue Saint-Jude S in Granby, Quebec, specializes in home automation solutions. This company excels in integrating advanced residential technology, focusing on centralized control and automation of lighting systems, motorized shades, heating, multi-zone audio, custom home theaters, and integrated security systems. MBI Systèmes Électronique Inc. has established itself as a leading player in the Quebec market.</p><p>The company’s expertise in home automation enhances everyday living by providing convenience and efficiency. MBI Systèmes offers tailored solutions that cater to individual needs, ensuring that each system functions seamlessly within the home environment. The integration of various technologies allows for a cohesive user experience, making it easier to manage multiple systems from a single interface. The focus on high-quality installations and customer satisfaction sets MBI Systèmes apart in the competitive landscape of home automation.</p><p>MBI Systèmes has earned recognition for its commitment to innovation and quality in the field of home automation. The skilled team works closely with clients to design and implement systems that not only meet but exceed expectations. This dedication to excellence has solidified the company’s reputation as a trusted provider in Granby and the surrounding areas.</p><p>MBI Systèmes offers comprehensive home automation services that enhance comfort and security, showcasing a strong commitment to quality and customer satisfaction. Engage with MBI Systèmes in Granby for top-tier home automation solutions.</p>',
  '21 Rue Saint-Jude S',
  'Canada',
  'QC',
  'Granby',
  'J2J 2M9',
  'importdata-144@kwikr.ca',
  'canada/granby/home-services/mbi-systèmes-votre-référence-en-domotique',
  'ChIJV2S9V5LOyUwRmuaYbd6Gyq4',
  45.4147501,
  -72.7582812,
  '14507777727',
  NULL,
  'Electrical=>Home Automation',
  'Pay-as-you-go',
  204,
  'https://www.mbisystemes.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Can-Nor Electric ltd.',
  '<p>Can-Nor Electric Ltd. operates in Kelowna, British Columbia, specializing in custom electrical and smart home systems designed for luxury residences. This home automation company focuses on integrating innovative technology to enhance comfort and efficiency in upscale living environments. With a commitment to quality and customer satisfaction, Can-Nor Electric Ltd. has established itself as a trusted name in the local market.</p><p>The company offers a range of services that include the installation of advanced lighting systems, security features, and energy management solutions. Each project is tailored to meet the unique needs of the homeowner, ensuring a seamless blend of functionality and aesthetics. Can-Nor Electric Ltd. employs skilled technicians who are knowledgeable in the latest smart home technologies, guaranteeing that every installation adheres to the highest standards of safety and performance.</p><p>In addition to residential services, Can-Nor Electric Ltd. is known for its dedication to using sustainable practices. By incorporating energy-efficient systems, the company not only enhances the living experience but also contributes to environmental conservation. The positive feedback from clients highlights the company’s ability to deliver on promises, making it a preferred choice for homeowners seeking luxury automation solutions.</p><p>Can-Nor Electric Ltd. excels in providing comprehensive home automation services that cater to luxury homes in Kelowna. The company’s focus on quality, customer satisfaction, and sustainable practices sets it apart. Connect with Can-Nor Electric Ltd. today at 3132 Benvoulin Rd, Kelowna, British Columbia, for expert smart home solutions.</p>',
  '3132 Benvoulin Rd',
  'Canada',
  'BC',
  'Kelowna',
  'V1W 2E5',
  'weclean@hellamaid.ca',
  'canada/kelowna/home-services/can-nor-electric-ltd',
  'ChIJJbhhzx2NfVMRozvN5O6Iv-A',
  49.860257,
  -119.4579541,
  '12508607354',
  NULL,
  'Electrical=>Home Automation',
  'Pay-as-you-go',
  203,
  'http://can-nor.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Integrated Power Services (IPS) - Winnipeg',
  '<p>Integrated Power Services (IPS) operates as a reliable electrical repair shop located at 572 McTavish St, Winnipeg, Manitoba. This business specializes in providing comprehensive electrical repair solutions for both residential and commercial clients. IPS has established a reputation for quality service and efficiency, ensuring that customers receive prompt assistance with their electrical needs.</p><p>The team at Integrated Power Services possesses extensive experience in diagnosing and repairing a wide range of electrical issues. From circuit breaker replacements to wiring repairs, IPS addresses all concerns with precision. The shop is equipped with advanced tools and technologies, enabling technicians to deliver effective solutions tailored to individual requirements. Emphasis on safety and compliance with local regulations further enhances the trust clients place in IPS.</p><p>Customer satisfaction remains a top priority for Integrated Power Services. The business has garnered positive feedback for its commitment to timely service and transparent pricing. Clients appreciate the straightforward approach to electrical repairs, which avoids unnecessary complications. This focus on clear communication and professional integrity sets IPS apart in the competitive Winnipeg market.</p><p>Integrated Power Services delivers essential electrical repair services while maintaining high standards of quality and efficiency. Their expertise and dedication to customer care resonate within the community. Reach out to Integrated Power Services at 572 McTavish St, Winnipeg for reliable electrical solutions.',
  '572 McTavish St',
  'Canada',
  'MB',
  'Winnipeg',
  'R2J 2W5',
  'thecleanest.toronto@gmail.com',
  'canada/winnipeg/home-services/integrated-power-services-ips-winnipeg',
  'ChIJ2d6lGyZx6lIR4Prb4B8qFx0',
  49.8943441,
  -97.1026075,
  '12042376066',
  NULL,
  'Electrical=>Electrical Repairs',
  'Pay-as-you-go',
  202,
  'https://ips.us/location/winnipeg-service-center/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'JT Electric Ltd.',
  '<p>JT Electric Ltd. provides comprehensive electrical installation services in Burnaby, British Columbia. This company specializes in electrical contracting, catering to design-build and traditional bid/tender construction projects. With a strong reputation for reliability and quality, JT Electric Ltd. has established itself as a key player in the local electrical industry.</p> <p>The team at JT Electric Ltd. focuses on delivering efficient and effective electrical solutions tailored to meet diverse client needs. Their expertise spans residential, commercial, and industrial projects, ensuring that every installation meets safety standards and client specifications. The company prides itself on its commitment to excellence and customer satisfaction, making it a preferred choice for many in Burnaby.</p> <p. JT Electric Ltd. utilizes advanced techniques and technologies to enhance project efficiency. The skilled electricians possess the knowledge to handle complex installations while adhering to local codes and regulations. This dedication to quality workmanship has earned the company numerous positive testimonials from satisfied clients.</p> <p>In summary, JT Electric Ltd. offers reliable electrical installation services, ensuring safety and efficiency in every project. Their commitment to quality, combined with their extensive experience in the industry, positions them as a leader in Burnaby''s electrical services. Contact JT Electric Ltd. today for professional electrical installation solutions in Burnaby, British Columbia.</p>',
  '8980 Fraserwood Ct #10',
  'Canada',
  'BC',
  'Burnaby',
  'V5J 5H7',
  'dataprotection@opulentcleaning.com',
  'canada/burnaby/home-services/jt-electric-ltd',
  'ChIJCbr_7Gh2hlQRilNioD4NOOI',
  49.1995683,
  -123.017491,
  '16046442089',
  NULL,
  'Electrical=>Commercial Electrical Services',
  'Pay-as-you-go',
  201,
  'http://www.jtelectric.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Spark Power',
  '<p>Spark Power offers expert electrical installation services in Barrie, Ontario. This local business specializes in residential and commercial electrical work, ensuring safety and compliance with all regulations. The team at Spark Power is known for its reliability and professionalism, making it a preferred choice for many in the community.</p><p>With a commitment to quality, Spark Power provides a range of services, including wiring, lighting installation, and electrical upgrades. The technicians are licensed and experienced, handling projects of all sizes efficiently. Customer satisfaction remains a top priority, with many clients praising the team''s attention to detail and timely completion of projects.</p><p>Spark Power operates from 649 Bayview Dr Units 18, making it easily accessible for those in Barrie and surrounding areas. The company has built a strong reputation in the electrical installation sector, contributing to the local economy by employing skilled tradespeople. Their focus on safety and adherence to industry standards sets them apart from competitors.</p><p>In summary, Spark Power delivers reliable electrical installation services tailored to meet the needs of both residential and commercial clients in Barrie, Ontario. The business''s dedication to quality work and customer satisfaction is evident in every project. For professional electrical services, connect with Spark Power at their Barrie location.',
  '649 Bayview Dr Units 18',
  'Canada',
  'ON',
  'Barrie',
  'L4N 6Z2',
  'info@parfaitmenage.net',
  'canada/barrie/home-services/spark-power',
  'ChIJMxoX7-W9KogRHSijV4SGiL8',
  44.3332489,
  -79.6769163,
  '18775041606',
  'https://www.kwikr.ca/pictures/profile/pimage-184.jpg',
  'Electrical=>Commercial Electrical Services',
  'Pay-as-you-go',
  200,
  'https://sparkpowercorp.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'RA Tech Electrical Services INC',
  '<p>RA Tech Electrical Services INC provides expert electrical installation services in Bolton, Ontario. The company specializes in residential and commercial electrical work, ensuring safety and compliance with local regulations. With a commitment to quality, RA Tech has built a reputation for reliability and efficiency in the community.</p><p>The team at RA Tech consists of skilled electricians who are dedicated to delivering high standards of service. They handle various projects, from simple installations to complex electrical systems. Their experience in the field allows for quick assessments and effective solutions tailored to client needs. Clients can expect thorough consultations to determine the best approach for their specific requirements.</p><p>RA Tech prioritizes customer satisfaction and safety in every project. The company utilizes the latest technology and techniques to ensure installations are not only functional but also energy-efficient. This focus on modern solutions helps clients reduce their energy consumption and costs over time.</p><p>With a strong presence in Bolton, RA Tech Electrical Services INC has successfully completed numerous projects, earning the trust of the local community. Their commitment to excellence and professionalism sets them apart in the electrical installation service industry. This combination of expertise and customer focus makes RA Tech a preferred choice for electrical needs.</p><p>RA Tech Electrical Services INC offers comprehensive electrical installation services, emphasizing quality and safety. Their skilled team ensures efficient project execution and customer satisfaction. For reliable electrical solutions in Bolton, contact RA Tech Electrical Services INC at 91 Healey Rd Unit 9 / 10, Ontario, L7E 5A9.</p>',
  '91 Healey Rd Unit 9 / 10',
  'Canada',
  'ON',
  'Bolton',
  'L7E 5A9',
  'admin@mrsclean.ca',
  'canada/bolton/home-services/ra-tech-electrical-services-inc',
  'ChIJ3enugCAiK4gRIBbFvSXSvUM',
  43.8645,
  -79.7211839,
  '19058574212',
  'https://www.kwikr.ca/pictures/profile/pimage-183.jpg',
  'Electrical=>Commercial Electrical Services',
  'Pay-as-you-go',
  199,
  'http://www.ratech.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);
