INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'VanDutch Exteriors',
  '<p>VanDutch Exteriors operates as a leading roofing contractor in Barrie, Ontario, specializing in high-quality roofing and exterior services. This business caters to the Muskoka region, offering a range of solutions designed to enhance the durability and aesthetic appeal of residential and commercial properties. With a commitment to excellence, VanDutch Exteriors has built a reputation for reliability and superior craftsmanship.</p><p>The team at VanDutch Exteriors consists of skilled professionals who prioritize customer satisfaction and deliver exceptional results. Each project receives meticulous attention to detail, ensuring that every roof installation or repair meets stringent quality standards. The company understands the unique challenges posed by the local climate and applies this knowledge to provide durable solutions that withstand the test of time.</p><p>VanDutch Exteriors is not just a roofing contractor; it is a trusted partner for homeowners and businesses seeking to improve their properties. The company’s dedication to using high-quality materials and innovative techniques sets it apart in the competitive market. Positive testimonials from satisfied customers highlight the professionalism and efficiency of the team, reinforcing the business''s standing in the community.</p><p>VanDutch Exteriors offers comprehensive roofing and exterior services tailored to meet diverse needs. The commitment to quality, customer care, and expertise ensures successful project outcomes. Visit Barrie to explore how VanDutch Exteriors can enhance property value and curb appeal. Reach out to VanDutch Exteriors for reliable roofing solutions in Barrie, Ontario.</p>',
  '649 Bayview Dr #16',
  'Canada',
  'ON',
  'Barrie',
  'L4N 6Z2',
  'info@couvreursboudreault.ca',
  'canada/barrie/home-services/vandutch-exteriors',
  'ChIJ55ZwpJDucm8RxtPIOFBgCW4',
  44.3332489,
  -79.6769163,
  '17053160907',
  NULL,
  'Roofing',
  'Growth Plan',
  873,
  'http://vandutchexteriors.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Couvreur Rolland Boudreault',
  '<p>Couvreur Rolland Boudreault operates as a roofing contractor in Gatineau, Quebec, offering commercial roofing services for three generations. This family-owned business has built a reputation for reliability and expertise in the roofing industry. The company focuses on delivering high-quality roofing solutions that meet the needs of local businesses.</p><p>The extensive experience of Couvreur Rolland Boudreault in commercial roofing ensures clients receive top-notch service. The team understands the unique challenges of roofing projects and provides tailored solutions that stand the test of time. From installation to maintenance, the company emphasizes quality craftsmanship and customer satisfaction. Each project reflects the dedication to excellence that has characterized this business for decades.</p><p>Couvreur Rolland Boudreault takes pride in its strong community ties in Gatineau. The company prioritizes using high-quality materials and innovative techniques to enhance the durability and performance of roofs. With a focus on safety and efficiency, the team works diligently to minimize disruptions during projects, ensuring a smooth experience for clients.</p><p>With a legacy of three generations in the roofing industry, Couvreur Rolland Boudreault continues to deliver exceptional commercial roofing services. The commitment to quality and community sets this contractor apart. Reach out to Couvreur Rolland Boudreault in Gatineau for reliable roofing solutions.</p>',
  '660 Rue Auguste Mondoux Apt. 4',
  'Canada',
  'QC',
  'Gatineau',
  'J9J 3K3',
  'info@couvreurslaplante.com',
  'canada/gatineau/home-services/couvreur-rolland-boudreault',
  'ChIJ-6yCzIwCzkwRiObwk7jCpzE',
  45.4431695,
  -75.8144427,
  '18197770654',
  'https://www.kwikr.ca/pictures/profile/pimage-871.jpg',
  'Roofing',
  'Growth Plan',
  872,
  'http://www.crb.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Couvreurs Laplante & Fils Inc',
  '<p>Couvreurs Laplante & Fils Inc offers expert roofing contractor services in Saint-Christophe-d''Arthabaska, Quebec. This local business specializes in residential and commercial roofing solutions, ensuring durability and quality. With a commitment to customer satisfaction, the company has built a strong reputation in the community.</p> <p>The team at Couvreurs Laplante & Fils Inc possesses extensive experience in various roofing materials and techniques. From asphalt shingles to metal roofing, they provide tailored solutions to meet specific needs. The company''s dedication to using high-quality materials ensures that roofs withstand harsh weather conditions, which is crucial in Quebec''s climate. Additionally, Couvreurs Laplante & Fils Inc emphasizes safety and compliance with local regulations, making them a reliable choice for roofing projects.</p> <p.Couvreurs Laplante & Fils Inc has successfully completed numerous projects, showcasing their expertise and reliability. Their focus on detail and craftsmanship has earned them positive feedback from clients. The company also offers free estimates, allowing potential customers to understand project costs upfront. This transparency builds trust and fosters long-term relationships with clients.</p> <p>In summary, Couvreurs Laplante & Fils Inc provides comprehensive roofing solutions, prioritizing quality and customer satisfaction in Saint-Christophe-d''Arthabaska. Their experienced team, commitment to safety, and positive community feedback highlight their strengths in the industry. Contact Couvreurs Laplante & Fils Inc at 14 Rue du Commerce for top-notch roofing services in Quebec.</p>',
  '14 Rue du Commerce',
  'Canada',
  'QC',
  'Saint-Christophe-d''Arthabaska',
  'G6R 0E8',
  'estelle.caron@publi-7.com',
  'canada/saint-christophe-d-arthabaska/home-services/couvreurs-laplante-fils-inc',
  'ChIJvb7EPTUCuEwRvsWdvq0fkUg',
  46.0259048,
  -71.9341771,
  '18193579853',
  'https://www.kwikr.ca/pictures/profile/pimage-870.jpg',
  'Roofing',
  'Growth Plan',
  871,
  'http://couvreurslaplante.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Toiture LM - Remplacement de toit plat',
  '<p>Toiture LM specializes in flat roof replacement and has been serving the Mirabel area of Quebec for over 20 years. This roofing contractor offers a range of services, ensuring quality and reliability in every project. With a commitment to excellence, Toiture LM has built a strong reputation in the local community.</p> <p>The company operates from 16500 Rue de la Tourmaline and boasts extensive experience in the roofing industry. Toiture LM understands the unique challenges posed by flat roofs and provides tailored solutions to meet the needs of both residential and commercial clients. Each project is approached with a focus on durability and customer satisfaction.</p> <p>Clients appreciate the company''s dedication to using high-quality materials and employing skilled professionals. The team at Toiture LM ensures that every flat roof replacement is completed efficiently and effectively, minimizing disruption to daily activities. The commitment to safety and adherence to industry standards further enhances the trust clients place in their services.</p> <p>Toiture LM continues to thrive in the competitive roofing market, backed by years of experience and a proven track record. The company remains a reliable choice for anyone in need of flat roof replacement in Mirabel, Quebec. Contact Toiture LM for expert roofing solutions that stand the test of time and provide peace of mind.</p>',
  '16500 Rue de la Tourmaline',
  'Canada',
  'QC',
  'Mirabel',
  'J7N 0R5',
  'toituredelacapitale@gmail.com',
  'canada/mirabel/home-services/toiture-lm-remplacement-de-toit-plat',
  'ChIJa7ZjnZ7TyEwRZf0zCIlIa0w',
  45.743157,
  -74.0596766,
  '14506940316',
  'https://www.kwikr.ca/pictures/profile/pimage-869.jpg',
  'Roofing',
  'Growth Plan',
  870,
  'https://www.toiturelm.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Toiture de la Capitale',
  '<p>Toiture de la Capitale serves the Sainte-Brigitte-de-Laval area in Quebec as a leading roofing contractor. This business specializes in roof renovation, recognized for competitive pricing and expert craftsmanship. Certified roofers receive training directly from manufacturers, ensuring high-quality installations. The company addresses various roofing needs, including repairs, renovations, and complete roof replacements.</p><p>Offering a wide range of services, Toiture de la Capitale excels in installing different types of roofing materials, ventilation systems, soffits, and fascias. The team is also skilled in converting traditional roofs into green roofs, promoting sustainability in the community. Each project, whether residential or commercial, receives personalized attention, focusing on customer needs and budget considerations.</p><p>Toiture de la Capitale has built a strong reputation in the local market, thanks to its commitment to quality and customer satisfaction. The company prioritizes effective communication and transparency throughout the project lifecycle. Clients can expect thorough assessments and tailored solutions that enhance the longevity and functionality of their roofs.</p><p>With a focus on quality workmanship and customer care, Toiture de la Capitale stands out in the roofing industry. The combination of certified expertise and competitive pricing makes this business a reliable choice for roofing needs in Sainte-Brigitte-de-Laval. Reach out to Toiture de la Capitale for exceptional roofing services in Quebec.</p>',
  '59 Rue Richelieu',
  'Canada',
  'QC',
  'Sainte-Brigitte-de-Laval',
  'G0A 3K0',
  'admin@uplandgroup.ca',
  'canada/sainte-brigitte-de-laval/home-services/toiture-de-la-capitale',
  'ChIJr4ChKruxuEwRYHqYt1Rms00',
  47.0076954,
  -71.1962438,
  '14188019948',
  'https://www.kwikr.ca/pictures/profile/pimage-868.jpg',
  'Roofing',
  'Growth Plan',
  869,
  'https://www.toituredelacapitale.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Upland Contracting Ltd',
  '<p>Upland Contracting Ltd, a reputable general contractor located in Campbell River, British Columbia, has been a cornerstone of the local construction industry since 1969. This family-owned business excels in a variety of services, including aggregate supply, civil contracting, and waste management. Upland''s commitment to quality and community has fostered long-lasting relationships with clients and partners.</p><p>With a workforce of over 100 full-time employees, Upland Contracting Ltd showcases its dedication to local employment. At peak times, the team can grow to nearly 200, reflecting the company''s ability to adapt to project demands. Upland specializes in essential services such as contaminated soils remediation, trucking, drilling, and blasting. The company also offers marine aggregate supply and has advanced facilities for custom crushing and screening.</p><p>Upland''s expertise extends to First Nations and joint ventures, ensuring that projects are managed with cultural sensitivity and respect. The company''s in-house capabilities allow for streamlined operations, enhancing efficiency and project outcomes. With a strong focus on safety and sustainability, Upland Contracting Ltd continues to lead in the construction sector.</p><p>Upland Contracting Ltd provides a comprehensive range of construction and contracting services, emphasizing quality and community engagement. The company''s long-standing history and skilled workforce contribute to its reputation for excellence. Connect with Upland Contracting Ltd in Campbell River for reliable general contracting services.</p>',
  '7295 Gold River Hwy',
  'Canada',
  'BC',
  'Campbell River',
  'V9H 1P1',
  'location@lachance.qc.ca',
  'canada/campbell-river/home-services/upland-contracting-ltd',
  'ChIJf4ZZZPOlYlQRFN8JO37CUk4',
  50.0050471,
  -125.362173,
  '12502861148',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  868,
  'https://uplandcontracting.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Enterprises Lachance Inc',
  '<p>Enterprises Lachance Inc operates as a reputable general contractor in Sherbrooke, Quebec, offering a diverse range of residential land options and house plans. This business prioritizes exceptional quality and outstanding after-sales service, catering to various housing needs in the local area. The company specializes in turnkey new home projects and provides a wide selection of apartments and rental housing in high-quality real estate developments.</p><p>With a commitment to excellence, Enterprises Lachance Inc delivers tailored solutions for clients seeking new homes or rental properties. The company’s extensive portfolio includes meticulously designed house plans that meet the demands of modern living. Each project reflects a dedication to quality craftsmanship and customer satisfaction. The focus on providing a seamless experience from initial consultation to project completion sets this business apart in the competitive construction industry.</p><p>Enterprises Lachance Inc has established itself as a reliable choice for those looking to invest in their future homes or rental properties. The company’s dedication to quality and service ensures that clients receive not only beautiful homes but also peace of mind throughout the building process. The local expertise in Sherbrooke enhances their ability to meet community needs effectively.</p><p>Enterprises Lachance Inc excels in delivering high-quality housing solutions, showcasing a commitment to customer satisfaction and a wide array of options. Connect with Enterprises Lachance Inc at 663 Rue de Charlemagne, Sherbrooke, Quebec, for exceptional general contracting services.</p>',
  '663 Rue de Charlemagne',
  'Canada',
  'QC',
  'Sherbrooke',
  'J1N 0S9',
  'info@cc-canadiancontractors.com',
  'canada/sherbrooke/home-services/enterprises-lachance-inc',
  'ChIJYyupTDK1t0wR5qfJxavB2EM',
  45.3692937,
  -71.9679389,
  '18198201545',
  'https://www.kwikr.ca/pictures/profile/pimage-866.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  867,
  'https://lachance.qc.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Canadian Contractors',
  '<p>Canadian Contractors operates as a general contractor in Surrey, British Columbia, offering a comprehensive range of services. The company specializes in managing, planning, designing, building, renovating, and maintaining both residential and commercial spaces. With a focus on aligning projects with client goals, Canadian Contractors has established a reputation for delivering reliable results.</p><p>In the competitive construction industry, Canadian Contractors has demonstrated expertise in various aspects of project management. The team consists of skilled professionals who understand the unique needs of each client. They prioritize clear communication and collaboration throughout the construction process, ensuring that every project is executed efficiently. The company’s commitment to quality workmanship and attention to detail has led to numerous successful projects across Surrey.</p><p>Canadian Contractors emphasizes the importance of tailored solutions. Every project begins with a thorough assessment of client requirements, followed by a strategic planning phase. This approach allows the team to create customized designs that reflect the client’s vision. Whether it’s a residential renovation or a commercial build, the company’s experience ensures that projects are completed on time and within budget.</p><p>With a strong focus on customer satisfaction, Canadian Contractors continues to build lasting relationships within the community. Their dedication to excellence and reliability makes them a preferred choice for construction needs in Surrey. Connect with Canadian Contractors at 10251 140 St, Surrey, British Columbia, to explore their services today.</p>',
  '10251 140 St',
  'Canada',
  'BC',
  'Surrey',
  'V3T 4N1',
  'terri.pcs@shaw.ca',
  'canada/surrey/home-services/canadian-contractors',
  'ChIJ4Yfqv73XhVQRAyu_-Zsa1c0',
  49.1886896,
  -122.8344779,
  '16047606434',
  'https://www.kwikr.ca/pictures/profile/pimage-865.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  866,
  'https://cc-canadiancontractors.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Professional Contracting Services Ltd',
  '<p>Professional Contracting Services Ltd operates as a general contractor in Calgary, Alberta, specializing in sealant application. With 40 years of industry experience, this company provides high-quality work and reliable service to contractors, building management companies, architects, building science engineers, and building owners across the region. The expertise in sealants ensures that projects are completed with precision and professionalism.</p><p>Professional Contracting Services Ltd has established a reputation for excellence in the construction sector. The team possesses extensive product knowledge, which enhances the quality of service offered. Clients appreciate the timely responses and dependable work ethic that characterize every project. This commitment to quality has led to long-lasting relationships with numerous stakeholders in the construction industry.</p><p>Located at 4415 58 Ave SE Unit C, Calgary, Alberta, the company remains dedicated to serving the local community. The focus on delivering top-notch results makes Professional Contracting Services Ltd a preferred choice for various construction needs. The commitment to understanding client requirements and providing tailored solutions sets this business apart in a competitive market.</p><p>Professional Contracting Services Ltd offers exceptional sealant application services, backed by decades of experience and a strong commitment to quality. The business continues to thrive by maintaining high standards and fostering positive relationships in the industry. Connect with Professional Contracting Services Ltd in Calgary for expert contracting services today.</p>',
  '4415 58 Ave SE Unit C',
  'Canada',
  'AB',
  'Calgary',
  'T2C 1Y3',
  'samantha@buildpress.com',
  'canada/calgary/home-services/professional-contracting-services-ltd',
  'ChIJfWSCTPZrcVMRxrMMpR5A06Q',
  51.0005293,
  -113.9719923,
  '14032864061',
  'https://www.kwikr.ca/pictures/profile/pimage-864.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  865,
  'https://professionalcontracting.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Van Maren Construction Group Ltd.',
  '<p>Van Maren Construction Group Ltd. operates as a reputable general contractor based in Chilliwack, British Columbia. The company specializes in residential and commercial construction projects, offering a range of services including renovations, new builds, and custom home designs. With a commitment to quality and customer satisfaction, Van Maren Construction has established a strong presence in the local construction industry.</p><p>The team at Van Maren Construction Group Ltd. combines extensive industry experience with a dedication to craftsmanship. Each project receives meticulous attention to detail, ensuring that the final results meet the highest standards. The company prides itself on its ability to manage projects efficiently, delivering results on time and within budget. This reliability has garnered the trust of many clients in Chilliwack and surrounding areas.</p><p>In addition to its construction services, Van Maren Construction Group Ltd. emphasizes transparency and communication throughout the entire process. Clients appreciate the straightforward approach to project management and the willingness to address any concerns promptly. This focus on client relations contributes to the company''s positive reputation in the community.</p><p>Van Maren Construction Group Ltd. provides comprehensive general contracting services that prioritize quality and client satisfaction. With a proven track record in Chilliwack, this company continues to deliver exceptional results in both residential and commercial projects. Connect with Van Maren Construction Group Ltd. at 45793 Luckakuck Way, Chilliwack, British Columbia, for expert construction services.</p>',
  '45793 Luckakuck Way',
  'Canada',
  'BC',
  'Chilliwack',
  'V2R 5S3',
  'position@laurin.ca',
  'canada/chilliwack/home-services/van-maren-construction-group-ltd',
  'ChIJZYmdTqNAhFQReuS-VZbqTp0',
  49.1442991,
  -121.9594518,
  '16048470700',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  864,
  'http://www.vanmarengroup.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Laurin Group',
  '<p>Laurin Group provides comprehensive general contracting services in Ottawa, Ontario. This company specializes in both residential and commercial projects, ensuring high-quality workmanship and customer satisfaction. The experienced team at Laurin Group tackles renovations, new constructions, and various project management tasks, making them a reliable partner for any construction needs.</p> <p>Established with a commitment to excellence, Laurin Group has built a solid reputation in the local community. The company emphasizes transparency and communication throughout every phase of a project, allowing clients to stay informed and engaged. With a focus on timely project completion, Laurin Group ensures that deadlines are met without compromising quality.</p> <p>The skilled professionals at Laurin Group utilize modern techniques and high-quality materials, contributing to durable and aesthetically pleasing results. Their portfolio showcases a range of successful projects, from residential remodels to large-scale commercial builds. Clients appreciate the attention to detail and personalized service that Laurin Group provides, making them a preferred choice in the Ottawa area.</p> <p>With a strong commitment to client satisfaction and a proven track record, Laurin Group stands ready to handle diverse construction projects. Their expertise and dedication make them a valuable asset for anyone looking to undertake renovations or new builds. Connect with Laurin Group at 43 Auriga Dr, Ottawa, Ontario, for reliable general contracting services.</p>',
  '43 Auriga Dr',
  'Canada',
  'ON',
  'Ottawa',
  'K2E 7Y8',
  'victor.giesbrecht@century21.ca',
  'canada/ottawa/home-services/laurin-group',
  'ChIJocFwIMMHzkwRLkB7OAouskI',
  45.329931,
  -75.7056337,
  '18005652874',
  'https://www.kwikr.ca/pictures/profile/pimage-862.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  863,
  'http://www.laurin.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Trikor Builders',
  '<p>Trikor Builders operates as a reputable general contractor in Winnipeg, Manitoba, providing a range of construction services to meet diverse client needs. This company specializes in residential and commercial projects, ensuring quality workmanship and timely delivery. With a commitment to customer satisfaction, Trikor Builders has built a solid reputation in the local community.</p><p>The team at Trikor Builders consists of skilled professionals who bring expertise and attention to detail to every project. From renovations and new builds to project management, the company handles various aspects of construction efficiently. Clients appreciate the transparent communication and collaborative approach taken by the team, which fosters trust and reliability.</p><p>Trikor Builders has successfully completed numerous projects throughout Winnipeg, showcasing their ability to adapt to different requirements and challenges. The company''s dedication to using high-quality materials and innovative techniques ensures that all work meets industry standards. This focus on excellence has led to repeat business and referrals from satisfied customers.</p><p>With a strong emphasis on safety and compliance, Trikor Builders prioritizes a secure working environment for its team and clients. The company''s established relationships with local suppliers contribute to the timely procurement of materials, further enhancing project efficiency. Trikor Builders remains committed to delivering exceptional results while maintaining a strong presence in the Winnipeg area.</p><p>Trikor Builders offers comprehensive general contracting services, emphasizing quality, reliability, and customer satisfaction. Their proven track record and professional approach make them a preferred choice for construction needs in Winnipeg. Contact Trikor Builders at 2141-B Henderson Hwy in Winnipeg, Manitoba, for expert services.',
  '2141-B Henderson Hwy',
  'Canada',
  'MB',
  'Winnipeg',
  'R2G 1P8',
  'candidatures@grnordique.ca',
  'canada/winnipeg/home-services/trikor-builders',
  'ChIJnbYE4UXYwVIRn2ckb-VS4RQ',
  49.9601971,
  -97.0674401,
  '12046633818',
  'https://www.kwikr.ca/pictures/profile/pimage-861.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  862,
  'http://www.trikor.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Equipements Nordiques',
  '<p>Equipements Nordiques serves as a prominent general contractor in Sept-Iles, Quebec, with a legacy dating back to 1976. This family-owned business has established itself within the Duplessis and Caniapiscau regions, offering a variety of services that include excavation, civil engineering, specialized mining work, hazardous materials transport, and industrial snow removal. The company also provides heavy machinery rentals and container services, showcasing a comprehensive approach to local contracting needs.</p> <p>The expertise of Equipements Nordiques spans over four decades, demonstrating a strong commitment to quality and reliability. The company’s proficiency in excavation and civil engineering projects ensures that clients receive top-notch service tailored to their specific requirements. By expanding into specialized mining services and hazardous materials transport, the company addresses the diverse needs of the local industry effectively.</p> <p>Equipements Nordiques stands out for its dedication to safety and efficiency, ensuring that all operations meet stringent regulatory standards. The company’s investment in modern equipment and skilled personnel enhances its ability to manage projects of various scales. Its reputation for excellence is evident in the successful completion of numerous contracts throughout the region.</p> <p>Equipements Nordiques offers a wide range of contracting services, with a strong focus on excavation, civil engineering, and specialized mining. The company’s commitment to quality and safety sets it apart in the industry. Connect with Equipements Nordiques at 440 Rue Holliday, Sept-Iles, Quebec, for reliable contracting solutions.</p>',
  '440 Rue Holliday',
  'Canada',
  'QC',
  'Sept-Iles',
  'G4R 4X6',
  'careers@tectonici.com',
  'canada/sept-iles/home-services/equipements-nordiques',
  'ChIJGURBRMvfkUwRCxBi9JGAtIM',
  50.2304158,
  -66.3361281,
  '14189621234',
  'https://www.kwikr.ca/pictures/profile/pimage-860.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  861,
  'https://www.equipementsnordiques.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Tectonic Infrastructure Inc',
  '<p>Tectonic Infrastructure Inc operates as a general contractor based in Maple, Ontario. This company specializes in a wide range of construction services, including residential and commercial projects. With a commitment to quality and efficiency, Tectonic Infrastructure Inc has earned a reputation for delivering projects on time and within budget. The business focuses on both new constructions and renovations, ensuring that client needs are met with precision.</p><p>The team at Tectonic Infrastructure Inc possesses extensive experience in the construction industry. Skilled professionals manage each project, from planning to execution. The company utilizes modern techniques and equipment, enhancing productivity and ensuring safety on job sites. Tectonic Infrastructure Inc prides itself on maintaining high standards and adhering to industry regulations, which fosters trust among clients.</p><p>Community engagement is a core value of Tectonic Infrastructure Inc. The company actively participates in local initiatives, demonstrating a commitment to Maple and its residents. This involvement not only strengthens community ties but also showcases the company''s dedication to supporting local growth and development.</p><p>Tectonic Infrastructure Inc provides reliable general contracting services, marked by professionalism and expertise. The focus on client satisfaction and community involvement sets this company apart. For quality construction solutions in Maple, Ontario, reach out to Tectonic Infrastructure Inc today. </p>',
  '120 Rodinea Rd',
  'Canada',
  'ON',
  'Maple',
  'L6A 1R5',
  'hr@j-concivil.com',
  'canada/maple/home-services/tectonic-infrastructure-inc',
  'ChIJYXPkfgQpK4gRAU_HB0ihyws',
  43.8718137,
  -79.5098991,
  '14166376073',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  860,
  'http://www.tectonicinfrastructure.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'J-CON Civil',
  '<p>J-CON Civil operates as a general contractor in Sunnyside, Manitoba, providing a range of construction and renovation services. With a focus on quality and efficiency, this local business has built a reputation for delivering projects on time and within budget. J-CON Civil specializes in residential and commercial construction, ensuring all clients receive tailored solutions that meet their specific needs.</p><p>Experience and professionalism define J-CON Civil''s approach to each project. The team consists of skilled professionals who understand the intricacies of construction work. They utilize the latest techniques and technologies to enhance productivity and ensure safety on every job site. This commitment to excellence has led to numerous successful projects throughout the region.</p><p>J-CON Civil emphasizes customer satisfaction, prioritizing clear communication and transparency throughout the construction process. Clients appreciate the attention to detail and the ability to adapt to changing project requirements. This flexibility has proven beneficial in managing timelines and budgets effectively.</p><p>Whether undertaking new builds or renovations, J-CON Civil remains a reliable choice for construction services in Sunnyside. The company’s dedication to quality craftsmanship and client-focused solutions sets it apart in the competitive construction industry. For those seeking dependable general contracting services, connect with J-CON Civil at 1127 Redonda St, Sunnyside, Manitoba.',
  '1127 Redonda St',
  'Canada',
  'MB',
  'Sunnyside',
  'R5R 0E7',
  'jeremy.dumont01@hotmail.com',
  'canada/sunnyside/home-services/j-con-civil',
  'ChIJoWHQhhlt6lIR3k1x4tO25t0',
  49.9262387,
  -96.9805937,
  '12043445666',
  'https://www.kwikr.ca/pictures/profile/pimage-858.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  859,
  'http://www.j-concivil.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Construction J et P Dumont inc.',
  '<p>Construction J et P Dumont inc. provides exceptional general contractor services in Saint-Jean-de-la-Lande, Quebec. This local business specializes in residential and commercial construction projects, focusing on quality workmanship and customer satisfaction. With years of experience, the company has built a solid reputation in the community for delivering reliable and efficient construction solutions.</p> <p>The team at Construction J et P Dumont inc. offers a wide range of services, including renovations, new builds, and project management. Their commitment to using high-quality materials ensures durability and longevity in every project undertaken. The skilled professionals understand the importance of timelines and work diligently to meet deadlines while maintaining high standards.</p> <p>Community engagement is a priority for this business. Construction J et P Dumont inc. actively participates in local events, fostering relationships with residents and other businesses. This involvement enhances their understanding of the unique needs of the community, allowing for tailored services that meet specific requirements.</p> <p>With a focus on transparency and open communication, clients can expect regular updates throughout the construction process. The dedication to customer service sets Construction J et P Dumont inc. apart in the competitive general contractor market. Their expertise and commitment to excellence make them a trusted choice for construction needs in Saint-Jean-de-la-Lande.</p> <p>Construction J et P Dumont inc. stands ready to assist with various construction projects, ensuring quality and satisfaction. Engage with this reliable general contractor in Saint-Jean-de-la-Lande for all construction needs. Visit Rte du Lac-Baker to learn more about their services.</p>',
  'Rte du Lac-Baker',
  'Canada',
  'QC',
  'Saint-Jean-de-la-Lande',
  'G0L 3N0',
  'info@mongrain.ca',
  'canada/saint-jean-de-la-lande/home-services/construction-j-et-p-dumont-inc',
  'ChIJkxhUeQW1vUwRUeFJAqUPT9s',
  47.425606,
  -68.678809,
  '14188535228',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  858,
  'http://www.constructionjetpdumont.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Mongrain Inc.',
  '<p>Mongrain Inc. operates as a leading general contractor in Mirabel, Quebec, providing a comprehensive range of services that cover building envelope protection from foundation to roof. This company specializes in new constructions and restorations, collaborating with developers, designers, owners, and managers from the initial phases of projects to deliver innovative and sustainable solutions.</p><p>The service offerings of Mongrain Inc. include insulation options such as polyurethane and wool, fireproofing with materials like cement, intumescent paint, and Fireboard Mongrain. Additionally, the company provides waterproofing, roofing, and structural protection services. This extensive portfolio highlights Mongrain''s commitment to quality and client satisfaction.</p><p>Mongrain Inc. emphasizes its ability to adapt to various project requirements, ensuring that every aspect of building protection is addressed. The team’s expertise in insulation techniques and fireproofing products positions them as a trusted partner in construction and renovation. Their proactive approach fosters collaboration, leading to successful project outcomes.</p><p.Mongrain Inc. continuously strives to exceed industry standards, showcasing a dedication to excellence in construction services. Their strong relationships with clients and stakeholders reflect their reputation for reliability and professionalism. Choose Mongrain Inc. for all general contracting needs in Mirabel, Quebec. Connect with Mongrain Inc. for expert assistance in building protection services today.</p>',
  '19867 Chem. de la Côte N',
  'Canada',
  'QC',
  'Mirabel',
  'J7J 2B4',
  'office@technicon-ind.com',
  'canada/mirabel/home-services/mongrain-inc',
  'ChIJYfiWfPwjyUwR_VfwIUvsAIA',
  45.642,
  -73.890662,
  '14506812881',
  'https://www.kwikr.ca/pictures/profile/pimage-856.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  857,
  'http://mongrain.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Technicon Industries',
  '<p>Technicon Industries provides comprehensive general contracting services in Terrace, British Columbia. This locally owned and operated business specializes in electrical, plumbing, HVAC, demolition, new build construction, as well as fire and water restoration. With a commitment to quality and customer satisfaction, Technicon Industries has established a solid reputation within the community.</p><p>The expertise of Technicon Industries encompasses a wide range of construction and restoration services. Skilled professionals handle every project, ensuring attention to detail and adherence to safety standards. Whether it is a residential renovation or a commercial build, Technicon Industries delivers reliable solutions tailored to client needs. The company’s experience in fire and water restoration positions it as a trusted partner for those facing unexpected challenges.</p><p>Technicon Industries emphasizes the importance of using high-quality materials and modern techniques. This approach not only enhances the durability of each project but also contributes to energy efficiency and sustainability. The team remains dedicated to staying updated with industry trends, ensuring clients receive the best possible service and results.</p><p>Offering a full spectrum of services, Technicon Industries excels in meeting the diverse needs of the Terrace community. The combination of local knowledge, skilled craftsmanship, and commitment to excellence sets this business apart. For reliable general contracting services, reach out to Technicon Industries at 2809 Kalum St, Terrace, British Columbia. </p>',
  '2809 Kalum St',
  'Canada',
  'BC',
  'Terrace',
  'V8G 2M4',
  'grant@ultimatecontracting.com',
  'canada/terrace/home-services/technicon-industries',
  'ChIJ2RuEMeyZdFQRb2i8KCrcv-U',
  54.5115291,
  -128.587482,
  '12506381111',
  'https://www.kwikr.ca/pictures/profile/pimage-855.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  856,
  'https://www.technicon-ind.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Ultimate Contracting Inc. & Duradek Installer Canmore',
  '<p>Ultimate Contracting Inc. & Duradek Installer serves Canmore, Alberta, as a reliable general contractor specializing in high-quality construction and renovation services. This local business focuses on delivering exceptional craftsmanship and customer satisfaction. With a commitment to excellence, it has earned a strong reputation in the community for its durable and efficient solutions.</p><p>The company offers a wide range of services, including residential and commercial renovations, deck installations, and custom builds. Ultimate Contracting Inc. utilizes top-grade materials and advanced techniques to ensure lasting results. The team consists of skilled professionals who prioritize attention to detail and adherence to timelines. Clients appreciate the transparent communication throughout the project, fostering trust and reliability.</p><p>Ultimate Contracting Inc. has completed numerous successful projects, showcasing its ability to handle various construction challenges. The business emphasizes sustainability by incorporating eco-friendly practices in its operations. This approach not only benefits the environment but also enhances the value of properties in Canmore.</p><p>With a strong focus on quality and customer service, Ultimate Contracting Inc. & Duradek Installer remains a preferred choice for general contracting needs in Canmore. The combination of experience, professionalism, and dedication to client satisfaction sets this business apart. For superior construction services in Canmore, reach out to Ultimate Contracting Inc. & Duradek Installer at 104 Boulder Crescent #2, Alberta, T1W 1L2.',
  '104 Boulder Crescent #2',
  'Canada',
  'AB',
  'Canmore',
  'T1W 1L2',
  'office@jbinc.org',
  'canada/canmore/home-services/ultimate-contracting-inc-duradek-installer-canmore',
  'ChIJezVks2LbcFMR6dvFRT-TkhU',
  51.0779259,
  -115.3237448,
  '14038121616',
  'https://www.kwikr.ca/pictures/profile/pimage-854.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  855,
  'http://www.ultimatecontracting.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Jillian Builders Inc.',
  '<p>Jillian Builders Inc. operates as a reputable general contractor in Edmonton, Alberta, specializing in residential and commercial construction projects. This business excels in delivering high-quality craftsmanship and reliable project management. With a commitment to customer satisfaction, Jillian Builders Inc. has built a strong reputation within the local community.</p> <p>The company offers a comprehensive range of services, including home renovations, new construction, and commercial build-outs. Skilled professionals ensure that each project meets industry standards and client expectations. Jillian Builders Inc. emphasizes the importance of using quality materials and innovative techniques, which enhances durability and aesthetics in every project. The team’s expertise in navigating local regulations and building codes further streamlines the construction process, making it efficient and hassle-free for clients.</p> <p>Jillian Builders Inc. has successfully completed numerous projects, showcasing versatility in both design and execution. The business has garnered positive feedback from clients, highlighting their attention to detail and commitment to timelines. This dedication to excellence has established a loyal customer base in Edmonton and surrounding areas.</p> <p>Jillian Builders Inc. provides essential services in general contracting, focusing on quality and client satisfaction. Their experience and local knowledge make them a preferred choice for construction needs. Reach out to Jillian Builders Inc. for reliable general contracting services in Edmonton, Alberta.',
  '5730 99 St NW',
  'Canada',
  'AB',
  'Edmonton',
  'T6E 3N9',
  'info@windleycontracting.com',
  'canada/edmonton/home-services/jillian-builders-inc',
  'ChIJm7IRD5sYoFMRlX_8b5oolRY',
  53.4935834,
  -113.486625,
  '17804444404',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  854,
  'http://www.jbinc.org/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Windley Contracting Ltd',
  '<p>Windley Contracting Ltd provides comprehensive general contracting services in Nanaimo, British Columbia. This company specializes in residential and commercial construction, offering expertise in project management, renovations, and custom builds. With a strong focus on quality and client satisfaction, Windley Contracting Ltd has earned a reputation for reliability and professionalism in the local construction industry.</p> <p>The skilled team at Windley Contracting Ltd brings years of experience to each project. They manage every aspect of construction, ensuring timelines are met and budgets are adhered to. This dedication to detail and efficiency has led to numerous successful projects across Nanaimo and surrounding areas. Clients appreciate the transparent communication and the commitment to delivering high-quality workmanship.</p> <p>Windley Contracting Ltd employs sustainable practices, contributing to environmentally friendly construction. The company utilizes local materials whenever possible, supporting the community and reducing environmental impact. Their approach not only enhances project quality but also fosters local economic growth.</p> <p>Windley Contracting Ltd stands as a reliable choice for general contracting needs in Nanaimo. The combination of experienced professionals, commitment to quality, and sustainable practices positions the company favorably within the industry. Contact Windley Contracting Ltd for expert general contracting services in Nanaimo, British Columbia. </p>',
  '3711 Shenton Rd',
  'Canada',
  'BC',
  'Nanaimo',
  'V9T 2H1',
  'nboudreau@edbrunet.com',
  'canada/nanaimo/home-services/windley-contracting-ltd',
  'ChIJ9Z5RvzKiiFQRuPUfQ2gq5JQ',
  49.2050232,
  -124.0116771,
  '12507583411',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  853,
  'http://www.windleycontracting.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Ed Brunet & Associates Canada Inc.',
  '<p>Ed Brunet & Associates Canada Inc. operates as a general contractor in Gatineau, Quebec, offering a wide range of construction services since 1901. This long-established company provides reliable solutions for various construction needs, ensuring quality and satisfaction for clients in the region. With a focus on residential and commercial projects, Ed Brunet & Associates Canada Inc. has built a reputation for excellence and dependability.</p> <p>The company specializes in new builds, renovations, and restorations, catering to diverse client requirements. Skilled professionals manage each project, ensuring adherence to timelines and budgets. The team prioritizes communication and transparency, fostering strong relationships with clients throughout the construction process. The commitment to high standards and craftsmanship sets this business apart in the competitive construction market.</p> <p>Ed Brunet & Associates Canada Inc. has achieved numerous milestones in its long history, reflecting its dedication to the construction industry. The company embraces modern techniques while respecting traditional values, creating a balanced approach to construction. This adaptability ensures the delivery of innovative solutions that meet the evolving needs of clients.</p> <p>With a strong foundation in the community, Ed Brunet & Associates Canada Inc. continues to serve Gatineau and surrounding areas with integrity and professionalism. The company’s extensive experience and commitment to quality make it a reliable choice for construction projects. Connect with Ed Brunet & Associates Canada Inc. at 4 Rue Dumas in Gatineau, Quebec, for exceptional construction services.</p>',
  '4 Rue Dumas',
  'Canada',
  'QC',
  'Gatineau',
  'J8Y 2M5',
  'info@maximproconstruction.com',
  'canada/gatineau/home-services/ed-brunet-associates-canada-inc',
  'ChIJBx6cI5sEzkwRJKm_4e2J5C0',
  45.4376628,
  -75.7300812,
  '18197773877',
  'https://www.kwikr.ca/pictures/profile/pimage-851.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  852,
  'http://www.edbrunet.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Maximpro Construction',
  '<p>Maximpro Construction operates as a reputable general contractor located in Brampton, Ontario. This company specializes in delivering high-quality construction services, including residential and commercial projects. With a commitment to excellence and customer satisfaction, Maximpro Construction has successfully completed numerous projects, showcasing their expertise in the construction industry.</p> <p>The team at Maximpro Construction brings a wealth of experience and knowledge to each project. They prioritize clear communication and effective project management to ensure that every client''s vision is realized. From renovations to new builds, the company handles all aspects of construction with precision and care. Their strong reputation in the Brampton area reflects their dedication to quality workmanship and reliability.</p> <p>Maximpro Construction employs skilled professionals who utilize the latest techniques and materials to achieve outstanding results. Their focus on safety and compliance ensures that all projects adhere to local regulations and standards. The company’s attention to detail and commitment to timelines have earned them a loyal client base in the community.</p> <p>Maximpro Construction offers a range of services that cater to various construction needs, highlighting their strengths in project management and customer relations. Their achievements in the industry underline their capabilities as a trusted general contractor. Engage with Maximpro Construction for reliable construction services in Brampton, Ontario.',
  '13 Edvac Dr Unit 7',
  'Canada',
  'ON',
  'Brampton',
  'L6S 5W6',
  'estimating@dawsonwallace.com',
  'canada/brampton/home-services/maximpro-construction',
  'ChIJOxjaJb49K4gRe0AKjphdIPg',
  43.7624348,
  -79.7046127,
  '16476338418',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  851,
  'https://www.maximproconstruction.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Dawson Wallace Construction Ltd.',
  '<p>Dawson Wallace Construction Ltd. operates as a trusted general contractor in Calgary, Alberta. This company specializes in residential and commercial construction projects, offering comprehensive services that include project management, renovations, and new builds. With a commitment to quality and customer satisfaction, Dawson Wallace Construction has earned a reputation for delivering projects on time and within budget.</p> <p>The team at Dawson Wallace Construction Ltd. possesses extensive experience in the construction industry. Their skilled professionals utilize the latest techniques and materials to ensure each project meets high standards. The company emphasizes collaboration with clients to understand their vision and execute it effectively. This approach fosters transparency and trust throughout the construction process.</p> <p>Dawson Wallace Construction Ltd. has successfully completed various projects across Calgary, showcasing their versatility and dedication. Their portfolio includes residential homes, commercial spaces, and renovations that enhance functionality and aesthetics. This company prioritizes safety and sustainability, implementing practices that minimize environmental impact while maximizing efficiency.</p> <p.With a focus on quality craftsmanship and customer service, Dawson Wallace Construction Ltd. stands ready to tackle diverse construction needs. Their proven track record and commitment to excellence make them a reliable choice for any construction project in Calgary. Visit Dawson Wallace Construction Ltd. at 2315 30 Ave NE #2, Calgary, Alberta for professional general contracting services.</p>',
  '2315 30 Ave NE #2',
  'Canada',
  'AB',
  'Calgary',
  'T2E 7C7',
  'admin@minersconstruction.com',
  'canada/calgary/home-services/dawson-wallace-construction-ltd',
  'ChIJ3QQerOFkcVMR81quU5atJdQ',
  51.0792136,
  -114.0068888,
  '14037355988',
  'https://www.kwikr.ca/pictures/profile/pimage-849.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  850,
  'https://dawsonwallace.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Miners Construction Co. Ltd.',
  '<p>Miners Construction Co. Ltd. operates as a general contractor in Saskatoon, Saskatchewan. This company specializes in residential and commercial construction projects, delivering quality workmanship and reliable services. With a focus on customer satisfaction, Miners Construction Co. Ltd. has built a solid reputation in the local area.</p><p>Experience defines the operations at Miners Construction Co. Ltd. The team comprises skilled professionals who manage every aspect of construction projects, from planning to execution. Clients benefit from the expertise in various construction methods and materials, ensuring that all projects meet industry standards. The business emphasizes safety and efficiency, which contributes to timely project completion.</p><p>Miners Construction Co. Ltd. has successfully completed numerous projects throughout Saskatoon, earning accolades for its commitment to excellence. The company prides itself on its transparent communication and collaboration with clients. This approach fosters trust and ensures that the final results align with client expectations.</p><p>Offering a wide range of services, including renovations, new builds, and commercial construction, Miners Construction Co. Ltd. caters to diverse needs. The business''s strengths lie in its attention to detail and dedication to quality. Positive feedback from satisfied clients highlights the effectiveness of the team in delivering exceptional results.</p><p>Explore the reliable construction services provided by Miners Construction Co. Ltd. in Saskatoon. This company exemplifies professionalism and expertise in the general contracting field. Reach out to Miners Construction Co. Ltd. for all construction needs in Saskatoon, Saskatchewan.',
  '440 Melville St',
  'Canada',
  'SK',
  'Saskatoon',
  'S7J 4M2',
  'info@alcorfacilities.com',
  'canada/saskatoon/home-services/miners-construction-co-ltd',
  'ChIJ74IL7vrwBFMR03SpZC7j8xY',
  52.0857949,
  -106.6570824,
  '13069344703',
  'https://www.kwikr.ca/pictures/profile/pimage-848.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  849,
  'https://www.minersconstruction.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);
