INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'PP Deslandes Inc',
  '<p>PP Deslandes Inc provides exceptional electrical installation services in Saint-Hyacinthe, Quebec. This local business specializes in residential and commercial electrical work, ensuring safety and efficiency in every project. With a commitment to quality, the company has built a solid reputation in the community for its reliable service and expertise.</p> <p>Established in the heart of Saint-Hyacinthe, PP Deslandes Inc focuses on delivering comprehensive electrical solutions. The team consists of skilled professionals who stay updated with the latest industry standards and technologies. They handle various electrical needs, from simple installations to complex wiring systems. The emphasis on customer satisfaction drives the team to complete projects on time and within budget.</p> <p>PP Deslandes Inc also prioritizes safety, adhering strictly to local codes and regulations. The company’s experience in the field allows it to tackle any electrical challenge efficiently. Clients appreciate the transparent communication throughout the project, which fosters trust and reliability. This dedication to service has led to numerous positive testimonials from satisfied customers.</p> <p>In summary, PP Deslandes Inc offers a range of electrical installation services backed by expertise and a strong commitment to safety. The company’s focus on client satisfaction and quality workmanship has solidified its place in the local market. Reach out to PP Deslandes Inc for reliable electrical services in Saint-Hyacinthe, Quebec.</p>',
  '4775 Av. Trudeau',
  'Canada',
  'QC',
  'Saint-Hyacinthe',
  'J2S 8V9',
  'careers@celelectric.com',
  'canada/saint-hyacinthe/home-services/pp-deslandes-inc',
  'ChIJq48-XRpOyEwR1nbpYW5vTWE',
  45.6333895,
  -72.9759962,
  '14507782426',
  'https://www.kwikr.ca/pictures/profile/pimage-563.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  573,
  'http://www.ppdeslandes.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Pronghorn Controls Ltd',
  '<p>Pronghorn Controls Ltd provides expert electrical installation services in Sundre, Alberta. This local business specializes in residential and commercial electrical projects, ensuring safety and efficiency. With a commitment to quality, Pronghorn Controls Ltd has built a strong reputation in the community for reliable and professional service.</p><p>Offering a range of services, Pronghorn Controls Ltd handles everything from new installations to upgrades and repairs. The team of qualified electricians possesses extensive knowledge and experience in the electrical industry. They prioritize customer satisfaction and adhere to all safety regulations, providing peace of mind to clients. The business operates from a central location at 605 Main Ave E, making it easily accessible for residents and businesses in Sundre.</p><p>Pronghorn Controls Ltd has achieved recognition for its dedication to high standards and efficient service. The company values transparency and clear communication, ensuring clients understand their options and the process involved. With a focus on using quality materials and advanced techniques, the business delivers durable and effective electrical solutions tailored to individual needs.</p><p>In summary, Pronghorn Controls Ltd offers comprehensive electrical installation services with a strong emphasis on safety and customer satisfaction. Their expertise and commitment to quality make them a trusted choice in Sundre, Alberta. Reach out to Pronghorn Controls Ltd for reliable electrical services today.',
  '605 Main Ave E',
  'Canada',
  'AB',
  'Sundre',
  'T0M 1X0',
  'admin@tnetworks.ca',
  'canada/sundre/home-services/pronghorn-controls-ltd',
  'ChIJn-6wrBaidlMRsCSrKLzXpgY',
  51.7947071,
  -114.6298912,
  '14036385096',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  572,
  'https://www.pronghorn.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Electrician Port Coquitlam - Kato Electrical Inc.',
  '<p>Kato Electrical Inc. provides top-notch electrical installation services in Port Coquitlam, British Columbia. Since 2015, this locally owned and operated company has built a reputation for reliability and excellence in both residential and commercial projects. With a focus on customer satisfaction, Kato Electrical offers upfront pricing and flexible scheduling to accommodate diverse needs.</p><p>This electrical service company handles a variety of tasks, from quick repairs to large-scale construction projects. Kato Electrical has successfully completed hundreds of projects, earning numerous 5-star reviews and an A rating from the Better Business Bureau. Their commitment to quality and professionalism ensures that every job meets the highest standards.</p><p>Clients in Port Coquitlam can expect guaranteed satisfaction when choosing Kato Electrical. The team is equipped to manage all job sizes, ensuring that no project is too small or too large. This versatility has made Kato Electrical a preferred choice for local residents and businesses alike.</p><p>With a strong focus on community and customer service, Kato Electrical Inc. continues to thrive in the competitive electrical installation market. The combination of experienced technicians, transparent pricing, and a dedication to quality makes this company a reliable partner for any electrical needs. Contact Kato Electrical Inc. today for exceptional service in Port Coquitlam. </p>',
  '2362 Whyte Ave Unit 101',
  'Canada',
  'BC',
  'Port Coquitlam',
  'V3C 2A4',
  'electriccompanyltd@gmail.com',
  'canada/port-coquitlam/home-services/electrician-port-coquitlam-kato-electrical-inc',
  'ChIJzWFMG5t5hlQRX-9P6NaXvMM',
  49.2627577,
  -122.7842667,
  '16042433011',
  'https://www.kwikr.ca/pictures/profile/pimage-561.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  571,
  'http://www.katoelectrical.com/?utm_campaign=GMB',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'R J S Electrical Contracting Ltd',
  '<p>R J S Electrical Contracting Ltd offers professional electrical installation services in Sechelt, British Columbia. This local business specializes in residential and commercial electrical work, ensuring safety and efficiency in every project. With a focus on quality and customer satisfaction, R J S Electrical Contracting Ltd has built a solid reputation in the community.</p><p>Located at 5536 Wharf Ave, R J S Electrical Contracting Ltd serves Sechelt and surrounding areas, providing a range of services that include wiring, lighting installation, and electrical panel upgrades. This company employs skilled technicians who are knowledgeable about the latest electrical codes and technologies. Their commitment to excellence is evident in their attention to detail and adherence to safety standards.</p><p>R J S Electrical Contracting Ltd has successfully completed numerous projects, showcasing their ability to handle both small and large-scale electrical installations. The team prioritizes clear communication with clients, ensuring that all needs and expectations are met throughout the project lifecycle. This approach fosters trust and reliability, essential qualities in the electrical service industry.</p><p>In summary, R J S Electrical Contracting Ltd provides comprehensive electrical installation services in Sechelt, British Columbia. Their expertise, commitment to safety, and customer-focused approach contribute to their strong reputation. For quality electrical solutions, reach out to R J S Electrical Contracting Ltd in Sechelt today. </p>',
  '5536 Wharf Ave',
  'Canada',
  'BC',
  'Sechelt',
  'V7Z 0P6',
  'info@artizanacanada.ca',
  'canada/sechelt/home-services/r-j-s-electrical-contracting-ltd',
  'ChIJSYDfZWw6hlQRgrOzxl96_Eg',
  49.4734146,
  -123.7542712,
  '16047401825',
  'https://www.kwikr.ca/pictures/profile/pimage-560.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  570,
  'http://www.rjselectrical.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Ele-Com Electrical Services Inc.',
  '<p>Ele-Com Electrical Services Inc. delivers comprehensive electrical installation services in Burlington, Ontario. This experienced electrical and telecommunications contractor operates across all sectors, ensuring quality and safety in every project. With a commitment to intelligent recommendations and experienced supervision, Ele-Com stands ready to assist in various electrical needs.</p><p>Offering a wide range of services, Ele-Com specializes in full electrical contracting up to 750v. The team excels in fiber and copper communications cabling installation and repairs, ensuring reliable connectivity for both residential and commercial clients. Additionally, Ele-Com provides design, fabrication, and installation of steel security cages and traffic guards, enhancing safety and security for various environments.</p><p>With a focus on quality work and safe operating practices, Ele-Com employs well-trained professionals who collaborate effectively with other trades. This cooperative approach ensures smooth project execution and timely completion. Post-construction repairs, refinishing, and clean-up services further demonstrate Ele-Com’s dedication to client satisfaction and project integrity.</p><p>Ele-Com Electrical Services Inc. combines expertise with a customer-centric approach, making it a trusted partner for electrical and telecommunications needs in Burlington, Ontario. The company’s strengths lie in its knowledgeable team, quality workmanship, and commitment to safety. Connect with Ele-Com for reliable electrical services that meet diverse project requirements in Burlington.</p>',
  '3466 Mainway',
  'Canada',
  'ON',
  'Burlington',
  'L7M 1A8',
  'invoices@horizonhv.com',
  'canada/burlington/home-services/ele-com-electrical-services-inc',
  'ChIJoYU3pyaeLIgRc9v0RrjyWWk',
  43.3689183,
  -79.7977567,
  '19055388001',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  569,
  'http://www.ele-com.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Riley Group Electrical Limited - Licensed electricians',
  '<p>Riley Group Electrical Limited offers comprehensive electrical installation services in Ajax, Ontario. This licensed electrician company specializes in a variety of electrical solutions, ensuring client satisfaction while maintaining budget considerations. Noteworthy services include free consultations and site visits, which enhance client engagement and project clarity.</p> <p>Riley Group excels in the replacement of knob and tube wiring as well as aluminum wiring. These specialties address common safety concerns in older homes and businesses. The company also provides wiring services for office spaces, retail environments, and industrial facilities, showcasing a diverse skill set tailored to meet various client needs. Their commitment to quality and affordability sets them apart in the local electrical service market.</p> <p>With a focus on customer satisfaction, Riley Group Electrical Limited prioritizes open communication and transparency throughout the project lifecycle. The team of licensed electricians works diligently to ensure that every project is completed on time and within budget. The emphasis on free consultations and site visits demonstrates a dedication to understanding client requirements and delivering tailored solutions.</p> <p>Riley Group Electrical Limited delivers reliable electrical installation services, specializing in knob and tube and aluminum wire replacement. Their strengths lie in customer focus, budget management, and diverse service offerings. Connect with Riley Group Electrical Limited in Ajax, Ontario, for expert electrical solutions that meet specific needs.',
  '138 Burcher Rd',
  'Canada',
  'ON',
  'Ajax',
  'L1S 2R4',
  'office@ganco.ca',
  'canada/ajax/home-services/riley-group-electrical-limited-licensed-electricians',
  'ChIJvT9z7SDh1IkRd_L-m6AX4po',
  43.839527,
  -79.0109379,
  '14168960669',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  568,
  'http://therileygroup4.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Capital Electric',
  '<p>Capital Electric, located at 111 Waterloo St Suite 311 in London, Ontario, offers reliable electrical installation services tailored to meet diverse customer needs. Established in 1992, this family-run business has built a solid reputation through quality workmanship and customer satisfaction. Word-of-mouth referrals have played a pivotal role in expanding its reach within London and neighboring municipalities.</p> <p>This father and son team focuses on providing comprehensive electrical solutions, ensuring all wiring requirements are met efficiently. Capital Electric specializes in residential and commercial installations, bringing expertise and dedication to every project. Clients benefit from personalized service and a deep understanding of electrical systems, which enhances safety and performance. The business emphasizes the importance of quality and reliability, aiming to exceed customer expectations with every job.</p> <p>Capital Electric has cultivated strong community ties, demonstrating commitment to local values and customer relationships. The business prides itself on transparency, ensuring clients are informed throughout the installation process. With decades of experience, the team remains updated on industry standards and innovations, allowing them to offer modern solutions for all electrical needs.</p> <p>Capital Electric provides exceptional electrical installation services, prioritizing customer satisfaction and community trust. The dedication to quality and expertise ensures that all wiring requirements are handled with care. Reach out to Capital Electric in London, Ontario, for reliable electrical solutions tailored to specific needs.</p>',
  '111 Waterloo St Suite 311',
  'Canada',
  'ON',
  'London',
  'N6B 2M4',
  'affilie@beqtechnology.com',
  'canada/london/home-services/capital-electric',
  'ChIJXRD3qhfyLogRLvrzrbfKvac',
  42.9768981,
  -81.2385024,
  '15194343312',
  'https://www.kwikr.ca/pictures/profile/pimage-557.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  567,
  'http://www.capitalelectric.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Mainway Electric Ltd',
  '<p>Mainway Electric Ltd provides top-tier electrical installation services in Burlington, Ontario, specializing in industrial and commercial projects. With 33 years of experience, this contractor has built a reputation for delivering safe and efficient electrical solutions. The company serves the Greater Toronto Area and the Golden Horseshoe, ensuring that clients receive reliable service tailored to their specific needs.</p><p>Mainway Electric Ltd focuses on making electrical systems safe and efficient. By prioritizing quality and safety, the company helps customers save money in the long term. Their expertise in electrical installations allows businesses to operate smoothly without disruptions. The team understands the complexities of electrical systems and works diligently to meet industry standards while addressing unique client requirements.</p><p>Clients benefit from Mainway Electric Ltd’s commitment to customer satisfaction. The company provides free quotes, allowing potential customers to understand costs upfront. This transparency fosters trust and confidence in their services. With a focus on industrial and commercial sectors, the company is well-equipped to handle various electrical installation projects, ensuring that all work meets regulatory requirements.</p><p>Mainway Electric Ltd excels in providing comprehensive electrical solutions that enhance safety and efficiency for clients in Burlington and surrounding areas. Their extensive experience and dedication to customer service make them a reliable choice for electrical installation needs. Reach out to Mainway Electric Ltd for expert electrical services in Burlington, Ontario.</p>',
  '1550 Yorkton Ct Unit #9',
  'Canada',
  'ON',
  'Burlington',
  'L7P 5B7',
  'adam@ryanselectrical.ca',
  'canada/burlington/home-services/mainway-electric-ltd',
  'ChIJn7DIcuJhK4gRdG7bur8x5I8',
  43.3248416,
  -79.8516598,
  '19053335966',
  'https://www.kwikr.ca/pictures/profile/pimage-556.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  566,
  'http://www.mainwayelectric.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Flyer Electric',
  '<p>Flyer Electric provides top-notch electrical installation services in Birch Hills No. 460, Canada. This company specializes in commercial and industrial projects across the province. With a diverse portfolio that includes mining, power generation, water treatment, oil and gas, and a strong emphasis on renewable energy, such as wind and solar power, Flyer Electric delivers reliable solutions for various electrical needs.</p> <p>Flyer Electric has established a reputation for excellence in electrical system integration. The company focuses on improving efficiency and safety while ensuring asset protection for every project. Expertise in handling different project sizes and types sets Flyer Electric apart in the electrical installation service industry. The commitment to renewable energy solutions reflects a forward-thinking approach to current energy demands.</p> <p>The team at Flyer Electric possesses extensive knowledge and experience, allowing for the successful execution of complex projects. Their ability to adapt to client needs while maintaining high standards of safety and efficiency is commendable. The emphasis on renewable energy showcases a dedication to sustainability, aligning with modern energy trends.</p> <p>Flyer Electric offers comprehensive electrical installation services, ensuring clients receive quality and efficiency. Their focus on commercial and industrial sectors, combined with a commitment to renewable energy, positions them as a reliable choice in the industry. Reach out to Flyer Electric for exceptional electrical solutions in Birch Hills No. 460.</p>',
  '#1 CanAm Highway 3 East',
  'Canada',
  'AB',
  'Birch Hills No. 460',
  'S0J 0G0',
  'info@flexisnap.com',
  'canada/birch-hills-no-460/home-services/flyer-electric',
  'ChIJR3eeHaYsAlMRh-iu6IZ3y7Q',
  52.9891991,
  -105.4162414,
  '18887493306',
  'https://www.kwikr.ca/pictures/profile/pimage-555.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  565,
  'https://www.flyerelectric.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Trueline Power & Consulting',
  '<p>Trueline Power & Consulting provides essential electrical installation services in Langley Twp, British Columbia. This locally owned and operated business specializes in Powerline solutions, including new Powerline construction, maintenance, and repair. As a BCHydro approved contractor, Trueline ensures high standards in safety watch, pole holding, pole setting, and storm repair. Their expertise extends to line designs, making them a comprehensive choice for electrical needs.</p><p>Trueline Power & Consulting has established a reputation for reliability and professionalism. The team approaches each project with a commitment to safety and efficiency. Their work in new Powerline construction meets industry standards, ensuring that all installations are durable and effective. Maintenance and repair services are prompt, addressing issues quickly to minimize disruptions. The company also offers specialized services like storm repair, showcasing their ability to handle unexpected challenges.</p><p>With a focus on customer satisfaction, Trueline Power & Consulting emphasizes transparency and communication throughout every project. Their commitment to quality and safety has earned them recognition in the local community. The skilled team is equipped to manage projects of varying sizes, providing tailored solutions that meet specific needs.</p><p>Trueline Power & Consulting delivers reliable electrical installation services, focusing on safety and efficiency. Their expertise in Powerline construction and maintenance makes them a trusted partner in Langley Twp. Connect with Trueline Power & Consulting for professional electrical services in British Columbia.</p>',
  '8029 199 St #105',
  'Canada',
  'BC',
  'Langley Twp',
  'V2Y 0E2',
  'info@fiberexelectric.ca',
  'canada/langley-twp/home-services/trueline-power-consulting',
  'ChIJd-AgXTTRhVQR04_SVmTozP4',
  49.148555,
  -122.6717715,
  '17788501035',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  564,
  'http://www.truelinepower.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Canadian Electrical Services',
  '<p>Canadian Electrical Services provides reliable electrical installation services in Burlington, Ontario. With over 22 years in business and 40 years of combined experience, this small company adheres to the rules of the Electrical Safety Authority (ESA). The team specializes in a variety of electrical solutions, ensuring safety and compliance for both residential and commercial projects.</p><p>The skilled electricians at Canadian Electrical Services handle home renovations, industrial amp service upgrades, and fuse, breaker, or motor control installations. They prioritize quality, using only the best electrical parts available. Each project is executed with precision, and the workmanship is guaranteed for a minimum of 10 years, providing peace of mind to clients.</p><p>Emergency situations are addressed promptly with 24/7 emergency and same-day service options. This commitment to customer satisfaction sets Canadian Electrical Services apart in the competitive electrical installation market. The team’s dedication to safety and quality has earned them a solid reputation in Burlington and surrounding areas.</p><p>Canadian Electrical Services offers a comprehensive range of electrical solutions, ensuring high standards and reliable service. With a focus on customer needs and industry regulations, the company stands ready to assist with any electrical project. Visit Canadian Electrical Services at 1235 Fairview St #105, Burlington, Ontario, for expert electrical services today.</p>',
  '1235 Fairview St #105',
  'Canada',
  'ON',
  'Burlington',
  'L7S 2H9',
  'info@bvelectric.ca',
  'canada/burlington/home-services/canadian-electrical-services',
  'ChIJvxWUvgSeLIgR7zeSBWv2Qi0',
  43.3310383,
  -79.8194314,
  '19056813940',
  'https://www.kwikr.ca/pictures/profile/pimage-553.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  563,
  'https://canadianelectricalservices.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'PTW Energy Services',
  '<p>PTW Energy Services Ltd. specializes in electrical installation services, delivering industry-leading solutions in fabrication, construction, and maintenance. Headquartered in Calgary, Alberta, this company serves clients across Canada, the United States, the Middle East, and Asia Pacific. With a strong focus on quality and efficiency, PTW Energy Services has established a reputation for reliability and expertise in the electrical sector.</p><p>This local business operates from its facility at 235038 Wrangler Road S.E, Rocky View, T1X 0K3. The team at PTW Energy Services is committed to meeting diverse energy needs, ensuring that every project is executed with precision. Their extensive experience in the industry allows them to tackle projects of varying scales, from small installations to large-scale constructions.</p><p>PTW Energy Services prioritizes customer satisfaction and safety, employing skilled professionals who are dedicated to delivering top-notch services. The company’s innovative approach and comprehensive service offerings make it a valuable partner for businesses in need of electrical solutions. With a robust network and a commitment to excellence, PTW Energy Services continues to grow and adapt to the evolving energy landscape.</p><p>Offering a wide range of electrical installation services, PTW Energy Services demonstrates strength in execution and a commitment to quality. Their achievements in the electrical sector highlight their dedication to service excellence. Connect with PTW Energy Services in Rocky View for reliable electrical installation services.</p>',
  '235038 Wrangler Road S.E',
  'Canada',
  'AB',
  'Rocky View',
  'T1X 0K3',
  'info@evtec.ca',
  'canada/rocky-view/home-services/ptw-energy-services',
  'ChIJeR7Ls2R5cVMRw-PdFUBlmi0',
  50.99617,
  -113.9026565,
  '14032348647',
  'https://www.kwikr.ca/pictures/profile/pimage-552.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  562,
  'http://www.ptwenergy.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Reseau Lam Inc',
  '<p>Reseau Lam Inc provides top-notch electrical installation services in Blainville, Quebec. This local business specializes in residential and commercial electrical systems, ensuring safe and efficient installations. With a team of qualified professionals, Reseau Lam Inc has built a reputation for reliability and expertise in the field.</p><p>Operating from 61 Rue Gaston-Dumoulin suite 400, Reseau Lam Inc serves the community with dedication. The company focuses on delivering high-quality electrical solutions tailored to meet the specific needs of each client. From new constructions to renovations, the skilled electricians handle all aspects of electrical work with precision.</p><p>Clients appreciate the transparent pricing and commitment to customer satisfaction. The team stays updated with the latest industry standards and technologies, ensuring compliance and safety in every project. Reseau Lam Inc also emphasizes the importance of energy efficiency, helping clients reduce their energy consumption through smart electrical installations.</p><p>Achievements include numerous successful projects across Blainville, showcasing the company’s ability to tackle diverse electrical challenges. The positive feedback from satisfied customers highlights the professionalism and expertise of the staff. Reseau Lam Inc continues to grow its presence in the local market, driven by a passion for excellence.</p><p>Electrical installation services at Reseau Lam Inc reflect a commitment to quality and safety. The company’s strengths lie in its skilled workforce and customer-oriented approach. Engage with Reseau Lam Inc for reliable electrical solutions in Blainville, Quebec.</p>',
  '61 Rue Gaston-Dumoulin suite 400',
  'Canada',
  'QC',
  'Blainville',
  'J7C 6B4',
  'info@lesentreprisessle.ca',
  'canada/blainville/home-services/reseau-lam-inc',
  'ChIJn-zfki8nyUwRp3nrqozz3i4',
  45.6707293,
  -73.8486719,
  '14508410711',
  'https://www.kwikr.ca/pictures/profile/pimage-551.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  561,
  'http://www.reseaulam.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Perfect Electricals Ltd',
  '<p>Perfect Electricals Ltd provides comprehensive electrical installation services in Brampton, Ontario. This business specializes in residential, commercial, and industrial electrical work. With a commitment to quality and safety, Perfect Electricals Ltd has built a reputation for reliability and professionalism in the local community.</p><p>The team at Perfect Electricals Ltd consists of skilled electricians who possess extensive knowledge in various electrical systems. They handle projects ranging from simple home wiring to complex industrial installations. Their expertise ensures that all work meets regulatory standards, providing peace of mind to clients. The company utilizes advanced technology and tools to deliver efficient solutions tailored to specific needs.</p><p>Perfect Electricals Ltd emphasizes customer satisfaction. The electricians prioritize clear communication, ensuring clients understand the scope and timeline of their projects. This approach fosters trust and leads to repeat business and referrals. Each project is executed with attention to detail, reflecting the company’s dedication to excellence in service.</p><p>In summary, Perfect Electricals Ltd offers reliable electrical installation services for residential, commercial, and industrial clients in Brampton, Ontario. The skilled team, commitment to quality, and focus on customer satisfaction contribute to the business''s strong reputation. Reach out to Perfect Electricals Ltd for professional electrical services in Brampton.',
  '11 Edvac Dr',
  'Canada',
  'ON',
  'Brampton',
  'L6S 5W5',
  'careers@smithandlong.com',
  'canada/brampton/home-services/perfect-electricals-ltd',
  'ChIJtbNGUXE9K4gRiEU1-x_px14',
  43.7622657,
  -79.7036448,
  '16475010697',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  560,
  'http://perfectelectricals.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Jim''s Electric 2006 Ltd',
  '<p>Jim''s Electric 2006 Ltd provides exceptional electrical installation services in Medicine Hat, Alberta. With over 30 years of experience, this locally owned and operated company delivers quality work and professional service. Customers can rely on Jim''s Electric for various electrical needs, ensuring safety and efficiency in every project.</p> <p>The team at Jim''s Electric understands the importance of reliable electrical systems in homes and businesses. They specialize in installations, repairs, and maintenance, catering to both residential and commercial clients. Their commitment to quality and customer satisfaction is evident in every job they undertake. The skilled electricians are trained to handle a range of electrical tasks, from simple repairs to complex installations.</p> <p>Jim''s Electric has built a strong reputation in the Medicine Hat community for its dedication to excellence. The company emphasizes professionalism and thoroughness, ensuring that every project meets industry standards. With a focus on customer service, they prioritize clear communication and timely completion of work. This approach fosters trust and builds lasting relationships with clients.</p> <p>Offering a wide range of electrical services, Jim''s Electric 2006 Ltd maintains high standards in all their work. Their extensive experience and commitment to quality make them a reliable choice for electrical needs in Medicine Hat. Reach out to Jim''s Electric today for expert electrical installation services in Alberta. </p>',
  '143 SW Dr S W',
  'Canada',
  'AB',
  'Medicine Hat',
  'T1A 8E8',
  'buddlyoburger@hotmail.com',
  'canada/medicine-hat/home-services/jim-s-electric-2006-ltd',
  'ChIJf_cSykctE1MRnwpnm1ecCWc',
  50.0165886,
  -110.7014541,
  '14035292566',
  'https://www.kwikr.ca/pictures/profile/pimage-549.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  559,
  'http://jimselectric.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Pronghorn Controls Ltd',
  '<p>Pronghorn Controls Ltd, located in Taber, Alberta, specializes in electrical installation services. This local business provides a range of solutions, including residential and commercial electrical work, ensuring safety and efficiency. With a commitment to quality and customer satisfaction, Pronghorn Controls Ltd has built a strong reputation in the community.</p><p>The team at Pronghorn Controls Ltd possesses extensive knowledge and experience in the electrical field. They handle projects of various sizes, from simple installations to complex systems. Their expertise includes wiring, lighting design, and energy-efficient solutions. Clients appreciate the professionalism and reliability that the company consistently delivers. Pronghorn Controls Ltd is dedicated to staying updated with industry standards and innovations, ensuring that all work meets or exceeds expectations.</p><p>Serving the Taber area, this business prioritizes customer needs and aims to provide tailored solutions. The skilled electricians understand the importance of timely service and clear communication throughout the project. They work closely with clients to ensure that all requirements are met, resulting in successful outcomes. Pronghorn Controls Ltd also emphasizes safety, adhering to all regulations and guidelines during every installation.</p><p>Pronghorn Controls Ltd offers exceptional electrical installation services, showcasing expertise and commitment to quality. Their strong local presence in Taber reinforces their dedication to the community. Connect with Pronghorn Controls Ltd for reliable electrical installations in Taber, Alberta.',
  '5810 66 Ave',
  'Canada',
  'AB',
  'Taber',
  'T1G 1W8',
  'brandon@ryman.ca',
  'canada/taber/home-services/pronghorn-controls-ltd',
  'ChIJc2SHQgA2bFMR8fq6zgMFnOs',
  49.80225,
  -112.1351399,
  '14032238811',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  558,
  'https://www.pronghorn.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'RBT Electrical & Automation Services',
  '<p>RBT Electrical & Automation Services offers comprehensive electrical installation services in Brantford, Ontario. Since 1997, this business has established a strong reputation for providing full-service electrical contracting and industrial automation solutions. The skilled team includes electrical design contractors, master electricians, and programmers, ensuring high-quality service for a variety of commercial and industrial clients.</p> <p>The company specializes in a range of services, including electrical contracting, PLC programming, and commercial lighting and control. RBT Electrical & Automation Services caters to the needs of businesses by delivering ongoing maintenance, repairs, and new installations. The focus remains on keeping operations running smoothly, which is critical for commercial and industrial sectors.</p> <p>RBT Electrical & Automation Services stands out for its commitment to quality and professionalism. The team''s expertise in electrical design and construction allows for tailored solutions that meet specific client requirements. This local business prioritizes efficiency and reliability in every project, reinforcing its status as a trusted partner in electrical services.</p> <p>With a proven track record and a dedicated team, RBT Electrical & Automation Services continues to serve Southern Ontario effectively. The combination of experience and a wide range of services ensures that clients receive exceptional support. Connect with RBT Electrical & Automation Services in Brantford for reliable electrical installation and automation services.</p>',
  '24 Sharp Rd',
  'Canada',
  'ON',
  'Brantford',
  'N3V 0A4',
  'info@robselectric.ca',
  'canada/brantford/home-services/rbt-electrical-automation-services',
  'ChIJA6voGpNuLIgRXzO_MlpctXM',
  43.178812,
  -80.345835,
  '15197523675',
  'https://www.kwikr.ca/pictures/profile/pimage-547.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  557,
  'https://rbtautomate.com/?utm_source=gmb&utm_medium=profile&utm_campaign=google-my-business',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Platinum Electric',
  '<p>Platinum Electric provides top-notch electrical installation services in Chilliwack, British Columbia. With over 30 years of experience, this company has established itself as a trusted name in the Fraser Valley. Known for quality work, Platinum Electric caters to both residential and commercial clients, ensuring safety and efficiency in every project.</p> <p>Expertise in electrical installation sets Platinum Electric apart. The team consists of skilled electricians who understand the complexities of electrical systems. They handle everything from wiring and lighting installations to panel upgrades and safety inspections. Their commitment to customer satisfaction ensures that all projects meet the highest standards.</p> <p>Community trust is evident through numerous positive testimonials. Clients appreciate the professionalism and reliability exhibited by the team. Platinum Electric’s long-standing presence in the Fraser Valley reflects a dedication to quality and service. The company adapts to evolving technologies, ensuring modern solutions for all electrical needs.</p> <p>With a focus on safety and compliance, Platinum Electric offers peace of mind for homeowners and businesses alike. Their extensive experience allows them to tackle projects of any size with confidence. This company not only meets expectations but often exceeds them, solidifying its reputation in the local area.</p> <p>Platinum Electric delivers exceptional electrical installation services in Chilliwack, British Columbia. Their experience, commitment to quality, and customer satisfaction make them a preferred choice. Connect with Platinum Electric today for reliable electrical services in Chilliwack. </p>',
  '46185 Olds Dr',
  'Canada',
  'BC',
  'Chilliwack',
  'V2P 0B5',
  'snfelectric@gmail.com',
  'canada/chilliwack/home-services/platinum-electric',
  'ChIJe06hvzcThFQRPgvQ8SqAAUw',
  49.150947,
  -121.9463243,
  '16047962988',
  'https://www.kwikr.ca/pictures/profile/pimage-546.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  556,
  'http://platinumelectric.pro/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'OKV Electrical Ltd.',
  '<p>OKV Electrical Ltd. provides reliable electrical installation services to the residents of Vernon, British Columbia. This local business specializes in a range of electrical needs, ensuring that no job is too small. With a commitment to completing projects on time and within budget, OKV Electric stands ready to assist with hot tub installations, service changes, and renovations. The company holds a TSBC License, showcasing its dedication to quality and compliance.</p><p>Located at 6098 Bella Vista Rd, OKV Electrical Ltd. has built a reputation for its customer-focused approach. The skilled team at OKV Electric understands the importance of timely service and adheres to strict safety standards. Whether adding or removing lights and plugs, or undertaking larger projects like new builds, the company guarantees a seamless experience from start to finish. Their expertise in the Okanagan region makes them a trusted choice for electrical installations.</p><p>OKV Electrical Ltd. prioritizes customer satisfaction and strives to meet the unique needs of each client. The business’s commitment to quality service and timely project completion has earned it a loyal customer base in Vernon. For those seeking dependable electrical solutions, OKV Electric offers free estimates and professional advice. Reach out to OKV Electrical Ltd. for all electrical needs in Vernon, British Columbia.</p>',
  '6098 Bella Vista Rd',
  'Canada',
  'BC',
  'Vernon',
  'V1H 1B4',
  'hugocharest@abixel.ca',
  'canada/vernon/home-services/okv-electrical-ltd',
  'ChIJz4TCSdOKfVMRtdO99AP8NXA',
  50.259369,
  -119.3233677,
  '12505406894',
  'https://www.kwikr.ca/pictures/profile/pimage-545.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  555,
  'http://okvelectric.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Community Electric Ltd. CEL',
  '<p>Community Electric Ltd. (CEL) provides top-notch electrical installation services in Surrey, British Columbia. This company specializes in industrial and commercial electrical contracting, ensuring projects meet the highest standards. CEL offers a range of services, including design-build solutions and emergency electrical services, catering to diverse client needs across Western Canada. The firm has established a strong reputation for reliability and expertise in the agri-industrial sector.</p><p>With a commitment to quality and safety, Community Electric Ltd. has successfully completed numerous projects, demonstrating its capability in handling complex electrical installations. The team of skilled professionals ensures that each project is executed efficiently, minimizing downtime for businesses. CEL''s dedication to customer satisfaction is evident through its responsive emergency service, providing immediate assistance when unexpected electrical issues arise.</p><p>Community Electric Ltd. operates from its location on Enterprise Way, serving the broader Surrey area and beyond. The company’s extensive experience in the industry positions it as a trusted partner for commercial and industrial electrical needs. Clients appreciate the combination of technical expertise and personalized service, which sets CEL apart in the competitive electrical contracting market.</p><p>Community Electric Ltd. excels in delivering reliable electrical installation services, with a focus on industrial and commercial sectors. The company''s strengths include its emergency services and design-build capabilities. For exceptional electrical solutions in Surrey, reach out to Community Electric Ltd. at Enterprise Way.</p>',
  '19329 Enterprise Way',
  'Canada',
  'BC',
  'Surrey',
  'V3S 6J8',
  'info@constcorp.ca',
  'canada/surrey/home-services/community-electric-ltd-cel',
  'ChIJBbPqHinRhVQRb3_bJRsmGvI',
  49.1084326,
  -122.6878218,
  '16043010730',
  'https://www.kwikr.ca/pictures/profile/pimage-544.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  554,
  'https://www.celelectric.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Turnkey Networks',
  '<p>Turnkey Networks delivers reliable electrical installation services in Winnipeg, Manitoba. This company specializes in a wide range of electrical solutions, ensuring safety and efficiency for both residential and commercial clients. With a focus on quality workmanship, Turnkey Networks has built a reputation for excellence in the local area.</p><p>Offering services such as wiring, lighting installation, and electrical system upgrades, Turnkey Networks caters to diverse customer needs. The team comprises experienced professionals who prioritize adherence to safety standards and regulations. This commitment to quality ensures that every project meets high industry benchmarks.</p><p>Turnkey Networks has successfully completed numerous projects across Winnipeg, showcasing their ability to handle both small and large-scale installations. Customer satisfaction remains a core value, reflected in the positive feedback received from clients. The business emphasizes timely project completion and clear communication throughout the process, which enhances the overall customer experience.</p><p>The company’s location at 939 Thomas Ave positions it as a convenient choice for residents and businesses in the area. With a strong focus on community engagement, Turnkey Networks supports local initiatives and fosters relationships within Winnipeg.</p><p>Turnkey Networks continues to provide exceptional electrical installation services, emphasizing safety, quality, and customer satisfaction. The commitment to excellence makes this company a trusted choice for electrical needs in Winnipeg. Connect with Turnkey Networks today for reliable electrical solutions in Manitoba.</p>',
  '939 Thomas Ave',
  'Canada',
  'MB',
  'Winnipeg',
  'R2L 2C6',
  'currentelectric.ltd@outlook.com',
  'canada/winnipeg/home-services/turnkey-networks',
  'ChIJv--TssRw6lIRKJri-Vl1PRQ',
  49.8996673,
  -97.0856407,
  '12042566667',
  'https://www.kwikr.ca/pictures/profile/pimage-543.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  553,
  'http://turnkeynetworks.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'The Electric Company Ltd.',
  '<p>The Electric Company Ltd. provides comprehensive electrical installation services in Fernie, British Columbia. This electrical contractor specializes in residential, commercial, and industrial installations and renovations. With a focus on quality and safety, the company has built a reputation for reliability and expertise in the local area.</p><p>Operating from 1591-9th avenue mailing box 1376, The Electric Company Ltd. has successfully completed numerous projects that highlight their commitment to excellence. Each installation adheres to industry standards, ensuring that clients receive safe and efficient electrical solutions. The team consists of skilled professionals who bring years of experience to every job, whether it involves upgrading a home’s electrical system or managing complex industrial projects.</p><p>The Electric Company Ltd. emphasizes customer satisfaction and strives to deliver timely service without compromising quality. Their extensive knowledge of electrical systems allows them to tackle various challenges effectively. From new constructions to renovations, the company provides tailored solutions that meet the unique needs of each client. This adaptability has positioned them as a trusted partner in the community.</p><p>The Electric Company Ltd. excels in delivering high-quality electrical installations and renovations across residential, commercial, and industrial sectors. Their commitment to safety and reliability makes them a preferred choice. Connect with The Electric Company Ltd. in Fernie for professional electrical services that meet all installation needs.',
  '1591-9th avenue mailing box 1376',
  'Canada',
  'BC',
  'Fernie',
  'V0B 1M0',
  'info@westshoreelectrical.com',
  'canada/fernie/home-services/the-electric-company-ltd',
  'ChIJi4YCVo1rZVMRTzcY2CgPYbM',
  49.5154421,
  -115.060769,
  '12504230625',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  552,
  'http://www.electriccompanyltd.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'ArtiZana - Bornes de recharge rapide',
  '<p>ArtiZana specializes in rapid charging station installations, serving the Montreal area in Quebec. As an authorized distributor for Chaevi Inc., a leading manufacturer from South Korea, ArtiZana provides high-quality electric vehicle charging solutions. The company has established a strong presence across North America, meeting the growing demand for efficient charging infrastructure.</p> <p>Electric vehicles are becoming increasingly popular, and the need for reliable charging stations is crucial. ArtiZana addresses this need by offering a range of advanced charging solutions tailored for residential and commercial use. The expertise in electrical installation ensures that each charging station is set up correctly and efficiently, maximizing performance and user satisfaction.</p> <p>With a focus on customer service and technical support, ArtiZana stands committed to helping clients navigate the complexities of electric vehicle charging. The team is knowledgeable about the latest technologies and trends in the industry, ensuring that customers receive the best possible advice and solutions for their specific needs. This commitment to excellence sets ArtiZana apart in the electrical installation service sector.</p> <p>ArtiZana provides exceptional products and services that contribute to a sustainable future. The dedication to quality and customer satisfaction has earned the trust of many clients in Montreal and beyond. For reliable electric vehicle charging solutions, connect with ArtiZana at 1200 McGill College Ave #1100, Montreal, Quebec, H3B 4G7.</p>',
  '1200 McGill College Ave #1100',
  'Canada',
  'QC',
  'Montreal',
  'H3B 4G7',
  'aadon@nbnet.nb.ca',
  'canada/montreal/home-services/artizana-bornes-de-recharge-rapide',
  'ChIJTUP0w6i-xCsR5ddt4qE5aa8',
  45.5013461,
  -73.5707069,
  '18003631799',
  'https://www.kwikr.ca/pictures/profile/pimage-541.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  551,
  'https://artizanacanada.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Horizon High Voltage Services',
  '<p>Horizon High Voltage Services, located at 1280 Seagrave Rd Unit E in Woodstock, Ontario, offers expert electrical installation services. Established in 2012, this fully licensed electrical contractor brings over 30 years of combined experience in high voltage and power distribution installations and testing. The company has built a reputation for reliability and expertise in the field.</p> <p>Horizon High Voltage Services specializes in a range of electrical installation tasks, ensuring safety and compliance with industry standards. Their team of skilled professionals handles projects of various sizes, from residential installations to large-scale commercial applications. The company’s commitment to quality and customer satisfaction sets it apart in the competitive electrical service market. Their extensive experience allows them to tackle complex projects efficiently, minimizing downtime for clients.</p> <p>The company’s focus on high voltage systems and power distribution positions it as a leader in the Woodstock area. Clients benefit from their thorough understanding of electrical systems and the latest technologies. Horizon High Voltage Services emphasizes ongoing training and development for its staff, ensuring they stay updated with industry advancements and safety protocols.</p> <p>In summary, Horizon High Voltage Services delivers top-notch electrical installation services, combining expertise with a strong commitment to client satisfaction. Their established presence in Woodstock reflects their dedication to quality work and reliability. Contact Horizon High Voltage Services today for professional electrical solutions in Ontario.</p>',
  '1280 Seagrave Rd Unit E',
  'Canada',
  'ON',
  'Woodstock',
  'N4T 0E3',
  'info@theelectriccompany.ca',
  'canada/woodstock/home-services/horizon-high-voltage-services',
  'ChIJ9xGkMtIYLIgRzbETx7avb8A',
  43.1382319,
  -80.7133854,
  '18554486587',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  550,
  'http://horizonhv.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Ganco Electric',
  '<p>Ganco Electric, located on Komoka Rd in Komoka, Ontario, specializes in electrical installation services for both residential and commercial properties. This family-owned and operated company prides itself on delivering quality workmanship. Ganco Electric has established itself as a leader in southwestern Ontario, particularly in the installation of Electric Vehicle charging solutions, catering to the growing demand for sustainable energy options.</p><p>The team at Ganco Electric focuses on meeting the diverse electrical needs of the local community. They offer a range of services that include electrical installations, upgrades, and maintenance. Their expertise extends to the installation of Electric Vehicle chargers, which supports the transition to greener transportation solutions. Ganco Electric’s commitment to quality and customer satisfaction is evident in every project, ensuring that clients receive reliable and efficient service.</p><p>Ganco Electric has built a reputation for professionalism and integrity. Their skilled technicians work diligently to ensure that all electrical installations meet safety standards and regulations. The company’s dedication to quality and service has earned them numerous positive reviews from satisfied customers in the area.</p><p>Ganco Electric provides essential electrical services while leading in Electric Vehicle charging installations. Their commitment to quality and customer satisfaction is commendable. For reliable electrical solutions in Komoka, Ontario, connect with Ganco Electric today.</p>',
  'Komoka Rd',
  'Canada',
  'ON',
  'Komoka',
  'N0L 1R0',
  'info@cablecc.ca',
  'canada/komoka/home-services/ganco-electric',
  'ChIJOyYb-oD9LogRUhDGgwiBttQ',
  42.9505023,
  -81.4386589,
  '15198540374',
  'https://www.kwikr.ca/pictures/profile/pimage-539.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  549,
  'http://ganco.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);
