INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Tri City Wholesale Flooring',
  '<p>Tri City Wholesale Flooring operates as a prominent general contractor in Kitchener, Ontario, specializing in high-quality flooring solutions. This company has been serving the Tri-City area since 1995, offering a diverse selection of flooring options including laminate, hardwood, ceramic, and carpet. With a commitment to customer satisfaction, Tri City Wholesale Flooring provides free in-home estimates, ensuring that clients find the perfect flooring to fit their budget and lifestyle.</p><p>This local business excels in importing European tiles, which enhances its unique offerings and provides customers with an unparalleled selection. The focus remains on quality and versatility, catering to various design preferences and functional needs. The showroom showcases an extensive range of products, allowing customers to visualize their choices in a real setting.</p><p>Tri City Wholesale Flooring has built a reputation for reliability and excellence in the flooring industry. The knowledgeable staff assists clients in navigating through options, ensuring informed decisions are made for every project. This dedication to service and quality has solidified its status as a go-to flooring provider in Kitchener.</p><p>Tri City Wholesale Flooring delivers exceptional flooring solutions tailored to individual needs. With a strong commitment to customer satisfaction and a wide selection of luxury products, the business remains a leader in the local market. Visit Kitchener today to explore flooring options and elevate any space with quality products and services.</p>',
  '334 Manitou Dr',
  'Canada',
  'ON',
  'Kitchener',
  'N2C 1L3',
  'info@rjmacisaac.ca',
  'canada/kitchener/home-services/tri-city-wholesale-flooring',
  'ChIJ3XVPbGGIK4gRFAr4iboOriE',
  43.4054648,
  -80.447863,
  '15192080241',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  773,
  'https://www.tricityflooring.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'R J MacIsaac Construction Ltd',
  '<p>R.J. MacIsaac Construction Ltd. offers comprehensive marine and general contracting services in Antigonish, Nova Scotia. This company specializes in marine salvage and green ship recycling, contributing to environmental sustainability in Atlantic Canada. With a strong reputation in the industry, R.J. MacIsaac Construction Ltd. combines expertise and local knowledge to deliver quality services.</p><p>The company operates from its base at 70 West St #1, ensuring accessibility for clients in the region. R.J. MacIsaac Construction Ltd. has successfully completed numerous projects, showcasing its commitment to excellence and innovation. The focus on marine salvage not only aids in the recovery of valuable materials but also emphasizes responsible practices in ship recycling. This dual approach positions the company as a leader in both general contracting and marine services.</p><p>Clients appreciate the professionalism and reliability that R.J. MacIsaac Construction Ltd. brings to every project. The skilled team ensures that all work meets high standards, whether it involves general contracting tasks or specialized marine services. The dedication to customer satisfaction is evident in the positive feedback received from the community.</p><p>R.J. MacIsaac Construction Ltd. excels in delivering top-notch marine and general contracting services while promoting sustainable practices. The combination of local expertise and a commitment to quality sets this company apart. Reach out to R.J. MacIsaac Construction Ltd. in Antigonish for reliable contracting solutions.</p>',
  '70 West St #1',
  'Canada',
  'NS',
  'Antigonish',
  'B2G 2X7',
  'demarco@demarcoconstruction.ca',
  'canada/antigonish/home-services/r-j-macisaac-construction-ltd',
  'ChIJv2RJJA5FXEsRHSgL4frCSk8',
  45.6155709,
  -61.9990121,
  '18335117447',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  772,
  'http://www.rjmacisaac.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'DeMarco Construction',
  '<p>DeMarco Construction operates as a reliable general contractor in Nepean, Ontario, specializing in residential and commercial projects. This business offers a wide range of services, including renovations, new builds, and project management. With a commitment to quality and customer satisfaction, DeMarco Construction has earned a solid reputation in the local community.</p><p>The team at DeMarco Construction possesses extensive experience in the construction industry, ensuring that every project meets high standards. Each project reflects a dedication to craftsmanship and attention to detail. Clients can expect clear communication and a streamlined process from start to finish. The company has successfully completed numerous projects, showcasing its ability to handle diverse construction needs.</p><p>DeMarco Construction emphasizes the importance of using quality materials and skilled labor. This approach not only enhances the durability of the projects but also contributes to the overall aesthetic appeal. The business maintains strong relationships with suppliers, which allows for competitive pricing and timely project completion. Clients appreciate the transparency and professionalism demonstrated throughout the construction process.</p><p>DeMarco Construction provides comprehensive general contracting services, focusing on quality, efficiency, and customer satisfaction. The company''s achievements in Nepean highlight its commitment to excellence in the construction field. For reliable and professional general contracting services, connect with DeMarco Construction in Nepean, Ontario. </p>',
  '195 Menten Pl Unit 103',
  'Canada',
  'ON',
  'Nepean',
  'K2H 9C1',
  'scott@holmanconstruct.com',
  'canada/nepean/home-services/demarco-construction',
  'ChIJi4_kYa34zUwRTx9M6kEUC4s',
  45.3271322,
  -75.8336061,
  '16138292777',
  'https://www.kwikr.ca/pictures/profile/pimage-768.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  771,
  'https://demarcoconstruction.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Holman Construction Inc.',
  '<p>Holman Construction Inc., located at 39782 Dashwood Rd in Hay, Ontario, excels in providing top-notch general contracting services. Established in 2016, this company focuses on commercial and residential renovations and remodeling, serving the London area and beyond. Holman Construction has built a reputation for delivering quality craftsmanship and reliable project management.</p> <p>The team at Holman Construction understands the unique needs of each client. They approach every project with a commitment to excellence, ensuring that the final result aligns with the client''s vision. The company utilizes modern techniques and high-quality materials to enhance both aesthetics and functionality in every renovation. From kitchen remodels to office renovations, Holman Construction handles projects of all sizes with professionalism and attention to detail.</p> <p>Client satisfaction remains a core value for Holman Construction. The business prides itself on clear communication and collaborative planning. This approach fosters trust and ensures that projects are completed on time and within budget. Positive feedback from clients highlights the company’s dedication to quality and service.</p> <p>Holman Construction Inc. offers comprehensive general contracting services, specializing in both commercial and residential renovations. Their commitment to quality and client satisfaction sets them apart in the industry. Connect with Holman Construction in Hay, Ontario, for expert renovation services that transform spaces effectively. </p>',
  '39782 Dashwood Rd',
  'Canada',
  'ON',
  'Hay',
  'N0M 1W0',
  'info@urquhartconstruction.com',
  'canada/hay/home-services/holman-construction-inc',
  'ChIJ00ISyOv7LogRxoLavOAzO9I',
  43.3588624,
  -81.509934,
  '15196609072',
  'https://www.kwikr.ca/pictures/profile/pimage-767.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  770,
  'http://www.holmanconstruct.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Urquhart Construction',
  '<p>Urquhart Construction operates as a general contractor in Charters Settlement, New Brunswick, specializing in constructing dream homes and providing quality home improvements. This local business is committed to ensuring that each project meets high standards of quality and customer satisfaction. With a focus on enhancing comfort and happiness for families, Urquhart Construction delivers results that last a lifetime.</p><p>The company offers a range of services, including new home construction, door and window upgrades, siding installations, kitchen and bathroom renovations, and new garage construction. Each project reflects a dedication to craftsmanship and attention to detail. Urquhart Construction understands the importance of building homes that not only meet the needs of the present but also accommodate future growth and changes in lifestyle.</p><p>Clients can expect personalized service from a team that values communication and transparency throughout the building process. The commitment to quality and customer satisfaction has earned Urquhart Construction a reputation for reliability in the local community. Each project showcases the company''s expertise and dedication to delivering exceptional results.</p><p>Urquhart Construction excels in creating comfortable living spaces tailored to family needs. Their range of services ensures that both new constructions and renovations are handled with care and professionalism. Connect with Urquhart Construction in Charters Settlement to start building or improving a dream home today.</p>',
  '23 Nates Ct',
  'Canada',
  'NB',
  'Charters Settlement',
  'E3C 0M9',
  'info@docksideatlantic.com',
  'canada/charters-settlement/home-services/urquhart-construction',
  'ChIJr2BnOpcnpEwRAMEjnC4-szg',
  45.86631,
  -66.71379,
  '15064471796',
  'https://www.kwikr.ca/pictures/profile/pimage-766.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  769,
  'http://www.urquhartconstruction.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Dockside Atlantic Group',
  '<p>Dockside Atlantic Group operates as a reputable general contractor in Fall River, Nova Scotia. This business specializes in a variety of construction services, including residential and commercial projects. With a commitment to quality and customer satisfaction, Dockside Atlantic Group has built a strong reputation in the local community for delivering reliable construction solutions.</p> <p>The team at Dockside Atlantic Group brings extensive experience and expertise to every project. They focus on understanding client needs and providing tailored solutions that meet specific requirements. This approach ensures that all projects, whether large or small, are completed on time and within budget. The use of high-quality materials and skilled craftsmanship distinguishes their work in the competitive construction industry.</p> <p>Dockside Atlantic Group has successfully completed numerous projects in Fall River and surrounding areas. Their portfolio includes renovations, new builds, and commercial construction. The business emphasizes safety and efficiency, adhering to industry standards and regulations. Clients appreciate the transparency and communication throughout the construction process, fostering trust and satisfaction.</p> <p>Offering a comprehensive range of construction services, Dockside Atlantic Group excels in meeting diverse client needs. Their commitment to quality and professionalism makes them a valuable asset to the local community. For reliable general contracting services in Fall River, Nova Scotia, connect with Dockside Atlantic Group today.',
  '1300 Fall River Rd',
  'Canada',
  'NS',
  'Fall River',
  'B2T 1E6',
  'estimates@royalhomeimprovements.ca',
  'canada/fall-river/home-services/dockside-atlantic-group',
  'ChIJR9dvU6iHWUsRCAOr-L1xh_I',
  44.8114571,
  -63.6171547,
  '19028359000',
  'https://www.kwikr.ca/pictures/profile/pimage-765.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  768,
  'https://www.docksideatlantic.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Royal Home Improvements',
  '<p>Royal Home Improvements serves as a reliable general contractor in Mississauga, Ontario, providing exceptional services since 1969. This family-owned business prides itself on a team-oriented approach to every project, ensuring that clients receive personalized attention and high-quality results. The company specializes in various renovations, including both interior and exterior projects, along with comprehensive design/build services.</p><p>The expertise of Royal Home Improvements extends across a wide range of renovation needs. Each project is managed by a staff of knowledgeable professionals who prioritize client satisfaction. The team commits to completing jobs on time and within budget, emphasizing clear communication throughout the process. This ensures that clients understand every step, leading to a finished product that reflects their vision.</p><p>With decades of experience, Royal Home Improvements has built a reputation for reliability and professionalism in the Toronto area. The company’s dedication to quality craftsmanship and customer service sets it apart in the competitive general contracting landscape. Clients benefit from a seamless experience, whether undertaking a small renovation or a large-scale project.</p><p>Royal Home Improvements offers a diverse range of services designed to meet the unique needs of each client. The combination of industry knowledge and a commitment to excellence results in outstanding renovations. Engage with Royal Home Improvements today for all contracting needs in Mississauga, Ontario. </p>',
  '2601 Matheson Blvd E #202',
  'Canada',
  'ON',
  'Mississauga',
  'L4W 5A8',
  'münchen@advito.com',
  'canada/mississauga/home-services/royal-home-improvements',
  'ChIJ567PHf02K4gREVgtLaNcRmc',
  43.6600982,
  -79.6002859,
  '14162364400',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  767,
  'https://www.royalhomeimprovements.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Roof Edge Eavestroughing',
  '<p>Roof Edge Eavestroughing serves the Coalhurst area in Alberta, specializing in eavestrough installation for commercial, residential, and custom projects. This general contractor excels in providing durable gutters and downspouts tailored to withstand the strong winds of Southern Alberta. The company has developed a perfected installation process that ensures customer satisfaction and long-lasting results.</p><p>The team at Roof Edge Eavestroughing focuses on efficiency and durability. They offer commercial gutter systems constructed from robust materials that can handle 40% more water than standard eavestroughs. This feature significantly reduces the risk of water damage, a common concern for property owners in the region. The expertise in custom installations allows for tailored solutions that meet specific client requirements, enhancing the overall functionality of drainage systems.</p><p>With a commitment to quality and customer service, Roof Edge Eavestroughing has established a solid reputation in the local community. The knowledgeable staff provides reliable advice and support throughout the installation process, ensuring that each project meets the highest standards. Clients can expect professional service and exceptional results that contribute to the longevity of their properties.</p><p>Roof Edge Eavestroughing delivers top-notch eavestrough installation services, focusing on durability and efficiency. The company’s expertise in handling commercial and residential projects sets it apart in the industry. Contact Roof Edge Eavestroughing in Coalhurst for reliable gutter solutions. </p>',
  'Box 350',
  'Canada',
  'AB',
  'Coalhurst',
  'T0L 0V0',
  'jobs.bc@emconservices.ca',
  'canada/coalhurst/home-services/roof-edge-eavestroughing',
  'ChIJ2zbsM6NiblMRSBbhzB3qe-A',
  49.726923,
  -112.915272,
  '14037154567',
  'https://www.kwikr.ca/pictures/profile/pimage-763.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  766,
  'https://roofedgeeavestroughing.ca/?utm_source=gmb&utm_campaign=local&utm_medium=organic',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Emcon Services Inc',
  '<p>Emcon Services Inc is a reputable general contractor based in Merritt, British Columbia. The company offers a wide range of construction and renovation services, focusing on quality and customer satisfaction. With a strong presence in the local community, Emcon Services Inc has built a solid reputation for delivering reliable and efficient construction solutions.</p> <p>This business specializes in various projects including residential and commercial construction, renovations, and maintenance services. Emcon Services Inc employs skilled professionals who ensure that every project meets high standards of quality and safety. The company has successfully completed numerous projects in Merritt and the surrounding areas, showcasing its commitment to excellence.</p> <p.Emcon Services Inc prioritizes customer needs, providing tailored solutions that fit specific project requirements. The team works closely with clients, ensuring clear communication and transparency throughout the construction process. This approach fosters trust and satisfaction among customers, leading to repeat business and referrals.</p> <p.Overall, Emcon Services Inc exemplifies professionalism and dedication in the general contracting field. Their extensive experience and local knowledge contribute to successful project outcomes. For those seeking reliable construction services in Merritt, Emcon Services Inc offers a solid choice. Connect with Emcon Services Inc at 1121 McFarlane Way, Merritt, British Columbia, to explore quality general contracting services.</p>',
  '1121 McFarlane Way',
  'Canada',
  'BC',
  'Merritt',
  'V1K 1B9',
  'info@icehouseent.ca',
  'canada/merritt/home-services/emcon-services-inc',
  'ChIJDz0EXF-QgVQRtaPY6F03YfU',
  50.0969622,
  -120.771521,
  '12503784176',
  'https://www.kwikr.ca/pictures/profile/pimage-762.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  765,
  'http://www.emconservices.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Ice House Enterprises Inc',
  '<p>Ice House Enterprises Inc provides comprehensive general contracting services in Airdrie, Alberta. This business excels in both residential and commercial projects, ensuring quality workmanship and timely completion. With a commitment to customer satisfaction, Ice House Enterprises has built a reputation for reliability and professionalism in the local construction industry.</p> <p>Founded with a vision to serve the Airdrie community, Ice House Enterprises Inc specializes in renovations, new builds, and project management. The team possesses extensive experience and knowledge in various construction methods, ensuring that every project meets industry standards. Clients appreciate the transparent communication and detailed planning that characterize their approach.</p> <p>Ice House Enterprises takes pride in its ability to handle projects of all sizes and complexities. The company focuses on using high-quality materials and skilled labor, which leads to durable and aesthetically pleasing results. This dedication to excellence has earned the business numerous repeat clients and referrals, demonstrating its strong standing in the local market.</p> <p>Ice House Enterprises Inc offers a full suite of general contracting services tailored to the unique needs of each client. The company''s strengths lie in its attention to detail, commitment to deadlines, and a strong focus on customer satisfaction. For those seeking reliable general contracting services in Airdrie, reach out to Ice House Enterprises Inc at 2914 Kingsview Blvd SE Unit 215.',
  '2914 Kingsview Blvd SE Unit 215',
  'Canada',
  'AB',
  'Airdrie',
  'T4A 0E1',
  'info@modernorestoration.com',
  'canada/airdrie/home-services/ice-house-enterprises-inc',
  'ChIJQ2gmuupfcVMRrd05nIlOtv4',
  51.26217,
  -113.9941221,
  '14039459902',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  764,
  'http://icehouseent.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Moderno Restoration Inc',
  '<p>Moderno Restoration Inc. serves as Toronto''s leading general contractor, specializing in high-rise and low-rise condominium projects. This company focuses on transforming condos into award-winning landmarks, providing exceptional service across various construction needs. With a strong commitment to quality, Moderno Restoration Inc. caters to the diverse requirements of condominium corporations throughout the city.</p><p>Operating from its location at 2220 Midland Ave Unit 15, Moderno Restoration Inc. has built a reputation for reliability and excellence in the construction industry. The team handles a wide range of projects, from minor repairs to extensive reserve fund initiatives. Many condominium management companies, board members, and managers trust Moderno for their construction needs, highlighting the company''s dedication to successful project delivery.</p><p>Clients appreciate the hands-on approach and the emphasis on communication throughout each project. Moderno Restoration Inc. understands the unique challenges faced by condominium corporations and tailors solutions to meet those specific demands. The company takes pride in its ability to deliver superior results that enhance the value and appeal of each property.</p><p>Moderno Restoration Inc. excels in providing comprehensive general contracting services, ensuring client satisfaction through quality workmanship. The commitment to excellence and client-focused approach positions the company as a leader in the Toronto area. Connect with Moderno Restoration Inc. for all general contracting needs in Toronto, Ontario.</p>',
  '2220 Midland Ave Unit 15',
  'Canada',
  'ON',
  'Toronto',
  'M1P 3E6',
  'info@sema.ca',
  'canada/toronto/home-services/moderno-restoration-inc',
  'ChIJU9PHNLbf1IkRGSiaJcU5ki4',
  43.7750656,
  -79.2750133,
  '16474945505',
  'https://www.kwikr.ca/pictures/profile/pimage-760.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  763,
  'http://www.modernorestoration.com/?utm_source=google&utm_medium=wix_google_business_profile&utm_campaign=2328274007949542319',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'SEMA Inc.',
  '<p>SEMA Inc., located at 125 Rue de l''Expansion in Sainte-Flavie, Quebec, specializes in the manufacturing and installation of railway and transportation infrastructure. This general contractor serves various clients, delivering reliable solutions in the transportation sector. With a strong focus on quality and efficiency, SEMA Inc. has established a reputation for excellence in its field.</p><p>The company''s expertise includes a wide range of services that cater to the needs of the railway industry. Projects often involve the construction and installation of tracks, bridges, and related infrastructure. SEMA Inc. utilizes advanced techniques and materials to ensure durability and safety, meeting the highest industry standards. The skilled team at SEMA Inc. works closely with clients to tailor solutions that align with specific project requirements.</p><p>SEMA Inc. has successfully completed numerous projects throughout Quebec, showcasing its commitment to customer satisfaction and operational excellence. The company prioritizes timely project delivery and adheres to budget constraints, making it a preferred choice for many in the region. The focus on innovation and sustainable practices further enhances its standing in the industry.</p><p>SEMA Inc. continues to provide top-notch services in railway and transportation infrastructure, demonstrating a proven track record of success. With a commitment to quality and client satisfaction, this general contractor remains a vital player in the market. Connect with SEMA Inc. in Sainte-Flavie for expert solutions in infrastructure development.</p>',
  '125 Rue de l''Expansion',
  'Canada',
  'QC',
  'Sainte-Flavie',
  'G0J 2L0',
  'webrequest@wkconstruction.ca',
  'canada/sainte-flavie/home-services/sema-inc',
  'ChIJPTJVSkt_lkwRpM0so-0su1g',
  48.6063611,
  -68.223966,
  '14187757141',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  762,
  'http://www.sema.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'White Knight Construction Ltd.',
  '<p>White Knight Construction Ltd. serves Edmonton, Alberta, as a reliable general contractor specializing in residential and commercial projects. The company has built a reputation for delivering high-quality construction services, including renovations, new builds, and project management. With a commitment to customer satisfaction and a focus on efficiency, White Knight Construction Ltd. has successfully completed numerous projects throughout the local area.</p><p>The team at White Knight Construction Ltd. brings extensive industry experience and expertise to every project. They understand the complexities involved in construction and work diligently to ensure that all aspects of a project run smoothly. Clients appreciate the transparent communication and attention to detail that the company provides, which helps eliminate common construction-related stressors. The firm uses high-quality materials and adheres to industry standards, ensuring durable and aesthetically pleasing results.</p><p>White Knight Construction Ltd. has achieved numerous accolades for its commitment to excellence in construction. The company''s portfolio showcases a variety of successful projects, highlighting its versatility and capability. By fostering strong relationships with clients and subcontractors, White Knight Construction Ltd. creates a collaborative environment that enhances project outcomes.</p><p>Offering a comprehensive range of construction services, White Knight Construction Ltd. stands out for its dedication to quality and client satisfaction. The company''s achievements reflect its strong work ethic and commitment to the community. Contact White Knight Construction Ltd. at 17215 106 Ave NW, Edmonton, Alberta, for expert construction services today.</p>',
  '17215 106 Ave NW',
  'Canada',
  'AB',
  'Edmonton',
  'T5S 1E7',
  'bdevelopment@kenaidan.com',
  'canada/edmonton/home-services/white-knight-construction-ltd',
  'ChIJ6Qos9B8hoFMRkcOmTlHNiyE',
  53.5499596,
  -113.619534,
  '17804887710',
  'https://www.kwikr.ca/pictures/profile/pimage-758.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  761,
  'http://www.wkconstruction.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Kenaidan Contracting Ltd',
  '<p>Kenaidan Contracting Ltd operates as a general contractor in Mississauga, Ontario, providing a range of construction services. The company specializes in commercial and residential projects, emphasizing quality and efficiency. With a reputation for reliability, Kenaidan has successfully completed numerous projects that highlight its commitment to customer satisfaction.</p><p>The firm’s expertise encompasses various aspects of construction, including project management, renovations, and new builds. Kenaidan Contracting Ltd employs skilled professionals who ensure that every project meets industry standards and client expectations. The team is dedicated to delivering exceptional results on time and within budget, reinforcing the company''s strong standing in the local market.</p><p>Kenaidan’s focus on sustainable practices and innovative solutions distinguishes it from competitors. The company''s commitment to using environmentally friendly materials and techniques contributes positively to the community and the environment. This approach not only enhances project outcomes but also supports local development goals.</p><p>With a strong portfolio and a history of successful collaborations, Kenaidan Contracting Ltd continues to serve the Mississauga area effectively. The blend of expertise, dedication, and a customer-centric approach positions the company as a reliable choice for construction needs. Engage with Kenaidan Contracting Ltd for quality general contracting services in Mississauga, Ontario.',
  '7080 Derrycrest Dr',
  'Canada',
  'ON',
  'Mississauga',
  'L5W 0G5',
  'tinthahack@con-tech.ca',
  'canada/mississauga/home-services/kenaidan-contracting-ltd',
  'ChIJBYKv_eQ-K4gROUmo7QVccFk',
  43.644954,
  -79.7113,
  '19056702660',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  760,
  'http://www.kenaidan.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'DKI - Con-Tech',
  '<p>DKI - Con-Tech, located at 755 Progress Ave, Scarborough, Ontario, offers comprehensive general contracting services with a focus on emergency disaster response and property restoration. Since 1990, this company has excelled in providing 24/7 services for both residential and commercial properties across the Greater Toronto Area. DKI - Con-Tech specializes in cleanup and recovery from various damages including wind, fire, smoke, water, vandalism, and vehicle impact.</p> <p>The company has built strong relationships with key clients such as insurance companies, financial institutions, and property management firms. Their expertise in handling insurable losses ensures efficient and reliable service delivery. DKI - Con-Tech employs skilled professionals who are trained to manage emergencies effectively, minimizing disruption for clients.</p> <p>With a proven track record, DKI - Con-Tech has established itself as a trusted partner in the community. The company’s commitment to quality and customer satisfaction drives its operations. Utilizing advanced techniques and equipment, they restore properties to their pre-loss condition swiftly and safely. This dedication to excellence has garnered a solid reputation within the industry.</p> <p>DKI - Con-Tech provides essential services for emergency disaster response, property restoration, and contents recovery. Their long-standing experience, strong client relationships, and commitment to quality make them a reliable choice. Visit DKI - Con-Tech in Scarborough for expert assistance with property damage recovery needs.</p>',
  '755 Progress Ave',
  'Canada',
  'ON',
  'Scarborough',
  'M1H 2W7',
  'info@arnoldconstruction.co',
  'canada/scarborough/home-services/dki-con-tech',
  'ChIJA0I-uJTR1IkRgVgXziWXCow',
  43.7795557,
  -79.2442382,
  '14162889932',
  'https://www.kwikr.ca/pictures/profile/pimage-756.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  759,
  'http://www.con-tech.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Arnold Construction Management Ltd',
  '<p>Arnold Construction Management Ltd serves as a leading general contractor in Kelowna, British Columbia. This company specializes in modern home builds, custom home building, and renovations, ensuring projects are completed on time and within budget. Arnold Construction''s commitment to quality and client satisfaction sets it apart in the construction management industry.</p> <p>With a focus on meticulous oversight, Arnold Construction manages every detail of each project. The team brings extensive experience and industry knowledge to the table, ensuring seamless execution from inception to completion. Clients can expect a personalized approach, where their unique needs are prioritized throughout the construction process. This dedication to client experience results in flawless project delivery.</p> <p>Arnold Construction''s reputation in Kelowna and the Okanagan Valley is built on successful project outcomes and satisfied clients. The company has established itself as a reliable partner for homeowners seeking to build or renovate their properties. The emphasis on modern design and custom solutions meets the diverse needs of the local community.</p> <p>Arnold Construction Management Ltd offers comprehensive services in general contracting, focusing on quality and client satisfaction. Their expertise covers modern home builds, custom homes, and renovations, ensuring each project is handled with care. Engage with Arnold Construction in Kelowna for exceptional construction management services.</p>',
  '808 Fuller Ave',
  'Canada',
  'BC',
  'Kelowna',
  'V1Y 6X3',
  'info@archivecontracting.com',
  'canada/kelowna/home-services/arnold-construction-management-ltd',
  'ChIJeW6m71nzfVMRRySFxrA8z28',
  49.8904872,
  -119.4853177,
  '12508631817',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  758,
  'http://arnoldconstruction.co/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Archive Contracting & Design',
  '<p>Archive Contracting & Design offers comprehensive general contracting services in Edmonton, Alberta. This business specializes in both residential and commercial projects, ensuring quality workmanship and timely completion. With a focus on client satisfaction, Archive Contracting & Design has built a reputation for reliability and professionalism in the local market.</p><p>Operating from 5913 90 St NW, Archive Contracting & Design caters to a diverse clientele. The team possesses extensive experience in various aspects of construction, including renovations, new builds, and commercial fit-outs. Each project reflects the company’s commitment to excellence and attention to detail. The skilled professionals at Archive Contracting & Design utilize the latest techniques and materials to deliver results that meet industry standards.</p><p>Customer testimonials highlight the company''s dedication to clear communication and project management. Archive Contracting & Design ensures that clients are informed throughout the process, fostering trust and transparency. The business''s ability to adapt to changing project requirements has positioned it as a leader in the Edmonton area.</p><p>Archive Contracting & Design provides a wide range of services tailored to meet the specific needs of each client. The combination of expertise and a customer-focused approach has led to numerous successful projects. For reliable general contracting services in Edmonton, connect with Archive Contracting & Design today.</p>',
  '5913 90 St NW',
  'Canada',
  'AB',
  'Edmonton',
  'T6E 6C2',
  'info@turnerbros.ca.',
  'canada/edmonton/home-services/archive-contracting-design',
  'ChIJ4QazKT0ZoFMRxXtFMuO2i8A',
  53.4953125,
  -113.465481,
  '18256005900',
  'https://www.kwikr.ca/pictures/profile/pimage-754.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  757,
  'http://www.archivecontracting.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Turner Bros Contractors Ltd',
  '<p>Turner Bros Contractors Ltd, located in Surrey, British Columbia, has been a reliable general contractor since 1932. This family-run business specializes in plaster, drywall, steel stud framing, and acoustic ceiling contracting services across Greater Vancouver. With four generations of experience, Turner Bros. is well-equipped to handle both commercial and large residential building projects.</p> <p>The company provides comprehensive drywall services that ensure durability and aesthetic appeal. Steel stud framing is another area of expertise, offering strength and stability for various construction needs. Acoustic ceiling installations enhance sound quality and provide a polished finish to commercial spaces. Turner Bros. Contractors Ltd is committed to quality workmanship, evident in their membership with the British Columbia Association of Wall and Ceiling Contractors and the NW Wall and Ceiling Bureau.</p> <p>Turner Bros. emphasizes customer satisfaction and community involvement, reflecting their dedication to local projects. Their extensive experience in commercial infrastructure contracting positions them as a trusted choice for contractors in the region. The company’s reputation is built on reliability and professionalism, making them a preferred partner for construction projects in Surrey.</p> <p>Turner Bros Contractors Ltd offers a range of services that cater to the needs of the community, showcasing their commitment to quality and expertise. Engage with this longstanding local business for expert contracting services in Surrey, British Columbia.',
  '17750 65A Ave #313',
  'Canada',
  'BC',
  'Surrey',
  'V3S 5N4',
  'kinbencollective@gmail.com',
  'canada/surrey/home-services/turner-bros-contractors-ltd',
  'ChIJ02k5N2bPhVQRHgdbY8giC0Q',
  49.1200094,
  -122.7304959,
  '16045321991',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  756,
  'https://www.turnerbros.ca/?utm_source=GMBlisting&utm_medium=organic',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Kinben Collective',
  '<p>Kinben Collective operates as a general contractor in Etobicoke, Ontario, specializing in residential renovations and commercial architecture. This Toronto-based company features a team of skilled tradesmen dedicated to delivering architectural and construction projects with exceptional craftsmanship. Kinben Collective emphasizes innovative service and solutions, ensuring that each project meets the unique needs of clients.</p><p>The company''s approach combines expertise with a commitment to quality. Kinben Collective undertakes various projects, from small home improvements to large-scale commercial builds. Every renovation or construction project reflects the company''s focus on detail and customer satisfaction. The skilled tradesmen at Kinben Collective utilize their extensive experience to tackle challenges effectively, ensuring timely completion without compromising quality.</p><p>Kinben Collective has built a reputation for reliability and excellence in the local construction industry. Each project showcases their dedication to superb craftsmanship and innovative solutions. The team collaborates closely with clients, ensuring that visions are realized through thoughtful planning and execution. This commitment to service has earned the company respect and trust among homeowners and business owners alike.</p><p>Kinben Collective offers a comprehensive range of general contracting services in Etobicoke, Ontario. Their strengths lie in skilled craftsmanship, innovative solutions, and a customer-focused approach. For quality renovations and commercial architecture, contact Kinben Collective at 234 Albion Rd, Etobicoke, Ontario, M9W 6A5.</p>',
  '234 Albion Rd',
  'Canada',
  'ON',
  'Etobicoke',
  'M9W 6A5',
  'admin@systematic.bc.ca',
  'canada/etobicoke/home-services/kinben-collective',
  'ChIJX81iBEwxK4gRPydO-CBlG_Q',
  43.7211304,
  -79.5441808,
  '16472216323',
  'https://www.kwikr.ca/pictures/profile/pimage-751.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  755,
  'http://kinbencollective.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Systematic Mill Installations Ltd',
  '<p>Systematic Mill Installations Ltd, located at 1226 St Paul St in Kelowna, British Columbia, specializes in general contracting services tailored for the heavy industrial sector. Since 1988, this firm has built a reputation for delivering quality construction solutions through consultation, project management, and technical services. The experienced team at Systematic Mill Installations Ltd focuses on innovative and cost-effective strategies that meet diverse project needs across North America.</p><p>This company thrives on its ability to adapt to unique project requirements, regardless of size or complexity. The combination of skilled trades and project management expertise allows Systematic to tackle various challenges efficiently. The firm emphasizes collaboration, ensuring that every project aligns with client specifications and industry standards. The commitment to quality and innovation has made Systematic a trusted partner in the construction industry.</p><p>Systematic Mill Installations Ltd continues to serve the heavy industrial sector with a strong focus on delivering results that exceed expectations. The firm’s extensive experience and proactive approach enable it to handle projects with precision and care. The dedication to client satisfaction remains a core value, fostering long-term relationships within the industry.</p><p>Systematic Mill Installations Ltd offers comprehensive general contracting services, ensuring quality and innovation in every project. Reach out to Systematic Mill Installations Ltd in Kelowna for expert construction solutions tailored to specific needs.</p>',
  '1226 St Paul St',
  'Canada',
  'BC',
  'Kelowna',
  'V1Y 2C8',
  'llavigne@jcb.ca',
  'canada/kelowna/home-services/systematic-mill-installations-ltd',
  'ChIJJ41BwabyfVMRP_A7_xbXoz0',
  49.8931948,
  -119.4923454,
  '12364204041',
  'https://www.kwikr.ca/pictures/profile/pimage-750.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  754,
  'http://www.systematic.bc.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'JCB Construction Canada',
  '<p>JCB Construction Canada excels as a general contractor, serving the Brossard area of Quebec. The company specializes in managing and executing major construction projects, delivering quality expansions, renovations, redevelopments, and new builds. With a strong focus on industrial, commercial, multi-residential, and institutional sectors, JCB Construction Canada has established itself as a reliable partner for various clients.</p><p>With a dedicated team of over a hundred skilled employees, JCB Construction Canada successfully completes dozens of projects each year. The firm operates in the greater Montreal and Toronto areas, showcasing its capacity to handle diverse construction needs. Each project reflects the company''s commitment to quality and client satisfaction, ensuring that all construction goals are met efficiently and effectively.</p><p>JCB Construction Canada demonstrates a deep understanding of the complexities involved in construction management. The team prioritizes clear communication and collaboration with clients, fostering strong relationships that enhance project outcomes. This approach has led to numerous successful projects across various sectors, establishing a reputation for excellence in the construction industry.</p><p>Specializing in a wide range of construction services, JCB Construction Canada combines expertise with dedication. The company’s strong track record highlights its ability to raise ambitions off the ground. Connect with JCB Construction Canada at 3875 Rue Isabelle, Brossard, Quebec, for exceptional general contracting services.',
  '3875 Rue Isabelle',
  'Canada',
  'QC',
  'Brossard',
  'J4Y 2R2',
  'info@norcope.com',
  'canada/brossard/home-services/jcb-construction-canada',
  'ChIJ2SGQzx4PyUwR7nO05iok8wU',
  45.4273872,
  -73.4674633,
  '14504448151',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  753,
  'http://www.jcb.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Norcope Enterprises',
  '<p>Norcope Enterprises, located at 66 River Ridge Lane in Whitehorse, Yukon, specializes in general contracting services. This local business excels in providing comprehensive construction solutions, including residential and commercial projects. With a commitment to quality and customer satisfaction, Norcope Enterprises has built a reputation for reliability and professionalism in the Yukon area.</p><p>The team at Norcope Enterprises brings extensive experience to each project, ensuring that clients receive top-notch service from start to finish. This general contractor focuses on delivering tailored solutions that meet the specific needs of every customer. From new builds to renovations, the skilled professionals handle various aspects of construction with precision and care.</p><p>Norcope Enterprises emphasizes the importance of using quality materials and innovative techniques. This approach not only guarantees durability but also enhances the overall aesthetic of each project. The company’s dedication to excellence is evident in its portfolio, showcasing successful projects that reflect the unique vision of its clients.</p><p>Clients in Whitehorse benefit from the expertise and attention to detail that Norcope Enterprises offers. With a strong focus on communication and transparency, the company ensures that all stakeholders are informed throughout the construction process. This commitment to service contributes to high levels of client satisfaction and repeat business.</p><p>Norcope Enterprises provides exceptional general contracting services in Whitehorse, Yukon, backed by a strong reputation for quality and professionalism. Connect with Norcope Enterprises for reliable construction services in the Yukon area.',
  '66 River Ridge Lane',
  'Canada',
  'YT',
  'Whitehorse',
  'Y1A 6J9',
  'techsupport@richtek.ca',
  'canada/whitehorse/home-services/norcope-enterprises',
  'ChIJd9KQFn1DVFERJ28wbW6QHso',
  60.7575166,
  -135.0860337,
  '18676685857',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  752,
  'http://norcope.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Richtek Industries',
  '<p>Richtek Industries operates as a general contractor in Abbotsford, British Columbia, specializing in a variety of construction services. This local business has built a reputation for quality workmanship and reliability. Richtek Industries handles both residential and commercial projects, ensuring clients receive tailored solutions that meet their specific needs.</p> <p>The company emphasizes a commitment to excellence, with a focus on timely project completion and customer satisfaction. Richtek Industries employs skilled professionals who bring extensive experience to each job. This dedication to quality has led to numerous successful projects across the region, showcasing the company''s ability to manage complex construction tasks efficiently.</p> <p>Richtek Industries also prioritizes sustainable building practices, integrating eco-friendly materials and methods into their projects. This approach not only benefits the environment but also enhances the longevity and efficiency of the structures they create. The team conducts thorough planning and execution, ensuring that all aspects of the construction process align with client expectations.</p> <p>With a solid track record in the industry, Richtek Industries continues to deliver exceptional general contracting services in Abbotsford. Their focus on quality, sustainability, and customer satisfaction sets them apart in the competitive construction market. Engage with Richtek Industries for reliable construction solutions in Abbotsford, British Columbia.</p>',
  '31265 Wheel Ave',
  'Canada',
  'BC',
  'Abbotsford',
  'V2T 6H2',
  'info@domain.ltd',
  'canada/abbotsford/home-services/richtek-industries',
  'ChIJ06qgS8LKhVQRO1CoUoP2yBY',
  49.0439472,
  -122.3579493,
  '16045570008',
  NULL,
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  751,
  'http://www.richtek.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Gypsum Drywall Interiors Ltd',
  '<p>Gypsum Drywall Interiors Ltd, located in Oak Bluff, Manitoba, serves as a reliable general contractor specializing in commercial, multi-family, and residential construction. With over 20 years of experience, GDI has established strong relationships with the largest and most professional contractors and home builders across Manitoba. The company operates under a COR safety program, emphasizing safety as its top priority.</p><p>GDI''s expertise extends beyond Oak Bluff, covering a wide geographical area that includes Thunder Bay, Ontario, and stretches to Saskatchewan and Alberta. The team consists of five principals and a dedicated office staff of 21, supported by an average workforce of over 100 skilled tradespeople. This robust structure enables GDI to manage projects efficiently while maintaining high standards of quality and safety.</p><p>The commitment to excellence and safety has driven GDI''s continuous growth and success in the construction industry. Clients benefit from the company''s extensive experience and professionalism, ensuring that projects are completed on time and within budget. GDI’s reputation for reliability and quality work has made it a preferred choice among contractors and builders in Manitoba.</p><p>Gypsum Drywall Interiors Ltd offers comprehensive general contracting services, prioritizing safety and quality. With a strong workforce and over two decades of experience, GDI remains a trusted partner in the construction industry. Contact Gypsum Drywall Interiors Ltd in Oak Bluff for exceptional service and expertise in general contracting.</p>',
  '17 S Landing Dr',
  'Canada',
  'MB',
  'Oak Bluff',
  'R4G 0C4',
  'emresponse@bltconstruction.com',
  'canada/oak-bluff/home-services/gypsum-drywall-interiors-ltd',
  'ChIJiQdH1Qx16lIRlW4YqdcmZEU',
  49.807583,
  -97.2461307,
  '12046618899',
  'https://www.kwikr.ca/pictures/profile/pimage-746.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  750,
  'http://www.gdi.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'BLT Construction Services',
  '<p>BLT Construction Services operates as a premier general contractor in Vancouver, British Columbia. This company excels in delivering high-quality construction solutions tailored to meet diverse client needs. With a strong focus on residential and commercial projects, BLT Construction Services has built a reputation for reliability and excellence in the local area.</p> <p>The team at BLT Construction Services comprises skilled professionals dedicated to ensuring each project is completed on time and within budget. Extensive experience in the construction industry allows the company to handle various tasks, from renovations to new builds. Clients appreciate the attention to detail and commitment to quality that BLT Construction Services brings to every project.</p><p>BLT Construction Services prioritizes customer satisfaction and maintains open communication throughout the construction process. This approach fosters trust and collaboration, which are essential for successful project completion. The company’s portfolio showcases a range of successful projects, highlighting its versatility and expertise in the field.</p><p>BLT Construction Services offers comprehensive construction services that cater to both residential and commercial sectors. The commitment to quality, reliability, and customer satisfaction sets this company apart in Vancouver. For those seeking a dependable general contractor, reach out to BLT Construction Services at their Vancouver location. </p>',
  '89 W Georgia St #901',
  'Canada',
  'BC',
  'Vancouver',
  'V6B 0N8',
  'info@dandrskylightinstallations.ca',
  'canada/vancouver/home-services/blt-construction-services',
  'ChIJHTcAc3hxhlQRAloN9bcau1g',
  49.2777179,
  -123.1097563,
  '16045632505',
  'https://www.kwikr.ca/pictures/profile/pimage-745.jpg',
  'Reno Contractors=>General Contracting',
  'Growth Plan',
  749,
  'http://www.bltconstruction.com/',
  NULL,
  NULL,
  NULL,
  NULL
);
