INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Lambs Window Cleaning',
  '<p>Lambs Window Cleaning provides exceptional window cleaning services in Winnipeg, Manitoba. This local business specializes in residential and commercial window cleaning, ensuring clear views and enhanced curb appeal. With a commitment to quality, Lambs Window Cleaning has built a reputation for reliability and professionalism in the community.</p><p>The team at Lambs Window Cleaning employs advanced techniques and eco-friendly products to deliver outstanding results. Each service is tailored to meet the specific needs of clients, whether for a single-family home or a large commercial building. The skilled professionals focus on attention to detail, guaranteeing streak-free finishes and sparkling windows. Customer satisfaction remains a top priority, and the business consistently receives positive feedback for its efficient service and friendly staff.</p><p>Lambs Window Cleaning operates in Winnipeg and surrounding areas, catering to both residential and commercial clients. The company understands the local climate and its impact on window maintenance. Regular cleaning not only improves the aesthetics of properties but also extends the lifespan of windows. The team is dedicated to providing a safe and effective cleaning experience, utilizing the latest equipment and techniques.</p><p>Lambs Window Cleaning offers reliable window cleaning solutions, emphasizing quality and customer satisfaction. The business excels in maintaining clear, clean windows that enhance property appearance. For exceptional window cleaning services in Winnipeg, connect with Lambs Window Cleaning at 211 Marygrove Crescent, Manitoba.',
  '211 Marygrove Crescent',
  'Canada',
  'MB',
  'Winnipeg',
  'R3Y 1M4',
  'wildrosegardeners@gmail.com',
  'canada/winnipeg/home-services/lambs-window-cleaning',
  'ChIJnQfOgIZz6lIRxypSGRTdTWg',
  49.8177271,
  -97.2029471,
  '12042262046',
  NULL,
  'Cleaning Services=>Window Cleaning',
  'Pay-as-you-go',
  173,
  'http://lambswindowcleaning.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Tinman Group',
  '<p>Tinman Group provides exceptional window cleaning services along with a range of outdoor maintenance solutions in Red Deer, Alberta. This local business specializes in window cleaning, pressure washing, yard care, snow removal, fence building, and deck building. Tinman Group has earned a reputation for delivering reliable and efficient services tailored to meet the needs of both residential and commercial clients.</p><p>The focus on quality and customer satisfaction sets Tinman Group apart in the competitive landscape of home maintenance services. The experienced team utilizes advanced techniques and equipment to ensure sparkling clean windows and well-maintained outdoor spaces. Clients appreciate the attention to detail and commitment to excellence that Tinman Group consistently demonstrates.</p><p>In addition to window cleaning, Tinman Group offers comprehensive pressure washing services that effectively remove dirt and grime from various surfaces. The yard care services help maintain lush and healthy landscapes, while snow removal ensures safe access during winter months. The skilled craftsmen at Tinman Group also excel in building durable fences and decks, enhancing outdoor living spaces.</p><p>Tinman Group combines a wide range of services with a strong dedication to quality and customer care. The business continues to grow within the Red Deer community, establishing itself as a trusted partner for home and business maintenance. Reach out to Tinman Group for reliable window cleaning and more in Red Deer, Alberta.</p>',
  '7660 76 Street Close Bay 120',
  'Canada',
  'AB',
  'Red Deer',
  'T4P 4G6',
  'jenny.anne.cook@gmail.com',
  'canada/red-deer/home-services/tinman-group',
  'ChIJGS73C3xVdFMROBL8a42Z98E',
  52.30474,
  -113.848889,
  '14035887158',
  NULL,
  'Cleaning Services=>Window Cleaning',
  'Pay-as-you-go',
  172,
  'https://tinmangroup.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Rembourrage D''Autos Longueuil Inc',
  '<p>Rembourrage D''Autos Longueuil Inc offers expert upholstery cleaning services in Longueuil, Quebec. Established 26 years ago, this business has built a reputation for excellence in the upholstery industry, particularly in the Montreal area. With over 40 years of experience, the founder leads a meticulous team dedicated to high-quality service.</p> <p>This company specializes in cleaning and restoring upholstery for modern vehicles, regardless of brand or model. Rembourrage D''Autos Longueuil Inc effectively handles even the most complex upholstery projects. The team''s expertise extends to luxury European cars, ensuring that every vehicle receives the specialized care it deserves. Customer satisfaction remains a top priority, and the attention to detail sets this business apart from competitors.</p> <p>Rembourrage D''Autos Longueuil Inc has consistently demonstrated a commitment to quality and professionalism. Their extensive experience in the upholstery cleaning industry allows them to tackle diverse challenges with confidence. The company’s strong track record and dedication to excellence make it a go-to choice for residents in Longueuil seeking reliable upholstery services.</p> <p>Rembourrage D''Autos Longueuil Inc excels in providing high-quality upholstery cleaning services tailored to the needs of modern vehicles. The company''s experience and dedication to customer satisfaction highlight its strengths in the industry. Reach out to Rembourrage D''Autos Longueuil Inc for exceptional upholstery services in Longueuil, Quebec.</p>',
  '2520, Chemin Du Lac',
  'Canada',
  'QC',
  'Longueuil',
  'J4N 1G7',
  'rebecca@tranquilitygardendesign.com',
  'canada/longueuil/home-services/rembourrage-d-autos-longueuil-inc',
  'ChIJcSUrQTIDyUwRIVp2q9PS2b8',
  45.5653518,
  -73.456271,
  '14506790330',
  NULL,
  'Cleaning Services=>Upholstery Cleaning',
  'Pay-as-you-go',
  171,
  'https://rembourrageautomobile.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Hallmark Housekeeping Services Inc - Ottawa Branch',
  '<p>Hallmark Housekeeping Services Inc., located at 1655 Russell Rd in Ottawa, Ontario, offers comprehensive commercial cleaning services tailored to meet the needs of various businesses. Established in 1977, this 100% Canadian owned company emphasizes environmentally friendly practices and innovative solutions. Hallmark has built a reputation as Canada’s premium janitorial service partner, serving a diverse range of facilities across the nation.</p> <p>The team at Hallmark Housekeeping Services Inc. brings extensive expertise to the commercial cleaning industry. Utilizing advanced cleaning techniques and eco-friendly products, they ensure that workplaces remain clean, safe, and healthy. The company caters to various sectors, including offices, educational institutions, and healthcare facilities. Commitment to quality and sustainability sets Hallmark apart in the competitive cleaning market.</p> <p>Clients appreciate Hallmark''s attention to detail and dedication to customer satisfaction. The company’s trained staff undergoes rigorous training, ensuring high standards are met consistently. With a focus on environmental responsibility, Hallmark minimizes its ecological footprint while delivering top-notch cleaning services. Their innovative approach to janitorial services enhances the overall cleanliness and hygiene of work environments.</p> <p>Hallmark Housekeeping Services Inc. provides reliable commercial cleaning solutions that prioritize health and sustainability. Their long-standing experience and commitment to excellence make them a trusted partner for businesses in Ottawa. Connect with Hallmark Housekeeping Services Inc. for professional cleaning services in Ottawa, Ontario.</p>',
  '1655 Russell Rd',
  'Canada',
  'ON',
  'Ottawa',
  'K1G 0N1',
  'colin.maybee@maybeebrothers.com',
  'canada/ottawa/home-services/hallmark-housekeeping-services-inc-ottawa-branch',
  'ChIJpeEXB3EPzkwR5E-FpQvI4fY',
  45.40755,
  -75.635531,
  '16132476000',
  'https://www.kwikr.ca/pictures/profile/pimage-154.jpg',
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  170,
  'https://hallmarkhousekeeping.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Nettoyages E.L.V.I.S. - entretien ménager résidentiel & commercial',
  '<p>Nettoyages E.L.V.I.S. offers comprehensive residential and commercial cleaning services in St-Bruno-de-Montarville, Quebec. Since 2008, this dedicated team has provided exceptional cleaning solutions to clients on the South Shore of Montreal. The company specializes in regular cleaning, deep cleaning, post-construction cleanups, carpet cleaning, window washing, mattress cleaning, and maintenance of common areas in condominiums and apartment buildings.</p> <p>The expertise of Nettoyages E.L.V.I.S. lies in delivering efficient, reliable, and meticulous cleaning services tailored to meet diverse client needs. The professional staff ensures that every task is completed to the highest standards, making homes and businesses shine. Each cleaning session is approached with a commitment to quality and customer satisfaction, reinforcing the company''s reputation in the local community.</p> <p>With a focus on both residential and commercial spaces, Nettoyages E.L.V.I.S. understands the importance of a clean environment. The team utilizes effective cleaning techniques and eco-friendly products to ensure safety and health for all clients. The company’s long-standing presence in the area highlights its dedication to service excellence and community trust.</p> <p>Nettoyages E.L.V.I.S. provides a wide range of cleaning services, showcasing a commitment to quality and professionalism. Connect with Nettoyages E.L.V.I.S. at 50 Chem. de la Rabastalière O, St-Bruno-de-Montarville for reliable cleaning solutions.</p>',
  '50 Chem. de la Rabastalière O',
  'Canada',
  'QC',
  'St-Bruno-de-Montarville',
  'J3V 1Y8',
  'info@precisionlandscaping.ca',
  'canada/st-bruno-de-montarville/home-services/nettoyages-e-l-v-i-s-entretien-ménager-résidentiel-commercial',
  'ChIJUTPHFI0ByUwRztlA74rATZw',
  45.5264853,
  -73.3425646,
  '15144341957',
  'https://www.kwikr.ca/pictures/profile/pimage-153.jpg',
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  169,
  'http://www.nettoyageselvis.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'The Climatic Group Inc.',
  '<p>The Climatic Group Inc., located at 62 Mcbrine Pl #9, Kitchener, Ontario, offers top-tier commercial cleaning services. Established in 1987, this company has built a reputation for delivering exceptional service quality to local businesses. The Climatic Group specializes in maintaining cleanliness and hygiene standards that meet the needs of various industries.</p><p>This commercial maintenance service focuses on high-quality cleaning solutions tailored to businesses. The team at The Climatic Group understands the importance of a clean environment for productivity and health. They implement effective cleaning strategies that not only meet but exceed client expectations. With decades of experience, this company has honed its skills to provide reliable and efficient services.</p><p>The Climatic Group emphasizes low expenses for customers without compromising service quality. Their commitment to maintaining high standards ensures that businesses can rely on them for consistent results. This dedication to excellence has fostered long-lasting relationships with clients in the Kitchener area.</p><p>With a strong focus on the needs of local businesses, The Climatic Group provides comprehensive commercial cleaning solutions. Their experienced professionals ensure that every corner of a facility is spotless and well-maintained. Trust in their expertise to elevate cleanliness standards in any workspace. Connect with The Climatic Group in Kitchener for reliable commercial cleaning services.</p>',
  '62 Mcbrine Pl #9',
  'Canada',
  'ON',
  'Kitchener',
  'N2R 1H3',
  'info@ecologicallandscaping.ca',
  'canada/kitchener/home-services/the-climatic-group-inc',
  'ChIJzUMBU131K4gRxchLmzZhmXs',
  43.40164,
  -80.47716,
  '15195700405',
  'https://www.kwikr.ca/pictures/profile/pimage-152.jpg',
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  168,
  'http://www.climaticgroup.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Signature Cleaning Services',
  '<p>Signature Cleaning Services delivers exceptional commercial cleaning solutions in Winnipeg, Manitoba. This woman-owned business has over twenty years of experience, utilizing the Signature Wash-Dry-Shine cleaning method to ensure spaces shine. The company specializes in a variety of cleaning services, including commercial office cleaning, house cleaning, post-construction cleaning, and move-out or move-in cleaning. Signature Cleaning Services operates in areas such as Headingley, Narol, West St. Paul, St. Andrews, River Heights, Tuxedo, Lindenwoods, and East St. Paul.</p> <p>The team consists of insured, experienced, skilled, and bonded cleaners committed to providing quality service. Each cleaning project receives meticulous attention to detail, ensuring satisfaction for every client. The company emphasizes reliability and thoroughness, making it a preferred choice for both residential and commercial cleaning needs. Clients can expect a consistent approach that prioritizes cleanliness and hygiene.</p> <p>Signature Cleaning Services has built a strong reputation over the years, focusing on delivering results that meet and exceed expectations. The dedication to the community and the environment is evident in their cleaning practices. This commitment to quality and care sets the company apart in the competitive cleaning industry.</p> <p>Signature Cleaning Services offers a range of cleaning services tailored to various needs, ensuring spaces remain pristine. The skilled team guarantees satisfaction with every job. Reach out to Signature Cleaning Services at 215 Oakland Ave, Winnipeg, Manitoba, for professional cleaning services that make a difference.</p>',
  '215 Oakland Ave',
  'Canada',
  'MB',
  'Winnipeg',
  'R2G 0A7',
  'info@spruced-up.ca',
  'canada/winnipeg/home-services/signature-cleaning-services',
  'ChIJWVmWm_Bt6lIR_1y8c1FZnwA',
  49.9373218,
  -97.0916716,
  '12047793600',
  'https://www.kwikr.ca/pictures/profile/pimage-151.jpg',
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  167,
  'https://signaturecleaning.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Double Clean Restoration Company in Vancouver',
  '<p>Double Clean Restoration Company, located in Burnaby, British Columbia, offers comprehensive commercial cleaning services specializing in water, mould, and fire damage restoration. This professional restoration company prioritizes efficiency and customer satisfaction, making it a reliable choice for businesses facing challenging disasters.</p> <p>With a focus on restoring properties to their original condition, Double Clean Restoration utilizes state-of-the-art equipment and techniques. The team is trained to handle various restoration scenarios, ensuring that each job is completed effectively and promptly. Strong relationships with insurance providers streamline the claims process, allowing businesses to recover without unnecessary delays.</p> <p>Double Clean Restoration Company understands the impact of disasters on operations and employee morale. Their commitment to quality service helps minimize downtime and supports businesses in getting back on their feet. The team’s expertise in dealing with water, mould, and fire damage sets them apart in the commercial cleaning sector.</p> <p>Recognized for their professionalism and reliability, Double Clean Restoration has built a reputation for excellence in Burnaby and surrounding areas. They effectively address the unique challenges posed by restoration projects, ensuring peace of mind for clients. Services include thorough assessments, efficient clean-up, and restoration work tailored to specific needs.</p> <p>Double Clean Restoration Company provides essential commercial cleaning and restoration services with a focus on quality and efficiency. Their expertise in handling water, mould, and fire damage ensures that businesses can recover swiftly. Connect with Double Clean Restoration Company in Burnaby for reliable restoration services.</p>',
  '7228 Winston St #14',
  'Canada',
  'BC',
  'Burnaby',
  'V5A 2G9',
  'info@jsslighting.ca',
  'canada/burnaby/home-services/double-clean-restoration-company-in-vancouver',
  'ChIJgfcZyuR3hlQRuEBvv0q6208',
  49.2493023,
  -122.9532214,
  '18886343939',
  'https://www.kwikr.ca/pictures/profile/pimage-150.jpg',
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  166,
  'https://doublecleanrestoration.ca/locations/vancouver-bc/?utm_source=google&utm_medium=gbp&utm_campaign=vancouver',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Riteway Filter Cleaning and Supply',
  '<p>Riteway Filter Cleaning and Supply, located in Erin, Ontario, has been a trusted provider of commercial cleaning services since 1988. This business excels in filter cleaning, serving the needs of both large and small clients across Southern Ontario. Riteway offers a comprehensive range of services, including pickup and delivery, ensuring convenience and efficiency for all customers.</p><p>The company specializes in cleaning filters for heavy equipment and dust collectors. Maintaining clean filters is essential for improving operational efficiency and minimizing downtime. Riteway Filter Cleaning and Supply understands the importance of high-quality service and is committed to delivering superior results for every client. With decades of experience, the team possesses the expertise to handle various filter cleaning needs effectively.</p><p>Riteway Filter Cleaning and Supply prioritizes customer satisfaction, providing reliable and efficient services tailored to individual requirements. The commitment to quality and attention to detail makes this company a preferred choice for commercial cleaning in the region. Clients appreciate the convenience of pickup and delivery, allowing for seamless service without disrupting daily operations.</p><p>Riteway Filter Cleaning and Supply offers essential services to keep filters clean and operational. The dedication to quality service and customer care enhances business efficiency. Connect with Riteway Filter Cleaning and Supply in Erin, Ontario, for all filter cleaning needs.</p>',
  '9646 Side Rd 10',
  'Canada',
  'ON',
  'Erin',
  'N0B 1T0',
  'info@earth-elements.ca',
  'canada/erin/home-services/riteway-filter-cleaning-and-supply',
  'ChIJa_eZE18JK4gRfppkpLyrmaY',
  43.7604447,
  -80.038276,
  '14165743828',
  'https://www.kwikr.ca/pictures/profile/pimage-149.jpg',
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  165,
  'http://www.filtercleaning.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'RONDEAUNET Services aux Immeubles',
  '<p>RONDEAUNET Services aux Immeubles offers comprehensive commercial cleaning services in Saint-Hubert, Quebec. This business has established high standards of quality through well-defined procedures and policies. Clients can expect exceptional satisfaction, regardless of the cleaning task at hand. RONDEAUNET Inc. emphasizes reliability and thoroughness in every job, ensuring a clean and hygienic environment for businesses.</p> <p>The commercial cleaning sector demands precision and attention to detail. RONDEAUNET excels in this area by implementing rigorous quality control measures. The team utilizes advanced cleaning techniques and eco-friendly products to ensure a safe environment for employees and customers alike. Regular training for staff guarantees adherence to the highest industry standards, making RONDEAUNET a trustworthy partner for businesses in need of cleaning services.</p> <p>Client testimonials highlight the company’s commitment to exceeding expectations. Many local businesses in Saint-Hubert have praised the responsive and professional approach of RONDEAUNET. The company’s dedication to customer service fosters long-term relationships and repeat business. This focus on quality and client satisfaction sets RONDEAUNET apart from competitors.</p> <p>RONDEAUNET Services aux Immeubles provides reliable commercial cleaning solutions tailored to meet diverse needs. With a strong reputation in Saint-Hubert, the company prioritizes quality and customer satisfaction. Engage with RONDEAUNET for exceptional cleaning services in Quebec.',
  '3928 Blvd. Sir-Wilfrid-Laurier local C',
  'Canada',
  'QC',
  'Saint-Hubert',
  'J3L 6T1',
  'info@moonstruck.ca',
  'canada/saint-hubert/home-services/rondeaunet-services-aux-immeubles',
  'ChIJzTr5mYoayUwR1jge47M1Css',
  45.5063307,
  -73.4473554,
  '15142842777',
  'https://www.kwikr.ca/pictures/profile/pimage-148.jpg',
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  164,
  'http://www.rondeaunet.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Gold Environmental Products Inc',
  '<p>Gold Environmental Products Inc provides essential commercial cleaning services in Barrie, Ontario. This business specializes in innovative in-situ technologies designed to decontaminate soil and water from harmful pollutants like oil and gasoline. The commitment to environmental protection highlights the importance of sustainable practices in the cleaning industry.</p> <p>Located at 2207 Penetanguishene Rd, Gold Environmental Products Inc focuses on delivering effective solutions that address industrial contamination. The company utilizes advanced technologies to ensure that the surrounding environment is safeguarded. With a strong emphasis on eco-friendly products, the services offered align with the growing demand for sustainable cleaning methods.</p> <p>The team at Gold Environmental Products Inc demonstrates expertise in managing complex cleaning challenges. Their approach not only targets immediate contamination issues but also contributes to long-term environmental health. This proactive strategy underlines the importance of responsible cleaning practices in commercial settings.</p> <p>Gold Environmental Products Inc stands out in Barrie for its dedication to environmental stewardship and effective cleaning solutions. The combination of specialized knowledge and commitment to sustainability positions the company as a leader in the commercial cleaning sector. Businesses seeking to enhance their environmental impact should consider the services offered by this local expert. Connect with Gold Environmental Products Inc in Barrie for reliable and eco-conscious cleaning services.</p>',
  '2207 Penetanguishene Rd',
  'Canada',
  'ON',
  'Barrie',
  'L4M 4Y8',
  'info@newagaincleaning.com',
  'canada/barrie/home-services/gold-environmental-products-inc',
  'ChIJvSqQJ1WgKogR0rfPZmPkkm8',
  44.5028341,
  -79.702196,
  '17057920418',
  NULL,
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  163,
  'http://www.goldenenviro.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'ServiceMaster of Ottawa',
  '<p>ServiceMaster of Ottawa provides comprehensive commercial cleaning services and emergency disaster restoration in Ottawa, Ontario. This business specializes in 24/7 emergency response for fire and flood damage, ensuring timely and effective recovery. The range of services includes office cleaning, carpet cleaning, tile and grout cleaning, and upholstery cleaning, catering to both residential and commercial needs.</p><p>With a commitment to quality and reliability, ServiceMaster of Ottawa has established itself as a trusted provider in the local community. The team employs advanced techniques and equipment to deliver exceptional results. The focus remains on customer satisfaction, ensuring that every cleaning task meets high standards. This dedication to excellence has earned the business a solid reputation among clients in the Ottawa area.</p><p>The 24/7 availability for emergency services sets ServiceMaster of Ottawa apart from competitors. Quick response times and effective solutions for disaster recovery help minimize damage and restore properties efficiently. The professional staff is trained to handle various cleaning challenges, making them a valuable resource for businesses and homeowners alike.</p><p>ServiceMaster of Ottawa excels in offering reliable cleaning and restoration services. The combination of expertise, prompt service, and a broad range of solutions makes this company a go-to choice in Ottawa. Contact ServiceMaster of Ottawa at 180 Wescar Ln for expert cleaning and restoration services in Ontario.</p>',
  '180 Wescar Ln',
  'Canada',
  'ON',
  'Ottawa',
  'K0A 1L0',
  'info@lightsupalberta.com',
  'canada/ottawa/home-services/servicemaster-of-ottawa',
  'ChIJbY6WTH8PzkwRIpRgpvSOj1A',
  45.2938585,
  -75.9819599,
  '16136996775',
  NULL,
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  162,
  'http://svmottawa.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'CityPro Parkade',
  '<p>CityPro Parkade provides exceptional commercial cleaning services in Calgary, Alberta. Specializing in parking lot maintenance, this business offers a comprehensive range of services, including parking lot line painting, sweeping, power washing, and power scrubbing. CityPro Parkade has built a reputation for precision and reliability in the industry.</p> <p>With years of experience, CityPro Parkade understands the importance of a clean and well-maintained parking facility. The team employs advanced techniques and equipment to ensure every project meets high standards. Parking lots often serve as the first impression for customers, and maintaining cleanliness reflects positively on businesses. The services offered by CityPro Parkade enhance not only the appearance but also the safety of parking areas.</p> <p>The commitment to customer satisfaction drives CityPro Parkade to deliver unmatched quality. Each service is tailored to meet the specific needs of clients, ensuring that every parking lot looks its best. The expertise in parking lot line painting guarantees clear and precise markings, while thorough sweeping and power washing restore the cleanliness that enhances customer experience.</p> <p>CityPro Parkade excels in providing reliable and efficient cleaning solutions for parking lots in Calgary. The dedication to quality and customer satisfaction sets the company apart in the commercial cleaning service sector. Engage with CityPro Parkade for professional parking lot maintenance services in Calgary, Alberta.</p>',
  '4950 106 Ave SE #133',
  'Canada',
  'AB',
  'Calgary',
  'T2C 5E9',
  'abbalandscaping1@gmail.com',
  'canada/calgary/home-services/citypro-parkade',
  'ChIJD_TLPeF5cVMRp91g5DVkz94',
  50.958376,
  -113.964243,
  '14036064545',
  NULL,
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  161,
  'https://cityproparkade.ca/?utm_source=Google&utm_medium=GMB_Calgary',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'First General Niagara Inc.',
  '<p>First General Niagara Inc. offers essential commercial cleaning services in St. Catharines, Ontario, and the surrounding Niagara region, from Grimsby to Fort Erie. This company specializes in damage mitigation, addressing issues from water, fire, wind, theft, and vandalism. With a strong focus on mold and biohazardous remediation, First General Niagara ensures a comprehensive approach to cleaning and restoring properties.</p><p>The business operates 24/7, providing emergency services to respond promptly to urgent situations. Clients benefit from pre-claim inspections, which help clarify the next steps in the claims process. This proactive service minimizes stress and aids in making informed decisions during challenging times. First General Niagara''s commitment to quality and reliability sets it apart in the commercial cleaning sector.</p><p>With a dedicated team of experts, First General Niagara Inc. prioritizes customer satisfaction and efficient service delivery. The company’s extensive experience in the field ensures that all cleaning and remediation tasks are handled with professionalism and expertise. The focus remains on creating a safe and clean environment for all clients, regardless of the nature of the damage.</p><p>This local business excels in providing vital cleaning and restoration services, ensuring that clients can navigate their losses smoothly. Trust the experts at First General Niagara for effective and reliable service. Visit St. Catharines to engage with First General Niagara Inc. for all cleaning and damage mitigation needs.</p>',
  '29 Neilson Ave',
  'Canada',
  'ON',
  'St. Catharines',
  'L2M 5V9',
  'info@eclairageoasis.com',
  'canada/st-catharines/home-services/first-general-niagara-inc',
  'ChIJg056PolQ04kRbyRydhCeCQM',
  43.1733041,
  -79.21582,
  '19056874149',
  NULL,
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  160,
  'http://www.firstgeneralniagara.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Pinnacle Hygiene and Facility Services Ltd.',
  '<p>Pinnacle Hygiene and Facility Services Ltd. operates as a leading commercial cleaning service based in Port Coquitlam, British Columbia. This company specializes in providing comprehensive cleaning solutions for both commercial and industrial clients. With a commitment to maintaining high standards of customer service, Pinnacle Hygiene has established a strong presence in the Greater Vancouver and Lower Mainland areas. The focus remains on achieving exceptional customer retention and satisfaction.</p><p>This cleaning service excels in delivering tailored solutions that meet the unique needs of each client. The team utilizes advanced cleaning techniques and eco-friendly products, ensuring a safe and clean environment for businesses. Pinnacle Hygiene’s dedication to quality is evident in their meticulous attention to detail and consistent performance. Their services cover a wide range of cleaning tasks, making them a reliable partner for various commercial establishments.</p><p>Pinnacle Hygiene and Facility Services Ltd. prioritizes customer feedback and continuously seeks to improve their offerings. The company recognizes that its growth is directly linked to the satisfaction of its clients. By focusing on world-class customer service, Pinnacle Hygiene has built a reputation as a trusted cleaning provider in the region.</p><p>With a strong commitment to quality and customer care, Pinnacle Hygiene and Facility Services Ltd. stands ready to meet diverse cleaning needs. Consider this company for reliable commercial cleaning solutions in Port Coquitlam. Connect with Pinnacle Hygiene today for professional cleaning services that ensure a pristine environment.</p>',
  '1515 Broadway St #304',
  'Canada',
  'BC',
  'Port Coquitlam',
  'V3C 6M2',
  'hello@cypresslighting.ca',
  'canada/port-coquitlam/home-services/pinnacle-hygiene-and-facility-services-ltd',
  'ChIJ47HFZyF_hlQRHTyOHofSr-8',
  49.2411211,
  -122.7631933,
  '18884703555',
  NULL,
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  159,
  'https://www.pinnaclehygiene.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Pearl Cleaning Concepts INC.',
  '<p>Pearl Cleaning Concepts Inc. provides comprehensive commercial cleaning services in Mississauga, Ontario. This full-service cleaning company caters to both residential and industrial clients, ensuring top-quality cleaning solutions for properties of all sizes. Equipped with advanced tools and eco-friendly products, Pearl Cleaning Concepts prioritizes cleanliness and environmental responsibility.</p> <p>The team at Pearl Cleaning Concepts is dedicated to delivering exceptional cleaning standards. Each cleaner is trained to handle various cleaning tasks, from routine office maintenance to deep industrial cleaning. The use of non-toxic chemicals ensures a safe environment for employees and customers alike. This commitment to safety and quality has earned the company a strong reputation in the Greater Toronto Area.</p> <p.Customers appreciate the attention to detail and professionalism exhibited by the staff. The cleaning services are tailored to meet specific client needs, making it a versatile choice for businesses looking for reliable cleaning solutions. Pearl Cleaning Concepts understands the importance of maintaining a clean workspace, which directly impacts employee productivity and overall business image.</p> <p.Pearl Cleaning Concepts Inc. excels in providing reliable and efficient cleaning services. The focus on eco-friendly practices and customer satisfaction sets the company apart in the competitive cleaning industry. For top-tier commercial cleaning services in Mississauga, reach out to Pearl Cleaning Concepts Inc. at 6660 Kennedy Rd #201, Ontario, L5T 2M9.</p>',
  '6660 Kennedy Rd #201',
  'Canada',
  'ON',
  'Mississauga',
  'L5T 2M9',
  'info@concept72.ca',
  'canada/mississauga/home-services/pearl-cleaning-concepts-inc',
  'ChIJo7_OHCITK4gRgav_Y2hfQQk',
  43.6489019,
  -79.687307,
  '16479856622',
  NULL,
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  158,
  'http://pearlcleaninginc.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Clean Answers Janitorial Supplies Support',
  '<p>Clean Answers Janitorial Supplies Support offers comprehensive commercial cleaning services in Abbotsford, British Columbia. This business specializes in providing high-quality cleaning equipment and supplies tailored for various commercial environments. Noteworthy training programs and support for building service workers enhance the skills and efficiency of cleaning crews, ensuring they perform at their best.</p><p>The focus on equipping businesses with the right tools and techniques sets Clean Answers apart in the commercial cleaning sector. Clients benefit from a wide range of cleaning supplies that meet industry standards. The training programs empower cleaning staff, improving their effectiveness and job satisfaction. This commitment to quality service and support fosters a productive cleaning environment. Businesses in Abbotsford can rely on Clean Answers to deliver the necessary resources for maintaining cleanliness and hygiene in their spaces.</p><p>With a strong emphasis on customer satisfaction, Clean Answers Janitorial Supplies Support demonstrates expertise in the cleaning industry. The company’s dedication to providing top-notch products and training ensures that clients receive the best possible service. By prioritizing the needs of cleaning crews, this business contributes to a cleaner and healthier community in Abbotsford.</p><p>Clean Answers Janitorial Supplies Support offers essential cleaning supplies and training for building service workers, positioning itself as a reliable partner in the commercial cleaning industry. Reach out to Clean Answers in Abbotsford for quality cleaning solutions and support.</p>',
  '30550 Great Northern Ave Unit A',
  'Canada',
  'BC',
  'Abbotsford',
  'V2T 6H4',
  'info@lightright.ca',
  'canada/abbotsford/home-services/clean-answers-janitorial-supplies-support',
  'ChIJr2MZUbjKhVQRSj7BcDMN9VU',
  49.0506074,
  -122.3773001,
  '18006687833',
  NULL,
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  157,
  'http://www.cleananswers.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Cintas Facility Services',
  '<p>Cintas Facility Services, located at 255 Harry Walker Pkwy S in Newmarket, Ontario, specializes in commercial cleaning services that enhance business operations. This local enterprise offers a comprehensive range of solutions, including industrial-grade janitorial supplies, mat rental, restroom cleaning, and towel services. Cintas Newmarket provides tailored programs that adapt to specific client needs, ensuring efficient service delivery.</p><p>With a focus on quality and reliability, Cintas Facility Services helps businesses maintain cleanliness and hygiene. The company supplies essential items such as mops, aprons, and cleaning chemicals, while also managing inventory levels and dispenser installations. This proactive approach allows businesses to improve their image and reduce operational costs.</p><p>Cintas UltraClean services stand out by deep cleaning and sanitizing restrooms effectively. This service can significantly decrease daily maintenance cleanings by up to 66%. Such efficiency not only saves time but also enhances the overall workplace environment for employees and customers alike.</p><p>Cintas Facility Services excels in providing flexible and efficient cleaning solutions tailored to the unique needs of businesses in Newmarket. The commitment to quality and customer satisfaction is evident in every aspect of service delivery. To experience these benefits firsthand, connect with Cintas Facility Services in Newmarket today.</p>',
  '255 Harry Walker Pkwy S',
  'Canada',
  'ON',
  'Newmarket',
  'L3Y 7B3',
  'contactus.web@enercare.ca',
  'canada/newmarket/home-services/cintas-facility-services',
  'ChIJP2pz4YHSKogR7ZtfL4SNPFg',
  44.0592685,
  -79.4199256,
  '12893190494',
  NULL,
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  156,
  'https://www.cintas.com/local/canada/on/newmarket/facility-services?utm_source=google&utm_medium=organic&utm_campaign=Profiles_Facility_Services',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'LowFare Commercial Maintenance | cleaning company',
  '<p>LowFare Commercial Maintenance provides exceptional commercial cleaning services in Markham, Ontario. This local business specializes in transforming workplaces through a variety of janitorial services, including post-construction cleaning and routine maintenance. With a commitment to client satisfaction, LowFare employs skilled professionals who utilize eco-friendly products and advanced techniques to deliver impressive results.</p> <p>The company’s focus on creating pristine environments ensures that businesses can operate in clean, sanitized spaces. LowFare Commercial Maintenance stands out in the competitive cleaning market by offering tailored solutions that meet the unique needs of each client. Their expertise in industrial carpet cleaning further enhances their service offerings, catering to various commercial sectors.</p> <p>LowFare’s dedication to quality is evident in their meticulous approach to cleanliness and maintenance. The team is well-trained and knowledgeable, ensuring that every corner of a workplace is addressed. Clients appreciate the reliability and affordability of their services, making them a preferred choice for commercial cleaning in the region.</p> <p>In summary, LowFare Commercial Maintenance delivers top-tier cleaning solutions that prioritize cleanliness and environmental responsibility. Their skilled team, diverse service offerings, and commitment to client satisfaction make them a leader in the commercial cleaning industry. Contact LowFare Commercial Maintenance for professional cleaning services in Markham, Ontario.</p>',
  '15 Allstate Pkwy #600',
  'Canada',
  'ON',
  'Markham',
  'L3R 5B4',
  'info@enterprisemechanical.ca',
  'canada/markham/home-services/lowfare-commercial-maintenance-cleaning-company',
  'ChIJz1Ln6ZDV1IkR6PCYEQMKNPU',
  43.8501216,
  -79.363327,
  '16472509918',
  NULL,
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  155,
  'https://lowfaremaintenance.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Pollute Free Initiative',
  '<p>Pollute Free Initiative offers comprehensive commercial cleaning services in Toronto, Ontario. This business focuses on sustainable practices to enhance environmental quality. The initiative aims to reduce consumption, pollution, and waste while promoting energy efficiency in both residential and commercial spaces. With a dedicated team led by experienced directors, Pollute Free Initiative emphasizes the importance of eco-friendly cleaning solutions.</p><p>The mission of Pollute Free Initiative revolves around preserving and restoring the environment. By retrofitting vehicles and structures, the company enhances energy efficiency, contributing to a cleaner community. The founders, John-Paul Santonato, Giancarlo Sacchetti, and Angelo Martino, bring a wealth of knowledge and experience to the table, ensuring that the services provided meet high standards of sustainability and effectiveness.</p><p>Pollute Free Initiative has established itself as a leader in the commercial cleaning sector by prioritizing sustainable systems. The focus on reducing waste and improving land use reflects a commitment to the environment and community well-being. Clients can expect reliable, efficient, and environmentally friendly cleaning services tailored to their specific needs.</p><p>Pollute Free Initiative stands committed to enhancing environmental sustainability through its services. The focus on eco-friendly practices and community improvement sets a positive example in the industry. Connect with Pollute Free Initiative at 543 Quebec Ave, Toronto, Ontario, for exceptional commercial cleaning services.</p>',
  '543 Quebec Ave',
  'Canada',
  'ON',
  'Toronto',
  'M6P 2V6',
  'inquiries@lairdandson.com',
  'canada/toronto/home-services/pollute-free-initiative',
  'ChIJb0qelTQ3K4gRHWLQDWEvVyY',
  43.6672176,
  -79.4725747,
  '16479477339',
  NULL,
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  154,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'ServiceMaster Clean of Canada',
  '<p>ServiceMaster Clean of Canada delivers exceptional commercial cleaning services in Oakville, Ontario. This company excels in various cleaning solutions, including janitorial services, commercial carpet cleaning, upholstery care, and hard floor maintenance. With a commitment to quality, ServiceMaster Clean has established itself as a reliable partner for businesses seeking cleanliness and professionalism.</p><p>ServiceMaster Clean operates with a focus on efficiency and effectiveness. The team employs advanced techniques and eco-friendly products to ensure a thorough cleaning experience. Clients benefit from tailored cleaning plans that meet their specific needs, enhancing the overall work environment. The business prides itself on its trained staff, who are dedicated to maintaining high standards in every service provided.</p><p>ServiceMaster Clean has garnered a reputation for reliability and excellence in the commercial cleaning sector. The company understands the importance of a clean workspace and its impact on employee productivity and health. By utilizing innovative cleaning solutions, ServiceMaster Clean not only addresses immediate cleanliness concerns but also contributes to the long-term maintenance of facilities.</p><p>In summary, ServiceMaster Clean of Canada offers comprehensive commercial cleaning services that include janitorial work, carpet cleaning, and more. Their commitment to quality and customer satisfaction sets them apart in the industry. Connect with ServiceMaster Clean today to experience top-tier cleaning services in Oakville, Ontario.</p>',
  '2275 Upper Middle Rd E Suite 200',
  'Canada',
  'ON',
  'Oakville',
  'L6H 0C3',
  'info@ahsbc.com',
  'canada/oakville/home-services/servicemaster-clean-of-canada',
  'ChIJHQsFWm1DK4gRZ_B7v8C2zYo',
  43.5044363,
  -79.671928,
  '18556407880',
  NULL,
  'Cleaning Services=>Office Cleaning',
  'Pay-as-you-go',
  153,
  'https://servicemasterclean.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Eh! Maids House Cleaning Services Brampton',
  '<p>Eh! Maids House Cleaning Services, located at 16 Gold Pine Ct in Brampton, Ontario, offers a comprehensive range of cleaning solutions tailored to meet diverse customer needs. Since its inception in 2012, this local business has expanded its services across Toronto, Brampton, Barrie, and Mississauga, establishing a reputation for exceptional customer satisfaction. The team prides itself on providing meticulous and reliable cleaning services.</p><p>The company specializes in various cleaning services, including house cleaning, condo cleaning, apartment cleaning, deep cleaning, move cleaning, vacation rental cleaning, and post-construction cleaning. Each service is designed to address specific cleaning challenges, ensuring that every customer receives personalized attention and care. The commitment to customer satisfaction drives the team to maintain high standards across all services.</p><p>Eh! Maids operates with a customer-centric approach, allowing for easy bookings and guaranteeing neat service. The team emphasizes problem-solving, making it easy for customers to receive assistance any day of the week. The growth from a small team to a large family reflects the dedication and passion for the cleaning industry.</p><p>Eh! Maids House Cleaning Services in Brampton delivers quality cleaning with a focus on customer satisfaction and reliability. The diverse range of services ensures that all cleaning needs are met efficiently. Contact Eh! Maids today for exceptional cleaning services in Brampton, Ontario.</p>',
  '16 Gold Pine Ct',
  'Canada',
  'ON',
  'Brampton',
  'L6S 2K6',
  'quotes@towerph.com',
  'canada/brampton/home-services/eh-maids-house-cleaning-services-brampton',
  'ChIJK0c1px89K4gRoRS9PHsWNow',
  43.7374553,
  -79.7259439,
  '16476896110',
  'https://www.kwikr.ca/pictures/profile/pimage-136.jpg',
  'Cleaning Services=>Move-In/Move-Out Cleaning',
  'Pay-as-you-go',
  152,
  'https://ehmaids.ca/brampton-on/?utm_source=google&utm_medium=organic&utm_campaign=gbp-listing&utm_content=brampton-on',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'MenageBonheur',
  '<p>MenageBonheur offers exceptional house cleaning services in Levis, Quebec. This local business specializes in residential and commercial cleaning, ensuring spaces remain spotless and inviting. With a commitment to quality, MenageBonheur caters to both homes and businesses, providing tailored cleaning solutions that meet diverse needs.</p> <p>The company focuses on delivering a thorough cleaning experience. Residential cleaning services include dusting, vacuuming, and sanitizing, while commercial cleaning ensures a professional environment. MenageBonheur employs trained staff who use effective cleaning techniques and eco-friendly products. This approach not only enhances cleanliness but also promotes a healthier living and working environment.</p> <p>MenageBonheur has built a reputation for reliability and customer satisfaction in Levis. The team understands the importance of a clean space, which directly contributes to overall well-being and productivity. Attention to detail remains a core value, ensuring every corner is attended to. Clients appreciate the flexibility in scheduling, accommodating various cleaning frequencies to fit individual lifestyles.</p> <p>MenageBonheur excels in providing comprehensive cleaning services tailored to the needs of both residential and commercial clients. The dedication to quality and customer satisfaction speaks volumes about their work ethic. Contact MenageBonheur for professional cleaning services in Levis, Quebec, and experience the difference in cleanliness.</p>',
  '4057 Av. des Chutes',
  'Canada',
  'QC',
  'Levis',
  'G6X 1G8',
  'info@greenapprovedsolutions.ca',
  'canada/levis/home-services/menagebonheur',
  'ChIJzan65XyTuEwRetpF9JQxoO4',
  46.7185399,
  -71.2754718,
  '14182615586',
  NULL,
  'Cleaning Services=>Move-In/Move-Out Cleaning',
  'Pay-as-you-go',
  151,
  'http://menagebonheur.ca/?utm_source=gmb&utm_medium=referral',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'A Woman''s Touch Housecleaning',
  '<p>A Woman''s Touch Housecleaning provides reliable and professional house cleaning services in North Vancouver and West Vancouver. Established in 1984, this local business has built a strong reputation under the guidance of owner Colleen Bell, who brings over 40 years of experience in the cleaning industry. The company specializes in both residential and contract cleaning, ensuring that every client receives top-notch service tailored to their needs.</p><p>Colleen Bell, a local businesswoman, has dedicated her career to serving the community. Her commitment to quality and attention to detail have positioned A Woman''s Touch Housecleaning as a leader in the industry. The business prides itself on its trustworthy staff and consistent results. Clients can expect thorough cleaning that enhances the comfort and cleanliness of their homes.</p><p>With a strong community connection, A Woman''s Touch Housecleaning understands the unique needs of North Vancouver residents. The company utilizes eco-friendly cleaning products, aligning with the values of sustainability that many local clients prioritize. This approach not only ensures a clean home but also contributes positively to the environment.</p><p>A Woman''s Touch Housecleaning offers comprehensive cleaning services that cater to residential and contract needs. The business''s longstanding presence in North Vancouver reflects its dedication and reliability. Engage with A Woman''s Touch Housecleaning today for exceptional cleaning services in North Vancouver, British Columbia.</p>',
  '1130 14th St W',
  'Canada',
  'BC',
  'North Vancouver',
  'V7P 1J8',
  'theratio_interior@mail.com',
  'canada/north-vancouver/home-services/a-woman-s-touch-housecleaning',
  'ChIJG-ZYCM5xhlQR-xUCR2Hm3NI',
  49.3212422,
  -123.1061556,
  '16049802310',
  'https://www.kwikr.ca/pictures/profile/pimage-134.jpg',
  'Cleaning Services=>Move-In/Move-Out Cleaning',
  'Pay-as-you-go',
  150,
  'https://www.womanstouchcleaning.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Clean Victoria',
  '<p>Clean Victoria, located at 388 Davida Ave in Victoria, British Columbia, is a dedicated house cleaning service that specializes in short-term rentals, residential properties, and commercial spaces. This business prioritizes eco-friendly cleaning solutions, ensuring that homes and businesses maintain a healthy environment while achieving high cleanliness standards.</p> <p>The team at Clean Victoria is fully trained to meet rigorous cleaning expectations. Each member understands the importance of using the right products and tools for effective cleaning. This attention to detail guarantees that every surface is sanitized, creating a welcoming atmosphere for guests and residents alike. The commitment to consistent upkeep ensures that spaces remain sparkling and inviting.</p> <p>Clean Victoria excels in providing a detailed approach to cleaning, focusing on the unique needs of each client. The use of eco-friendly cleaning solutions not only promotes a healthier living space but also supports sustainable practices in the local community. The goal is to enhance the overall guest experience, making every visit enjoyable and stress-free.</p> <p>This cleaning service stands out for its dedication to quality and customer satisfaction. Clean Victoria offers a reliable solution for maintaining clean and sanitized environments in Victoria, BC. Contact Clean Victoria today to experience professional house cleaning services that prioritize health and cleanliness in every space.</p>',
  '388 Davida Ave',
  'Canada',
  'BC',
  'Victoria',
  'V9A 2C5',
  'info@av-chandeliers.com',
  'canada/victoria/home-services/clean-victoria',
  'ChIJEYGuyYKGNiQRfDpM7bqE4Rc',
  48.452162,
  -123.3997549,
  '17786778660',
  'https://www.kwikr.ca/pictures/profile/pimage-133.jpg',
  'Cleaning Services=>Move-In/Move-Out Cleaning',
  'Pay-as-you-go',
  149,
  'http://cleanvictoria.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);
