INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Sweeney Electric Ltd',
  '<p>Sweeney Electric Ltd, located in Prince Albert, Saskatchewan, has provided reliable electrical installation services since 1914. This family-owned and operated business specializes in both residential and commercial electrical needs, ensuring high-quality workmanship and customer satisfaction. With 24/7 emergency service, Sweeney Electric is always ready to assist clients in urgent situations.</p><p>The company offers a comprehensive range of services, from simple light fixture replacements to complete electrical installations for new builds. Sweeney Electric Ltd also serves as a Generac generator dealer, providing sales and service for essential backup power solutions. This commitment to meeting diverse electrical needs makes Sweeney Electric a trusted choice for the local community.</p><p>With a strong focus on quality and reliability, Sweeney Electric Ltd has built a solid reputation in the Prince Albert area. The experienced team is dedicated to delivering efficient solutions tailored to each client''s unique requirements. This commitment to service excellence has made Sweeney Electric a preferred partner for many residents and businesses alike.</p><p>Sweeney Electric Ltd excels in providing a full range of electrical services, ensuring quality work and prompt response times. Their long-standing presence in the community highlights their dedication to customer care and expertise. For comprehensive electrical solutions, reach out to Sweeney Electric Ltd in Prince Albert, Saskatchewan, for dependable service. </p>',
  'RR 5 Site 17',
  'Canada',
  'SK',
  'Prince Albert',
  'S6V 5R3',
  'contact@floorsdepot.ca',
  'canada/prince-albert/home-services/sweeney-electric-ltd',
  'ChIJHwAA--R6AVMRFg1IvBB4eQM',
  53.176332,
  -105.756925,
  '13067634212',
  'https://www.kwikr.ca/pictures/profile/pimage-487.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  498,
  'http://www.sweeneyelectric.net/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'PTW Energy Services',
  '<p>PTW Energy Services provides top-tier electrical installation services in Grande Prairie, Alberta. The company specializes in delivering reliable solutions for residential and commercial electrical needs. With a commitment to safety and efficiency, PTW Energy Services has built a reputation for quality workmanship and customer satisfaction.</p><p>Located at 11418 91 Ave, PTW Energy Services offers a wide range of electrical solutions tailored to meet the specific requirements of each project. The skilled team focuses on various aspects of electrical installation, including wiring, lighting, and power distribution systems. The company emphasizes the importance of adhering to local codes and standards, ensuring that all work is performed to the highest safety and quality benchmarks.</p><p>PTW Energy Services has achieved numerous successful projects, showcasing expertise in both small-scale and large-scale electrical installations. The team’s extensive knowledge in the field allows for innovative solutions that enhance energy efficiency and functionality. Clients appreciate the attention to detail and the professional approach taken throughout each project.</p><p>In summary, PTW Energy Services excels in providing comprehensive electrical installation services in Grande Prairie, Alberta. Their commitment to quality, safety, and customer satisfaction sets them apart in the industry. Connect with PTW Energy Services today for reliable electrical solutions in Grande Prairie.',
  '11418 91 Ave',
  'Canada',
  'AB',
  'Grande Prairie',
  'T8V 6K6',
  'info@priorityoneflooring.com',
  'canada/grande-prairie/home-services/ptw-energy-services',
  'ChIJDQnyAQ6RkFMRVFM58F6DDqU',
  55.1607796,
  -118.8416583,
  '17805399367',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  497,
  'https://www.ptwenergy.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'BC HighLight Electric',
  '<p>BC HighLight Electric provides top-notch electrical installation services in Surrey, British Columbia. This local business emphasizes professionalism and experience, transforming projects into exceptional results. With a commitment to quality, BC HighLight Electric caters to both residential and commercial needs, ensuring every installation meets the highest standards.</p> <p>Expertise in electrical systems allows BC HighLight Electric to tackle a variety of projects. Whether it involves new construction, renovations, or upgrades, the team delivers reliable solutions tailored to client specifications. The company''s approach combines a thorough understanding of electrical safety regulations with innovative techniques, ensuring efficient and effective services. Clients appreciate the willingness to offer input on project designs or execute existing plans seamlessly.</p> <p>BC HighLight Electric has built a solid reputation within the community for its dedication to customer satisfaction. The team’s attention to detail and commitment to excellence contribute to the successful completion of each project. With a focus on fostering positive relationships, the business prioritizes clear communication and transparency throughout the installation process.</p> <p>In summary, BC HighLight Electric excels in providing electrical installation services in Surrey, British Columbia. The company’s strengths lie in its professionalism, experience, and customer-centric approach. For reliable electrical solutions that meet specific needs, reach out to BC HighLight Electric at 19567 Fraser Hwy #233, Surrey, British Columbia, V3S 9A4.</p>',
  '19567 Fraser Hwy #233',
  'Canada',
  'BC',
  'Surrey',
  'V3S 9A4',
  'info@evergreenflooring.ca',
  'canada/surrey/home-services/bc-highlight-electric',
  'ChIJadSrXVRzhlQRGUm0wtgGEvw',
  49.1150121,
  -122.6801329,
  '16042254448',
  'https://www.kwikr.ca/pictures/profile/pimage-485.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  496,
  'https://bchighlightelectric.com/locations/electrician-in-surrey/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Vicar Electric Ltd',
  '<p>Vicar Electric Ltd offers expert electrical installation services in Campbell River, British Columbia. This First Nations commercial industrial electrical contractor specializes in a range of services tailored to meet the unique needs of both commercial and industrial clients. With a commitment to quality and safety, Vicar Electric Ltd ensures that every project is completed to the highest standards.</p><p>The company operates from its location at 1040 9 Ave #7, providing accessible and efficient electrical solutions to the local community. Vicar Electric Ltd has built a reputation for reliability and professionalism, making it a trusted partner for various electrical projects. Their team is skilled in handling complex electrical installations, ensuring that all work complies with industry regulations.</p><p>By focusing on the needs of First Nations businesses, Vicar Electric Ltd understands the importance of cultural sensitivity and community engagement. This approach fosters strong relationships with clients and contributes to the success of local projects. The company’s dedication to sustainable practices and innovative solutions sets it apart in the electrical installation service sector.</p><p>Vicar Electric Ltd excels in delivering comprehensive electrical services that prioritize customer satisfaction and safety. The combination of expertise and community focus positions the company as a leader in the industry. Connect with Vicar Electric Ltd for reliable electrical installation services in Campbell River, British Columbia.</p>',
  '1040 9 Ave #7',
  'Canada',
  'BC',
  'Campbell River',
  'V9W 4C2',
  'info@sourcefloor.com',
  'canada/campbell-river/home-services/vicar-electric-ltd',
  'ChIJd46YFMqnYlQR92Zz74u6Eyo',
  50.023864,
  -125.2566307,
  '12505322480',
  'https://www.kwikr.ca/pictures/profile/pimage-484.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  495,
  'https://vicarelectric.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Halton Electric',
  '<p>Halton Electric provides essential electrical installation services to the Burlington area in Ontario. This business specializes in emergency services available 24/7, ensuring that residents and businesses receive timely assistance for their electrical needs. Located at 4180 Morris Dr Unit 5, Halton Electric is dedicated to delivering reliable and efficient solutions, making it a trusted choice for local customers.</p><p>The team at Halton Electric understands the importance of electricity in daily life. They offer a wide range of services, including installation, repair, and maintenance of electrical systems. This commitment to quality ensures that every job meets safety standards and customer satisfaction. The experienced technicians are equipped to handle both residential and commercial projects, providing tailored solutions to fit specific requirements.</p><p>Halton Electric has built a reputation for reliability and professionalism in the Burlington community. Their 24/7 emergency service demonstrates a strong commitment to customer care, as clients can rely on immediate support during critical situations. The business emphasizes transparent communication and efficient service delivery, which contributes to its growing client base.</p><p>Halton Electric excels in providing comprehensive electrical installation services and emergency support. Their commitment to quality and customer satisfaction reinforces their position in the local market. For reliable electrical services in Burlington, connect with Halton Electric today.',
  '4180 Morris Dr Unit 5',
  'Canada',
  'ON',
  'Burlington',
  'L7L 5L6',
  'michellewarren@rogers.com',
  'canada/burlington/home-services/halton-electric',
  'ChIJzZSq2Q9hK4gR84knEifmRtA',
  43.3690878,
  -79.7815406,
  '19053352104',
  'https://www.kwikr.ca/pictures/profile/pimage-483.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  494,
  'https://www.haltonelectric.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Seacliff Electric',
  '<p>Seacliff Electric provides top-tier electrical installation services in Calgary, Alberta, with over 60 years of personal management experience. This commercial electrical contractor excels in delivering reliable and efficient solutions for various electrical needs, ensuring projects are completed on time and within budget. The company specializes in a wide range of services, including wiring, lighting installations, and maintenance, making it a comprehensive choice for businesses in the area.</p> <p>Seacliff Electric has built a reputation for professionalism and expertise in the electrical installation sector. The team consists of skilled electricians who prioritize safety and quality in every project. They understand the unique requirements of commercial spaces and work diligently to meet client expectations. With a commitment to customer satisfaction, Seacliff Electric has successfully completed numerous projects, contributing to the local economy and enhancing community infrastructure.</p> <p>Investing in advanced technology and ongoing training for employees allows Seacliff Electric to stay ahead in the industry. The company’s dedication to innovation ensures that clients receive the most effective solutions tailored to their specific needs. Their extensive experience in managing complex electrical systems sets them apart from competitors.</p> <p>Seacliff Electric offers a wide range of electrical installation services, showcasing strengths in reliability and expertise. The company’s commitment to quality and customer satisfaction is evident in every project. Engage with Seacliff Electric for exceptional electrical services in Calgary, Alberta.</p>',
  '4615 112 Ave SE #333',
  'Canada',
  'AB',
  'Calgary',
  'T2C 5J3',
  'info@armourguard.ca',
  'canada/calgary/home-services/seacliff-electric',
  'ChIJ6W7Q8UB3cVMRNfe6mBqwIx8',
  50.9511009,
  -113.9692191,
  '15873914545',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  493,
  'http://www.seacliffelectric.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Osprey Electric',
  '<p>Osprey Electric, located at 1690 Maple St in Campbell River, British Columbia, specializes in electrical installation services. This company serves Western BC and Vancouver Island, offering a range of solutions including custom electrical construction, photovoltaic systems, upgrades, renovations, and retrofitting. With a commitment to quality and safety, Osprey Electric employs experienced project managers and electricians who ensure every project meets industry standards.</p> <p>Fully licensed, insured, and bonded, Osprey Electric operates with integrity and professionalism. The company’s competitive pricing structure makes it accessible for various budgets, allowing clients to receive top-notch services without overspending. The team possesses expertise across multiple industry sectors, ensuring that all electrical needs are met efficiently and effectively. Osprey Electric prioritizes customer satisfaction, making it a trusted choice for both residential and commercial projects.</p> <p>Osprey Electric has built a solid reputation in Campbell River and surrounding areas. Their dedication to providing high-quality electrical services has made them a key player in the local market. Clients can expect timely project completion and a focus on safety throughout the entire process. With a wide array of services, Osprey Electric remains committed to delivering reliable and innovative electrical solutions.</p> <p>Explore the comprehensive electrical services offered by Osprey Electric. Their strengths lie in experience, competitive pricing, and customer-focused service. Reach out to Osprey Electric in Campbell River for expert electrical installation services.</p>',
  '1690 Maple St',
  'Canada',
  'BC',
  'Campbell River',
  'V9W 3G2',
  'info@wallandfloor.ca',
  'canada/campbell-river/home-services/osprey-electric',
  'ChIJGyGyBRKvYlQRMobwOqof4jQ',
  50.0310541,
  -125.2650525,
  '12508300997',
  'https://www.kwikr.ca/pictures/profile/pimage-481.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  492,
  'https://www.ospreyelectric.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'ARTICULATE INTEGRATION & TECHNOLOGIES',
  '<p>ARTICULATE INTEGRATION & TECHNOLOGIES offers expert electrical installation services in Edmonton, Alberta. This local business specializes in delivering high-quality electrical solutions for both residential and commercial clients. With a commitment to safety and efficiency, ARTICULATE INTEGRATION & TECHNOLOGIES has built a reputation for reliability and professionalism in the community.</p> <p>The team at ARTICULATE INTEGRATION & TECHNOLOGIES possesses extensive experience in various electrical projects, ensuring that all installations meet the highest industry standards. They provide services such as wiring, lighting installation, and electrical panel upgrades. Each project receives careful planning and execution, resulting in optimal performance and customer satisfaction. The technicians are well-versed in the latest technologies and techniques, which enhances their service offerings.</p> <p>This Edmonton-based company emphasizes customer care and transparent communication throughout the installation process. They prioritize understanding the unique needs of each client, which allows for tailored solutions that enhance the functionality and safety of electrical systems. ARTICULATE INTEGRATION & TECHNOLOGIES also adheres to all local regulations, ensuring compliance and peace of mind for clients.</p> <p>ARTICULATE INTEGRATION & TECHNOLOGIES delivers reliable electrical installation services characterized by professionalism and expertise. Their commitment to quality and customer satisfaction positions them as a trusted choice in Edmonton. Reach out to ARTICULATE INTEGRATION & TECHNOLOGIES for exceptional electrical services in Edmonton, Alberta.</p>',
  '17628 103 Ave NW #101',
  'Canada',
  'AB',
  'Edmonton',
  'T5S 1J9',
  'info@topfloorsanddesign.ca',
  'canada/edmonton/home-services/articulate-integration-technologies',
  'ChIJ__8_ZR4hoFMRWKATE-1W0fI',
  53.5456084,
  -113.6253707,
  '17804467479',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  491,
  'http://aitechnologies.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'PTW Energy Services',
  '<p>PTW Energy Services Ltd. specializes in electrical installation services, delivering high-quality solutions in Redwater, Alberta. This private company, headquartered in Calgary, has established a reputation for excellence in fabrication, construction, and maintenance services. With a robust network extending across Canada, the United States, and regions in the Middle East and Asia Pacific, PTW Energy Services is equipped to handle diverse electrical needs.</p> <p>The company’s team of skilled professionals ensures that every project meets industry standards and client expectations. PTW Energy Services focuses on providing safe and efficient electrical installations that enhance operational performance. With years of experience and a commitment to quality, the company has successfully completed numerous projects, making it a reliable choice for local and international clients alike.</p> <p>PTW Energy Services emphasizes innovation and customer satisfaction. The company utilizes advanced technologies and methodologies to deliver effective solutions tailored to specific requirements. Their dedication to safety and compliance further enhances their standing in the electrical installation service sector. Clients benefit from a comprehensive approach that includes consultation, planning, and execution, ensuring projects are completed on time and within budget.</p> <p>In summary, PTW Energy Services offers exceptional electrical installation services in Redwater, Alberta, backed by a strong commitment to quality and safety. The company’s extensive experience and innovative solutions position it as a leader in the industry. Contact PTW Energy Services today for professional electrical installation services in Redwater, Alberta.</p>',
  '4806 44 St',
  'Canada',
  'AB',
  'Redwater',
  'T0A 2W0',
  'tepalconstruction@outlook.com',
  'canada/redwater/home-services/ptw-energy-services',
  'ChIJGUwqiM5SoFMRU67KHm3Hpbg',
  53.9500958,
  -113.0992471,
  '17809422225',
  'https://www.kwikr.ca/pictures/profile/pimage-479.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  490,
  'http://www.ptwenergy.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Feldt Electric Inc',
  '<p>Feldt Electric Inc provides comprehensive electrical installation services to the Markham area in Ontario. This local business specializes in a wide range of electrical solutions, ensuring quality and safety in every project. With a reputation for reliability, Feldt Electric Inc serves both residential and commercial clients, offering expertise in electrical installations, upgrades, and repairs.</p> <p>Established with a commitment to excellence, Feldt Electric Inc has built a strong presence in the community. The skilled team of contractors is equipped to handle various electrical needs, from lighting installations to wiring upgrades. The focus on customer satisfaction drives the business to deliver timely and efficient services. Each project reflects the company’s dedication to quality workmanship and adherence to safety standards.</p> <p>In addition to their technical skills, Feldt Electric Inc emphasizes transparency and communication with clients. This approach fosters trust and ensures that customers are informed throughout the process. The company’s commitment to using high-quality materials further enhances the durability and performance of their electrical installations.</p> <p>Feldt Electric Inc remains a top choice for electrical installation services in Markham. The combination of expertise, reliability, and customer-focused service solidifies its position in the local market. Connect with Feldt Electric Inc for all electrical needs in Markham, Ontario.',
  '2600 John St.',
  'Canada',
  'ON',
  'Markham',
  'L3R 3W3',
  'info@luxepoxy.ca',
  'canada/markham/home-services/feldt-electric-inc',
  'ChIJZUo-717T1IkRlRXgJhX7E24',
  43.825864,
  -79.360372,
  '19057521550',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  489,
  'http://feldtelectric.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'PTW Energy Services',
  '<p>PTW Energy Services Ltd. delivers expert electrical installation services in Estevan, Saskatchewan. This private company, based in Calgary, Alberta, excels in providing comprehensive solutions that include fabrication, construction, and maintenance. The extensive network spans across Canada, the United States, the Middle East, and the Asia Pacific, showcasing the company’s capability and reach.</p> <p>With a commitment to quality and efficiency, PTW Energy Services focuses on meeting the unique needs of each project, ensuring that clients receive reliable and innovative electrical solutions. The skilled team possesses extensive knowledge and experience in the electrical installation sector, which enhances the overall service delivery. This dedication to excellence has positioned the company as a leader in the industry.</p> <p>PTW Energy Services has successfully completed numerous projects, demonstrating their ability to handle various electrical installation challenges. Their approach integrates advanced technology and best practices, resulting in high-quality outcomes that adhere to safety standards. The company’s reputation is built on trust and reliability, making it a preferred choice for clients in Estevan and beyond.</p> <p>PTW Energy Services Ltd. offers a range of electrical installation services characterized by expertise and professionalism. The company’s strengths lie in its extensive experience and commitment to client satisfaction. For quality electrical solutions in Estevan, connect with PTW Energy Services today. </p>',
  '310 Kensington Ave',
  'Canada',
  'SK',
  'Estevan',
  'S4A 2K9',
  'francisco@ecowoods.ca',
  'canada/estevan/home-services/ptw-energy-services',
  'ChIJm5dR_L4iIFMRKwthf2Vw4Yc',
  49.1370055,
  -102.9698703,
  '13066345617',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  488,
  'https://www.ptwenergy.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Vancouver Green Electric Ltd',
  '<p>Vancouver Green Electric Ltd delivers exceptional electrical installation services in Richmond, British Columbia. This business specializes in professional electrical work, catering to both residential and commercial needs. From installing electrical equipment to new construction wiring, Vancouver Green Electric Ltd ensures high-quality results that meet industry standards. Their commitment to excellence has earned them a solid reputation in the local area.</p><p>The company operates from 11780 River Rd Unit 170, providing a range of services tailored to the specific requirements of clients. Vancouver Green Electric Ltd employs skilled technicians who utilize advanced techniques and equipment, ensuring efficient and safe installations. Their team stays updated on the latest technologies and practices, which enhances their service delivery. Vancouver Green Electric Ltd is known for its reliability and professionalism, making them a preferred choice for electrical projects in the region.</p><p>With a focus on customer satisfaction, Vancouver Green Electric Ltd prioritizes effective communication and transparency throughout the project lifecycle. Their extensive experience in electrical installation positions them as a leader in the industry. Clients can expect timely completion of projects without compromising quality. Vancouver Green Electric Ltd is dedicated to making a difference in the community through their services.</p><p>Vancouver Green Electric Ltd provides comprehensive electrical installation services, ensuring quality and safety in every project. Their commitment to excellence and customer satisfaction sets them apart in Richmond. Connect with Vancouver Green Electric Ltd for professional electrical services in British Columbia.</p>',
  '11780 River Rd Unit 170',
  'Canada',
  'BC',
  'Richmond',
  'V6X 1Z7',
  'info@flooringservice.ca',
  'canada/richmond/home-services/vancouver-green-electric-ltd',
  'ChIJw2_gDx91hlQR_zfdbPMiXd8',
  49.196618,
  -123.094234,
  '16046440451',
  'https://www.kwikr.ca/pictures/profile/pimage-476.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  487,
  'http://www.vancouvergreenelectric.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Connect Energy Services',
  '<p>Connect Energy Services offers reliable electrical installation services in Redwater, Alberta. This local business specializes in residential and commercial electrical needs, ensuring safety and efficiency. With a commitment to quality workmanship, Connect Energy Services has built a reputation for prompt and professional service in the community.</p><p>The skilled team at Connect Energy Services handles various tasks, including lighting installation, circuit upgrades, and electrical repairs. Their expertise extends to both new constructions and renovations, providing tailored solutions that meet specific client requirements. The business prides itself on using high-quality materials and adhering to industry standards, which enhances safety and longevity in every project.</p><p>Connect Energy Services has successfully completed numerous projects in Redwater and surrounding areas. Their customer-focused approach has resulted in positive feedback from clients, highlighting the team''s professionalism and attention to detail. The business understands the importance of reliable electrical systems and works diligently to ensure every installation meets the highest standards.</p><p>In summary, Connect Energy Services delivers exceptional electrical installation services in Redwater, Alberta. Their dedication to quality, safety, and customer satisfaction positions them as a trusted choice for electrical needs. For reliable electrical solutions, reach out to Connect Energy Services at 4808 44 St, Redwater, Alberta, T0A 2W0. </p>',
  '4808 44 St',
  'Canada',
  'AB',
  'Redwater',
  'T0A 2W0',
  'info@expo-sol.com',
  'canada/redwater/home-services/connect-energy-services',
  'ChIJLwgAfc5SoFMRjsHhh6KKQIk',
  53.9504614,
  -113.099247,
  '17809915590',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  486,
  'https://connectenergyservices.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'TradeCo Electric and Automation Inc',
  '<p>TradeCo Electric and Automation Inc provides comprehensive electrical installation services in Ayr, Ontario. This industrial electrical controls and automation company specializes in turnkey automation cells, robotic integration, and a variety of industrial electrical services and maintenance. With a commitment to quality and efficiency, TradeCo serves a diverse clientele, ensuring that each project meets the highest standards.</p> <p>The expertise of TradeCo Electric and Automation Inc lies in its ability to deliver customized solutions tailored to the unique needs of each client. The team possesses extensive knowledge in automation technologies and electrical installations, which enhances operational efficiency for businesses in the area. Their focus on robotic integration allows clients to streamline processes and improve productivity, making them a valuable partner for industrial operations.</p> <p>TradeCo has garnered a reputation for reliability and professionalism. Clients appreciate the company’s attention to detail and commitment to safety. The team works closely with customers to understand their specific requirements, ensuring that all aspects of the project are executed smoothly. This approach has led to successful partnerships and repeat business within the local community.</p> <p>In summary, TradeCo Electric and Automation Inc offers essential electrical installation services and automation solutions in Ayr, Ontario. Their expertise in robotic integration and industrial electrical services positions them as a leader in the field. Connect with TradeCo Electric and Automation Inc for reliable electrical solutions in Ayr, Ontario.</p>',
  '71 Nith River Wy',
  'Canada',
  'ON',
  'Ayr',
  'N0B 1E0',
  'info@buildingblocksco.com',
  'canada/ayr/home-services/tradeco-electric-and-automation-inc',
  'ChIJSUWs3mZtLIgRj6hsEUv93Tk',
  43.2910923,
  -80.4668104,
  '15195778694',
  'https://www.kwikr.ca/pictures/profile/pimage-474.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  485,
  'https://tradecoelectric.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Langstaff & Sloan Inc.',
  '<p>Langstaff & Sloan Inc. offers comprehensive electrical installation services in Etobicoke, Ontario. Established in 1991, this company has built a reputation for reliability and professionalism in both residential and commercial sectors. As an Authorized Contractor of Toronto Hydro Energy Services, Langstaff & Sloan specializes in Knob and Tube rewiring, high-rise Sub Metering, retrofit lighting, and leasehold improvements. The company also engages in multiple Utility/OPA sponsored programs, including Peak Saver, showcasing its commitment to innovative and sustainable solutions.</p><p>With over three decades of experience, Langstaff & Sloan has developed a strong presence in the Greater Toronto Area. The team prioritizes customer satisfaction by delivering courteous service at competitive rates. The focus on embracing green technologies aligns with modern energy-saving initiatives, making this business a valuable partner for clients looking to enhance their electrical systems. The expertise in complex projects, such as high-rise Sub Metering, positions Langstaff & Sloan as a leader in the electrical installation service sector.</p><p>Langstaff & Sloan Inc. continues to provide exceptional electrical services, ensuring that clients receive reliable and efficient solutions. The combination of extensive experience, commitment to innovation, and dedication to customer service underscores the strengths of this local business. Engage with Langstaff & Sloan for all electrical installation needs in Etobicoke, Ontario.</p>',
  '300 New Toronto St #6',
  'Canada',
  'ON',
  'Etobicoke',
  'M8V 2E8',
  'infocentre@polysurface.ca',
  'canada/etobicoke/home-services/langstaff-sloan-inc',
  'ChIJPb2ZhjJIK4gRe9C1E55AI0Y',
  43.6044251,
  -79.5192205,
  '16473602844',
  'https://www.kwikr.ca/pictures/profile/pimage-473.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  484,
  'https://langstaffandsloan.com/?utm_campaign=gmb&utm_medium=organic&utm_source=gmblisting',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'PTW Energy Services',
  '<p>PTW Energy Services Ltd. offers comprehensive electrical installation services in Slave Lake, Alberta. This private company, headquartered in Calgary, specializes in fabrication, construction, and maintenance services. With a robust network extending across Canada, the United States, the Middle East, and Asia Pacific, PTW Energy Services demonstrates a commitment to quality and efficiency in every project.</p><p>The company excels in delivering tailored solutions to meet diverse client needs. PTW Energy Services employs a skilled workforce trained in the latest industry standards. The emphasis on safety and innovation ensures that projects are completed on time and within budget. Clients benefit from a wide range of services, including electrical installations that adhere to regulatory requirements and industry best practices.</p><p>PTW Energy Services has built a reputation for reliability and expertise. The company’s dedication to customer satisfaction drives its operational excellence. With a focus on sustainable practices, PTW Energy Services contributes positively to the communities it serves. The team is equipped to handle projects of varying scales, providing flexibility and responsiveness to client demands.</p><p>In summary, PTW Energy Services Ltd. provides essential electrical installation services in Slave Lake, Alberta. The company’s strengths lie in its skilled workforce, commitment to safety, and customer-focused approach. Engage with PTW Energy Services for reliable electrical solutions in Slave Lake.</p>',
  '400 Birch Rd NE',
  'Canada',
  'AB',
  'Slave Lake',
  'T0G 2A2',
  'varant@valiantflooring.ca',
  'canada/slave-lake/home-services/ptw-energy-services',
  'ChIJa-QHMpmSolMRU-zKoTmGkBo',
  55.2940111,
  -114.7653581,
  '17808492789',
  NULL,
  'Electrical=>Electrical Installations',
  'Growth Plan',
  483,
  'https://www.ptwenergy.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'M&M Electric Services',
  '<p>M&M Electric Services provides top-notch electrical installation services in London, Ontario. This local business specializes in residential and commercial projects, ensuring safe and efficient electrical systems. With a commitment to quality and customer satisfaction, M&M Electric Services has built a reputation for reliability and expertise in the electrical industry.</p><p>The team at M&M Electric Services is equipped with the knowledge and skills to handle various electrical needs. From wiring and lighting installations to panel upgrades and troubleshooting, they deliver comprehensive solutions tailored to client requirements. The business prides itself on adhering to the highest safety standards, ensuring that all installations meet regulatory guidelines.</p><p>M&M Electric Services has achieved numerous milestones in the local community. Their dedication to excellence has led to positive feedback from satisfied customers. The company values transparency and communication, keeping clients informed throughout the project process. This approach fosters trust and long-lasting relationships with the community.</p><p>Offering a range of services, M&M Electric Services excels in providing quality electrical installations for homes and businesses alike. Their knowledgeable team, commitment to safety, and focus on customer satisfaction position them as a reliable choice for electrical needs in London, Ontario. Connect with M&M Electric Services today for expert electrical installation services in the area.</p>',
  '610 Newbold St #5',
  'Canada',
  'ON',
  'London',
  'N6E 2T6',
  'askus@coastalfloors.ca',
  'canada/london/home-services/m-m-electric-services',
  'ChIJcwA9egvzLogRCnGiMO8dLlQ',
  42.9358153,
  -81.2028041,
  '15196599959',
  'https://www.kwikr.ca/pictures/profile/pimage-471.jpg',
  'Electrical=>Electrical Installations',
  'Growth Plan',
  482,
  'https://www.mmelectricians.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Surface Stylz',
  '<p>Surface Stylz Flooring offers eco-friendly flooring solutions in Calgary, Alberta. Established in 2005, this flooring contractor has become a trusted name in sustainable flooring, providing quality products and skilled craftsmanship. Specializing in a variety of materials, Surface Stylz serves both residential and commercial clients throughout Southern Alberta.</p> <p>The range of flooring options includes cork, linoleum, ceramic, wood, and wool, catering to diverse design preferences and environmental needs. Surface Stylz prioritizes sustainability, ensuring that all products meet eco-friendly standards. The team consists of professionally trained craftsmen who bring expertise and attention to detail to every project.</p> <p>Customer satisfaction is a key focus. Surface Stylz has built a reputation for reliability and quality in the flooring industry. Clients appreciate the personalized service and the commitment to delivering projects on time and within budget. The company’s dedication to using green materials sets it apart in the marketplace.</p> <p>Surface Stylz Flooring combines quality, sustainability, and expert craftsmanship to meet the flooring needs of Calgary residents and businesses. With years of experience and a commitment to eco-friendly practices, this company continues to lead the way in green flooring solutions. Visit 1140 44 Ave SE, Calgary, Alberta, to explore sustainable flooring options and engage with the knowledgeable team at Surface Stylz.</p>',
  '1140 44 Ave SE',
  'Canada',
  'AB',
  'Calgary',
  'T2G 4W6',
  'info@concreteinspirations.ca',
  'canada/calgary/home-services/surface-stylz',
  'ChIJPwWW-GZxcVMRWJUu5LHC-IA',
  51.0141896,
  -114.0378062,
  '14036176822',
  'https://www.kwikr.ca/pictures/profile/pimage-470.jpg',
  'Flooring',
  'Growth Plan',
  481,
  'http://surfacestylz.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'VALHALLA CONTRACTING',
  '<p>VALHALLA CONTRACTING, located in Etobicoke, Ontario, specializes in flooring solutions that enhance the aesthetic appeal and functionality of residential and commercial spaces. This flooring contractor offers an innovative product known as Jewel Stone, an acrylic modified cement-based coating that transforms ordinary concrete into stunning decorative faux stone finishes. Jewel Stone concrete resurfacing is ideal for steps and patio areas, providing a customized look that complements any home or landscape.</p><p>This advanced resurfacing system combines polymer resins with cement, sand, and other additives, ensuring superior performance and wear resistance. Jewel Stone adheres effectively to existing concrete surfaces, making it a practical choice for rejuvenating worn or damaged areas. Its resistance to UV exposure, freeze-thaw cycles, and abrasion guarantees long-lasting beauty and functionality.</p><p>VALHALLA CONTRACTING has built a reputation for quality and reliability in the flooring industry. The focus on customer satisfaction and attention to detail sets this business apart. The Jewel Stone product not only enhances the visual appeal of outdoor spaces but also adds significant value to properties. Homeowners and businesses in Etobicoke can trust VALHALLA CONTRACTING for their flooring needs.</p><p>With a commitment to excellence and innovative solutions, VALHALLA CONTRACTING is the go-to flooring contractor in Etobicoke. Explore the benefits of Jewel Stone for concrete resurfacing. Connect with VALHALLA CONTRACTING today at their location on Lake Shore Blvd W.</p>',
  '2212 Lake Shore Blvd W',
  'Canada',
  'ON',
  'Etobicoke',
  'M8V 0C2',
  'dataprotection@stonhard.com',
  'canada/etobicoke/home-services/valhalla-contracting',
  'ChIJq6pG6uBGK4gRlAQv8rm8S-4',
  43.6225186,
  -79.4824312,
  '14168577480',
  'https://www.kwikr.ca/pictures/profile/pimage-469.jpg',
  'Flooring',
  'Growth Plan',
  480,
  'https://valhallacontracting.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Boisco Enterprise Ltd',
  '<p>Boisco Enterprise Ltd, located at 601 Washington Ave in Winnipeg, Manitoba, specializes in flooring contracting, providing innovative seamless flooring solutions, concrete services, and commercial and industrial painting since 2002. This company serves the broader regions of Manitoba, Ontario, and Saskatchewan, establishing a strong presence in the flooring industry.</p><p>With a commitment to integrity and high-quality workmanship, Boisco Enterprise Ltd has built a solid reputation over the years. The focus on maintaining strong relationships with customers sets this business apart. Qualified workers ensure a safe and positive work environment, which is crucial in the construction industry. The company’s COR certification highlights its dedication to safety on all job sites, reinforcing its commitment to providing reliable services.</p><p>Boisco Enterprise Ltd offers a range of services tailored to meet the needs of both commercial and industrial clients. The seamless flooring solutions not only enhance the aesthetic appeal of spaces but also provide durability and ease of maintenance. Concrete services further showcase the company’s versatility, while the painting division ensures that all projects receive the finishing touches required for a professional look.</p><p>Boisco Enterprise Ltd excels in delivering quality flooring solutions and has earned the trust of many clients across the region. Their commitment to safety and customer satisfaction remains paramount. Engage with Boisco Enterprise Ltd for expert flooring contracting services in Winnipeg, Manitoba.</p>',
  '601 Washington Ave',
  'Canada',
  'MB',
  'Winnipeg',
  'R2K 1M4',
  'realsealepoxy@gmail.com',
  'canada/winnipeg/home-services/boisco-enterprise-ltd',
  'ChIJjxUMuuRw6lIRWSOl7AfCqAA',
  49.9143665,
  -97.094665,
  '12042338693',
  'https://www.kwikr.ca/pictures/profile/pimage-468.jpg',
  'Flooring',
  'Growth Plan',
  479,
  'https://www.boisco.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Floorlab',
  '<p>Floorlab, located at 235 Medland St #104 in Toronto, Ontario, specializes in polished concrete flooring. Since 2001, this flooring contractor has delivered exceptional results for both residential and commercial clients. With a focus on balancing beauty and practicality, Floorlab provides a variety of finishes that cater to diverse aesthetic preferences and functional requirements.</p><p>The polished concrete offered by Floorlab stands out for its durability and low maintenance. This flooring option not only enhances the visual appeal of any space but also ensures a solid foundation that lasts for years. Clients can choose from a shimmering finish that reflects light beautifully or a matte option for a more subdued look. The versatility of polished concrete makes it suitable for homes, commercial buildings, and industrial applications.</p><p>Floorlab’s expertise lies in understanding client needs and delivering tailored solutions. The team prioritizes quality craftsmanship and customer satisfaction, ensuring each project meets high standards. With over two decades of experience, Floorlab has built a reputation for reliability and excellence in the flooring industry.</p><p>Floorlab excels in providing polished concrete flooring solutions that combine aesthetics with functionality. Their commitment to quality and customer service has made them a trusted choice in Toronto. Contact Floorlab to explore polished concrete options for any space in Ontario.</p>',
  '235 Medland St #104',
  'Canada',
  'ON',
  'Toronto',
  'M6P 2N6',
  'info@m3flooring.com',
  'canada/toronto/home-services/floorlab',
  'ChIJ3wY5tyE0K4gRUDeXDclc2YI',
  43.6651231,
  -79.4669709,
  '14164543819',
  NULL,
  'Flooring',
  'Growth Plan',
  478,
  'http://www.floorlab.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Athletic Flooring Systems',
  '<p>Athletic Flooring Systems provides expert flooring solutions in Winnipeg, Manitoba, and the surrounding areas. This flooring contractor specializes in high-quality sports flooring tailored for various applications. The company offers a diverse range of products, including outdoor multi-sport game courts, home gym flooring, commercial gym flooring, and event flooring. Athletic Flooring Systems also excels in synthetic turf and putting greens, catering to both residential and commercial needs.</p><p.With a strong focus on quality and performance, Athletic Flooring Systems meets the demands of athletes and enthusiasts alike. The company’s experience in the industry ensures that clients receive durable and reliable flooring options. Whether it’s a home gym or a professional sports facility, the right flooring is crucial for safety and performance. The team understands the unique requirements of each project and delivers customized solutions that enhance functionality and aesthetics.</p><p.Athletic Flooring Systems has established itself as a trusted partner for sports flooring in Manitoba and North Western Ontario. The commitment to customer satisfaction drives the company to provide exceptional service and high-quality products. Clients appreciate the attention to detail and the ability to meet tight deadlines without compromising quality.</p><p.Choose Athletic Flooring Systems for all sports flooring needs in Winnipeg. The diverse range of offerings and dedication to excellence make this company a valuable resource. Connect with Athletic Flooring Systems at 3130 Wilkes Ave, Winnipeg, Manitoba, for professional flooring solutions.</p>',
  '3130 Wilkes Ave',
  'Canada',
  'MB',
  'Winnipeg',
  'R3S 1A7',
  'martin@robarflooring.com',
  'canada/winnipeg/home-services/athletic-flooring-systems',
  'ChIJJZUTak4L6lIRKDRktgB7cOA',
  49.8423365,
  -97.2541547,
  '12048377896',
  NULL,
  'Flooring',
  'Growth Plan',
  477,
  'http://athleticflooring.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Béton LC',
  '<p>Béton LC, located in Terrebonne, Quebec, specializes in polished concrete flooring solutions. With over twenty years of experience, this flooring contractor serves the Montreal, Repentigny, and Laval areas. The company focuses on providing durable and low-maintenance flooring options that enhance the aesthetic appeal of industrial and commercial properties.</p><p>This flooring contractor emphasizes the benefits of polished concrete, which offers a sleek and modern look while being highly resilient. Béton LC understands the needs of businesses seeking flooring that can withstand heavy foot traffic and machinery. The team is committed to delivering quality workmanship and exceptional customer service, ensuring every project meets the highest standards.</p><p>Béton LC''s expertise in polished concrete flooring sets it apart in the industry. The company takes pride in its ability to transform spaces with stylish and functional flooring solutions. Clients appreciate the low maintenance required for polished concrete, making it an ideal choice for busy commercial environments. The company’s reputation for reliability and professionalism continues to grow, attracting more customers in the region.</p><p.Béton LC offers a range of services tailored to meet the specific needs of commercial and industrial clients. The combination of durability, ease of maintenance, and aesthetic appeal makes polished concrete an excellent choice for various applications. Engage with Béton LC today to explore flooring solutions that elevate properties in Terrebonne, Quebec.</p>',
  '505 Rue Fernand Poitras #110',
  'Canada',
  'QC',
  'Terrebonne',
  'J6Y 1Y5',
  'journet@aluminiumjclement.com',
  'canada/terrebonne/home-services/béton-lc',
  'ChIJl_MEAVzYyEwRRNehO5ldBF8',
  45.685995,
  -73.773489,
  '14506217356',
  'https://www.kwikr.ca/pictures/profile/pimage-465.jpg',
  'Flooring',
  'Growth Plan',
  476,
  'https://www.betonlc.com/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Vepox Epoxy Coatings',
  '<p>Vepox Epoxy Coatings, located at 39 Vernay Dr in Memramcook, New Brunswick, specializes in high-quality epoxy and polyaspartic coatings. This flooring contractor serves the Greater Moncton area and all of New Brunswick, focusing on concrete preparation and resinous coatings. Vepox provides exceptional solutions for garages, basements, doorsteps, and walkways, ensuring durability and aesthetic appeal.</p><p>Established with a commitment to customer satisfaction, Vepox Epoxy Coatings prioritizes quality service from the initial phone call to project completion. The skilled team understands the importance of delivering reliable and effective flooring solutions. By utilizing advanced techniques and high-grade materials, Vepox guarantees a finished product that meets the specific needs of each client.</p><p>Vepox often undertakes projects in various cities, including Moncton, Dieppe, Shediac, Riverview, Bouctouche, and Miramichi, extending its reach to the Acadian Peninsula. The company’s reputation for excellence in epoxy coatings has made it a preferred choice among local homeowners and businesses. Customers appreciate the attention to detail and professional approach that Vepox brings to every job.</p><p>Vepox Epoxy Coatings offers comprehensive services in epoxy flooring, ensuring quality and satisfaction. With a focus on concrete preparation and resinous coatings, the company excels in transforming spaces. Connect with Vepox Epoxy Coatings in Memramcook for a free quote today.</p>',
  '39 Vernay Dr',
  'Canada',
  'NB',
  'Memramcook',
  'E4K 0E4',
  'office@epoxyguys.com',
  'canada/memramcook/home-services/vepox-epoxy-coatings',
  'ChIJdRUv4Kq5oEwR9iYOzYxCJIA',
  46.0385113,
  -64.6614103,
  '15067772505',
  'https://www.kwikr.ca/pictures/profile/pimage-464.jpg',
  'Flooring',
  'Growth Plan',
  475,
  'http://www.vepox.ca/',
  NULL,
  NULL,
  NULL,
  NULL
);

INSERT INTO worker_profiles_new (
  company, description, address, country, province, city, postal_code,
  email, filename, google_place_id, latitude, longitude, phone,
  profile_photo, category, subscription_type, user_id, website,
  hours_of_operation, hourly_rate, price_range, services_provided
  'Renowest Flooring and Renovation',
  '<p>Renowest Flooring and Renovation operates as a premier flooring contractor located in Coquitlam, British Columbia. Since its establishment in 2018, the company has provided comprehensive flooring solutions to the Metro Vancouver area. Renowest specializes in a variety of flooring options, including hardwood, vinyl, and laminate flooring, along with stair renovations, wallpaper installation, and expert painting services.</p> <p>The company focuses on delivering exceptional services with an emphasis on customer satisfaction. Renowest''s team comprises skilled technicians who ensure quality workmanship on every project. The efficient project completion process makes Renowest a preferred choice for both homeowners and businesses in the region. A commitment to durability and style sets Renowest apart in the competitive flooring market.</p> <p>Renowest Flooring and Renovation has built a reputation for excellence in flooring solutions. The wide range of options available caters to diverse customer needs, ensuring that every project aligns with individual preferences. The company’s dedication to quality craftsmanship and customer service has earned it recognition in the local community.</p> <p>Renowest Flooring and Renovation stands ready to provide top-notch flooring solutions and renovations. The combination of expertise, customer focus, and a variety of services makes this company a reliable choice in Coquitlam. Reach out to Renowest Flooring and Renovation for exceptional flooring services in British Columbia.</p>',
  '1637 Pinetree Wy',
  'Canada',
  'BC',
  'Coquitlam',
  'V3E 3B7',
  'info@coatsystems.com',
  'canada/coquitlam/home-services/renowest-flooring-and-renovation',
  'ChIJwQJxZGl_hlQRzRsl9e37NH0',
  49.3057667,
  -122.7836192,
  '17789577006',
  'https://www.kwikr.ca/pictures/profile/pimage-463.jpg',
  'Flooring',
  'Growth Plan',
  474,
  'https://renowestflooring.com/',
  NULL,
  NULL,
  NULL,
  NULL
);
